### ISSUE TITLE
Which release/artifact can be installed on Ubuntu 22.10(kinetic)?

### ISSUE THREAD

**Issue by DingGuodong** [mydumper/mydumper#1012]
Which release/artifact can be installed on Ubuntu 22.10(**kinetic**)? 
Such as 'https://github.com/mydumper/mydumper/releases/download/v0.13.1-2/mydumper_0.13.1-2.kinetic_amd64.deb'.

**Comment by davidducos** [comment]
Hi @DingGuodong,
I only create packages for LTS releases on Ubuntu, but this is a project that you can contribute, so if you want to you can create a PR with the changes that:
1- create the docker image like: https://github.com/mydumper/mydumper/tree/master/docker
2- Modify https://github.com/mydumper/mydumper/blob/master/.circleci/circleci_config_builder.sh that builds [config.yml](https://github.com/mydumper/mydumper/blob/master/.circleci/config.yml)
And I will be glad to review and give you feedback. 
The alternative is that you build the binaries for your environment.

**Comment by DingGuodong** [comment]
Hi @davidducos thanks for your reply.
I have viewed the instruction you mentioned above. Also viewed the files which build the packages.
I learned that how had it was for you build packages. It is really great job and you've earned my respect!
I have built the binaries with the source before I opened this issue. Thank you again.
