### ISSUE TITLE
myloader is hanging after the execution,  and also can't exit via CTRL+C and Y.

### ISSUE THREAD

**Issue by jmbkeyes** [mydumper/mydumper#1015]
**Describe the bug**

**To Reproduce**
Command executed:
* mydumper with all the parameters
* myloader with all the parameters

What mydumper and myloader version has been used?
mydumper0.13.1-2, built against MySQL 5.7.40-43 with SSL support with GZIP
myloader0.13.1-2, built against MySQL 5.7.40-43 with SSL support with GZIP
**Expected behavior**
**Firstly**，I export the data via mydump via  mydumper --host 10.0.0.12 --port 3306 --user root -p Forzadata1234 --database bocai --tables-list trainee_sub_center_info --outputdir /root/test --no-schemas --complete-insert --where centerId=269
**Then**, I import the data via  myloader -h 10.0.0.12 -u root -p Forzadata1234  -B bocai2 -d /root/test.
The shell is always in running mode, but I'm sure that the load processs is completed after several minutes, I can see the imported data in target database.
![1675679452488](https://user-images.githubusercontent.com/12583734/216948903-554df326-e28c-462d-a7b0-d280a3147f9d.png)

Finally, I  want to exit the process just with short key CTRL+ C, and press Y. But the process is not be killed.
![1675679593304](https://user-images.githubusercontent.com/12583734/216949364-da202ba1-f4b3-4ee5-b9e8-5a830fb6468d.png)
I have to the use the command kill -9 pid(myloader process id)

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
** Message: 18:25:40.940: Server version reported as: 5.7.38-log
** Message: 18:25:42.806: Intermediate queue: Sending END job
** Message: 18:25:42.806: Adding new table: `bocai`.`trainee_sub_center_info`

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough
[root@master0 test]# ls -al
total 3060
drwxr-x---  2 root root      91 Feb  6 18:32 .
dr-xr-x---. 5 root root    4096 Feb  6 16:20 ..
-rw-r--r--  1 root root 3123913 Feb  6 17:49 bocai.trainee_sub_center_info.00000.sql
-rw-r--r--  1 root root     142 Feb  6 17:49 metadata
-rw-r--r--  1 root root       0 Feb  6 18:32 resume.partial

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
Or upload a [core dump](https://github.com/mydumper/mydumper/wiki/Support#core-dump) for cases where mydumper or myloader is crashing.

**Environment (please complete the following information):**
 - OS version:  CentOS Linux release 7.9.2009 (Core)
 - MyDumper version: mydumper0.13.1-2

**Additional context**

**Comment by davidducos** [comment]
Hi @jmbkeyes, 
Can you test it with the latest prerelease?

**Comment by jmbkeyes** [comment]
I install the lastest prerelease version(mydumper-0.14.0-2), but still not work.

**Comment by jmbkeyes** [comment]
OK, thanks for your reply.
