### ISSUE TITLE
what's the difference whether specify the parameter --defaults-file or not?

### ISSUE THREAD

**Issue by jmbkeyes** [mydumper/mydumper#1016]
1. specify the defaults-file.
    there will be 4 sql files.
    **defaults-file:**
[mydumper]
host = 10.0.0.12
user = root
password = Forzadata1234
database = bocai
rows = 10000
    **command:** mydumper --defaults-file=../mydumper.conf --tables-list bocai.trainee_sub_center_info --outputdir /root/test --rows 1000  --no-schemas --complete-insert --where centerId=269 --no-locks
    
![1675680632102](https://user-images.githubusercontent.com/12583734/216952975-cfff01b0-1b16-47a2-97ae-4aa787467644.png)

2. not specify the defaults-file.
    there will be only 1 sql files.
    **command:** mydumper --host 10.0.0.12 --port 3306 --user root -p Forzadata1234 --database bocai --tables-list bocai.trainee_sub_center_info --outputdir /root/test --no-schemas --complete-insert --where centerId=269 --no-locks
![1675680590206](https://user-images.githubusercontent.com/12583734/216952872-1d39caf1-c48b-405c-ae18-c230f36161ec.png)

**Comment by davidducos** [comment]
@jmbkeyes, you are using --rows 1000 in the first execution which explain the behavior. It is not related to --defaults-file

**Comment by jmbkeyes** [comment]
I had remove the parameter --rows yesterday, and I'm sorry attaching the wrong screeshot.
![1675731761987](https://user-images.githubusercontent.com/12583734/217121618-7becca42-4d66-4932-bf4a-f82843bcdefa.png)
