### ISSUE TITLE
[BUG] Segmentation fault after using myloader on a directory of files dumped by mydumper

### ISSUE THREAD

**Issue by kyleboddy** [mydumper/mydumper#1018]
**Describe the bug**
Ran `mydumper` to successfully dump a 240GB database into many files. Attempting to use `myloader` on this directory caused segmentation faults. 

From the same server, I tried using `myloader` to load it to two remote servers - one on the local network, one across the Internet. Both failed in the same way.

**To Reproduce**
Command executed:
* mydumper with all the parameters

```nohup mydumper -v 3 -o doclusterdump02062023 -t 7 -h [redacted] -u [redacted] -p [redacted] --ssl --port=[redacted] --regex '^(?!(mysql\.|test\.|sys\.))' --statement-size 1000000000 > mydumper.log 2>&1 &```

This succeeded. Last lines of the mydumper.log file:

> ** Message: 18:03:52.387: InnoDB tables completed
> ** Message: 18:03:52.387: Thread 3: shutting down
> ** Message: 18:03:52.387: Waiting threads to complete
> ** Message: 18:11:35.925: Thread 6: shutting down
> ** Message: 18:14:38.705: Thread 4: shutting down
> ** Message: 18:21:55.061: Thread 7: shutting down
> ** Message: 18:51:13.525: Thread 1: shutting down
> ** Message: 19:04:28.215: Thread 5: shutting down
> ** Message: 19:14:36.220: Thread 2: shutting down
> ** Message: 19:14:36.231: Queue count: 0 0 0 0 0
> ** Message: 19:14:36.231: Main connection closed
> ** Message: 19:14:36.244: Finished dump at: 2023-02-06 19:14:36

* myloader with all the parameters

```myloader -P 3306 -C -t 7 -d doclusterdump02062023/ -v 3 --defaults-file myloader.conf```

This did not. Contents of myloader.conf:

> [myloader]
> host = [redacted, valid IPv4 address]
> user = [redacted]
> password = [redacted]

**What mydumper and myloader version has been used?**

`myloader0.13.1-2, built against MySQL 8.0.30-22 with SSL support with GZIP`

`mydumper0.13.1-2, built against MySQL 8.0.30-22 with SSL support with GZIP`

**Expected behavior**
For `myloader` to connect and start writing to the remote database without crashing.

**Log**

Stdout crash log:

> kyle@kentreplication1:~$ tail -f nohup.out
> ** Message: 00:22:14.799: Config file loaded
> ** Message: 00:22:14.927: Server version reported as: 5.5.5-10.4.25-MariaDB
> ** Message: 00:22:16.627: Intermediate queue: Sending END job
> ** Message: 00:22:16.632: Adding new table: `biomech_pitching_db`.`bp_markers`
> ** Message: 00:22:16.632: Adding new table: `biomech_hitting_db`.`bh_sessions`
> Command terminated by signal 11
> 0.01user 0.01system 0:03.31elapsed 0%CPU (0avgtext+0avgdata 11960maxresident)k
> 7760inputs+8outputs (34major+824minor)pagefaults 0swaps

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

Here are the first few files from the directory.

> kyle@kentreplication1:~/doclusterdump02062023$ ls -la
> total 265212144
> drwxr-x--- 2 kyle kyle       36864 Feb  7 00:08 .
> drwxr-x--- 6 kyle kyle        4096 Feb  7 00:26 ..
> -rw-rw-r-- 1 kyle kyle     1908741 Feb  6 18:03 biomech_db.biomech_pitching_add_metties.00000.sql
> -rw-rw-r-- 1 kyle kyle           5 Feb  6 19:14 biomech_db.biomech_pitching_add_metties-metadata
> -rw-rw-r-- 1 kyle kyle        2799 Feb  6 10:06 biomech_db.biomech_pitching_add_metties-schema.sql
> -rw-rw-r-- 1 kyle kyle 13563966083 Feb  6 19:14 biomech_db.biomech_pitching_full_signal.00000.sql
> -rw-rw-r-- 1 kyle kyle           5 Feb  6 19:14 biomech_db.biomech_pitching_full_signal-metadata
> -rw-rw-r-- 1 kyle kyle         647 Feb  6 10:06 biomech_db.biomech_pitching_full_signal-schema.sql

**How to repeat**
Core dump attached. The database is 200+ GB, I won't be attaching that.

**Environment (please complete the following information):**
 - OS version: Ubuntu Server 22.04.1 LTS

**Additional context**
I think it is possible there is a collation match error going from an older MySQL version to a newer MariaDB version, but a segfault seems unlikely. I have run `gdb` and done a quick lookup with the symbols attached, but nothing stood out. I'll continue to diagnose as well, but I have attached a core dump here for analysis.

[core-myloader.1533.kentreplication1.1675758471.zip](https://github.com/mydumper/mydumper/files/10673077/core-myloader.1533.kentreplication1.1675758471.zip)

EDIT:

Interestingly, I just noticed it creates these databases/tables before crashing:

![image](https://user-images.githubusercontent.com/746351/217198464-38f6c67f-f414-4291-9757-202989597f17.png)

**Comment by kyleboddy** [comment]
I am running the following commands to swap out known collation issues and when they're complete, will attempt to run `myloader` again.

`sed -i 's/utf8mb4_0900_ai_ci/utf8mb4_general_ci/g' *`
`sed -i 's/CHARSET=utf8mb4/CHARSET=utf8/g' *`

**Comment by kyleboddy** [comment]
Nope. Ran `sed` overnight and replaced all those instances, same output today.

> kyle@kentreplication1:~$ myloader -P 3306 -C -t 4 -d doclusterdump02062023/ -v 3 --defaults-file myloader.conf
> ** Message: 09:02:42.698: Config file loaded
> ** Message: 09:02:42.814: Server version reported as: 5.5.5-10.4.25-MariaDB
> ** Message: 09:02:43.782: Intermediate queue: Sending END job
> ** Message: 09:02:43.789: Adding new table: `biomech_pitching_db`.`bp_markers`
> ** Message: 09:02:43.789: Adding new table: `biomech_hitting_db`.`bh_sessions`
> Segmentation fault (core dumped)
>

**Comment by kyleboddy** [comment]
I tried to install the latest pre-release and ran into libglib2.0 dependency errors. I purged `mydumper` and ran `sudo apt-get install libglib2.0-dev`, then tried to install the latest pre-release using `dpkg` and got an error saying lib-glib2.0 wasn't installed.

`apt install libglib2.0` finds no targets, hence why I tried the dev branch, per SO tickets like this one:

https://unix.stackexchange.com/questions/182156/gentoo-no-package-glib-2-0-found

I purged all relevant packages and tried again:

`apt install libgtk2.0-dev libglib2.0-dev`

and

`dpkg -i mydumper_0.14.0-2-zstd.jammy_amd64.deb`

To which I get:

> kyle@kentreplication1:~$ sudo dpkg -i mydumper_0.14.0-2-zstd.jammy_amd64.deb
> Selecting previously unselected package mydumper.
> (Reading database ... 99464 files and directories currently installed.)
> Preparing to unpack mydumper_0.14.0-2-zstd.jammy_amd64.deb ...
> Unpacking mydumper (0.14.0-2-zstd~jammy) ...
> dpkg: dependency problems prevent configuration of mydumper:
>  mydumper depends on glib-2.0; however:
>   Package glib-2.0 is not installed.
> 
> dpkg: error processing package mydumper (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  mydumper

And then:

> kyle@kentreplication1:~$ sudo apt install glib-2.0
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Package glib-2.0 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'glib-2.0' has no installation candidate

Then it says to run --fix-broken-install:

> kyle@kentreplication1:~$ sudo apt --fix-broken install
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Correcting dependencies... Done
> The following packages were automatically installed and are no longer required:
>   libflashrom1 libftdi1-2
> Use 'sudo apt autoremove' to remove them.
> The following packages will be REMOVED:
>   mydumper
> 0 upgraded, 0 newly installed, 1 to remove and 4 not upgraded.
> 1 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> 

And that's where we are at right now.

**Comment by davidducos** [comment]
@kyleboddy 

Can you test with https://github.com/mydumper/mydumper/releases/tag/v0.14.0-3 ??

**Comment by kyleboddy** [comment]
Installation succeeded.

> kyle@kentreplication1:~$ sudo dpkg -i mydumper_0.14.0-3.jammy_amd64.deb
> Selecting previously unselected package mydumper.
> (Reading database ... 102749 files and directories currently installed.)
> Preparing to unpack mydumper_0.14.0-3.jammy_amd64.deb ...
> Unpacking mydumper (0.14.0-3~jammy) ...
> Setting up mydumper (0.14.0-3~jammy) ...

Segmentation fault still occurs.

`nohup time myloader -P 3306 -C -t 6 -d doclusterdump02062023/ -v 3 --defaults-file myloader.conf > myloader.nohup.log`

> kyle@kentreplication1:~$ cat myloader.nohup.log
> ** Message: 18:50:49.661: Using default file: myloader.conf
> ** Message: 18:50:49.662: Config file loaded
> ** Message: 18:50:49.772: Server version reported as: 5.5.5-10.4.25-MariaDB
> ** Message: 18:50:50.870: Adding new table: `biomech_pitching_db`.`bp_markers`
> ** Message: 18:50:50.870: Adding new table: `biomech_hitting_db`.`bh_sessions`
> ** Message: 18:50:50.870: Intermediate queue: Sending END job
> Command terminated by signal 11
> 0.00user 0.00system 0:02.47elapsed 0%CPU (0avgtext+0avgdata 11760maxresident)k
> 0inputs+8outputs (0major+685minor)pagefaults 0swaps

Core dump attached.

[core-myloader.6763.kentreplication1.1675824735.zip](https://github.com/mydumper/mydumper/files/10681233/core-myloader.6763.kentreplication1.1675824735.zip)

**Comment by davidducos** [comment]
Hi @kyleboddy 
From your core dump:
```
168	          gchar** create_table= g_strsplit(data->str, "`", 3);
(gdb) p data->str
$1 = (gchar *) 0x7f77a8002ec0 "CREATE TABLE \"bh_sessions\" (\n  \"session\" smallint NOT NULL,\n  \"session_date\" date NOT NULL,\n  \"user\" smallint NOT NULL,\n  \"session_height_in\" decimal(10,4) NOT NULL,\n  \"session_mass_lbs\" decimal(10,4)"...
```
you are using " instead of `. I think that there is already a ticket open to fix this kind of issue which is related to ANSI usage.

**Comment by davidducos** [comment]
Duplicate #968

**Comment by davidducos** [comment]
Related to #969

**Comment by kyleboddy** [comment]
So in the myloader config file, include ANSI_QUOTES in sql_mode?

It's not clear to me in the linked posts and the documentation here:

https://github.com/mydumper/mydumper/blob/master/docs/myloader_usage.rst

Where that would go necessarily?

**Comment by davidducos** [comment]
When you dump the database, you need to remove the ANSI_QUOTES from the sql_mode. For instance, if you have this:

| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,ANSI_QUOTES |

you need to set in section mydumper_session_variables this: `ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
Like  this:
```
[mydumper_session_variables]
sql_mode = ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
I didn't test it, but it should work.

**Comment by kyleboddy** [comment]
Ah. And if I don't do that before the dump, there's no way to use `myloader` settings to get around that?

**Comment by kyleboddy** [comment]
Also this is what I get from our DB server when I run `SELECT @@sql_mode;` and there's no ANSI_QUOTES showing. Slightly confused on the whole process.

![image](https://user-images.githubusercontent.com/746351/217930827-7077721b-3202-42f8-a348-7b4b22226428.png)

Should I set `mydumper` session variables equal to what comes out of that, or your snippet? Appreciate the help.

**Comment by kyleboddy** [comment]
I ran SELECT @@sql_mode; on our DB for backup and got these variables back:

`REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION`

I then put it into a conf file, loaded it using a defaults command line from the newest `mydumper` release, and got this warning saying the set session failed:

>  (mydumper:3820): WARNING **: 05:48:01.601: Set session failed: SET SESSION sql_mode = REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

**Comment by kyleboddy** [comment]
Setting the target DB sql_mode to that line and trying to use `myloader` segfaulted as well.

> ** Message: 00:05:35.139: Using default file: myloader.conf
> ** Message: 00:05:35.140: Config file loaded
> ** Message: 00:05:40.115: Server version reported as: 5.5.5-10.4.27-MariaDB
> ** Message: 00:05:40.268: Adding new table: `statcast_db`.`steamer_ps_projections_hitting`
> ** Message: 00:05:40.268: Intermediate queue: Sending END job
> Command terminated by signal 11

Back to the drawing board...

**Comment by kyleboddy** [comment]
Sadly with this conf file loaded in mydumper:

[mydumper_session_variables]
sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION"

I still get segfaults in the same spot. Literally no idea what to do from here.
