### ISSUE TITLE
--rows SMALLINT support on MyDumper version: 0.14.0-3

### ISSUE THREAD

**Issue by VMEMachuca** [mydumper/mydumper#1020]
create table t(id1 smallint, id2 int, c char(200), primary key(id1,id2));

+----------+----------+--------+--------+----------+----------+--------+----------+
| id1_cnt  | id1_dcnt | id1_mn | id1_mx | id1_cnt  | id2_dcnt | id2_mn | id2_mx   |
+----------+----------+--------+--------+----------+----------+--------+----------+
| 27556890 |      278 |     33 |   1321 | 27556890 | 15863246 |      1 | 15987728 |
+----------+----------+--------+--------+----------+----------+--------+----------+

mydumper-0.14.0/usr/bin/mydumper --user=XXX --password=XXX --verbose=3 --regex '^35k_20_d_vme_mysql_3307[.]t$' --rows 60000 

wc -l /home/victor.machuca/35k_20_d_vme_mysql_3307.t.0*sql.gz|head
176963 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00000.sql.gz

**Comment by davidducos** [comment]
Hi @VMEMachuca, 
We are using just first column in the primary key, that is why you will see 1 file with all the rows. If you want to split the file in multiple pieces, you can use -F.

**Comment by davidducos** [comment]
We might implement --rows per table which might be added in the configuration file as we already do for other scenarios, that might help for your table structures.

**Comment by VMEMachuca** [comment]
This is what I see on mydumper-0.10.3 without -F option. 

mydumper-0.10.3/usr/bin/mydumper --user=XXX --password=XXX --verbose=3 --regex '^35k_20_d_vme_mysql_3307[.]t$' --rows 60000

 wc -l /home/victor.machuca/35k_20_d_vme_mysql_3307.t.0*sql.gz|head
    3467 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00000.sql.gz
      45 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00001.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00002.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00003.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00004.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00005.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00006.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00007.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00008.sql.gz
       0 /home/victor.machuca/35k_20_d_vme_mysql_3307.t.00009.sql.gz

**Comment by davidducos** [comment]
Please, explain better what is the issue.

**Comment by VMEMachuca** [comment]
We assumed, the –rows argument will give you the ability to split tables in chunks of X number of rows. Each chunk can run in parallel, so it is a huge speed bump for big tables.
