### ISSUE TITLE
myloader takes more time to load into a docker mysql

### ISSUE THREAD

**Issue by sajiljosephs** [mydumper/mydumper#1031]
mydumper takes one hour to take a dump and is complete. mydumper-files folder is around 192MB. 
myloader takes more than 6 hours to load into a docker mysql. Is 6 hours normal to a db restored with 192 MB of data?

**Comment by aqueos** [comment]
Le 14/02/2023 à 09:44, sajiljosephs a écrit :
> mydumper takes one hour to take a dump and is complete. mydumper-files folder is around 192MB.
> myloader takes more than 6 hours to load into a docker mysql. Is 6 hours normal to a db restored with 192 MB of data?
> 


  192M of compress data can lead to huge uncompressed files in some case.

   You should look of what it is doing, if transaction/locking is not an issue and see if your disk io is not the problem.

   Any import can take hours if not properly done (and even if properly done in some case).

Things to look could be

--disable-redo-log
--innodb-optimize-keys
are you using triggers or foreign key constraints ?


triggers can really be a mess in an import situation.



-- 
cordialement,
Ghislain ADNET.
AQUEOS.

**Comment by sajiljosephs** [comment]
Did all suggested methods to improve. mydumper-files is around 900 MB. Dump was completed in less than 5 minutes. Loading takes more than 6 hours. After 5 hours, I still see in logs that many tables are created. 
There are around 500 Schemas and I see more than 100000 files in mydumper-files. Cant really relate looking at the counts.

**Comment by davidducos** [comment]
How do you pretend that we help you with this little amount of information?
We need logs, a detailed explanation of the issue, a test case... why don't you fill the bug issue template?
