### ISSUE TITLE
[Question] loading mydumper: Key file does not have group “mydumper”

### ISSUE THREAD

**Issue by marcatsmci** [mydumper/mydumper#1032]
**Describe the question**
Message found in mydumper's log file, each time a dump runs.

Which file does not have the correct group?

**To Reproduce**
Command executed:
`mydumper  -u ${DB_USER} -p ${DB_PASS} -B ${DB_NAME} --outputdir="dir..." --logfile="log.log" --compress --build-empty-files --compress-protocol --events --triggers --routines --trx-consistency-only --threads=2 --rows=50000`

What mydumper and myloader version has been used?
`mydumper0.14.0-3, built against MySQL 8.0.30-22 with SSL support with ZSTD`

**Expected behavior**
How to deal with this message? Why is it generated?

**Log**
`2023-02-14 08:27:01 [WARNING] - loading mydumper: Key file does not have group “mydumper”`

**Environment (please complete the following information):**
 - OS version: Debian GNU/Linux 11 (bullseye) / 5.10.0-21-amd64
 - MyDumper version: mydumper0.14.0-3, built against MySQL 8.0.30-22 with SSL support with ZSTD

**Comment by davidducos** [comment]
Hi @marcatsmci, 
When you use the defaults-file, it will be send to mysql library to use the mydumper section info to connect to the database. We could check if the mydumper section exists to avoid that warning.

**Comment by marcatsmci** [comment]
Hi @davidducos, thanks !
