### ISSUE TITLE
[Question] Any way to set zstd parameters ?

### ISSUE THREAD

**Issue by marcatsmci** [mydumper/mydumper#1033]
**Describe the bug**
How can we set zstd parameters ? 

My favorites :

- `--threads=0`
- `--fast=0`
- `-q`

Which parameters are defined in mydumper/zstd version ?

**Expected behavior**
A way to change/set zstd settings.

**Environment (please complete the following information):**

 *  `OS version: Debian GNU/Linux 11 (bullseye) / 5.10.0-21-amd64`
 *  MyDumper version: `mydumper0.14.0-3, built against MySQL 8.0.30-22 with SSL support with ZSTD`

**Comment by davidducos** [comment]
Hi @marcatsmci, 

We use https://github.com/facebook/zstd/tree/dev/zlibWrapper. Let me know if you find any doc on how to configure the library.

**Comment by marcatsmci** [comment]
HI @davidducos,
I will wait for mydumper to use the API ;-)

The only way i found for now is to set the global variables : 

# Use number of threads available for parallel compression  (0 means "autodetect number available") 
ZSTD_NBTHREADS="0"

# Sets the default compression level (from 1 to 19)
ZSTD_CLEVEL="1"

**Comment by davidducos** [comment]
Hi @marcatsmci,

Sorry to disappoint you but I don't think that I will be implement it with the API. Actually, what you can do is use:
```
  --exec-per-thread                Set the command that will receive by STDIN and write in the STDOUT into the output file
  --exec-per-thread-extension      Set the extension for the STDOUT file when --exec-per-thread is used
```
to accomplish what you want.
