### ISSUE TITLE
SHOW TRIGGERS <DB> LIKE <TABLE> recursion when using --triggers

### ISSUE THREAD

**Issue by z3nby** [mydumper/mydumper#1034]
**Describe the bug**
SHOW TRIGGERS DATABASE LIKE TABLE
which costs alot of time -> This command checks every table if they have triggers   --triggers command
can be improve i believe just by using SHOW TRIGGERS DATABASE LIKE TABLE since it will show all triggers already on that database

**To Reproduce**
Command executed:
 mydumper --events --triggers --routines --trx-consistency-only --less-locking -u "$DB_USER" -p "$DB_PASS" -h "$DB_HOST" -B "$db" -o "$backup_file" --verbose=3

What mydumper and myloader version has been used?

MyDumper 13.0.1 Latest

**Expected behavior**
It appears when using --triggers it use the command SHOW TRIGGERS DATABASE LIKE TABLE 
It recursively looking for all the tables on the database instead of just using the command SHOW TRIGGERS <DB> to dump all the triggers that was found there

Using the LIKE TABLE on SHOW TRIGGERS i think it would fetch per recursively per table since that is what happening as per checking to making dumping process faster.

**How to repeat**
Just Dump any db with table with --triggers

If applicable, add the minimal table structure and data that we need to reproduce the issue.
Or upload a [core dump](https://github.com/mydumper/mydumper/wiki/Support#core-dump) for cases where mydumper or myloader is crashing.

**Environment (please complete the following information):**
 - OS version: [Ubuntu 22.04]
 - MyDumper version: mydumper0.13.1-2, built against MySQL 8.0.30-22 with SSL support with GZIP

**Additional context**

**Comment by davidducos** [comment]
Hi @z3nby, we could show triggers if --regex is not used.

**Comment by z3nby** [comment]
> Hi @z3nby, we could show triggers if --regex is not used.

its weird that it does SHOW TRIGGERS <DB> LIKE <TABLE> every time we use --triggers as behavior of the command instead of just doing SHOW TRIGGERS as my observation.

**Comment by davidducos** [comment]
We will need to add a schema-triggers file per database **when it is possible**. We need to add a variable on the database structure to avoid creating schema-trigger based on tables.
