### ISSUE TITLE
[BUG] mydumper slower than mysqldump ?

### ISSUE THREAD

**Issue by marcatsmci** [mydumper/mydumper#1039]
**Describe the bug**
Same server, same DB : 

**Mydumper** : 
```
 ... DB export: a7databases => a7databases-WD-4-H-14 [80M]
 +-- duration => 00:00:07
 ... DB export: nextcloud => nextcloud-WD-4-H-14 [9.6M]
 +-- duration => 00:00:05
 ... DB export: pwm => pwm-WD-4-H-14 [550M]
 +-- duration => 00:00:42
 End of run on Thu 2023-02-16 14:35:59
 Global duration => 00:00:54
```
**Mysqldump** :
 ```
... DB export: a7databases => a7databases-WD-4-H-14.sql.zst [80M]
 +-- duration => 00:00:02
 ... DB export: nextcloud => nextcloud-WD-4-H-14.sql.zst [11M]
 +-- duration => 00:00:03
 ... DB export: pwm => pwm-WD-4-H-14.sql.zst [554M]
 +-- duration => 00:00:17
 End of run on Thu 2023-02-16 14:37:23
 Global duration => 00:00:22
```

**To Reproduce**
Command executed:
* `mydumper -u... -p... -B db_name --outputdir=... --logfile=...  --compress --build-empty-files --compress-protocol --trx-consistency-only --threads=3 --rows=50000`
* `mysqldump  -u... --skip-triggers --single-transaction --skip-lock-tables ${DB_NAME} | zstd -q --fast=10 --threads=0 > output_file.sql.zst`

What mydumper and myloader version has been used?

v0.14.0-3 or v0.13.1-2

**Expected behavior**
With 2 cpus, mydumper should be much faster than mysqldump

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.

[pwm.log.gz](https://github.com/mydumper/mydumper/files/10756803/pwm.log.gz)

**Environment (please complete the following information):**
 - OS version: `OS version: Debian GNU/Linux 11 (bullseye) / 5.10.0-21-amd64`
 - MyDumper version: `mydumper0.14.0-3, built against MySQL 8.0.30-22 with SSL support with ZSTD
`

**Additional context**
**lscpu**
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       2
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

```
**free -m**
```
               total        used        free      shared  buff/cache   available
Mem:            3920        2036         232          28        1651        1601
Swap:           2045        2012          33
```

**Comment by davidducos** [comment]
@marcatsmci,

mydumper is not faster in all use cases. However, when I reviewed the log I saw that all the thread ended in 10 seconds but thread 1 was working on `pwm`.`fileimport_data`. Did/Can you check if there is a select after 10 seconds of executions?
```
...
2023-02-16 14:55:56 [INFO] - Thread 1: dumping data for `pwm`.`fileimport_data`          into (null)| Remaining jobs: 0
...
2023-02-16 14:55:58 [INFO] - Thread 3: shutting down
2023-02-16 14:56:31 [INFO] - Thread 1: shutting down
```

**Comment by marcatsmci** [comment]
@davidducos,
another test at 22:35, without users.

I don't understand what you mean by "check if there is a select after 10 seconds of executions", sorry...

[pwm2.log.gz](https://github.com/mydumper/mydumper/files/10761113/pwm2.log.gz)

**Comment by davidducos** [comment]
@marcatsmci, during execution, execute "show processlist" every a couple of seconds to see what mydumper is doing. And after, also execute:
```
use pwm;
show create table `fileimport_data`;
show table status like 'fileimport_data';
```

**Comment by marcatsmci** [comment]
@davidducos 

`| 538868 | ... | localhost     | NULL | Query   |    34 | Writing to net | SELECT /*!40001 SQL_NO_CACHE */ * FROM pwm.fileimport_data |    0.000 |`

```
MariaDB [pwm]> SELECT COUNT(*) from fileimport_data;
+----------+
| COUNT(*) |
+----------+
|     4313 |
+----------+
```
```
MariaDB [pwm]> show create table `fileimport_data`;
+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table           | Create Table                                                                                                                                                                                                                                                                                                                     |
+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| fileimport_data | CREATE TABLE `fileimport_data` (
  `FileID` int(11) NOT NULL,
  `FileData` longblob DEFAULT NULL,
  `FileState` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`FileID`),
  CONSTRAINT `FK_FILEIMPDATA` FOREIGN KEY (`FileID`) REFERENCES `fileimport_log` (`IDENT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci |
+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
```
MariaDB [pwm]> show table status like 'fileimport_data';
+-----------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+------------------+-----------+
| Name            | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time | Collation       | Checksum | Create_options | Comment | Max_index_length | Temporary |
+-----------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+------------------+-----------+
| fileimport_data | InnoDB |      10 | Dynamic    | 4440 |         105924 |   470302720 |               0 |            0 |   5242880 |           NULL | 2023-02-14 19:37:24 | 2023-02-17 09:28:04 | NULL       | utf8_general_ci |     NULL |                |         |                0 | N         |
+-----------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+------------------+-----------+
```

**Comment by davidducos** [comment]
try with -r 100:500:50000 instead of --rows=50000

**Comment by marcatsmci** [comment]
Same elapsed time...

```
| 599988 | ... | localhost     | pwm  | Sleep   |    37 |                | NULL                                                                                                 |    0.000 |
| 599989 | ... | localhost     | pwm  | Query   |     0 | Writing to net | SELECT /*!40001 SQL_NO_CACHE */ * FROM `pwm`.`fileimport_data`  WHERE (  ( 11179 < `FileID` AND `Fil |    0.000 |
```
```
SELECT COUNT(*) from fileimport_data;
+----------+
| COUNT(*) |
+----------+
|     4329 |
+----------+
```
```
show table status like 'fileimport_data';
+-----------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+------------------+-----------+
| Name            | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time | Collation       | Checksum | Create_options | Comment | Max_index_length | Temporary |
+-----------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+------------------+-----------+
| fileimport_data | InnoDB |      10 | Dynamic    | 4440 |         105924 |   470302720 |               0 |            0 |   6291456 |           NULL | 2023-02-14 19:37:24 | 2023-02-20 08:20:14 | NULL       | utf8_general_ci |     NULL |                |         |                0 | N         |
+-----------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-----------------+----------+----------------+---------+------------------+-----------+
```

**Comment by davidducos** [comment]
@marcatsmci can you share the latest log? as I can see that the table is being splitted into chunks but it might be possible that it is increasing too fast, can you try -r 500 ?

**Comment by marcatsmci** [comment]
The log with `rows=500`

[230221.log.gz](https://github.com/mydumper/mydumper/files/10793055/230221.log.gz)

**Comment by marcatsmci** [comment]
Elapsed : 29 s (mysqldump : 16 s)
Size compressed : 1.1G (mysqldump : 554M)

[230221-stream.log.gz](https://github.com/mydumper/mydumper/files/10795545/230221-stream.log.gz)

**Comment by davidducos** [comment]
@marcatsmci 
This doesn't makes sense to me. 
1- You said that the size compressed is 1.1G, but the log reported:
```
2023-02-21 17:18:36 [INFO] - All data transferred was 1239634451 at a rate of 42 MB/s
```
that is 1.1G decompressed. 
2- The `Finished dump` entry was after 26 seconds, which means that the uncompressed backup will take 26 seconds which is faster than the 53 seconds using --compress. What ZSTD library are you using?!?!

**Comment by marcatsmci** [comment]
@davidducos 

results with compress removed, stream added and pipe to zstd as you suggested.

1- what I see is that the file obtained is 1.1G
2- the dump duration is 29s (not 53s as you wrote)

The version of mydumper is   `mydumper0.14.0-3, built against MySQL 8.0.30-22 with SSL support with ZSTD`

The version of ZSTD is : `*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***` (default package for Debian bullseye `https://packages.debian.org/bullseye/zstd`)

RED => `mysqldump... | zstd -q --fast=5 --threads=0`
BLUE => `mydumper... | zstd -q --fast=5 --threads=0`

![2023-02-22_mydumper](https://user-images.githubusercontent.com/47881838/220578085-fcb0e4a1-0226-431f-a9dd-f8c1f820993d.png)

I have been using mydumper on 2 other debian for about 10 days, without any problem but they have only 1 cpu, which is not very relevant to test parallelism.

**Comment by davidducos** [comment]
This file: https://github.com/mydumper/mydumper/files/10793055/230221.log.gz says:
```
2023-02-21 12:31:27 [INFO] - MyDumper backup version: 0.13.1-2
...
2023-02-21 12:32:20 [INFO] - Finished dump at: 2023-02-21 12:32:20
```
That is 53 seconds, which is similar of what you said in the first comment of the ticket. 
What I was trying to you to understand, is that mydumper is being faster without compression, which doesn't makes sense as ZSTD is faster. 
And then we have this other scenario where you pipe to zstd:
BLUE => `mydumper... | zstd -q --fast=5 --threads=0`
There, mydumper reported that it is sending 1.1GB of uncompressed data and zstd is "compressing" to get a file of 1.1GB... it is like it is not compressing the file... 
Can you review the content of the zstd files created by mydumper? 
Please, use something like this: `head -1 FILE | cut -b1-80`

**Comment by marcatsmci** [comment]
zstd file created by mydumper : 

```
file pwm-WD-3-H-14.sql.zst 
pwm-WD-3-H-14.sql.zst: Zstandard compressed data (v0.8+), Dictionary ID: None
```
`head` only applys on text files...

```
ls -ltrh
total 2.2G
-rw-r--r-- 1 root root 1.1G Feb 22 14:53 pwm-WD-3-H-14.sql.zst
-rw-r--r-- 1 root root 1.2G Feb 22 14:53 pwm-WD-3-H-14.sql
```

```
head pwm-WD-3-H-14.sql

-- pwm-schema-create.sql 117
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `pwm` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

-- pwm.accountingledger-schema.sql 1422
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
CREATE TABLE `accountingledger` (
  `IDENT` int(11) NOT NULL,
```

**Comment by davidducos** [comment]
I'm almost sure that this is not related to MyDumper, it is related to the ZSTD version that you are using.

**Comment by marcatsmci** [comment]
I installed the GZIP version : `mydumper0.14.0-3, built against MySQL 8.0.30-22 with SSL support with GZIP`

Even worse !

[230223-gzip.log.gz](https://github.com/mydumper/mydumper/files/10811241/230223-gzip.log.gz)

I really don't understand anything ;-(

**Comment by marcatsmci** [comment]
@davidducos 
as you said : _I'm almost sure that this is not related to MyDumper, it is related to the ZSTD version that you are using_

I tried without ZSTD to get a comparison point.

`--threads=2`  : [230223-zstd.log.gz](https://github.com/mydumper/mydumper/files/10816354/230223-zstd.log.gz)

Version :   `mydumper0.14.0-3, built against MySQL 8.0.30-22 with SSL support with ZSTD`

**Comment by davidducos** [comment]
37 seconds... makes sense now... you are overloading the server. Increase the cores on the server.

**Comment by marcatsmci** [comment]
> 37 seconds... makes sense now... 

For me, no! It takes 17 sec with mysqldump...

**Comment by davidducos** [comment]
Did you increase the cores on the server?

**Comment by marcatsmci** [comment]
The server is doing very well! No need to change its configuration, the customer is very happy and the performance is perfect for him.

Mydumpper has obviously a problem with this DB and I hope you will understand why. 

I unfortunately have to continue with mysqldump which is 2 times faster...
