### ISSUE TITLE
cannot connect to mysql since upgrade to 0.14.1-1 from 0.12.7

### ISSUE THREAD

**Issue by aqueos** [mydumper/mydumper#1049]
hi,

 i use mydumper like this since month:
mydumper --defaults-file=/etc/mysql/debian.cnf         --triggers --events --routines         --compress         --logfile=/var/backups/mysql/sauvergarde.2023-02-27-08h01.log         --outputdir=/var/backups/mysql/2023-02-27-08h01         --regex '^(?!(test\.|sys\.))'         --use-savepoints --less-locking         --long-query-guard 120 --kill-long-queries         --verbose 3  --lock-all-tables ;

since i upgraded to 0.14-1 this does not dump anymore but return : 
2023-02-27 07:56:23 [ERROR] - Error connection to database: Access denied for user 'root'@'localhost' (using password: NO)

  seems you modified the use of --defaults-file does it mean we have to create a special config file for mydumper and cannot anymore use the default debian configuration for authentification ??

best regards,
Ghislain.

**Comment by davidducos** [comment]
Sorry @aqueos, yeah, things changed related to how default-file is being used. It became more important I will check later today but I think that will be better in this way to avoid unexpected scenarios.

**Comment by aqueos** [comment]
hi,

  Thanks for the quick answer :)

  The debian default file is quite handy, we do not have to create maintain and sync users/pass between several files it just works with ease to dump and load for the whole debian/ubuntu family. 
  
  I agree it would be better to have one specific user with only read to dump and one only write to load just for the my(dumper|loader) tool in two specific configuration file but i dont know if this is how most people do it. This was permitting very easy setup on debian/ubuntu even for beginner sysadmin to implement backups this way.
  
best regards,
Ghislain.

**Comment by davidducos** [comment]
@aqueos, can you download and compile master to see if works as you expected?

**Comment by aqueos** [comment]
sorry david i failed compilation. I have perconna 8 on my machine and cmake 

-- Found mariadb_config: /usr/bin/mariadb_config
-- Using mysql-config: /usr/bin/mariadb_config
-- MySQL not found.
CMake Error at CMakeLists.txt:14 (MESSAGE):
  Could not find MySQL or MariaDB client libraries

i used instruction replacing the
apt-get install libperconaserverclient20-dev
by
apt-get install libperconaserverclient21-dev

sorry i did not found a way to get around, even installing libperconaserverclient20-dev destroying my v8.0 server do not helped here :(

regards,
Ghislain

**Comment by davidducos** [comment]
@aqueos, no worries, I can build a prerelease for you...

**Comment by aqueos** [comment]
it seems it failed 14.2-2 with

2023-02-28 15:51:52 [INFO] - Using default file: /etc/mysql/debian.cnf
2023-02-28 15:51:52 [WARNING] - Section mydumper not found
2023-02-28 15:51:52 [ERROR] - Error connection to database: Access denied for user 'root'@'localhost' (using password: NO)


[client]  section seems to not be taken in account :(


```
VSGUEST:root@testlxcfs:[~]: mysql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

VSGUEST:root@testlxcfs:[~]: mysql --defaults-file=/etc/mysql/debian.cnf 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 49
Server version: 8.0.31-23 Percona Server (GPL), Release '23', Revision '71449379'

Copyright (c) 2009-2022 Percona LLC and/or its affiliates
Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> quit
Bye


VSGUEST:root@testlxcfs:[~]: mydumper --defaults-file=/etc/mysql/debian.cnf         --triggers --events --routines         --compress         --logfile=/var/backups/mysql/sauvergarde.2023-02-28-15h50.log         --outputdir=/var/backups/mysql/2023-02-28-15h50         --regex '^(?!(test\.|sys\.))'  --use-savepoints --less-locking         --long-query-guard 120 --kill-long-queries         --verbose 3  --lock-all-tables ;


VSGUEST:root@testlxcfs:[~]: more /var/backups/mysql/sauvergarde.2023-02-28-15h50.log
2023-02-28 15:51:52 [INFO] - MyDumper backup version: 0.14.2-2
2023-02-28 15:51:52 [INFO] - Using default file: /etc/mysql/debian.cnf
2023-02-28 15:51:52 [WARNING] - Section mydumper not found
2023-02-28 15:51:52 [ERROR] - Error connection to database: Access denied for user 'root'@'localhost' (using password: NO)

VSGUEST:root@testlxcfs:[~]: date
Tue 28 Feb 2023 03:52:02 PM CET

VSGUEST:root@testlxcfs:[~]: mydumper --version
mydumper0.14.2-2, built against MySQL 8.0.31-23 with SSL support with ZSTD

```

**Comment by davidducos** [comment]
Oh no, wait, when you use the --defaults-file, mydumper will expect `[mydumper]`, if you don't use anything, then the mysql library it will load the defaults file for the connection. 
Ok, so what you want is that if `[mydumper]` is not found but you are using --defaults-file then we still load `[client]`... mmmm ok, I think that it is doable...

**Comment by aqueos** [comment]
hi,

 i just tried the latest  pre release but it fail also and cannot use the [client] part like in the 0.12- versions.
 I have some issues with the 0.12 version but i cannot upgrade to any new ones as it now impossible to connect to mysql unless i go to every machines one by one to add that specific section in the debian.cnf.

i can share a very bad puppet recipe to recover pre 0.14 way of working to prevent all backup to sudenly fail:

```

                # ajoute l'auth pour mydumper 0.14+
                # si le fichier existe et seulement si on ne l'a pas deja fait
                exec { 'debiancnfmydumper':
                                onlyif  => 'test -f /etc/mysql/debian.cnf',
                                unless  => 'grep -q mydumper /etc/mysql/debian.cnf',
                                command => "echo '[mydumper]' >> /etc/mysql/debian.cnf && grep -E -m 2  '^(user|password)' /etc/mysql/debian.cnf |tee -a /etc/mysql/debian.cnf",
                                user    => 'root',
                }
```


best regards,
Ghislain.
