### ISSUE TITLE
** (mydumper:58850): WARNING **: 16:44:33.911: Section mydumper not found

### ISSUE THREAD

**Issue by myabce** [mydumper/mydumper#1050]
when use mydumper backup database , met a warning :

** (mydumper:58850): WARNING **: 16:44:33.911: Section mydumper not found

OS: Debian GNU/Linux 10 (buster)

**Comment by yoni-yad2** [comment]
The warning I got was at a different line:

** (mydumper:8527): WARNING **: 07:06:13.214: Section mydumper not found

**Comment by yoni-yad2** [comment]
Thanks for the clarification.
