### ISSUE TITLE
New lines needs to be removed from values in the metadata file

### ISSUE THREAD

**Issue by akilanrajmahendran** [mydumper/mydumper#1056]
Hi team , 

### myloader issue while restoring data if dumped with --no-schemas option 

I am trying to backup and restore the structure and data separately.
Loading data file is not working as expected. 

versions tested  : 0.12.7-3  and 0.14.1-1

dump command : (only structure) 

`++ /bin/mydumper -u uname --password=pwd -h localhost -P 3306 --database=my_backup --tables-list=my_backup.table --no-data --outputdir=/data/backup/fast_12/backup/table/ --threads=2`

load command : (only structure) 

`/bin/myloader -u uname --password=pwd -h localhost -P 3306 --source-db=backup --directory=/data/backup/fast_12/backup/table/  --compress  --compress-protocol  --threads=2`

structure is loaded properly. 

dump command : (only data) 

 `/bin/mydumper -u uname --password=pwd -h localhost -P 3306 --database=my_backup --no-schemas --tables-list=my_backup.table --outputdir=/data/backup/slow_09/backup/table/  --compress --compress-protocol --threads=2`
 
 
 issue on data loading :
 
 
 versions tested  : 0.12.7-3  

```
 /bin/myloader -u uname --password=pwd -h localhost -P 3306 --source-db=backup --directory=/data/backup/slow_09/backup/table/ --queries-per-transaction=100 --threads=2
 [root@ip logmig]# echo $?
0
[root@ip logmig]# mysql 
MariaDB [(none)]> select count(*) from my_backup.table;
+----------+
| count(*) |
+----------+
|       20 |
+----------+
1 row in set (0.002 sec)

MariaDB [(none)]> select count(*) from backup.table;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.003 sec)


```

  versions tested  : 0.14.1-1
  
  
` /bin/myloader -u uname --password=pwd -h localhost -P 3306 --source-db=backup --directory=/data/backup/slow_09/backup/table/ --queries-per-transaction=100 --threads=2`
 
error :  

```
** (myloader:4936): WARNING **: 15:17:32.009: Failed to load config file  //data/backup/slow_09/backup/table/ metadata : Key file contains line “	Connection name: ” which is not a key-value pair, group, or comment
** (myloader:4936): ERROR **: 15:17:32.009: Global metadata file processing was not possible
```

 
 Please let me know in case of any issues or dependencies . 

Thanks ,
Akilan RM.

**Comment by davidducos** [comment]
Hi @akilanrajmahendran,
Restores with a different version are not supported.

**Comment by akilanrajmahendran** [comment]
Hi davidducos, 

I had triggered  dump and restore using same  version only . 
first tested with version 0.12.7 later with 0.14.1 for both dumper and loader. 

Please let me know if you need more clarity in it . 


Thanks ,
Akilan RM.

**Comment by davidducos** [comment]
This errors:
```
** (myloader:4936): WARNING **: 15:17:32.009: Failed to load config file  //data/backup/slow_09/backup/table/ metadata : Key file contains line “	Connection name: ” which is not a key-value pair, group, or comment
** (myloader:4936): ERROR **: 15:17:32.009: Global metadata file processing was not possible
```
means that you were trying to restore a backup v0.12.7 with v0.14.1

**Comment by akilanrajmahendran** [comment]
Hi  davidducos,

I  have tested  it with latest version now again . 
it was for both dump and restoration . 
please check the logs for dump file created. 



```
[root@bl-ip table]# ls -lrth
dtotal 0
-rwxrwxrwx. 1 root root 2.0M Mar  1 16:21 my_backup.table.00000.sql.gz
-rwxrwxrwx. 1 root root 2.4K Mar  1 16:21 metadata
[root@bl-ip table]# date
Wed Mar  1 16:25:26 CET 2023
[root@bl-ip table]# mydumper --version 
mydumper0.14.1-1, built against MySQL 5.7.40-43 with SSL support with GZIP
```


still facing the same error while restoring . 


error : 

```
** (myloader:11403): ESC[1;31mERRORESC[0m **: ESC[34m16:24:24.299ESC[0m: Global metadata file processing was not possible
+ a=133
```

I have tested it with different output path as well for a fresh backup . It is for our server side restricted storage confirmation . 
it is reflecting the same while restoration . 

please let me know in case of any dependencies . 


Thanks ,
Akilan RM.

**Comment by davidducos** [comment]
Can you upload the metadata file?

**Comment by akilanrajmahendran** [comment]
Hi Davidducos, 

Please check the metadata information shared below . 
Let me know in case of further dependencies.

```
# Started dump at: 2023-03-01 16:32:51
[master]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
File = binlog.000099
Position = 87762290
Executed_Gtid_Set = 0-10-37746907

[replication]
	Connection name: 
# relay_master_log_file = 'binlog.000157'
# exec_master_log_pos = 800377294
# Gtid_Slave_Pos = 0-10-37746907
# Connection_name = ''
# Slave_SQL_State = 'Slave has read all relay log; waiting for more updates'
# Slave_IO_State = 'Waiting for master to send event'
# Master_Host = 'ip'
# Master_User = 'ngslave'
# Master_Port = 3306
# Connect_Retry = 10
# Master_Log_File = 'binlog.000157'
# Read_Master_Log_Pos = 800377294
# Relay_Log_File = 'bl-mdb-1-relay-bin.000099'
# Relay_Log_Pos = 124299152
# Relay_Master_Log_File = 'binlog.000157'
# Slave_IO_Running = 'Yes'
# Slave_SQL_Running = 'Yes'
# Replicate_Do_DB = ''
# Replicate_Ignore_DB = ''
# Replicate_Do_Table = ''
# Replicate_Ignore_Table = ''
# Replicate_Wild_Do_Table = ''
# Replicate_Wild_Ignore_Table = ''
# Last_Errno = 0
# Last_Error = ''
# Skip_Counter = 0
# Exec_Master_Log_Pos = 800377294
# Relay_Log_Space = 124299464
# Until_Condition = 'None'
# Until_Log_File = ''
# Until_Log_Pos = 0
# Master_SSL_Allowed = 'No'
# Master_SSL_CA_File = ''
# Master_SSL_CA_Path = ''
# Master_SSL_Cert = ''
# Master_SSL_Cipher = ''
# Master_SSL_Key = ''
# Seconds_Behind_Master = 0
# Master_SSL_Verify_Server_Cert = 'No'
# Last_IO_Errno = 0
# Last_IO_Error = ''
# Last_SQL_Errno = 0
# Last_SQL_Error = ''
# Replicate_Ignore_Server_Ids = ''
# Master_Server_Id = 10
# Master_SSL_Crl = ''
# Master_SSL_Crlpath = ''
# Using_Gtid = 'No'
# Gtid_IO_Pos = ''
# Replicate_Do_Domain_Ids = ''
# Replicate_Ignore_Domain_Ids = ''
# Parallel_Mode = 'optimistic'
# SQL_Delay = 0
# SQL_Remaining_Delay = (null)
# Slave_SQL_Running_State = 'Slave has read all relay log; waiting for more updates'
# Slave_DDL_Groups = 0
# Slave_Non_Transactional_Groups = 0
# Slave_Transactional_Groups = 38941
# Retried_transactions = 0
# Max_relay_log_size = 1073741824
# Executed_log_entries = 359122
# Slave_received_heartbeats = 4383
# Slave_heartbeat_period = '30.000'
# Gtid_Slave_Pos = '0-10-37746907'
# myloader_exec_reset_slave = 0 # 1 means execute the command
# myloader_exec_change_master = 0 # 1 means execute the command
# myloader_exec_start_slave = 0 # 1 means execute the command

[`my_backup`.`table`]
Rows = 66311
# Finished dump at: 2023-03-01 16:32:51
```


Thanks ,
Akilan RM.

**Comment by davidducos** [comment]
THANKS! yes, this is bug because of those 3 lines. I will be fixing it asap.

**Comment by davidducos** [comment]
Can you check with master? I was not able to test the fix on the linked PR
