### ISSUE TITLE
[BUG]inaccurate binlog position in mydumper metadata file

### ISSUE THREAD

**Issue by Chehai** [mydumper/mydumper#1062]
**Describe the bug**

binlog position in the metadata file does not match rows in data dump files (like db.table.00000.sql).

**To Reproduce**
1. Create a database and a table in mysql (8.0.31, binlog enabled by default).
```
create database bug_binlog;
create table bug_binlog.t (id int not null auto_increment, data varchar(255), primary key (id));
```
2. Create a script `insert.sh` to insert data in an infinite loop.
```
#!/bin/bash
while true
do
	mysql -e 'insert into bug_binlog.t(data) values (md5(rand()))'
done
```
3. Run the script `./insert.sh`.
4. At another terminal, run `mydumper --trx-consistency-only --database bug_binlog -o bug_binlog`.
5. Stop `./insert.sh` with `ctrl-c`.
6. `tail -n 5 bug_binlog/bug_binlog.t.00000.sql`. Look at `id` of the last record.
7. `cat bug_binlog/metadata`. Look at File (`binlog_file`) and Position (`binlog_position`).
8. `mysqlbinlog --verbose --base64-output=DECODE-ROWS binlog_file` to look at the content around `binlog_position`.
9. The last record in `bug_binlog/bug_binlog.t.00000.sql` is not the record that was inserted just before `binlog_position`. 

What mydumper and myloader version has been used?
`mydumper0.14.1-1, built against MySQL 8.0.32 with SSL support with GZIP`

**Expected behavior**
binlog position in the metadata file matches rows in data dump files (like db.table.00000.sql).

**Log**
```
** Message: 15:49:10.368: MyDumper backup version: 0.14.1-1
** Message: 15:49:10.368: Using no configuration file

** (mydumper:19255): WARNING **: 15:49:10.369: Using trx_consistency_only, binlog coordinates will not be accurate if you are writing to non transactional tables.
** Message: 15:49:10.389: Server version reported as: 8.0.31
** Message: 15:49:10.389: Connected to a MySQL server
** Message: 15:49:10.390: Sending Flush Table
** Message: 15:49:10.390: Acquiring FTWRL
** Message: 15:49:10.391: Started dump at: 2023-03-02 15:49:10
** Message: 15:49:10.391: conf created
** Message: 15:49:10.391: End job creation
** Message: 15:49:10.391: Creating workers
** Message: 15:49:10.391: Starting Non-InnoDB tables
** Message: 15:49:10.422: Thread 1: connected using MySQL connection ID 962
** Message: 15:49:10.422: Thread 4: connected using MySQL connection ID 964
** Message: 15:49:10.422: Thread 2: connected using MySQL connection ID 963
** Message: 15:49:10.423: Thread 3: connected using MySQL connection ID 965
** Message: 15:49:10.425: Thread 1: Creating Jobs
** Message: 15:49:10.425: Thread 1: dumping db information for `bug_binlog`
** Message: 15:49:10.425: Thread 4: Creating Jobs
** Message: 15:49:10.426: Thread 2: Creating Jobs
** Message: 15:49:10.427: Thread 3: Creating Jobs
** Message: 15:49:10.427: Transactions started, unlocking tables
** Message: 15:49:10.427: Waiting database finish
** Message: 15:49:10.431: Thread 2: Schema queue
** Message: 15:49:10.431: Thread 4: Schema queue
** Message: 15:49:10.431: Shutdown jobs for less locking enqueued
** Message: 15:49:10.431: Thread 3: Schema queue
** Message: 15:49:10.431: Thread 3: dumping schema for `bug_binlog`.`t`
** Message: 15:49:10.431: Thread 4: dumping schema create for `bug_binlog`
** Message: 15:49:10.431: Thread 1: Schema queue
** Message: 15:49:10.431: Thread 1: Schema Done, Starting Non-Innodb
** Message: 15:49:10.431: Written master status
** Message: 15:49:10.431: Non-InnoDB tables completed
** Message: 15:49:10.431: Starting InnoDB tables
** Message: 15:49:10.431: Thread 1: Non-Innodb Done, Starting Innodb
** Message: 15:49:10.431: Thread 4: Schema Done, Starting Non-Innodb
** Message: 15:49:10.431: Thread 4: Non-Innodb Done, Starting Innodb
** Message: 15:49:10.431: InnoDB tables completed
** Message: 15:49:10.431: Thread 4: shutting down
** Message: 15:49:10.431: Waiting threads to complete
** Message: 15:49:10.431: Thread 2: Schema Done, Starting Non-Innodb
** Message: 15:49:10.431: Thread 2: Non-Innodb Done, Starting Innodb
** Message: 15:49:10.431: Thread 2: shutting down
** Message: 15:49:10.432: Thread 3: Schema Done, Starting Non-Innodb
** Message: 15:49:10.432: Thread 3: Non-Innodb Done, Starting Innodb
** Message: 15:49:10.432: Thread 3: shutting down
** Message: 15:49:10.432: Thread 1: dumping data for `bug_binlog`.`t`          into bug_binlog/bug_binlog.t.00000.sql| Remaining jobs in this table: 0
** Message: 15:49:10.432: Thread 1: shutting down
** Message: 15:49:10.433: Queue count: 0 0 0 0 0
** Message: 15:49:10.433: Main connection closed
** Message: 15:49:10.434: Finished dump at: 2023-03-02 15:49:10
```
**Backup**

**How to repeat**

**Environment (please complete the following information):**
 - OS version: Amazon Linux 2, MacOS Ventura 13.2.1 (22D68) 
 - MyDumper version: mydumper0.14.1-1, built against MySQL 8.0.32 with SSL support with GZIP

**Additional context**

**Comment by Chehai** [comment]
We only use InnoDB tables, so `--trx-consistency-only` should work according to mydumper's documentation, right?

**Comment by davidducos** [comment]
No, and I think that I will remove that option as it is pointless nowadays

**Comment by thadraibley** [comment]
So is there no way with mydumper to take a transitionally consistent snapshot against an active database?

**Comment by davidducos** [comment]
That is the default on MyDumper... 
the only way to do not take a consistent snapshot is using --no-locks, and even thought if you are using Percona >= 5.7 and gtid_mode ON, you might be able to take a consistent snapshot...

**Comment by davidducos** [comment]
Hi @Chehai, 
Huge mistake from my side... will fix shortly.

**Comment by davidducos** [comment]
Hi @Chehai, 
I wanted to apologize to you, as I didn't work on this issue as I used to, or maybe I did, but I didn't find the right solution. 
I want to state 2 things:
1- --trx-consistency-only should be use if you are 100% that all the tables that you are going to export are Innodb or any other transactional engine. 
2- This issue only affects to PS57, so on previous version to v0.15.1, if you have gtid on you should use --no-locks.
