### ISSUE TITLE
Shema and data file names

### ISSUE THREAD

**Issue by montes2012** [mydumper/mydumper#1063]
It can be the name of the database.table

It can be the name of the database.table as you can see in this image:
![image](https://user-images.githubusercontent.com/3384541/222620241-7eeb914d-d62b-4e2c-962e-7ffde57a02f4.png)

'W_ALFZ$BHZ$OM.alfz$bhz$om$$2016_07_21.sql'

not this

![image](https://user-images.githubusercontent.com/3384541/222621390-f98de46e-32c7-43ec-8916-c9c6d6cd3744.png)

mydumper_0.mydumper_690.00000.sql
mydumper_0.mydumper_691.00000.sql
mydumper_0.mydumper_692.00000.sql
mydumper_0.mydumper_693.00000.sql
mydumper_0.mydumper_694.00000.sql

mydumper --database=W_ALFZ\$BHZ\$OM --host=192.168.102.200 --port=3312 --user=root --password= --no-data -o /mnt/dataMySQL/dumps/test_alf/tablas/ --verbose=3 --kill-long-queries

mydumper --database=W_ALFZ\$BHZ\$OM --host=192.168.102.200 --port=3312 --user=root --password= --hex-blob --insert-ignore --no-schemas --rows=10000 -t 8 -o /mnt/dataMySQL/dumps/test_alf/datos/ --verbose=3 --kill-long-queries

**Comment by davidducos** [comment]
@montes2012,

I understand that you might want to use `$` in your database and table names, but we decided to use a referential table to avoid issue when we parse the filenames. 

If the problem/question that you have is related to filtering options, we are using the real database and table names, if it is not working at expected, then we have a bug.

**Comment by montes2012** [comment]
is a bug

**Comment by montes2012** [comment]
![image](https://user-images.githubusercontent.com/3384541/222860922-c624e491-34cf-4afa-bad4-29d0877bd0ff.png)

**Comment by davidducos** [comment]
@montes2012, 
Please, help me to understand. What is the issue that you have? Take into account that we are not using the database and table name to build the filename, we changed that a long time ago and we are not going to change it back. Again, please, help me to understand what is the problem that you have?
