### ISSUE TITLE
[BUG] CRITICAL error about can not remove import directory

### ISSUE THREAD

**Issue by yaskinny** [mydumper/mydumper#1073]
**Describe the bug**
When restoring in stream mode after finishing successful restore(I'm not sure if it really successful or not, but I can see in logs it prints everything is imported), I get an error with severity CRITICAL. Exit code is **0**

I think the problem is import directory isn't empty, it does not remove `db.tbl.00000.sql` file. thats why it can not removes the directory(?)

**To Reproduce**
Command executed:
`cat backupfile.sql | myloader --stream`
or any kind of streaming like
`mydumper --database=x --stream | myloader --database=y --stream`
What mydumper and myloader version has been used?
`myloader0.14.1-1, built against MySQL 5.7.40-43 with SSL support with GZIP`
running inside of container based on ubuntu focal. installed from github releases deb packages. 
**Expected behavior**
don't have any error

**Log**
```
** Message: 18:56:43.375: Intermediate queue: Sending END job
** Message: 18:56:43.375: Intermediate thread ended
** Message: 18:56:43.376: Thread 1: restoring `db`.`tbl` part 1 of 1 from db.tbl.00000.sql. Progress 1 of 1.
** Message: 18:56:43.377: Intermediate thread: SHUTDOWN
** Message: 18:56:43.381: Thread 3: Data import ended
** Message: 18:56:43.381: Thread 2: Data import ended
** Message: 18:56:43.384: Thread 4: Data import ended
** Message: 18:56:43.588: Removing file: /tmp/tmp.QkXVdyre06-asd/import-20230314-185643/db.tbl.00000.sql
** Message: 18:56:43.588: Thread 1: Data import ended
** Message: 18:56:43.589: Thread 1: Starting post import task over table
** Message: 18:56:43.589: Thread 4: Starting post import task over table
** Message: 18:56:43.589: Thread 3: Starting post import task over table
** Message: 18:56:43.589: Thread 2: Starting post import task over table
** Message: 18:56:43.591: Starting table checksum verification
** Message: 18:56:43.591: Removing file: /tmp/tmp.QkXVdyre06-asd/import-20230314-185643/metadata

** (myloader:1299): CRITICAL **: 18:56:43.591: Restore directory not removed: /tmp/tmp.QkXVdyre06-asd/import-20230314-185643
```

**Comment by yaskinny** [comment]
I also get this warnings for both dumper and loader(same message just different name and line number):
`** (myloader:1373): WARNING **: 19:08:44.600: Section myloader not found`

**Comment by davidducos** [comment]
Hi @yaskinny , I think that both issues has been fixed on master. I will be creating a prerelease, so you can test and confirm.

**Comment by davidducos** [comment]
Pre release created, closing now, please let me know if you have more issues.
