### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lkotzian-boku** [mydumper/mydumper#1085]
**Describe the bug**
The mydumper runs for a long time (and never finishes) and utilizes more memory until hitting the system memory limit. 
It happens for the specific tables when (2 scenarios):
- the primary key is stored as varchar (values examples: '000000016a6bf5deb56283b6','fffffffb14123502a0b90cc5') 
- the primary key "spread" is large.  For example, the table includes 277600030 rows, but the difference between maximum and minimum PK values reaches 1018347689605371794.

In my situation, after the mydumper reached OS memory limit, it caused to crash mysqld (which was running on the same node as mydumper).

**To Reproduce**
The framework command which was executed:
* mydumper  -T ...  --compress --chunk-filesize 1000  --threads 4 --no-locks --rows 1000000 -v 3 --outputdir ...  -L ...

What mydumper version has been used?
mydumper version used - mydumper0.14.1-1, built against MySQL 5.7.40-43 with SSL support with ZSTD

**Expected behavior**
The messages about remaining "jobs" shows high number of jobs, for example: Remaining jobs in this table: 1012323327848

**How to repeat**
create table with numeric PK, and populate with min and max PK values are widely spread apart.

**Environment (please complete the following information):**
 - OS version: CentOS Linux release 7.7.1908 (Core)
 - MyDumper version: mydumper version used - mydumper0.14.1-1, built against MySQL 5.7.40-43 with SSL support with ZSTD

**Comment by davidducos** [comment]
Hi @lkotzian-boku, Can you test with the latest prerelease?

**Comment by davidducos** [comment]
```
the primary key "spread" is large. For example, the table includes 277600030 rows, but the difference between maximum and minimum PK values reaches 1018347689605371794.
```
^ has been fixed on #1084

**Comment by davidducos** [comment]
@lkotzian-boku feel free to use https://github.com/mydumper/mydumper/releases/tag/v0.14.2-10

**Comment by lkotzian-boku** [comment]
Hello @davidducos - 
yes, I've used 14.2:
mydumper --version
mydumper0.14.2-10, built against MySQL 5.7.41-44 with SSL support with ZSTD

mydumper syntax:
mydumper --rows 1000000 -v 3  -T DB_NAME.TABLE_NAME --compress --chunk-filesize 1000  --threads 6 --no-locks --outputdir ./DB_NAME/TABLE_NAME  -L DB_NAME.TABLE_NAME.log

the mydumper is running for 6 hrs, and did not run out of the memory.
However it is still running the table size (data + indexes) occupies 32GB. The mysqldump single thread executed in 5 minutes. 

Seeing this log:
2023-04-03 17:33:23 [INFO] - Thread 6: dumping data for `DB_NAME`.`TABLE_NAME`  WHERE (  ( 620106050024522923 < `ID` AND `ID` <= 620106050025522923))       into ./DB_NAME/TABLE_NAME/DB_NAME.TABLE_NAME.00002.sql.zst| Remaining jobs in this table: 1012348723753

**Comment by davidducos** [comment]
Hi @lkotzian-boku ,
Now you can use latest release v0.14.3-1 and please, use the feature added to fix this issue. Now, when you use --rows you can select the min value, starting point value and max value which can be unlimited. I recommend you to use this: --rows 10000:1000000:0 which means 10000 for minimal amount of rows, your setting at 1000000 will be the starting point, and finally there will be no limit on the amount of rows.
```
  -r, --rows                       Splitting tables into chunks of this many rows. It can be MIN:START_AT:MAX. MAX can be 0 which means that there is no limit. It will double the chunk size if query takes less than 1 second and half of the size if it is more than 2 seconds
```

**Comment by davidducos** [comment]
Hi @lkotzian-boku , I'm going to build prerelease v0.14.4-1 for you with this fix.

**Comment by davidducos** [comment]
https://github.com/mydumper/mydumper/releases/tag/v0.14.4-1 is available

**Comment by davidducos** [comment]
Thank you to report so many bugs and make MyDumper better!

**Comment by lkotzian-boku** [comment]
Executed the remaining tests without problem. I do have one more question, and please let me know if I should take it out and post it somewhere else to avoid trashing the github). Does "--max-threads-for-index-creation"  option really spawn multiple ALTERs for the same table?

**Comment by davidducos** [comment]
Depending on the kind of indexes that the table has, but we tried to create all the indexes in the less amount of ALTER as possible and there will be ALTER per table at a time.
