### ISSUE TITLE
GTIDs with carriage returns causes metadata file to be unusable

### ISSUE THREAD

**Issue by SingingArrowRose** [mydumper/mydumper#1086]
I have a metadata file that looks like this
```
# Started dump at: 2023-03-30 18:01:45
[master]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
File = mysql-bin-changelog.194656
Position = 694
Executed_Gtid_Set = 208389f9-c558-11eb-bfdc-02bd2e549d49:1-6586949655,
2f65bc8b-ba1b-11ea-a5bc-069d047c9d40:1-2426150392,
b7c82ba7-ad73-11ed-9654-066947978545:1-12191,
c65ac912-c7f4-11eb-809f-02169839e16d:1-17600


[`database`.`table`]
Rows = 55
# Finished dump at: 2023-03-30 18:01:47
```

The myloader is failing, because it doesn't expect the extra Executed log sets on new lines.  The code that prints this is here:
https://github.com/mydumper/mydumper/blob/5b24c347cc6cd88213aff0e89af17591f90507f2/src/mydumper_working_thread.c#L643

It would probably be most accurate if the myloader code recognized that the ',' at the end of the Executed_Gtid_Set meant that there was another line, but you could take the '\n' out of the Executed_Gtid_Set when you print it and that should also work.

Also, I am not using the GTID on the restore, so I'd be happy if I could just suppress the [master] data in the metadata.  It doesn't seem like that is possible looking at the code.

Thank you 
Singing Arrow Rose
singingarrowman@gmail.com

**Comment by davidducos** [comment]
Hi @SingingArrowRose, I think that you are using a previous version, as this issue has been already addressed on this like: https://github.com/mydumper/mydumper/blob/5b24c347cc6cd88213aff0e89af17591f90507f2/src/mydumper_working_thread.c#L627
