### ISSUE TITLE
[BUG] debian buster package is missing zstd deps, fail to restore 

### ISSUE THREAD

**Issue by grinapo** [mydumper/mydumper#1097]
**Describe the bug**
A dump created on bullseye with same version cannot be restored on buster, since buster myloader is missing libzstd1 compiled in.

Bullseye version also seems to be unable to create gzipped versions.

**Environment (please complete the following information):**
 - OS version: Debian buster (vs. bullseye)
 - MyDumper version: 
     - mydumper0.14.3-1, built against MySQL 5.7.41-44 with SSL support with GZIP
     - mydumper0.14.3-1, built against MySQL 8.0.32-24 with SSL support with ZSTD

**Comment by davidducos** [comment]
Hi @grinapo,
You must use same compression method on both ends. You can NOT use ZSTD package to backup and GZIP package to restore!! You can use --exec-per-thread if you want any other specific compression method and when we implement https://github.com/mydumper/mydumper/issues/924, we might be able to remove the GZIP and ZSTD support from MyDumper.
