### ISSUE TITLE
compress and rsyncable

### ISSUE THREAD

**Issue by rbro** [mydumper/mydumper#11]
When using the --compress option, is it possible to create the gz files using the --rsyncable option of gzip?  When I run mysqldump, I always pipe it to gzip --rsyncable like:

`mysqldump ... | gzip --rsyncable > backup.sql.gz`

Thanks for your help.

**Comment by maxbube** [comment]
Hi, 

I will check this, but last time I did it there were no support for this on the lib

**Comment by kehh** [comment]
:+1:

**Comment by braco** [comment]
👍

Is the pipe method orders of magnitude slower?

**Comment by enboig** [comment]
:+1:

**Comment by Catscrash** [comment]
anyone have any news on this?

**Comment by Catscrash** [comment]
I modified the code and created a Pull Request for this: #190

**Comment by davidducos** [comment]
I think that we can close it now.
