### ISSUE TITLE
Loading wrong config files

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1123]
Hi @MJabirBaig,

What is the content of /etc/my.cnf ?? I almost sure that it doesn't contain the groups that myloader needs. Anyways, we have a bug as it should not show those entries

_Originally posted by @davidducos in https://github.com/mydumper/mydumper/issues/440#issuecomment-1540565085_

**Comment by MJabirBaig** [comment]
Hi David,

i don't have any entries related to mydumper.myloader in my.cnf, i am using my default configuration file as --defaults-file=/etc/my.cnf, what ever the config setting in /etc/mydumper.cnf we have in my.cnf, i am using the below command to load data
`myloader --user=dba --ask-password --socket=/database/mysql/mysql.sock --threads=8 --overwrite-tables --verbose=3 --defaults-file=/etc/my.cnf --directory=/database/backup/mydumper/fullbackup --logfile=/database/backup/mydumper/fullbackup_restore.log`

and if we have a bug in `mydumper-0.14.3-1-zstd.el7.x86_64.rpm` version, which version can i use now, will there be a new release soon
