### ISSUE TITLE
ZSTD version do not support gzip and running a long time before stopping doing nothing

### ISSUE THREAD

**Issue by aqueos** [mydumper/mydumper#1128]
hi,

 i dont know if we can call this a bug but it seems strange:

source :       mydumper0.14.3-1, built against MySQL 5.7.41-44 with SSL support with GZIP  more than 6gb database
destination:  myloader0.14.3-1, built against MySQL 8.0.32-24 with SSL support with ZSTD

When i try import all the gz files are ignored. Seems the ZSTD version do not support zstd+gzip but only zstd ?

It would seems that having both should be a good thing here  :) 
needing to change the package when importing data from another older server seems odd to me as mostly new compression algorithm are added to the older ones instead of replacing them. Those 2 are widely used so having both would be great :)

If we can only have one compression method could be have a better message than 'file ignored' and have 'this version does not support .gz files, please uncompress them" because it confused me a lot and i took ages to understand the issue ?

 i took long time to understand as myloader kept running 100% cpu and hours after ignoring ALL the files and ended doing not any data recovery at all. And i failed to understand that is the files where really completly ignored as  it would take hours and lots of cpu to just stop doign nothing in the end :)

regards,
Ghislain.

**Comment by davidducos** [comment]
Hi @aqueos,

Ok, let me address all the issues/inquires
1- About GZIP and ZSTD, honestly, I implemented zstd in the faster way possible: using the zlib wrapper. That is why I had to release 2 packages. Having both compression method would be nice but might be hard to support at long term. Actually, I think that I will stop supporting compression and start using external commands, once I implement https://github.com/mydumper/mydumper/issues/924. Then user will decide which compression or other command wants to use.

2-  Yes, true, I could check file extension, sorry about that. 

3- About myloader running for a long time using 100% cpu is weird. Can you create a test case ?

**Comment by davidducos** [comment]
@aqueos 
FYI the latest prerelease published support GZIP and ZSTD, has a better file handling and you might find that works for you use case. Please, let me know if you still have issues. Closing this for now...
