### ISSUE TITLE
[BUG]Backup is in the waiting state for a long time

### ISSUE THREAD

**Issue by Charles7c** [mydumper/mydumper#1131]
**Describe the bug**
While performing the backup to the end, stuck, keeps showing wait but does nothing.

**To Reproduce**
Command executed:
* mydumper -h {} -P {} -u {} -p {} -B {} -E -R -G -C -c -t {} -k -F 1 -s 4000000 -v 3 -l 360 --complete-insert -o /data

**Expected behavior**
Normal backup completed.

**Environment (please complete the following information):**
 - OS version: CentOS 7.5
 - MyDumper version: v0.14.4-6

**Additional context**
<img width="900" alt="1" src="https://github.com/mydumper/mydumper/assets/25446948/9c23c585-dbca-4912-9f27-f3a54849e628">

**Comment by Charles7c** [comment]
> @Charles7c what `show processlist` says? As thread 1, 3 and 4, seams that are doing something...

Yes, eventually it ends, but the splicing process takes a long time and doesn't show any progress.

**Comment by Charles7c** [comment]
900 megabytes of data took nearly an hour, including more than 40 minutes for the final process.

**Comment by davidducos** [comment]
Hi @Charles7c, can you test with latest published prerelease? https://github.com/mydumper/mydumper/releases/tag/v0.15.0-6 ??

**Comment by Charles7c** [comment]
> Hi @Charles7c, can you test with latest published prerelease? https://github.com/mydumper/mydumper/releases/tag/v0.15.0-6 ??

Hi @davidducos , I have tested with the latest published prerelease and it’s working fine now. 😄 👍
