### ISSUE TITLE
[BUG]:Segmentation Fault Error While Using Myloader on mydumper-0.14.3-1.x86_64

### ISSUE THREAD

**Issue by MJabirBaig** [mydumper/mydumper#1133]
Hi,
I am getting segmentation fault issue on mydumper-0.14.3-1.x86_64(mydumper-0.14.3-1-zstd.el7.x86_64.rpm), i am using the following command to import and i have enabled the parameters in mydumper.cnf file

+ AURG='--defaults-file=/etc/mydumper.cnf --socket=/database/mysql/mysql.sock --threads=12 --overwrite-tables --enable-binlog --queries-per-transaction=1500 --verbose=3 --directory=/opt/backup/test01p1/mydumper/fullbackup-2023-05-17_00-40-45 --logfile=/mysqllogs/tmp/backup/MYLOADER-FULLBACKUP-IMPORT-2023-05-18_04-15-22.log'
+ myloader --defaults-file=/etc/mydumper.cnf --socket=/database/mysql/mysql.sock --threads=12 --overwrite-tables --enable-binlog --queries-per-transaction=1500 --verbose=3 --directory=/opt/backup/test01p1/mydumper/fullbackup-2023-05-17_00-40-45 --logfile=/mysqllogs/tmp/backup/MYLOADER-FULLBACKUP-IMPORT-2023-05-18_04-15-22.log
/home/mysql/scripts/myloader_import.sh: line 247: 12210 **Segmentation fault**      myloader $AURG > $ERRORLOG 2>&1
++ grep -w ERROR /mysqllogs/tmp/backup/MYLOADER-FULLBACKUP-IMPORT-2023-05-18_04-15-22.log

can i have a solution for this

this is my mydumper.cnf file

`[client]
user=test
password=Password@321

[mydumper]
triggers=true
events=true
routines=true
compress=true
threads=12
rows=50000

[mydumper_global_variables]

sync_binlog = 0
sql_mode="NO_ENGINE_SUBSTITUTION"

[mydumper_session_variables]
wait_timeout = 600
#sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
#sql_mode='ANSI_QUOTES';

[myloader]
threads=12
queries-per-transaction=1500
verbose=3
max-threads-per-table=4
innodb-optimize-keys=AFTER_IMPORT_PER_TABLE
rows=5000
overwrite-tables=true
enable-binlog=true
serialized-table-creation=true
#sql_mode='NO_ENGINE_SUBSTITUTION'

[myloader_global_variables]
#sync_binlog = 0
innodb_flush_log_at_trx_commit = 0
#sql_mode="NO_ENGINE_SUBSTITUTION"

[myloader_session_variables]
#SQL_MODE='NO_AUTO_VALUE_ON_ZERO' /*!40101
#SQL_MODE='NO_ENGINE_SUBSTITUTION'
#UNIQUE_CHECKS=0 /*!40114
#FOREIGN_KEY_CHECKS=0 /*!40114

#sync_binlog = 0
innodb_flush_log_at_trx_commit = 0

[myloader_session_variables_mariadb]
# This setting replaces the default in the section [myloader_session_variables]. More details in #987
#UNIQUE_CHECKS=1 /*!40114
`

Log File Output:
2023-05-18 04:27:23 [INFO] - Using default file: /etc/mydumper.cnf
2023-05-18 04:27:23 [INFO] - Config file loaded
2023-05-18 04:27:23 [INFO] - Server version reported as: 5.7.41-44-log
2023-05-18 04:27:23 [INFO] - Initializing initialize_worker_schema
2023-05-18 04:27:23 [DEBUG] - I-Thread 1: Starting import
2023-05-18 04:27:23 [DEBUG] - I-Thread 2: Starting import
2023-05-18 04:27:23 [DEBUG] - I-Thread 3: Starting import
2023-05-18 04:27:23 [INFO] - S-Thread 1: Starting import
2023-05-18 04:27:23 [DEBUG] - I-Thread 4: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 1: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 2: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 3: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 4: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 5: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 6: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 9: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 7: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 8: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 11: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 10: Starting import
2023-05-18 04:27:23 [DEBUG] - Thread 12: Starting import

found no errors in the Log file.

Solution Looked Into
https://jvns.ca/blog/2018/04/28/debugging-a-segfault-on-linux/
https://medium.com/@sourabhedake/core-dumps-how-to-enable-them-73856a437711

Thanks,
Jabir Baig

**Comment by davidducos** [comment]
@MJabirBaig 
Can you test with the latest prerelease https://github.com/mydumper/mydumper/releases/tag/v0.14.4-8 ?

**Comment by MJabirBaig** [comment]
Hi David,
Tested Myloader with the pre-release version, but getting the same Segmentation Fault Error, please find the details below

`mysql@test01p1:/mysqllogs/tmp/backup$ sysctl kernel.core_pattern
kernel.core_pattern = /coredumps/core-%e-%s-%u-%g-%p-%t
mysql@test01p1$ myloader --defaults-file=/etc/mydumper.cnf --socket=/database/mysql/mysql.sock --threads=10 --overwrite-tables --enable-binlog --queries-per-transaction=1500 --verbose=3 --directory=/opt/backup/test02p01/mydumper/fullbackup-2023-05-17_00-40-45 --logfile=/mysqllogs/tmp/backup/MYLOADER-FULLBACKUP-IMPORT-2023-05-25_05.log
Segmentation fault
mysql@test01p1:/mysqllogs/tmp/backup$ rpm -qa|grep mydumper
mydumper-0.14.4-8.x86_64
mysql@test01p1:/mysqllogs/tmp/backup$ ulimit -c -S
unlimited
`
Thanks,
Jabir

**Comment by davidducos** [comment]
Hi @MJabirBaig, can you share the core dumped in `/coredumps/` ?

**Comment by MJabirBaig** [comment]
Hi @davidducos , i don't see any dir like  /coredumps/ on my test box.

**Comment by davidducos** [comment]
@MJabirBaig, You might need to create the directory, execute myloader again and see if the coredump is created.

**Comment by MJabirBaig** [comment]
Hi @davidducos , please find the attached core dump below
[core-myloader-11-1000-1000-201489-1685027648.gz](https://github.com/mydumper/mydumper/files/11567172/core-myloader-11-1000-1000-201489-1685027648.gz)

**Comment by davidducos** [comment]
I will need an `ls -l` of the backup dir, as there is a file that is causing the issue. Take into account that other files in the backups directory might cause myloader to fail.

**Comment by MJabirBaig** [comment]
please find the list of backup files in the dir, i have taken a look but could not find any outside file
[backup-files.txt](https://github.com/mydumper/mydumper/files/11593075/backup-files.txt)

**Comment by davidducos** [comment]
Hi @MJabirBaig ,
Sorry, I tried but I wasn't able to found out the issue. Can you test with the latest released version and let me know if you have the same issue?

**Comment by MJabirBaig** [comment]
Hi @davidducos ,
i am seeing similar issue with the latest version as well, please find the details below

[root@test01p1 ~]# rpm -Uvh mydumper-0.14.5-2-zstd.el7.x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:mydumper-0.14.5-2                ################################# [ 50%]
Cleaning up / removing...
   2:mydumper-0.14.4-8                ################################# [100%]


mysql@test01p1:/mysqllogs/tmp/backup$ rpm -qa | grep mydumper

mydumper-0.14.5-2.x86_64

mysql@test01p1$ myloader --defaults-file=/etc/mydumper.cnf --socket=/database/mysql/mysql.sock --threads=10 --overwrite-tables --enable-binlog --queries-per-transaction=1000 --verbose=3 --directory=/opt/backup/test02p01/mydumper//MYDUMPER-FULLBACKUP-2023-05-25_03-58-46 --logfile=/mysqllogs/tmp/backup/MYLOADER-FULLBACKUP-IMPORT.log

Segmentation fault

**Comment by davidducos** [comment]
Hi @MJabirBaig,

I found that we were not performing full tests as I thought that we were doing. I had to fix several issue, one of them was a seg fault issue. Can you test again with v0.15.0-1 ?
Thanks!

**Comment by davidducos** [comment]
Hi @MJabirBaig, 
Can you test with: https://github.com/mydumper/mydumper/releases/tag/v0.14.5-2 ?? I'm closing this issue until you provide some feedback.
