### ISSUE TITLE
[BUG] stream has stopped working 

### ISSUE THREAD

**Issue by szuras** [mydumper/mydumper#1135]
**Describe the bug**
I have noticed that that a stream feature has stopped working. It was working ok in the version mydumper_**0.13.1-1** but it doesn't in the newest version of mydumper_**0.14.3-1**.

**To Reproduce**
Command executed:
* mydumper -h source_host.example.com -u user -p PASS_HERE -o /mnt/big/out/ -T data.table -L /var/log/export.log -v 3 -F 200 --split-partitions -t 4 --stream | myloader -h destination_host.example.com -u user -p PASS_HERE -o -B data -L /var/log/import.log -v 3 -t 8 --stream

What mydumper and myloader version has been used?
0.14.3-1

**Expected behavior**
0.14.3-1

**How to repeat**
If you run above command you will see that mydumper [ ver. 0.14.3-1 ] will start downloading/backuping data into a separate files [ data will be splited into 200MB files ] you will notice that myloader won't start to upload data into the destination_host.example.coms server. The myloader will wait as long as mydumper is still processing backup. Once mydumper finishes downloading all data then myloader will start processing downloaded files.

In the version 0.13.1-1 it works as expected. Mydumper starts download data and myloader will start to upload data as soon as first file is ready. The myloader won't wait to finish all jobs by mydumper.

**Environment (please complete the following information):**
 - OS version:  SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux [ 5.10.0-21-amd64 ] 
 - MyDumper version: mydumper0.14.3-1

**Comment by szuras** [comment]
more over running this command I noticed that downloaded files are deleted but not processed by myloader 
ls -la /mnt/big/out/:
total 4474740
drwxr-xr-x  2 root root     69632 May 19 10:33 .
drwxr-xr-x 55 root root     12288 May 19 10:31 ..
-rw-r--r--  1 root root 209998498 May 19 10:31 data.table .00000.00008.sql
-rw-r--r--  1 root root 209998651 May 19 10:31 data.table .00000.00009.sql
-rw-r--r--  1 root root 209998722 May 19 10:31 data.table .00000.00010.sql
-rw-r--r--  1 root root 209998776 May 19 10:31 data.table .00000.00011.sql
-rw-r--r--  1 root root 209998520 May 19 10:32 data.table .00000.00012.sql
-rw-r--r--  1 root root 209998685 May 19 10:32 data.table .00000.00013.sql
-rw-r--r--  1 root root 209998635 May 19 10:32 data.table .00000.00014.sql
-rw-r--r--  1 root root 209998625 May 19 10:32 data.table .00000.00015.sql
-rw-r--r--  1 root root 209998591 May 19 10:32 data.table .00000.00016.sql
-rw-r--r--  1 root root      2086 May 19 10:31 metadata.partial


so files with a suffix like data.table .**00000.00001**.sql / data.table .**00000.00002**.sql were deleted but the data wasn't uploaded into the destination_host.example.com

**Comment by davidducos** [comment]
Hi @szuras,

Can you test with the latest released version? I think that I know where the issue might be and it should be fixed on the latest release. Please, let me know so I can close this bug.

**Comment by szuras** [comment]
Hi @davidducos ,
Yes, I confirm that the newest version 0.14.5-2 works as expected.

Thank you for fixing it!

**Comment by szuras** [comment]
it seems to work.
