### ISSUE TITLE
[BUG] GLib-CRITICAL

### ISSUE THREAD

**Issue by verydarksun** [mydumper/mydumper#1137]
**Describe the bug**
(myloader:20904): GLib-CRITICAL **: 13:50:15.590: g_str_has_suffix: assertion 'suffix != NULL' failed

**To Reproduce**
Command executed:
myloader --directory=Dir/file -overwrite-tables --user=dev --password=xxxxxx  --database=xxxxx  --verbose=2

What mydumper and myloader version has been used?
myloader0.14.5-1, built against MySQL 8.0.33 with SSL support with GZIP

**Expected behavior**
Shell script has worked for months with not error not report the  GLib-CRITICAL

**Log**
no erros on log ..  looks like the GLib-CRITICA is not as bad as it looks ?
2023-05-23 14:09:33 [INFO] - Using no configuration file
2023-05-23 14:09:33 [INFO] - Server version reported as: 5.5.5-10.11.3-MariaDB
2023-05-23 14:09:33 [INFO] - Filename to open: //Users/paulbrown/db_backups/od_learner/export-20230523-134220/admin_ondemand-schema-create.sql
2023-05-23 14:09:33 [INFO] - Initializing initialize_worker_schema
2023-05-23 14:09:33 [INFO] - S-Thread 2: Starting import

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
Or upload a [core dump](https://github.com/mydumper/mydumper/wiki/Support#core-dump) for cases where mydumper or myloader is crashing.

**Environment (please complete the following information):**
OSX ver 13.4 ( 22F66) installed using brew

**Comment by yaskinny** [comment]
I have the same issue using `myloader` version `0.14.5-1`. but restoring seems okay and exit code is always `0` even with this `CRITICAL` error.
