### ISSUE TITLE
[BUG] Not triggers and views export in v0.14.5-1

### ISSUE THREAD

**Issue by sakrow** [mydumper/mydumper#1142]
**Describe the bug**

When you launch mydumper with `--triggers --routines --events` in `v0.14.5-1`, mydumper not dumps this schemas.

**To Reproduce**
Command executed:

```
mydumper --compress --verbose=3 --compress-protocol --triggers --routines --events --less-locking --threads=12 --build-empty-files --rows=10000 --logfile=/root/dumpfile --outputdir=/mnt/tmp --defaults-file=/root/.my.cnf
```
Same command in `v0.14.5-1` not dump triggers and views. In `v0.14.3-1` works fine

EDIT: Checked in v0.14.5-2 with same result.

**Expected behavior**

mydumper should export views ans triggers correctly

**Environment (please complete the following information):**
 - OS version: Rocky Linux release 8.7 (Green Obsidian)
 - MyDumper version: 

Working version: `myloader0.14.3-1, built against MySQL 5.7.41-44 with SSL support with ZSTD`
Not Working version: `myloader0.14.5-1, built against MySQL 5.7.41-44 with SSL support with ZSTD`

**Comment by davidducos** [comment]
Hi @sakrow, I'm not able to reproduce your issue. Can you share an `ls -l` of the file in `/mnt/tmp`. And do NOT use `--defaults-file` for credentials in `/root/.my.cnf` use `--defaults-extra-file` as MyDumper started to configure several things in /etc/mydumper.cnf which by default is in /etc/mydumper.cnf

**Comment by sakrow** [comment]
Sorry for late response.

I executed this with `v0.14.5-1`:
```
mydumper --compress --verbose=3 --compress-protocol --triggers --routines --events --less-locking --threads=12 --build-empty-files --rows=10000 --logfile=/root/dumpfile --outputdir=/mnt/temporal/2023_06_01 --defaults-extra-file=/root/.my.cnf
```

Result: [2023_06_01_14.5-1.list.txt](https://github.com/mydumper/mydumper/files/11629685/2023_06_01_14.5-1.list.txt)

And this wwith `v0.14.3-1, because this version not have `-defaults-extra-file`

```
mydumper --compress --verbose=3 --compress-protocol --triggers --routines --events --less-locking --threads=12 --build-empty-files --rows=10000 --logfile=/root/dumpfile --outputdir=/mnt/temporal/2023_06_01_14.3_1 --defaults-file=/root/.my.cnf
```
Result: [2023_06_01_14.3_1.list.txt](https://github.com/mydumper/mydumper/files/11629683/2023_06_01_14.3_1.list.txt)

Here you can view that the first one has no triggers.

I attach results with database and tables ofuscated.
