### ISSUE TITLE
[BUG] 0.14.5-2, --verbose=3 and --rows=100000, the log file will grow very large

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#1143]
**Describe the bug**
When "--verbose=3" and "--rows" are used at the same time, the logfile will grow very large, and a large amount of the following content will be printed in the log file(sysno is primary key):
![image](https://github.com/mydumper/mydumper/assets/9590209/18c08e6b-3913-479a-a79c-bddafdc7b954)

**To Reproduce**
Command executed:
* mydumper with all the parameters
--set-names=utf8mb4 --less-locking --skip-tz-utc --complete-insert --trx-consistency-only --hex-blob --skip-definer --no-check-generated-fields --rows 100000 --disk-limits 1024:10240 -v 3 -R -G -E -c -e

What mydumper and myloader version has been used?
mydumper0.14.5-2, built against MySQL 5.7.42-45 with SSL support with ZSTD

**Expected behavior**
When "--verbose=3" and "--rows" are used at the same time

**Log**
-

**Backup**
-

**How to repeat**
-

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
 - MyDumper version: [ mydumper --version ]
CentOS 7

**Additional context**
-

**Comment by davidducos** [comment]
Hi @peng19832 

Why don't you try with --rows=10000:100000:0 ?? which means min:starting_point:max where 0 on max mean unlimited.

**Comment by peng19832** [comment]
> Hi @peng19832
> 
> Why don't you try with --rows=10000:100000:0 ?? which means min:starting_point:max where 0 on max mean unlimited.

@davidducos 
OK, i will try.
However, I would like to know, in this case, is it normal for the logfile to grow? Because, when this happens, the data will not be saved normally, only the logfile will keep increasing.

**Comment by kratkyzobak** [comment]
Do you have PK specified in your table? It seems, that `rows=N` for tables with no PK does this.

I found one table like this in our database, where PK is not specified, there is only unique key over nullable column... Table is fucked up enough, but "valid". It seems mydumper uses InnoDB RowID and tries to use them to split table by first column of unique index.

Our table:
```
CREATE TABLE `dealers_legacy_clicks` (
  `dealer_id` bigint DEFAULT NULL,
  `shop` varchar(50) NOT NULL,
  `clicks` bigint NOT NULL,
  UNIQUE KEY `dealers_legacy_clicks_pk` (`dealer_id`,`shop`)
) 
```

My log file with `--rows=100000`.
```
** Message: 09:48:19.816: Thread 2: dumping data for `quant_data`.`dealers_legacy_clicks`  WHERE (  ( 663186856646303991 < `dealer_id` AND `dealer_id` <= 663186856646403991))       into /backup/quant_data_20230614.093822/quant_data.dealers_legacy_clicks.00088.sql.gz| Remaining jobs in this table: 2715208295637 All remaining jobs: 2715208295655
** Message: 09:48:19.816: Thread 1: dumping data for `quant_data`.`dealers_legacy_clicks`  WHERE (  ( 694046855333553991 < `dealer_id` AND `dealer_id` <= 694046855333653991))       into /backup/quant_data_20230614.093822/quant_data.dealers_legacy_clicks.00056.sql.gz| Remaining jobs in this table: 2715208295637 All remaining jobs: 2715208295655
** Message: 09:48:19.816: Thread 6: dumping data for `quant_data`.`dealers_legacy_clicks`  WHERE (  ( 66035030957 < `dealer_id` AND `dealer_id` <= 66035130957))       into /backup/quant_data_20230614.093822/quant_data.dealers_legacy_clicks.00000.sql.gz| Remaining jobs in this table: 2715208295637 All remaining jobs: 2715208295655
** Message: 09:48:19.816: Thread 3: dumping data for `quant_data`.`dealers_legacy_clicks`  WHERE (  ( 72057668625158651 < `dealer_id` AND `dealer_id` <= 72057668625258651))       into /backup/quant_data_20230614.093822/quant_data.dealers_legacy_clicks.00064.sql.gz| Remaining jobs in this table: 2715208295635 All remaining jobs: 2715208295654
** Message: 09:48:19.816: Thread 5: dumping data for `quant_data`.`dealers_legacy_clicks`  WHERE (  ( 9079256929166048544 < `dealer_id` AND `dealer_id` <= 9079256929166148544))       into /backup/quant_data_20230614.093822/quant_data.dealers_legacy_clicks.00063.sql.gz| Remaining jobs in this table: 2715208295634 All remaining jobs: 2715208295652
```

With `--rows=1000:100000:0` dump is successfully created as mydumper does not try to split it at all.

**Comment by davidducos** [comment]
@peng19832,
Closing this bug as you said that is working. Feel free to open it up again if I missed something.
