### ISSUE TITLE
[BUG] myloader -B (--database) fails when triggers present

### ISSUE THREAD

**Issue by stephen322** [mydumper/mydumper#1144]
When using -B (An alternative database to restore into), triggers fail as they still are attempted to load into the original database name.

**Comment by davidducos** [comment]
Hi @stephen322, the use case that you presented is tested and is not failing. Can you share a test case?

**Comment by stephen322** [comment]
Investigating further, it appears to be due to the trigger specifying the database name within the definition, eg.
CREATE TRIGGER dbname.triggername

**Comment by davidducos** [comment]
Hi @stephen322 
I found the problem. It is related to how we export the triggers. We do a SHOW CREATE TRIGGER. 
In MySQL you can create triggers naming the schema. For instance:
```
USE issue_1144;
CREATE DEFINER=`root`@`localhost` TRIGGER perftest_trigger  AFTER    UPDATE ON issue_1144.perftest    FOR EACH ROW      INSERT INTO perftest_2 VALUES (old.id,old.val);
```
To avoid your issue, you should create the trigger without naming the database on triggers creation. For instance:
```
USE issue_1144;
CREATE DEFINER=`root`@`localhost` TRIGGER perftest_trigger  AFTER    UPDATE ON perftest    FOR EACH ROW      INSERT INTO perftest_2 VALUES (old.id,old.val);
```
BTW, mysqldump has the same behavior. I will be closing this ticket as this is a design issue, not a MyDumper bug. Sorry for not been able to help.
