### ISSUE TITLE
[BUG] myloader (--stream) different file size

### ISSUE THREAD

**Issue by szuras** [mydumper/mydumper#1146]
**Describe the bug**
I'm getting errors like: `** (mydumper:2150563): ERROR **: 12:14:36.554: Stream failed during transmition of file: /mnt/path/data.__entity_body.00000.00007.sql`

and in the logs from different run:
`2023-05-29 12:14:36 [INFO] - File /mnt/path/data.__entity_body.00000.00006.sql transferred | Global: 66MB/s
2023-05-29 12:14:36 [ERROR] - Different file size in data.__entity_body.00000.00006.sql. Should be: 209751990 | Written: 209752038`

The database contains many different tables, total size ~200GB.
I was not able to accomplish the task, I tried to run the same script a few times without success. As soon as I revert myloader into 0.13.1-1 version everything starts to work correctly.

**To Reproduce**
Command executed:
* mydumper -h source_host.example.com -u user -p PASS_HERE -o /mnt/big/out/ -L /var/log/export.log -v 3 -F 200 --split-partitions -t 4 --stream | myloader -h destination_host.example.com -u user -p PASS_HERE -o -B data -L /var/log/import.log -v 3 -t 8 --stream

What mydumper and myloader version has been used?
* used version: 0.14.5-2
* working version: 0.13.1-1 all works fine while I use this version, there is no issues with wrong file size.

**Expected behavior**
The program stops working as soon as the problem appears.

**Environment (please complete the following information):**
 - OS version: SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux [ 5.10.0-21-amd64 ]
 - MyDumper version: mydumper0.14.5-2

**Comment by davidducos** [comment]
Hi @szuras ,

I need to to try one more time with v0.14.5-2, but I need to to collect some info for me.

First, when you execute myloader, you are not setting the temporary directory, so myloader is creating a default directory. Please, can you set -d on myloader on any location you prefer? and after execution I need to you do a `ls -l`, so I can check the files that remains in the directory.
Then I will need you to do a tail and a head of the file/s that is/are failing. For instance:
`head /mnt/path/data.__entity_body.00000.00007.sql`
`tail /mnt/path/data.__entity_body.00000.00007.sql`

Thanks!

**Comment by szuras** [comment]
It doesn't matter if I use my own folder or created by the myloader. The result is the same.

**Comment by davidducos** [comment]
Hi @szuras,
In order to help you, I need the information that I requested:
- I need to you do a ls -l, so I can check the files that remains in the directory.
- Then I will need you to do a tail and a head of the file/s that is/are failing. For instance:
```
head /mnt/path/data.__entity_body.00000.00007.sql
tail /mnt/path/data.__entity_body.00000.00007.sql
```
If you don't provide that info, I will not be able to help.

**Comment by SamQuigley** [comment]
Hi, 

Also experiencing this issue on v0.14.5-2 using the --stream feature. 

mydumper options:

`      --omit-from-file=ignore_table.txt \
      --no-locks \
      --no-views \
      --compress-protocol \
      --verbose=3 \
      --threads=16 \
      --chunk-filesize=512 \
      --outputdir=xyz/backup \
      --stream \`

myloader options:
`            --compress-protocol \
            --innodb-optimize-keys \
            --queries-per-transaction=100 \
            --skip-post \
            --skip-definer \
            --skip-triggers \
            --verbose=3 \
            --threads=20 \
            --directory=xyz/restore \
            --stream `
            
   Error:
`** (myloader:12): CRITICAL **: 09:50:48.163: Different file size in schema.xyz.00000.00019.sql. Should be: 5407 | Written: 540730985`
and
`** (mydumper:11): ERROR **: 09:50:49.747: Stream failed during transmition of file: xyz/backup/schema.xxxxx.00000.sql`

**Comment by davidducos** [comment]
Hi @SamQuigley 
Hang in there... I'm already working on [it](https://github.com/mydumper/mydumper/pull/1167)

**Comment by SamQuigley** [comment]
Appreciate the quick response @davidducos 💯

**Comment by szuras** [comment]
thank you. In which version will it be fixed?

**Comment by caleb-terry** [comment]
@SamQuigley Did the latest fix resolve your issue? I'm curious because I encountered this same issue on Ubuntu Bionic with MariaDB 10.5.21 while streaming mydumper into myloader. I attempted the latest release as well as the pre-release. I also encountered this issue on RHEL8 which makes me think there are incompatibilities with the latest mydumper and MariaDB 10.5.

**Comment by szuras** [comment]
No, I've tried the 0.15.1-3 version and the problem still persists.
