### ISSUE TITLE
[BUG] Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by juanrodicio** [mydumper/mydumper#1151]
**Describe the bug**
Core dump when restoring data with myloade

**To Reproduce**
Command executed:
myloader --host=$HOST_LOCAL_DOCKER --user=$USER_LOCAL_DOCKER --password=$PWD_LOCAL_DOCKER --port=$PORT_LOCAL_DOCKER --directory=$destinoScript/at_sistema_gestion_pro --threads=3 --database=at_sistema_gestion_ofuscada --verbose=3 --innodb-optimize-keys

What mydumper and myloader version has been used?
myloader0.14.5-2, built against MySQL 5.7.42-45 with SSL support with GZIP.
**Expected behavior**
Restore data on dest db.

**Log**
 Restaurando Datos de at_sistema_gestion_ofuscada en Docker Local...
** Message: 09:11:34.828: Server version reported as: 8.0.31
** Message: 09:11:34.832: Initializing initialize_worker_schema
** Message: 09:11:34.902: S-Thread 1: Starting import
** Message: 09:11:34.920: S-Thread 3: Starting import
** Message: 09:11:34.923: S-Thread 4: Starting import
** Message: 09:11:34.924: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_certificado_buena_ejecucion
** Message: 09:11:34.925: S-Thread 2: Starting import
** Message: 09:11:34.927: Fast index creation will be use for table: at_sistema_gestion_ofuscada.paract_parte_sin_servicio
** Message: 09:11:34.928: Intermediate queue: Sending END job
** Message: 09:11:34.935: Fast index creation will be use for table: at_sistema_gestion_ofuscada.oportu_oportunidad_responsable_historico
** Message: 09:11:34.942: Fast index creation will be use for table: at_sistema_gestion_ofuscada.jerarquia_organica_aplanada
** Message: 09:11:34.946: Fast index creation will be use for table: at_sistema_gestion_ofuscada.vacaci_dias_disponibles
** Message: 09:11:34.947: Fast index creation will be use for table: at_sistema_gestion_ofuscada.bedesk_rest_service_permiso
** Message: 09:11:34.948: Fast index creation will be use for table: at_sistema_gestion_ofuscada.teletr_cuestionario_prl_respuestas
** Message: 09:11:34.949: Fast index creation will be use for table: at_sistema_gestion_ofuscada.interno_observaciones
** Message: 09:11:34.950: Fast index creation will be use for table: at_sistema_gestion_ofuscada.revsal_revision_salarial_politicas_roles
** Message: 09:11:34.951: Fast index creation will be use for table: at_sistema_gestion_ofuscada.sedes_oficina
** Message: 09:11:34.954: Fast index creation will be use for table: at_sistema_gestion_ofuscada.costes_extraordinarios_devengos
** Message: 09:11:34.955: Fast index creation will be use for table: at_sistema_gestion_ofuscada.curric_experiencia_profesional
** Message: 09:11:34.956: Fast index creation will be use for table: at_sistema_gestion_ofuscada.intern_salarios_analitica
** Message: 09:11:34.957: Fast index creation will be use for table: at_sistema_gestion_ofuscada.nivest_nivel_estudios_periodo_prueba
** Message: 09:11:34.957: Fast index creation will be use for table: at_sistema_gestion_ofuscada.projec_sincronizacion
** Message: 09:11:34.958: Fast index creation will be use for table: at_sistema_gestion_ofuscada.pretbf_prevision_comercial_linea_negocio
** Message: 09:11:34.959: Fast index creation will be use for table: at_sistema_gestion_ofuscada.evalua_evaluacion
** Message: 09:11:34.961: Fast index creation will be use for table: at_sistema_gestion_ofuscada.datos_inventario_temp
** Message: 09:11:34.961: Fast index creation will be use for table: at_sistema_gestion_ofuscada.tarper_tarea_oportunidad
** Message: 09:11:34.962: Fast index creation will be use for table: at_sistema_gestion_ofuscada.invent_historico_inventario
** Message: 09:11:34.964: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_preasignacion_correo_destinatario
** Message: 09:11:34.965: Fast index creation will be use for table: at_sistema_gestion_ofuscada.pretbf_prevision_comercial
** Message: 09:11:34.965: Fast index creation will be use for table: at_sistema_gestion_ofuscada.workfl_candidato
** Message: 09:11:34.967: Fast index creation will be use for table: at_sistema_gestion_ofuscada.bedesk_usuario_token
** Message: 09:11:34.968: Fast index creation will be use for table: at_sistema_gestion_ofuscada.intern_motivo_baja
** Message: 09:11:34.969: Fast index creation will be use for table: at_sistema_gestion_ofuscada.paract_imputacion_con_servicio
** Message: 09:11:34.969: Fast index creation will be use for table: at_sistema_gestion_ofuscada.incidencia_asignacion_material
** Message: 09:11:34.971: Fast index creation will be use for table: at_sistema_gestion_ofuscada.correo_emails_adjuntos
** Message: 09:11:34.971: Fast index creation will be use for table: at_sistema_gestion_ofuscada.teletr_cuestionario_prl
** Message: 09:11:34.972: Fast index creation will be use for table: at_sistema_gestion_ofuscada.candid_historico_entrevistas
** Message: 09:11:34.973: Fast index creation will be use for table: at_sistema_gestion_ofuscada.coment_comentario
** Message: 09:11:34.974: Fast index creation will be use for table: at_sistema_gestion_ofuscada.invent_telefono
** Message: 09:11:34.975: Fast index creation will be use for table: at_sistema_gestion_ofuscada.factur_factura
** Message: 09:11:34.976: Fast index creation will be use for table: at_sistema_gestion_ofuscada.invent_linea_telefono
** Message: 09:11:34.977: Fast index creation will be use for table: at_sistema_gestion_ofuscada.rol_historico_coste_roles
** Message: 09:11:34.978: Fast index creation will be use for table: at_sistema_gestion_ofuscada.paract_imputaciones_rrhh
** Message: 09:11:34.978: Fast index creation will be use for table: at_sistema_gestion_ofuscada.evento_convocatorias_dias
** Message: 09:11:34.979: Fast index creation will be use for table: at_sistema_gestion_ofuscada.vacint_puesto_publicado
** Message: 09:11:34.980: Fast index creation will be use for table: at_sistema_gestion_ofuscada.curric2_titulo
** Message: 09:11:34.981: Fast index creation will be use for table: at_sistema_gestion_ofuscada.revsal_revision_empleado
** Message: 09:11:34.982: Fast index creation will be use for table: at_sistema_gestion_ofuscada.oportu_fabricante
** Message: 09:11:34.984: Fast index creation will be use for table: at_sistema_gestion_ofuscada.presu_gasto
** Message: 09:11:34.984: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_asignacion_linea_negocio
** Message: 09:11:34.985: Fast index creation will be use for table: at_sistema_gestion_ofuscada.tarper_respuesta_adjunto
** Message: 09:11:34.986: Fast index creation will be use for table: at_sistema_gestion_ofuscada.petrec_peticion_recurso_responsable
** Message: 09:11:34.987: Fast index creation will be use for table: at_sistema_gestion_ofuscada.intern_contrato
** Message: 09:11:34.988: Fast index creation will be use for table: at_sistema_gestion_ofuscada.evaemp_evaluacion_persona
** Message: 09:11:34.989: Fast index creation will be use for table: at_sistema_gestion_ofuscada.bedesk_permiso_rol
** Message: 09:11:34.989: Fast index creation will be use for table: at_sistema_gestion_ofuscada.ldapat_ruta_sede
** Message: 09:11:34.990: Fast index creation will be use for table: at_sistema_gestion_ofuscada.incorp_oferta
** Message: 09:11:34.992: Fast index creation will be use for table: at_sistema_gestion_ofuscada.incorp_propuesta
** Message: 09:11:34.992: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_servicio_centro_coste
** Message: 09:11:34.993: Fast index creation will be use for table: at_sistema_gestion_ofuscada.intern_nivel_idioma
** Message: 09:11:34.994: Fast index creation will be use for table: at_sistema_gestion_ofuscada.campan_lead
** Message: 09:11:34.995: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_servicio_grupo_conocimiento
** Message: 09:11:34.996: Fast index creation will be use for table: at_sistema_gestion_ofuscada.sedes_centro_trabajo
** Message: 09:11:34.997: Fast index creation will be use for table: at_sistema_gestion_ofuscada.evalua_people
** Message: 09:11:34.998: Fast index creation will be use for table: at_sistema_gestion_ofuscada.presu_partida_presupuestaria
** Message: 09:11:34.998: Fast index creation will be use for table: at_sistema_gestion_ofuscada.referente_linea_entorno
** Message: 09:11:34.999: Fast index creation will be use for table: at_sistema_gestion_ofuscada.proyecto
** Message: 09:11:35.000: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_certificado_buena_ejecucion_desglose_anual_importe
** Message: 09:11:35.001: Fast index creation will be use for table: at_sistema_gestion_ofuscada.historico_disponibilidad
** Message: 09:11:35.001: Fast index creation will be use for table: at_sistema_gestion_ofuscada.incide_personal_asignado
** Message: 09:11:35.002: Fast index creation will be use for table: at_sistema_gestion_ofuscada.varcom_facturas_impagadas
** Message: 09:11:35.003: Fast index creation will be use for table: at_sistema_gestion_ofuscada.bedesk_rol_naturaleza
** Message: 09:11:35.004: Fast index creation will be use for table: at_sistema_gestion_ofuscada.sedes_reservas_puestos
** Message: 09:11:35.005: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_historico_facturacion
** Message: 09:11:35.005: Fast index creation will be use for table: at_sistema_gestion_ofuscada.paract_parte_sin_servicio_historico_observaciones
** Message: 09:11:35.007: Fast index creation will be use for table: at_sistema_gestion_ofuscada.paract_parte_actividad_historico_observaciones
** Message: 09:11:35.008: Fast index creation will be use for table: at_sistema_gestion_ofuscada.atmail_email
** Message: 09:11:35.009: Fast index creation will be use for table: at_sistema_gestion_ofuscada.servic_servicio_conocimiento
** Message: 09:11:35.011: Fast index creation will be use for table: at_sistema_gestion_ofuscada.altemp_alta_empleado
** Message: 09:11:35.012: Fast index creation will be use for table: at_sistema_gestion_ofuscada.varcom_impagos_facturas
** Message: 09:11:35.015: Fast index creation will be use for table: at_sistema_gestion_ofuscada.comp_compensacion_solicitudes
** Message: 09:11:35.082: Fast index creation will be use for table: at_sistema_gestion_ofuscada.nomina_nomina
** Message: 09:11:35.085: Fast index creation will be use for table: at_sistema_gestion_ofuscada.reghor_registro_diario
** Message: 09:11:35.091: Fast index creation will be use for table: at_sistema_gestion_ofuscada.nomina_concepto
** Message: 09:11:35.102: Fast index creation will be use for table: at_sistema_gestion_ofuscada.contac_contacto_temporal
** Message: 09:11:35.153: Fast index creation will be use for table: at_sistema_gestion_ofuscada.superusuario
** Message: 09:11:35.189: Fast index creation will be use for table: at_sistema_gestion_ofuscada.bedesk_tareas_bandeja
** Message: 09:11:35.200: Fast index creation will be use for table: at_sistema_gestion_ofuscada.evaemp_evaluacion_permiso
** Message: 09:11:35.233: Fast index creation will be use for table: at_sistema_gestion_ofuscada.reghor_registro_diario_horas
** Message: 09:11:35.242: Fast index creation will be use for table: at_sistema_gestion_ofuscada.tarper_tarea_servicio
** Message: 09:11:35.254: Thread 1: restoring table `at_sistema_gestion_ofuscada`.`curric_titulo_persona` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.curric_titulo_persona-schema.sql
** Message: 09:11:35.254: Thread 1: Creating table `at_sistema_gestion_ofuscada`.`curric_titulo_persona` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.curric_titulo_persona-schema.sql.
** Message: 09:11:35.255: Thread 3: restoring table `at_sistema_gestion_ofuscada`.`encues_hans_respuestas` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.encues_hans_respuestas-schema.sql
** Message: 09:11:35.255: Thread 3: Creating table `at_sistema_gestion_ofuscada`.`encues_hans_respuestas` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.encues_hans_respuestas-schema.sql.
** Message: 09:11:35.256: Thread 4: restoring table `at_sistema_gestion_ofuscada`.`tarper_destinatario_area_trabajo` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.tarper_destinatario_area_trabajo-schema.sql
** Message: 09:11:35.256: Thread 4: Creating table `at_sistema_gestion_ofuscada`.`tarper_destinatario_area_trabajo` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.tarper_destinatario_area_trabajo-schema.sql.
** Message: 09:11:35.260: Thread 2: restoring table `at_sistema_gestion_ofuscada`.`bedesk_tarea_a_ejecutar` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.bedesk_tarea_a_ejecutar-schema.sql
** Message: 09:11:35.260: Thread 2: Creating table `at_sistema_gestion_ofuscada`.`bedesk_tarea_a_ejecutar` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.bedesk_tarea_a_ejecutar-schema.sql.

** (myloader:9875): WARNING **: 09:11:35.288: Filename views has been ignored
** Message: 09:11:35.316: Thread 4: Table `at_sistema_gestion_ofuscada`.`tarper_destinatario_area_trabajo` created. Tables 0 of 542 completed
** Message: 09:11:35.316: Thread 4: restoring table `at_sistema_gestion_ofuscada`.`propietario_cliente` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.propietario_cliente-schema.sql
** Message: 09:11:35.316: Thread 4: Creating table `at_sistema_gestion_ofuscada`.`propietario_cliente` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.propietario_cliente-schema.sql.
** Message: 09:11:35.316: Thread 1: restoring `at_sistema_gestion_ofuscada`.`tarper_destinatario_area_trabajo` part 1 of 1 from at_sistema_gestion_pro.tarper_destinatario_area_trabajo.00000.sql. Progress 1 of 375. Tables 0 of 542 completed
** Message: 09:11:35.316: Filename to open: /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.tarper_destinatario_area_trabajo.00000.sql
** Message: 09:11:35.320: Fast index creation will be use for table: at_sistema_gestion_ofuscada.sedes_reservas_servicios
** Message: 09:11:35.324: Thread 2: Table `at_sistema_gestion_ofuscada`.`bedesk_tarea_a_ejecutar` created. Tables 0 of 542 completed
** Message: 09:11:35.324: Thread 2: restoring table `at_sistema_gestion_ofuscada`.`invent_uso_licencias` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.invent_uso_licencias-schema.sql
** Message: 09:11:35.324: Thread 2: Creating table `at_sistema_gestion_ofuscada`.`invent_uso_licencias` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.invent_uso_licencias-schema.sql.
** Message: 09:11:35.325: Thread 2: restoring `at_sistema_gestion_ofuscada`.`bedesk_tarea_a_ejecutar` part 1 of 5 from at_sistema_gestion_pro.bedesk_tarea_a_ejecutar.00000.sql. Progress 2 of 377. Tables 0 of 542 completed
** Message: 09:11:35.325: Filename to open: /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.bedesk_tarea_a_ejecutar.00000.sql
** Message: 09:11:35.325: Thread 3: restoring `at_sistema_gestion_ofuscada`.`bedesk_tarea_a_ejecutar` part 4 of 5 from at_sistema_gestion_pro.bedesk_tarea_a_ejecutar.00000.00003.sql. Progress 3 of 377. Tables 0 of 542 completed
** Message: 09:11:35.325: Filename to open: /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.bedesk_tarea_a_ejecutar.00000.00003.sql
** Message: 09:11:35.364: Thread 3: Table `at_sistema_gestion_ofuscada`.`encues_hans_respuestas` created. Tables 0 of 542 completed
** Message: 09:11:35.364: Thread 3: restoring table `at_sistema_gestion_ofuscada`.`bedesk_catalogo_item_1` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.bedesk_catalogo_item_1-schema.sql
** Message: 09:11:35.364: Thread 3: Creating table `at_sistema_gestion_ofuscada`.`bedesk_catalogo_item_1` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.bedesk_catalogo_item_1-schema.sql.
** Message: 09:11:35.368: Thread 1: restoring `at_sistema_gestion_ofuscada`.`bedesk_tarea_a_ejecutar` part 5 of 5 from at_sistema_gestion_pro.bedesk_tarea_a_ejecutar.00000.00004.sql. Progress 4 of 378. Tables 0 of 542 completed
** Message: 09:11:35.368: Filename to open: /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.bedesk_tarea_a_ejecutar.00000.00004.sql
** Message: 09:11:35.375: Fast index creation will be use for table: at_sistema_gestion_ofuscada.factur_saldar_horas
** Message: 09:11:35.393: Thread 1: Table `at_sistema_gestion_ofuscada`.`curric_titulo_persona` created. Tables 0 of 542 completed
** Message: 09:11:35.393: Thread 1: restoring table `at_sistema_gestion_ofuscada`.`incidencia_mensaje` from /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.incidencia_mensaje-schema.sql
** Message: 09:11:35.393: Thread 1: Creating table `at_sistema_gestion_ofuscada`.`incidencia_mensaje` from content in /srv/jenkins/workspace/Servicios_Corporativos/Ofuscar_BBDD_PRE/mnt/backup/ofuscada/at_sistema_gestion_pro/at_sistema_gestion_pro.incidencia_mensaje-schema.sql.
/tmp/build_step_template6261745915992812514.sh: línea 52:  9875 Violación de segmento  (`core' generado) myloader --host=$HOST_LOCAL_DOCKER --user=$USER_LOCAL_DOCKER --password=$PWD_LOCAL_DOCKER --port=$PORT_LOCAL_DOCKER --directory=$destinoScript/at_sistema_gestion_pro --threads=3 --database=at_sistema_gestion_ofuscada --verbose=3 --innodb-optimize-keys

**How to repeat**
[core-dump.zip](https://github.com/mydumper/mydumper/files/11649847/core-dump.zip)

**Environment (please complete the following information):**
 - OS version: Centos 7
 - MyDumper version: 0.14.5-2

**Comment by davidducos** [comment]
Hi @juanrodicio, v0.15.0-1 will be released today, please, could you test that version?

**Comment by juanrodicio** [comment]
Yes, it's working now after updated.
Thank you!
