### ISSUE TITLE
myloader taking too much time to restore table schema when restoring with all data (dump size 618G) 

### ISSUE THREAD

**Issue by BhushanGawade92** [mydumper/mydumper#1165]
Hi, 

I am trying to dump and restore approx 600 GB of data from one RDS to another existing RDS. With approx table count 35809.

When I tried to do a schema dump and restore it worked fine, and schema restoration was done only in 7 min.

`[root@nc-mongo-ops backup]# time \
> mydumper --no-data \
> --host=pdb5.netcore.co.in \
> --user=admin \
> --password=qwerasdf \
> --outputdir=/backup/pdb5_mysql_dump_schema_only/ \
> --long-query-guard 99999 \
> --less-locking \
> -G -E -R \
> --skip-definer \
> --build-empty-files \
> --threads=8 \
> --regex '^(?!(information_schema|SMARTECH_DB|SMARTECH_MASTER_DB|innodb|mysql|performance_schema|sys|tmp))' \
> -v 3 \
> -L /backup/mydumper-logs_$(date +%Y%m%d%H%M).txt

real	0m20.178s
user	0m3.057s
sys	0m4.170s
[root@nc-mongo-ops backup]# 
[root@nc-mongo-ops backup]# 
[root@nc-mongo-ops backup]# 
[root@nc-mongo-ops backup]# 
[root@nc-mongo-ops backup]# 
[root@nc-mongo-ops backup]# time \
> myloader \
> --host=pdb1.netcore.co.in \
> --user=admin \
> --password=qwerasdf \
> --directory=/backup/pdb5_mysql_dump_schema_only/ \
> --queries-per-transaction=500 \
> --threads=8 \
> --verbose=3 -e 2> /backup/myloader-logs_$(date +%Y%m%d%H%M).txt 
 
real	6m9.985s
user	4m25.836s
sys	0m4.743s
[root@nc-mongo-ops backup]# `

But when I tried to do the same with all data, the dump process took ~90 min. But the restoration (myloader) taking too much time.
For the last 20hrs it's working on schema restoration only and in between it waited for 8hrs and till 12pm it restored only 12570 (40%) table schema. The job was started at 2023-06-15 14:31:00 and I canceled it on 2023-06-16 12:00:00

`** Message: 14:31:44.797: Thread 3: restoring table `9dot9`.`netcore_list_unsubscribe` from //backup/pdb5_mysql_dump/9dot9.netcore_list_unsubscribe-schema.sql
** Message: 14:31:44.797: Thread 3: Creating table `9dot9`.`netcore_list_unsubscribe` from content in //backup/pdb5_mysql_dump/9dot9.netcore_list_unsubscribe-schema.sql.
** Message: 14:31:44.807: Thread 4: Table `allcargologisticsst`.`nt_etrack_map` created. Tables 0 of 3257 completed
** Message: 14:31:44.817: Thread 1: Table `asuransiastrasmart`.`netcore_list_summary` created. Tables 0 of 3258 completed
** Message: 14:31:44.817: Thread 3: Table `9dot9`.`netcore_list_unsubscribe` created. Tables 0 of 3258 completed
** Message: 23:25:28.713: Thread 2: restoring table `aihpsmt`.`netcore_msg_alerts` from //backup/pdb5_mysql_dump/aihpsmt.netcore_msg_alerts-schema.sql
** Message: 23:25:28.713: Thread 2: Creating table `aihpsmt`.`netcore_msg_alerts` from content in //backup/pdb5_mysql_dump/aihpsmt.netcore_msg_alerts-schema.sql.
** Message: 23:25:32.566: Thread 4: restoring table `angelbroking01`.`21766_temp_user_user_attribute_151843855279991_ceaf1` from //backup/pdb5_mysql_dump/angelbroking01.21766_temp_user_u
ser_attribute_151843855279991_ceaf1-schema.sql
** Message: 23:25:32.566: Thread 4: Creating table `angelbroking01`.`21766_temp_user_user_attribute_151843855279991_ceaf1` from content in //backup/pdb5_mysql_dump/angelbroking01.21766_t
emp_user_user_attribute_151843855279991_ceaf1-schema.sql.
`

Also attached is the entire log file for reference.

EC2 instance type is c5.9xlarge (36 vCPU and 92GB memory) with 1TB EBS for backup partition 
OS : CentOS Linux 7
Mydumper version : mydumper v0.15.0-2, built against MySQL 8.0.33 with SSL support
Myloader version : myloader v0.15.0-2, built against MySQL 8.0.33 with SSL support

Destination RDS details
Instance Type : db.m5.4xlarge (16 vCPU , 64 GB RAM)
MySQL version : 5.7.41

Tunned Parameters 
`innodb_log_buffer_size = 256M
innodb_log_file_size = 1G
innodb_buffer_pool_size = {DBInstanceClassMemory*4/5}
innodb_io_capacity = 2000
innodb_io_capacity_max = 3000
innodb_read_io_threads = 8
innodb_write_io_threads = 16
innodb_purge_threads = 2
innodb_buffer_pool_instances = 16
innodb_flush_log_at_trx_commit = 0
max_allowed_packet = 900MB`

Need some help in figuring out what I am doing wrong [
[myloader-logs_202306151431.txt](https://github.com/mydumper/mydumper/files/11768066/myloader-logs_202306151431.txt)
](url)

**Comment by davidducos** [comment]
Hi @BhushanGawade92,
This is interesting. Did you delete anything of the log file?
```
** Message: 14:31:44.788: Thread 4: restoring table `allcargologisticsst`.`nt_etrack_map` from //backup/pdb5_mysql_dump/allcargologisticsst.nt_etrack_map-schema.sql
** Message: 14:31:44.788: Thread 4: Creating table `allcargologisticsst`.`nt_etrack_map` from content in //backup/pdb5_mysql_dump/allcargologisticsst.nt_etrack_map-schema.sql.
** Message: 14:31:44.797: Thread 1: Table `5nancesmart`.`osname_map` created. Tables 0 of 3256 completed
** Message: 14:31:44.797: Thread 3: Table `affordableswitzer`.`netcore_listuser_temp_1054` created. Tables 0 of 3256 completed
** Message: 14:31:44.797: Thread 2: Table `aman_test`.`phplist_eventlog` created. Tables 0 of 3256 completed
** Message: 14:31:44.797: Thread 1: restoring table `asuransiastrasmart`.`netcore_list_summary` from //backup/pdb5_mysql_dump/asuransiastrasmart.netcore_list_summary-schema.sql
** Message: 14:31:44.797: Thread 1: Creating table `asuransiastrasmart`.`netcore_list_summary` from content in //backup/pdb5_mysql_dump/asuransiastrasmart.netcore_list_summary-schema.sql.
** Message: 14:31:44.797: Thread 3: restoring table `9dot9`.`netcore_list_unsubscribe` from //backup/pdb5_mysql_dump/9dot9.netcore_list_unsubscribe-schema.sql
** Message: 14:31:44.797: Thread 3: Creating table `9dot9`.`netcore_list_unsubscribe` from content in //backup/pdb5_mysql_dump/9dot9.netcore_list_unsubscribe-schema.sql.
** Message: 14:31:44.807: Thread 4: Table `allcargologisticsst`.`nt_etrack_map` created. Tables 0 of 3257 completed
** Message: 14:31:44.817: Thread 1: Table `asuransiastrasmart`.`netcore_list_summary` created. Tables 0 of 3258 completed
** Message: 14:31:44.817: Thread 3: Table `9dot9`.`netcore_list_unsubscribe` created. Tables 0 of 3258 completed
** Message: 23:25:28.713: Thread 2: restoring table `aihpsmt`.`netcore_msg_alerts` from //backup/pdb5_mysql_dump/aihpsmt.netcore_msg_alerts-schema.sql
** Message: 23:25:28.713: Thread 2: Creating table `aihpsmt`.`netcore_msg_alerts` from content in //backup/pdb5_mysql_dump/aihpsmt.netcore_msg_alerts-schema.sql.
** Message: 23:25:32.566: Thread 4: restoring table `angelbroking01`.`21766_temp_user_user_attribute_151843855279991_ceaf1` from //backup/pdb5_mysql_dump/angelbroking01.21766_temp_user_user_attribute_151843855279991_ceaf1-schema.sql
** Message: 23:25:32.566: Thread 4: Creating table `angelbroking01`.`21766_temp_user_user_attribute_151843855279991_ceaf1` from content in //backup/pdb5_mysql_dump/angelbroking01.21766_temp_user_user_attribute_151843855279991_ceaf1-schema.sql.
** Message: 23:25:32.567: Thread 2: Table `aihpsmt`.`netcore_msg_alerts` created. Tables 0 of 35513 completed
** Message: 23:25:36.385: Thread 1: restoring table `affordableswitzer`.`netcore_listuser_temp_66` from //backup/pdb5_mysql_dump/affordableswitzer.netcore_listuser_temp_66-schema.sql
** Message: 23:25:36.385: Thread 1: Creating table `affordableswitzer`.`netcore_listuser_temp_66` from content in //backup/pdb5_mysql_dump/affordableswitzer.netcore_listuser_temp_66-schema.sql.
** Message: 23:25:36.386: Thread 4: Table `angelbroking01`.`21766_temp_user_user_attribute_151843855279991_ceaf1` created. Tables 0 of 35513 completed
** Message: 23:25:40.260: Thread 3: restoring table `aman_test`.`phplist_journeytag` from //backup/pdb5_mysql_dump/aman_test.phplist_journeytag-schema.sql
** Message: 23:25:40.260: Thread 3: Creating table `aman_test`.`phplist_journeytag` from content in //backup/pdb5_mysql_dump/aman_test.phplist_journeytag-schema.sql.
** Message: 23:25:40.260: Thread 1: Table `affordableswitzer`.`netcore_listuser_temp_66` created. Tables 0 of 35513 completed
** Message: 23:25:44.160: Thread 2: restoring table `allcargologisticsst`.`onsite_attributes` from //backup/pdb5_mysql_dump/allcargologisticsst.onsite_attributes-schema.sql
** Message: 23:25:44.160: Thread 2: Creating table `allcargologisticsst`.`onsite_attributes` from content in //backup/pdb5_mysql_dump/allcargologisticsst.onsite_attributes-schema.sql.
** Message: 23:25:44.161: Thread 3: Table `aman_test`.`phplist_journeytag` created. Tables 0 of 35513 completed
```
as there is a gap of almost 9 hours in the log file, maybe the disk got full?. If not, there might be a bug that I need to identify, because the other thing that I saw is that the table creation is getting slower in time. First I need to reproduce the issue, so I will be creating a 30k table schema and try to export and import and let you know what I found. 

Cheers

**Comment by BhushanGawade92** [comment]
@davidducos thanks for the response.

Due to using separate 1 TB space for backup and restore there is no disk space issue and it is only 68% used.

Also, when I tried to export and load only the schema for the same database server the schema restoration took only 6-7 minutes to complete but with the data it was taking time.

**Comment by davidducos** [comment]
Hi @BhushanGawade92 can you test with https://github.com/mydumper/mydumper/releases/tag/v0.14.5-2 ?

**Comment by davidducos** [comment]
Sorry, I meant https://github.com/mydumper/mydumper/releases/tag/v0.15.0-6

**Comment by davidducos** [comment]
No feedback provided
