### ISSUE TITLE
[Feature] mydumper backup sequence

### ISSUE THREAD

**Issue by VictorBusch** [mydumper/mydumper#1169]
Hello,

I can't find my wish here, so I'll tell you now ;-)

I would like it if there was an option to set or manually specify the backup sequence according to the size of the databases, because these threads have the longest runtime. 

This would be useful, because I have more than 30 databases in my MySQL and the last ones are the biggest ones (Typo3 databases with prefix t3_) and unfortunately they are only backed up at the end of the backup.

Best regards,
Victor

**Comment by VictorBusch** [comment]
Hello David,

we don't talk about restore, but about backup ;-)

I have  found your page yesterday (and register me for Github to write you ;-) ) and use v0.9 on Ubuntu. 
I will try 0.14 on the weekend again (yesterday it doesn't work), but I have read the changelogs and can't find a solution for my problem. 
Or am I wrong?

My problem:
If I backup the databases one by one, it should be a longer task, because the next backup starts after the last thread has finished of the previous database.

I have 30 databases and use 24 threads for backup. It takes me 10 minutes to backup all databases without the ten largest tables. 
The largest tables are spread over ten databases. Each large table also takes 8-10 minutes to backup. 
Today it takes me 20 minutes to do the backup. IMO it can be 10-12 minutes if mydumper starts with the largest databases first.

So it is interesting for me to do a mydumper run with all databases and with the largest database first.

Best regards
Victor

**Comment by davidducos** [comment]
Oh! wait, are you wishing something that you are not sure that it is already there?? Why did you asume that mydumper waits til a database has finish to continue? 
Hehehe... in terms of backups, we are trying to take all the info as fast as possible, doesn't care if the database is huge or small, and even if the schema is huge or small, doesn't care if you sort it, as what is going to make a backup faster, is not possible to see, which are the pages that are on memory, but that is a laaaaaarger discussion. 
So, just to summaries, mydumper will backup with 1 thread when table doesn't have a pk. If not, it will try to split depending on what you configure but it will export the data in chunk that should take between 1 and 2 seconds. mydumper will print in the long the remaining chunks...

**Comment by VictorBusch** [comment]
Sorry for the confusion. I use mydumper some years. I tried 0.14.5 but it doesn't work with my installation:

I start mydumper 0.14 with -h localhost -P 3306 -u mysuperuser -p 'passwd' ... and got this error:
2023-06-20 23:04:32 [INFO] - MyDumper backup version: 0.14.5-2
2023-06-20 23:04:32 [ERROR] - Error connection to database: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

But mysql -h localhost -P 3306 ... works.

But back to my wish: I looked in the changelog and I can't see a solution. But if the behaviour is changed I will be happy.

"Why did you asume that mydumper waits til a database has finish to continue?"
I understand you words as "backup DB1, then DB2, then DB3...". So I would start mydumper for each database one by one with a script.  But then mydumper starts  when the last thread is finished. And this needs to much time for me.

Is it possible to get the information over the information_schema like
mysql -u root -p'pwd' -e 'select table_schema "Database",round(sum(data_length+index_length)/1024/1024,4) "Size (MB)" from information_schema.tables group by table_schema;'  and sort the databases in the order from biggest to smallest?

But its fine if it is not possible.
Btw:  It is good to see that the tool is being further developed. Good luck!

**Comment by davidducos** [comment]
What I understood from your last message is that you have an script that it is doing:
```
mydumper -B DB1
mydumper -B DB2
mydumper -B DB3
```
but you can do this `mydumper -B DB1,DB2,DB3`
When you use `-B DB1,DB2,DB3` mydumper is going to search for all the tables on each DB without any order. We could add it, but it is not guarantee cross all the databases. With `--regex` will be almost the same.

**Comment by VictorBusch** [comment]
Thank you for your hints.

Normally I call mydumper as follows:
_mydumper -h 127.0.0.1 -P 3306 -u root -p 'pw' -x '^(?!(test|tmp|backup))' --less-locking --kill-long-queries -ecGER -t 12 -l 1200 -o /mysqltmp/backup -v 3 -L /mysqltmp/backup/mydump.log_

But now it seems to be better. Thank you for your time. You can tag this ticket as solved.
