### ISSUE TITLE
[BUG] Too many open files

### ISSUE THREAD

**Issue by jvargas-minitab** [mydumper/mydumper#1171]
**Describe the bug**
When running myloader if the total quantity of tables being loaded exceeds the user's ulimit myloader errors with a too many open files limit

**To Reproduce**
Command executed:
* myloader with all the parameters
```
/bin/bash -c "/usr/bin/myloader -u user  \
            -h external_host -a -t 4 \
            --directory=/var/local/export_db \
            --database=database_name \
            --compress-protocol --ssl --enable-binlog \
            > /tmp/myloader_database_name_stdout \
            2>myloader_database_name_stderr""
```

What mydumper and myloader version has been used?
mydumper 0.12.1, built against MySQL 5.7.33-36
myloader 0.12.1, built against MySQL 5.7.33-36

**Expected behavior**
I expected the database to open only the required files it needed for uploading the sql files it was processing

**How to repeat**
create enough tables to exceed the ulimit account set `ulimit -u your_user`
Then use mydumper to dump the files (this part works fine)
Then use myloader to import to an external database using 4 threads.  It will run the appropriate amount of threads, but will exceed the open file limit.  myloader is opening all of the metadata files at once and not closing them.  Shouldn't it only open the needed metadata file for the table being uploaded?

**Environment (please complete the following information):**
 - OS version: Debian 10
 - MyDumper version: 0.12.1buster-1

**Additional context**
We worked around the issue by using ulimit -n xxxx where xxxx is significantly greater than the quantity of the metadata files found in our dump directory.

**Comment by davidducos** [comment]
Hi @jvargas-minitab , on newer version of MyDumper, we suppressed .metadata and .checksum extension, which should reduce the amount of file descriptors opened by mydumper and myloader. 
Can you test with a newer version and let me know if you find the issue?

**Comment by jvargas-minitab** [comment]
@davidducos We can give the latest version a try.  We just have to schedule our migration test process in order to try with the latest version.

**Comment by davidducos** [comment]
Hi @jvargas-minitab you can test with: https://github.com/mydumper/mydumper/releases/tag/v0.14.5-2

**Comment by davidducos** [comment]
@jvargas-minitab 
Did you have the opportunity to test it??

**Comment by jvargas-minitab** [comment]
@davidducos I'm looking at testing it out in the next couple days.

**Comment by davidducos** [comment]
Closing for now until we get some feedback

**Comment by benediktblank** [comment]
@davidducos 
This seems to be an issue, still. We have 409 tables in our database and myloader failed with a "cannot open file" error and no obvious error message that gives any meaningful information.
With the help of AI we received information about raising the ulimit and did a "ulimit -n 65536" and now it works.

**Comment by davidducos** [comment]
Hi @benediktblank , what version are you testing? what was the previos value of "ulimit -n" ?

**Comment by hsteimann** [comment]
ulimit is 256 as a default when launching a new shell ... MacOS Tahoe 26.1.  ... Version: myloader v0.21.1-1

**Comment by davidducos** [comment]
Hi @hsteimann / @benediktblank , can you test with the latest prerelease?

**Comment by hsteimann** [comment]
@davidducos - I will give it a shot tomorrow - 0.21.2-3

**Comment by hsteimann** [comment]
@davidducos - I ran 0.21.2-3 with a dump of 820 files and 409 tables (same as before) on MacOS Tahoe 26.1 with ulimit -n 256 ... and it worked fine - good job!
