### ISSUE TITLE
What's the meaning of read_data in common.c

### ISSUE THREAD

**Issue by flttgjq** [mydumper/mydumper#1175]
![image](https://github.com/mydumper/mydumper/assets/35005856/04e3ed04-2004-4315-ab20-43e50b56037b)
As the picture above，There are two places here that confuse me：
1. why threre was a "while" scope here, the while scope seems meaningless, because `buffer[strlen(buffer)] != '\0'`is always false
2. `if (strlen(buffer) != 256` is always true, when a single line contains more than 256 characters, variable `line` will increase twice and will be inconsistent with the line number in file.

**Comment by davidducos** [comment]
Hi @flttgjq, 
read_data reads per line, because fgets reads per line. Your 1- is not TRUE, because it will be FALSE when you read data that has a '\n' at a N position. The same reason for 2- to be false.

**Comment by flttgjq** [comment]
Hi @davidducos 
![image](https://github.com/mydumper/mydumper/assets/35005856/eae6b1f1-db02-4129-aa32-e4c9363a550f)
![image](https://github.com/mydumper/mydumper/assets/35005856/de9d2300-c099-470c-a171-0243eb5b18fa)
fgets will add a ‘\0’ character to buffer. And strlen get length terminated by '\0'.
Is there any situation that can make the condition in while be TRUE？

**Comment by flttgjq** [comment]
And I did some test, when we read a single line over 256 characters with `fgets(buffer, 256, file)`，the value of `strlen(buffer)` is 255, which means `strlen(buffer)` will never greater than 255.
