### ISSUE TITLE
Start using MySQL 8 Libraries on all the packages

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1185]
Taking into account that Oct 2023 is the EOL of MySQL 5.7, we are going to start using MySQL 8.0 Libraries for all MyDumper packages.

**Comment by davidducos** [comment]
It is failing on el7 and el8.

**Comment by gdubicki** [comment]
Hi @davidducos! Thanks for your work on this great project. :) Does this issue mean that MySQL 5.7 will stop being supported?

**Comment by davidducos** [comment]
Hi @gdubicki, 
MyDumper can be compiled with the MySQL/Percona/MariaDB libraries. We are using the [C API](https://dev.mysql.com/doc/c-api/8.0/en/) that they offer. You could use MyDumper with any vendor that implements the same interface, for instance, Clickhouse or even ProxySQL Admin. But take into account that MyDumper executes some commands that are not present on those vendors, so you might need to disable some features. 
This doesn't mean that we support them or that we don't support them, you just need to configure in the right way. Take also into account [what is MyDumper](https://github.com/mydumper/mydumper?tab=readme-ov-file#what-is-mydumper).

This ticket was created to move from MySQL 5.7 libraries to 8.0 for the PACKAGES that we provide that can be found in the [release](https://github.com/mydumper/mydumper/releases) section.

**Comment by davidducos** [comment]
Taking into account that el7 is EOL on June/24, we are going to continue building package until it start to fail with 5.7 libraries. I'm going to test again on el8 during v0.16.5-1 preparation.
