### ISSUE TITLE
Schema Field Order Keeps Changing

### ISSUE THREAD

**Issue by egous-bunnings** [mydumper/mydumper#1204]
**Describe the bug**
If I do subsequent runs of mydumper I get different field ordering in the schema files.
This then shows up as changes in GIT across many tables that actually havent changed at all.
I have tried to run the dump process with a single thread but still get the same result.
Is there a way to ensure the export files and their field / schema order doesn't change?

I am running an system initialize before dumper runs that sets up DB schema, maybe this one is running inconsistently?
Is there a way to "order" fields as part of the dump command?

![image](https://github.com/mydumper/mydumper/assets/81303780/d2d7e87d-e251-4166-ac9d-05c5fda0f9da)

**To Reproduce**
Command executed:
My current command looks like this
`mydumper --host=mysql --user=${MYSQL_ROOT_USER} --password=${MYSQL_ROOT_PASSWORD} --database=${MYSQL_DATABASE} --outputdir=db-data --verbose=2 --order-by-primary --checksum-all --lock-all-tables --threads=1`

What mydumper and myloader version has been used?
v0.14.5-2

**Expected behavior**
I want subsequent runs to dump schema files consistently so I dont have to commit 300+ files on each re-generation, this will ensure Pull Requests can be small and ACTUAL changes are more obvious for PR reviewers

**How to repeat**
1. Run my bespoke system DB initialize that creates schema and inserts sample data. (I cannot share this)
2. Run a mydumper and commit files to git
3. Start again at step 1 on the exact same data and schema and I get changes

**Environment (please complete the following information):**
- Docker MyDumper container
- Connected to a MYSQL container
- Connected to an ecommerce system

**Comment by davidducos** [comment]
Hi @egous-bunnings,
First of all, what we need to review is myloader, not mydumper, but you didn't add the myloader command. Anyways, I can assume that you used --innodb-optimize-keys. When you use --innodb-optimize-keys, we split the CREATE TABLE statement in 3 pieces:
- create table with columns and primary key
- secondary indexes
- constraints
And we execute them in that order per table. We do not re order the indexes, that is something that the database vendor could do. So to be clear, myloader is executing:
```
CREATE TABLE
....
```
Then:
```
ALTER TABLE ...
  ADD KEY k1 (),
  ADD KEY k2 (),
  ADD KEY k3 ();
```
What is the from and to db vendor and version?

**Comment by egous-bunnings** [comment]
Thanks @davidducos, to elaborate on my use case.

1. I am working with packaged software that has an "initialize" command that sets up a default DB, schema and some sample data however this process takes 45 minutes when done through their App and ORM, It writes to a MYSQL 8 docker db.
2. I am using Myloader and MyDumper to fast track that for some test scenarios and instead of doing the above process I load files from disk (Previously written by MyDumper) and use MyLoader to standup the MYSQL db almost instantly.
3. Both the source and destination is the same container DB, same version of mysql etc.
4. I am seeing inconsistency in the "order" of fields in the .SQL files
5. This is troublesome as the result from mydumper is circa 600 files on disk, lots of them change each time I run mydumper but its not "real" change just field order change causing lots of GIT file churn
6. Its unclear to me if there is a solution for this with mydumper configs OR
7. If its being caused by step 1 and it possibly being the result of race conditions as part of a multi-threaded proccess working with the DB

I dont think the issue is with myloader however here is how I load the SQL files back into the empty DB
`myloader --host=mysql --user=${MYSQL_ROOT_USER} --password=${MYSQL_ROOT_PASSWORD} --directory=db-data --overwrite-tables --verbose=2 --innodb-optimize-keys`

**Comment by davidducos** [comment]
Hi @egous-bunnings, 

I was not able to reproduce your scenario on 8.0.33-25 Percona Server. Please, I will need a reproducible test with all the information. There is no problem if this is on Docker, but I need full version of the software that you are using, the schema of the table and the commands executed.

**Comment by egous-bunnings** [comment]
Thanks @davidducos, I am going to interpret this as the DB field order is inconsistent as a result of my source system not DBDumper itself and there isnt a built in feature to rectify this.
I am unable to share the source system with you as its a large piece of licensed software.
I will close the ticket for now and be sure to comment here if I find a plausible workaround that others could benefit from.
