### ISSUE TITLE
[BUG] dump views failed

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#1215]
**Describe the bug**
When exporting views, it will cause the backup task to fail

**To Reproduce**
Command executed:
* mydumper with all the parameters
* myloader with all the parameters
mydumper --set-names=utf8mb4 --use-savepoints --less-locking --skip-tz-utc --complete-insert --trx-consistency-only --hex-blob --skip-definer --no-check-generated-fields --disk-limits=1024:10240 --rows=10000:100000:0 -v 3 -R -G -E -c -e

What mydumper and myloader version has been used?
mydumper0.14.5-2, built against MySQL 5.7.42-45 with SSL support with ZSTD

**Log**
The logs will only be printed to the following location：
![image](https://github.com/mydumper/mydumper/assets/9590209/c7941c73-484b-4c14-ba74-26fa202fe1e7)

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
 - MyDumper version: [ mydumper --version ]
centos 7
mydumper0.14.5-2, built against MySQL 5.7.42-45 with SSL support with ZSTD

**Comment by davidducos** [comment]
Hi @peng19832,
Can you share the table structure of the view that is failing? If the view is jwell_fms.view_pcg then we have a problem as data is being extracted from that view, but I don't see that you are using --views-as-tables.

**Comment by peng19832** [comment]
> Hi @peng19832, Can you share the table structure of the view that is failing? If the view is jwell_fms.view_pcg then we have a problem as data is being extracted from that view, but I don't see that you are using --views-as-tables.

Do you need the structure of the underlying table that the view depends on?
I don't want to export the view as a table. 
Can mydumper export the ddl of the view like mysqldump, so that myloader only needs to execute the create view statement to rebuild the view？

**Comment by peng19832** [comment]
> Hi @peng19832, Can you share the table structure of the view that is failing? If the view is jwell_fms.view_pcg then we have a problem as data is being extracted from that view, but I don't see that you are using --views-as-tables.

At present, I can't determine whether the backup failed because of the view, because I saw that the backup was successful before July 4th, and only this one instance failed.
![image](https://github.com/mydumper/mydumper/assets/9590209/1626d8b0-ee25-4ad8-b592-bdd893249554)

**Comment by peng19832** [comment]
> Hi @peng19832, Can you share the table structure of the view that is failing? If the view is jwell_fms.view_pcg then we have a problem as data is being extracted from that view, but I don't see that you are using --views-as-tables.

I found the following segfault log. Excuse me, will mydumper export the wrong core file to help troubleshoot the cause?
Jul 21 02:30:31 dbdatastorage kernel: mydumper[12135]: segfault at 10 ip 000000000044c29d sp 00007fcf3a381c90 error 4 in mydumper[400000+373000]

**Comment by davidducos** [comment]
@peng19832,

Just to clarify, mydumper export views in files with suffix `-schema-view`, in your case, you should have `jwell_fms.view_pcg.schema-view.sql`, do you have it?
mydumper also creates `jwell_fms.view_pcg.schema.sql` with a create table statement to avoid other issues in myloader.

So, as you don't want to export the view content, I need to confirm that jwell_fms.view_pcg is a VIEW and not a table. Can you execute:
```
SHOW CREATE TABLE jwell_fms.view_pcg ;
```

**Comment by peng19832** [comment]
> @peng19832,
> 
> Just to clarify, mydumper export views in files with suffix `-schema-view`, in your case, you should have `jwell_fms.view_pcg.schema-view.sql`, do you have it? mydumper also creates `jwell_fms.view_pcg.schema.sql` with a create table statement to avoid other issues in myloader.
> 
> So, as you don't want to export the view content, I need to confirm that jwell_fms.view_pcg is a VIEW and not a table. Can you execute:
> 
> ```
> SHOW CREATE TABLE jwell_fms.view_pcg ;
> ```

@davidducos 
Sorry, I checked again. This view_pcg is a table, not a view.
This table name misled me：
![image](https://github.com/mydumper/mydumper/assets/9590209/5270ef5f-6cbd-4710-b442-f713f7bf52b4)

However, at this time, a segfault is indeed triggered, will mydumper export some useful files?
![image](https://github.com/mydumper/mydumper/assets/9590209/dbbb1727-b0df-43be-9de9-3696eb2f5201)

**Comment by peng19832** [comment]
![image](https://github.com/mydumper/mydumper/assets/9590209/7513aaeb-587f-400f-a18c-46e3bd722308)

[core-mydumper.zip](https://github.com/mydumper/mydumper/files/12159274/core-mydumper.zip)

**Comment by davidducos** [comment]
Hi @peng19832, 
I think that I have found the issue, this is the query that is failing:
```
SHOW CREATE PROCEDURE `jwell_fms`.`P_AC_AT_REPORT_ZS``
```
As you can see, there is an extra backtick. Do you have a store procedure with a backtick at the end like that?

**Comment by peng19832** [comment]
@davidducos 
Ha, it is indeed because of this stored procedure.
thanks BOSS.

**Comment by davidducos** [comment]
Ok! I will need to add a new test case and see how to fix this.
