### ISSUE TITLE
[BUG] Process spawn issue with compression or --exec options

### ISSUE THREAD

**Issue by tanji** [mydumper/mydumper#1226]
**Describe the bug**
Process spawn issue with compression or --exec options
When using the commands below multiple processes are spawned and mydumper will never terminate.
Besides, schema dump will hang or give connection errors. e.g.:
** (mydumper:12840): CRITICAL **: 14:59:35.544: Error dumping schemas (xxx.xxx): Lost connection to MySQL server during query
We can see below the multiple processes running.
```
$ pgrep -f -a mydumper -c
292
```
This does not appear if exec options or compression are not used.

Note that Ctrl-C will not work and processes have to be cleaned up with signal 9.

This works fine with older versions of mydumper (e.g. 0.10.x)

**To Reproduce**
Command executed:
`mydumper -h xxx -u xxx -p xxx --exec-per-thread="zstd -c" --exec-per-thread-extension=".zst" -v 3`
or
`mydumper -h xxx -u xxx -p xxx -c -v 3`

What mydumper and myloader version has been used?
mydumper v0.15.1-1 built against MySQL 8.0.33-25 with SSL support

**Expected behavior**
Schema dump should proceed normally and reach next stage

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
-> Cannot upload for legal reasons

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough
-> Cannot list for legal reasons. There are ~10 schemas in each cluster which contain innodb tables

**How to repeat**
Same effect happens no matter what the database schema or target cluster is.

**Environment (please complete the following information):**
 - OS version: Debian 10 amd64
 - MyDumper version: 0.15
 - MariaDB 10.5.21 Galera Cluster

**Comment by davidducos** [comment]
Hi @tanji, 

can you confirm that `mydumper -c ZSTD` is not working either?
can you run `which gzip`? as we consider the default on /usr/bin/gzip

**Comment by tanji** [comment]
Confirming that it works fine with [v0.14.5-2](https://github.com/mydumper/mydumper/releases/tag/v0.14.5-2) so the issue is probably with 15.0

Yes, I have tested with zstd, same issue.
```
# which gzip
/bin/gzip
```

this is a normal Debian 10 system.

**Comment by davidducos** [comment]
@tanji can you use the absolute path on --exec-per-thread ?? and retry to confirm the bug

**Comment by tanji** [comment]
ok, zstd was not installed in the system. So that's why. It works fine with the absolute path
I think the system needs a bit of sanity check , or maybe document that it needs absolute path :)
Also, gzip is now in `/bin/` in debian at least (/usr/bin is deprecated) that is why `-c` was not working
Anyway, thanks for your help! :pray:

**Comment by davidducos** [comment]
agree! agree! agree! a lot of things changed, whit out the proper documentation. Thanks!
BTW, https://github.com/mydumper/mydumper/issues/1228 was created
