### ISSUE TITLE
[BUG] Broken parallelism when using --exec-per-thread

### ISSUE THREAD

**Issue by tanji** [mydumper/mydumper#1230]
**Describe the bug**
When using --exec-per-thread option (for example for compression), the N threads aren't used fully. The other threads are sleeping until the currently remaining thread has terminated.
e.g. with 4 threads
thread 1: dump table A
thread 2: dump table B
thread 3: dump table C
thread 4: dump table D

if 1, 2 have finished they seem to wait until 3 then 4 has finished to start working again.
This behavior is only visible when --exec-per-thread option is used 

example:
```
Query  102568455  Writing to net      external  1.1.1.1    usage_data           00:05.179  SELECT /*!40001 SQL_NO_CACHE */ * FROM `usage_data`.`tseb`  
Sleep  102568457                      external  1.1.1.1    api_st         00:05.175                                                                                 
Sleep  102568456                      external  1.1.1.1    quay                 00:05.085                                                                                 
Query  102568454  Writing to net      external  1.1.1.1    pim                  00:01.828  SELECT /*!40001 SQL_NO_CACHE */ * FROM `usage_data`.`sepc`
```

Here 2 threads are sleeping although there are still tables to dump... This is causing a much longer backup time.

If looking from strace context one can clearly see 3 of the threads are in `wait4` state while the 4th is receiving data

```
rundeck@usher:~$ strace -p 12691 -f
strace: Process 12691 attached with 8 threads
[pid 12764] write(11, "66253246714F3366344F36317171584F"..., 5667571 <unfinished ...>
[pid 12763] wait4(98252,  <unfinished ...>
[pid 12762] wait4(98257,  <unfinished ...>
[pid 12761] wait4(98195,  <unfinished ...>
[pid 12759] futex(0x5578aa5043a0, FUTEX_WAIT_PRIVATE, 787, NULL <unfinished ...>
[pid 12734] restart_syscall(<... resuming interrupted poll ...> <unfinished ...>
[pid 12691] futex(0x7f7a068629d0, FUTEX_WAIT, 12759, NULL <unfinished ...>
[pid 12736] restart_syscall(<... resuming interrupted poll ...> <unfinished ...>
[pid 12764] <... write resumed> )       = 5667571
[pid 12764] recvfrom(10, "\2452+e\0071175601\0047364\00537145\0071107614#"..., 16384, 0, NULL, NULL) = 16384
[pid 12764] recvfrom(10, "cnIjBv8NJwzaAsQN6wrhYGeVsoNja9bh"..., 2814633, 0, NULL, NULL) = 1941729
[pid 12764] recvfrom(10, "inH5QKnbdJzNincd6h3MekcS%2Fj%2FD"..., 872904, 0, NULL, NULL) = 23168
[pid 12764] recvfrom(10, "GIVCkBaQ5RkiUVDg70u4PWAdtPWBTUEE"..., 849736, 0, NULL, NULL) = 23168
```

**To Reproduce**
Command executed:
```
mydumper -h xxx -u xxx -p xxx --exec-per-thread="/usr/bin/lz4 -c" --exec-per-thread-extension=".lz4"
```
Same behavior regardless of what compression method is used

**Expected behavior**
Parallelism should be fully used :)

**Environment (please complete the following information):**
 - OS version: Debian 10
 - MyDumper version: 15.1

**Comment by davidducos** [comment]
Seems that is happening because of:
```
# grep -n waitpid src/mydumper*
src/mydumper_common.c:129:    waitpid(f->pid, &status, 0)
```
I found that in Debian, it is not the same use this:
```
#include <wait.h>
```
instead of :
```
```
It is not clear for me yet, why the first option `#include <wait.h>` is working as expected. So, if you are able to download, change and compile with the latest version, will be awesome, as I can't test on docker Circle CI testing env.
