### ISSUE TITLE
[BUG] mydumper on ARM laptop (osx M1) infinite sleep for AWS aurora DB

### ISSUE THREAD

**Issue by zeetabit** [mydumper/mydumper#1231]
**Describe the bug**

Infinite wait after schema dumping step (I see only schema files), wait 2 days and nothing happens.

**To Reproduce**
Command executed:
* mydumper with all the parameters

```
   mydumper \
    --host=host.rds.amazonaws.com \
    --user=db_user \
    --password=db_pass \
    --outputdir=/Users/user/dumps/db_name \
    --max-rows=70000 \
    --no-locks  \
    -G -E -R \
    --compress \
    --build-empty-files \
    --threads=4 \
    --compress-protocol \
    --regex '^(db_name\.)'
```
 
* myloader with all the parameters

What mydumper and myloader version has been used?
on ARM:
mydumper v0.15.1-1, built against MySQL 8.0.33 with SSL support
mydumper v0.15.2-1, built against MariaDB 11.0.2 with SSL support
on Intel:
mydumper v0.14.5-2, built against MySQL 8.0.33 with SSL support with GZIP

**Expected behavior**
Work as usual as on Intel. I tried the same command and it works, on ARM laptop - not working.

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
NDA

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough
NDA

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
Or upload a [core dump](https://github.com/mydumper/mydumper/wiki/Support#core-dump) for cases where mydumper or myloader is crashing.
I not sure that it depends on table structure, as it working fine on Intel laptop and not working on ARM based laptop.

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
 Intel: MacOS Monterey 12.5.1
 ARM: MacOS Ventura 13.3.1

 - MyDumper version: [ mydumper --version ] - already provided

**Additional context**

**Comment by zeetabit** [comment]
Tried v0.14.5-2 on ARM and have
```
** (mydumper:25572): WARNING **: 14:40:12.929: Executing in no-locks mode, snapshot might not be consistent

** (mydumper:25572): WARNING **: 14:40:14.634: We are not able to determine if the backup will be consistent.

** (mydumper:25572): WARNING **: 14:40:14.634: We are not able to determine if the backup will be consistent.

** (mydumper:25572): WARNING **: 14:40:14.634: We are not able to determine if the backup will be consistent.

** (mydumper:25572): WARNING **: 14:40:14.634: We are not able to determine if the backup will be consistent.
gzip: error writing to output: Broken pipe
```

**Comment by davidducos** [comment]
Hi @zeetabit, 
In order to troubleshoot your issue, I would like you to use the latest release: v0.15.1-2, is it possible? as I think that this might be related that mydumper/myloader is not able to detect the gzip location and you might need to use --exec-per-thread

**Comment by davidducos** [comment]
closing for now, reopen when you have some feedback.

**Comment by zeetabit** [comment]
Works for `v0.15.2-6`, thanks!
