### ISSUE TITLE
[FEATURE REQUEST] Can ignore LOCK BINLOG FOR BACKUP?

### ISSUE THREAD

**Issue by baixiaoyu** [mydumper/mydumper#1240]
**Describe the Feature Request**
mydumper use " lock binlog for  backup" to get binlog coordinates ,this cause binlog lock contention. 

**Current behaviour**
for now ,mydumper use  "LOCK TABLES FOR BACKUP" and "LOCK BINLOG FOR BACKUP" for percona mysql57 backup no matter if we need to get binlog information.

**Expected behavior**
Don't use lock binlog for backup to get binlog information if we don't want it

**Comment by davidducos** [comment]
Hi @baixiaoyu, 
Why don't you use --no-backup-locks ?
```
  --no-backup-locks                Do not use Percona backup locks
```
