### ISSUE TITLE
Mydumper 0.14 not splitting the large table for dumping data 

### ISSUE THREAD

**Issue by viswaprsnl** [mydumper/mydumper#1244]
**Describe the bug**
We are trying to compare the exports between 0.10 and 0.14 and we see a huge increase in overall time taken 2x . What we observed is in 0.10 mydumper took the largest table and assigned all the threads to it making it optimal where in 0.14 its mostly using single thread for that particular table which is the cause for 2X

**To Reproduce**
Command executed:
/usr/bin/mydumper --user=perfdev --password=***** --host=s- --port=--database=newyottapayviswa_s_2m294806kr --outputdir=/data/exports/yottapay/dfgsdrg.xar.newyottapayviswa_s_dfsgdfh.tempdir/wdx.D_Dir-00 --less-locking --build-empty-files --trx-consistency-only --events --routines --triggers --compress --logfile=/perfshared/software/wmu/logs/mydumper.1691090286742.log --verbose=3 --threads=16 --rows=500000 --long-query-guard=86400

What mydumper and myloader version has been used?

mydumper0.14.5-2

**Expected behavior**
No regression from 0.10 to 0.14

**Log**
I will attach the logs for 0.10 and 0.14

**Backup**

If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**

.

**Environment (please complete the following information):**
centos 9

**Comment by davidducos** [comment]
Hi @viswaprsnl,

Can you share the CREATE TABLE statement for `newyottapayviswa_s_2m294806kr`.`audited_instance`  ? I'm requesting this, as in mydumper.0.14_.log I found:
```
2023-08-02 15:50:21 [INFO] - Thread 34: dumping data for `newyottapayviswa_s_2m294806kr`.`audited_instance`          into /data/exports/yottapay/s2m294806kr_yottapay.Save.20230801.xar.newyottapayviswa_s_2m294806kr.tempdir/wdx.D_Dir-00/newyottapayviswa_s_2m294806kr.audited_instance.00000.sql.gz| Remaining jobs in this table: 0 All remaining jobs: 2
...
2023-08-02 16:41:47 [INFO] - Thread 19: shutting down
2023-08-03 02:33:48 [INFO] - Thread 34: shutting down
```

This means that mydumper didn't detect the integer primary key that the table should have to split the table as it was doing on the v0.10 log.

**Comment by viswaprsnl** [comment]
Hi @davidducos pfb the create statement
---------------------------------------------------------------------------------------------+
| Table            | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| audited_instance | CREATE TABLE `audited_instance` (
  `class` int unsigned NOT NULL,
  `inst` bigint unsigned NOT NULL,
  `add_chg` bigint unsigned NOT NULL,
  `del_chg` bigint unsigned DEFAULT NULL,
  `upd_txn` bigint unsigned NOT NULL,
  `imm_txn` bigint unsigned NOT NULL DEFAULT '0',
  `options` tinyint NOT NULL DEFAULT '0',
  `iv` binary(16) NOT NULL,
  `data` longblob NOT NULL,
  PRIMARY KEY (`class`,`inst`),
  KEY `upd_txn` (`upd_txn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 |

**Comment by davidducos** [comment]
Ok, the issue seems that your compound primary key granularity is causing the issue plus the fact that we change the way that we determine the chunks per table. 
I recommend you to use --rows 10:100:0, but this needs to be reviewed as depends on the granularity of the first column. 
BTW this is a good opportunity to talk about the possibility to support multi column tables.

**Comment by viswaprsnl** [comment]
@davidducos even after adding the flags i see the audited instance is taking the same time and my overall export time is 12 hours which is 2X of my 0.10 dumper export times PFB the new log 
[mydumper.0.14_newflag.log.zip](https://github.com/mydumper/mydumper/files/12267691/mydumper.0.14_newflag.log.zip)

This is my dumper command 
/usr/bin/mydumper --user=--password= --host= --database=newyottapayviswa_s_2m294806kr --outputdir=kfjlkfdjglgfdkj --less-locking --build-empty-files --trx-consistency-only --events --routines --triggers --compress --logfile=/log.log --verbose=3 --threads=16 --rows=500000 --long-query-guard=86400 --chunk-filesize=2000 --rows 100000:100000:500000

let me know if this needs any other newer flag ?

**Comment by davidducos** [comment]
Hi @viswaprsnl,
The command shows that you set --rows twice which shouldn't happen. On the other hand, you use different values of what I propose. Please, follow my instructions, try again and send me the log. BTW, you should test with latest version.

**Comment by viswaprsnl** [comment]
Hi @davidducos  i see no difference in overall timings and the behavior  .Please find attached the new log 
[mydumper_viswa_works_todavid.log.zip](https://github.com/mydumper/mydumper/files/12287512/mydumper_viswa_works_todavid.log.zip)

/usr/bin/mydumper --host=s-server. --port=(*(* --database=mocked--outputdirlocation.tempdir/wdx.D_Dir-00 --less-locking --build-empty-files --trx-consistency-only --events --routines --triggers --compress --logfile=.log --verbose=3 --threads=40 --long-query-guard=86400  --rows 10:100:0

**Comment by davidducos** [comment]
Hi @viswaprsnl 
Can you add the option -T <database_name>.audited_instance with -r 1 and upload the log?
I want to have an idea what is better for you, if we add --rows per table or implement the split on multi-column primary keys. 
Later today I will be creating both tickets but I know that adding --rows will be much simpler.

**Comment by viswaprsnl** [comment]
@davidducos -T dbname.audited_instance -r 1 ? to the existing mydumper command that i am using ? audited instance is 700gig table will -r 1 will just do one row each time ?

**Comment by davidducos** [comment]
@viswaprsnl, it will do each class at a time. I suspect that you have millions of rows under certain class.

**Comment by viswaprsnl** [comment]
@davidducos 

I am using the below mydumper command as suggested by  you

```
/usr/bin/mydumper --user= --password= --host=host --port=3306 --database=DBANME --outputdir=/data/exports/yottapayexp/DBANME.Save.20230801.xar.DBANME.tempdir/wdx.D_Dir-00 --less-locking --build-empty-files --trx-consistency-only --events 
--routines --triggers --compress --logfile=/perfshared/users/viswanathan.kan
[mydumper_viswa_newchunk_auditedtable_david.log](https://github.com/mydumper/mydumper/files/12296361/mydumper_viswa_newchunk_auditedtable_david.log)
nan/mydumper_viswa_newchunk_auditedtable.log --verbose=3 --threads=40 --long-query-guard=86400 --chunk-filesize=2000 --rows 10:100:0 -T DBANME.audited_instance r -15
```

I am not seeing anything different , its just that it started dumping audited_instance table first , but its single threaded and with the way its progressing i still feel the export timings are going to remain the same (it has hardly done 70gb in hour , it needs to to 750gb just for audited instance).

[mydumper_viswa_newchunk_auditedtable_david.log](https://github.com/mydumper/mydumper/files/12296362/mydumper_viswa_newchunk_auditedtable_david.log)

**Comment by martysweet** [comment]
@davidducos 

We have seen similar behaviour with  `mydumper v0.15.1-3` vs `mydumper 0.10.7`.
For us, it seems with 0.15.1 the output we get is single thread per-table for any table (mostly single column PK), and thus imports also occur on a single thread.

I had put this down to the old DB version we are exporting from and ignored the behaviour `10.1.21-MariaDB MariaDB Server`.
Most of our tables are `TokuDB` with some larger tables having row counts of millions -> billions.
In these examples, 695 tables were exported (some empty) across 4 schemas.

For the 0.10.7 run (Creates 000001,2,34...sql files for each table as required - or just .sql if small)
```bash
mydumper --regex '^(<selector>)' -G -E -R \
--outputdir ./10-7-2/ \
--logfile ./10-7-2/dump.log \
--threads 16 \
--rows 2000000 \
--host <host> \
--user <user> \
--ask-password \
--verbose 3 \
--long-query-guard 86400 \
--lock-all-tables

ls -1 ./10-7-2/ | wc -l 
7455

du -sh ./10-7-2/
1.1T    .
```

For the 0.15.1 run (Only creates table-00000.sql)
```bash
mydumper --regex '^(<selector>)' -G -E -R \
--outputdir ./fulldataset/ \
--logfile ./fulldataset/dump.log \
--threads 16 \
--split-partitions \
--rows 10000 \
--host <host> \
--user <user> \
--ask-password \
--lock-all-tables

ls -1 ./fulldataset/ | wc -l
1383

du -sh ./fulldataset/
1.4T    .
```

I can't explain the size difference (the dumps are on the same filesystem) - We are yet to verify either dump.

Hope this helps -  Let me know if further information would be useful.

**Comment by viswaprsnl** [comment]
@martysweet any idea on the timings ( is your export/import times have regressed from 0.10) .

**Comment by martysweet** [comment]
@viswaprsnl That's correct regarding keys - I don't believe this is specific to composite keys. Unless something triggers single threaded behaviour for all schemas related to the job?

The commands in my above post resulted in the following times (measured from first file modified time - last (metadata) written time).

```
0.10.7 = 8.33 hours
0.15.1 = 24.23 hours
```

**Comment by davidducos** [comment]
Hi @martysweet,

A lot of things changed from 0.10 to 0.15, you should get better timings if you set `--rows 10000:10000:0`.

The most important change that we did is related to the chunks, as you can see, the amount of file is smaller, which was something that we wanted for a long time, as there was no need to keep a lot of small files. Nowadays, we split the table into chunks, depending on the amount of threads that are exporting data from that particular table. That is way --rows has 3 values now, first one is the min, tables with lower than min are going to be extracted with full table scan. Middle value is the starting point, every table start with chunks of that size, but the chunk size can increase if the SELECT takes less than 1 second and decreases if it takes more than 2 seconds. The max is the third value and 0 (zero) means no limit. 

If you want multiple files, then you can use -F. 

Ah but if you use --rows X, the X is set to min, starting point and max, which in some scenarios is not desirable but it is useful in others. That is also why I implemented the `rows` per table. So, you can decide what is the best per table basis. 

@viswaprsnl, About your issue and the log that you share, you will find that Thread 7 is still running and it didn't finish yet. That is what it was doing:
```
2023-08-08 14:11:24 [INFO] - Thread 7: dumping data for `mydbname`.`audited_instance`  WHERE (  ( 1313 < `class` AND `class` <= 1328))       into /data/exports/yottapayexp/hostname_yottapay.Save.20230801.xar.mydbname.tempdir/wdx.D_Dir-00/mydbname.audited_instance.00096.sql.gz| Remaining jobs in this table: 2999 All remaining jobs: 2999
```
Can you execute: 
```
ls -lh /data/exports/yottapayexp/hostname_yottapay.Save.20230801.xar.mydbname.tempdir/wdx.D_Dir-00/mydbname.audited_instance.*.sql.gz
```
?? 
Because I 100% sure that the table is not evenly distributed and that might be causing the issue. 
For instance, if you check the log on v10 you have:
```
2023-07-28 00:38:33 [INFO] - Thread 15 dumping data for `yotta_pay`.`audited_instance` where (`class` >= 1308 AND `class` < 1323)
...
2023-07-28 02:26:09 [INFO] - Thread 7 shutting down
2023-07-28 05:54:12 [INFO] - Thread 15 shutting down
2023-07-28 05:54:12 [INFO] - Finished dump at: 2023-07-28 05:54:12
```
That means that the class between 1313 and 1323 has more rows that the rest of the class. That is why I almost sure that setting a lower value of rows on that particular table, will help you.

**Comment by viswaprsnl** [comment]
@davidducos if you go back to our previous chats , I did set lower values for that particular table and i did see it started the instance table in the first place but showed the same behavior . This is the command i used 
 `/usr/bin/mydumper --user= --password= --host=host --port=3306 --database=DBANME --outputdir=/data/exports/yottapayexp/DBANME.Save.20230801.xar.DBANME.tempdir/wdx.D_Dir-00 --less-locking --build-empty-files --trx-consistency-only --events 
--routines --triggers --compress --logfile=/perfshared/users/viswanathan.kan
[mydumper_viswa_newchunk_auditedtable_david.log](https://github.com/mydumper/mydumper/files/12296361/mydumper_viswa_newchunk_auditedtable_david.log)
nan/mydumper_viswa_newchunk_auditedtable.log --verbose=3 --threads=40 --long-query-guard=86400 --chunk-filesize=2000 --rows 10:100:0 -T DBANME.audited_instance r -15`

[mydumper_viswa_newchunk_auditedtable_david.log](https://github.com/mydumper/mydumper/files/12296362/mydumper_viswa_newchunk_auditedtable_david.log)

The above log has the details of that run . I cancelled the run in the midway because it showd the same rate ..

**Comment by davidducos** [comment]
Hi @viswaprsnl, sorry that I'm not able to explain it correctly. Let me try one more time. 
According to v0.10 log, the chunk of table `yotta_pay`.`audited_instance` where (`class` >= 1308 AND `class` < 1323 ) took 5 hours and 16 minutes. All the other chunks took less than 2 hours. 

That means that the distribution of the table by class is uneven, that can be verified with:
```
SELECT class, count(*) FROM audited_instance GROUP BY class;
```
On v0.15, when we set --rows 15 we tried to simulate the same chunk size, but the problem is that we don't know which are the class that has the highest amount of rows.
You said that you cancel that execution but it could take 5 hours as the previous one or not, we don't know, for sure, the SELECT will show the table distribution and it will iron out any doubts about that. 

So, the solutions?? I already added the rows option per table which will help us to configure the min:start_point:max per table. However, it doesn't solve all the issues, as when we have a multi column primary key, it fails. I'm already thinking about how to implement https://github.com/mydumper/mydumper/issues/1254.

**Comment by viswaprsnl** [comment]
@davidducos  , in the first place is there a way to know what could have caused this from 0.10 version . audited_instance table did not change . Marty sweet has also confirmed that the export time went up drastically , Is there a chance to revert the exact change that would have caused it . FYI ( i will run the audited table with r -15 ) but i strongly believe its not going to change anything .

One more question: what is the optimum  --rows 10000:10000:0 for the DB you suggest . you were suggesting multiple param values in this thread .

**Comment by viswaprsnl** [comment]
@davidducos . I have some new analysis data from my runs , I do see tabular_wid table also has composite primary key and has a specific class having 2 bil record ,similar to audited_instance . the only diff is tabilar_wid  has 3 cols where audited has 9 cols 
I will list both the create DDL statement below . The only catch here in in 0.10 the dumper does in this order auidted_instance then tabular_wid , but in 0.14 its not taking audited instance in first place which is the reason for contention . is there a way to tell dumper to order the table by largest (like how we do in 0.10)

```

tabular_wid \| CREATE TABLE `tabular_wid` (  `class` bigint NOT NULL,  `inst` bigint NOT NULL,  `wid` binary(16) NOT NULL,  PRIMARY KEY (`class`,`inst`),  UNIQUE KEY `IDX_WID` (`wid`))
--

```audited_instance | CREATE TABLE `audited_instance` (
  `class` int unsigned NOT NULL,
  `inst` bigint unsigned NOT NULL,
  `add_chg` bigint unsigned NOT NULL,
  `del_chg` bigint unsigned DEFAULT NULL,
  `upd_txn` bigint unsigned NOT NULL,
  `imm_txn` bigint unsigned NOT NULL DEFAULT '0',
  `options` tinyint NOT NULL DEFAULT '0',
  `iv` binary(16) NOT NULL,
  `data` longblob NOT NULL,
  PRIMARY KEY (`class`,`inst`),
  KEY `upd_txn` (`upd_txn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3

**Comment by viswaprsnl** [comment]
@davidducos but if you see my create statements of the 2 tables above ? both has composite primary key (multicolumn) , but tabular_instance was able to perform as same as 0.10 while audited instance was unable to ? So i am just thinking its not the Multi column that will remediate this ? let me know if i am wrong

**Comment by mdkent** [comment]
> @davidducos
> 
> We have seen similar behaviour with `mydumper v0.15.1-3` vs `mydumper 0.10.7`. For us, it seems with 0.15.1 the output we get is single thread per-table for any table (mostly single column PK), and thus imports also occur on a single thread.
> 
> I had put this down to the old DB version we are exporting from and ignored the behaviour `10.1.21-MariaDB MariaDB Server`. Most of our tables are `TokuDB` with some larger tables having row counts of millions -> billions. In these examples, 695 tables were exported (some empty) across 4 schemas.
> 

Seeing similar behaviour here with `MyDumper backup version: 0.15.1-3` dumping `10.1.16-MariaDB` via
```
time mydumper \
--compress ZSTD \
--max-rows 1 \
--verbose 3 \
--long-query-guard 999999 \
--no-locks \
--outputdir /mnt/export \
--logfile /mnt/export/mydumper.log \
--build-empty-files \
-T redacted.hooks \
--defaults-file /mnt/mariadb.cnf
```
where the schema is
```
root@foo:/mnt# zstdcat export/redacted.hooks-schema.sql.zst
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
CREATE TABLE `hooks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bucket_id` int(11) DEFAULT NULL,
  `payload_url` varchar(8000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `types` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `index_hooks_on_bucket_id` (`bucket_id`),
  CONSTRAINT `_fk_rails_2ca4b25af9` FOREIGN KEY (`bucket_id`) REFERENCES `buckets` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1362873 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
Regardless of `--max-rows 1` or `--rows x:y:0` it always dumps everything into one file.

The log doesn't say much, just
```
2023-09-27 22:03:22 [INFO] - Thread 4: dumping data for `redacted`.`hooks`          into /mnt/export/redacted.hooks.00000.sql| Remaining jobs in this table: 0 All remaining jobs: 0
```
The table has some 375955 rows.

**Comment by peterdk** [comment]
I tried migrating to mydumper from 0.10 to latest git, but my table with 48 billion rows, does not get split into separate files (1 per billion) anymore. So for now I have reverted back to 0.10. 
I did use:
`nice mydumper --trx-consistency-only -B db --exec-per-thread="/usr/local/bin/zstdmt -11" --exec-per-thread-extension=".zst"  -o $FOLDER -h host -P port -u user -p pass -t 4 --rows 1000000000`

**Comment by davidducos** [comment]
Hi all,
I'm already working on this issue

**Comment by peterdk** [comment]
The issue is closed, but I still only get a single thread on a single table when dumping with latest master mydumper.

Table I am dumping:
```
CREATE TABLE `foo` (
  `a` int(10) unsigned NOT NULL,
  `b` int(10) unsigned NOT NULL,
  PRIMARY KEY (`a`,`b`),
  KEY `class_app_version` (`a`,`b`)
) ENGINE=ROCKSDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```
Command:
```
mydumper -h 127.0.0.1 -u user -p pass -B db -o ./ -t 4 --rows 1000000000:1000000000:0 --order-by-primary --exec-per-thread '/usr/local/bin/zstdmt -11' --exec-per-thread-extension=".zst" -T database.table  --verbose 3  --trx-consistency-only  
```
Output:
```
Thread 4: dumping data for `database`.`table`        ORDER BY `a`,`b` into ./database.table.00000.sql | Remaining jobs in this table: 1 All remaining jobs: 0
```
No other threads are doing any work, just this single one.

**Comment by davidducos** [comment]
Hi @peterdk , seems that you are not using --rows correctly, as you have the opportunity to set the MIN:STARTING_POINT:MAX, so you are setting min as 1000000000, so only the tables larger than 1000000000 will be split into chunks. Feel free to set more realistic numbers. Ah and btw, ENGINE=ROCKSDB is not supported to be chunked. So you might need to create a feature request.
