### ISSUE TITLE
[BUG] Myloader imports table from wrong database using -s and -B

### ISSUE THREAD

**Issue by hubiongithub** [mydumper/mydumper#1245]
**Describe the bug**
Myloader imports table from wrong database
I have imported myslq test database sakila into the server several time so I have
dakila
sakila2
sakila3
sakila4
made a backup with mydumper (version see below)

**To Reproduce**
Command executed:
* mydumper with all the parameters
* myloader with all the parameters

 myloader -d . -s "sakila" -B "sakila15" -t 2 -o -e -q 10000 -v 3

What mydumper and myloader version has been used? 
myloader -V
myloader v0.15.1-3, built against MySQL 8.0.33-25 with SSL support

**Expected behavior**

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
```
...
** Message: 13:43:54.213: Intermediate thread ended
** Message: 13:43:54.214: Intermediate thread: SHUTDOWN
** Message: 13:44:44.090: Thread 3: Table `sakila15`.`city` created. Tables 0 of 223 completed
** Message: 13:44:44.090: Thread 3: restoring table `sakila15`.`film_actor` from .../2023-08-04_1333/./**sakila2**.film_actor-schema.sql.gz
** Message: 13:44:44.090: Dropping table or view (if exists) `sakila15`.`film_actor`

** (myloader:1159905): CRITICAL **: 13:44:44.093: Drop table failed: Lock wait timeout exceeded; try restarting transaction

gzip: stdout: Broken pipe
```

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
have databases with names starting with the same string I assume, like a grep source_database is done and not grep -w or something like that.

**Environment (please complete the following information):**
 - OS version: ubuntu 22.04
 - MyDumper version:  v0.15.1-3, built against MySQL 8.0.33-25 with SSL support

**Additional context**
imported into a mariadb 10.11 but that should not be the problem, as myloader uses the wrong file

**Comment by hubiongithub** [comment]
Hello

a short way to reproduce;
`create datebase d;
use d;
create table t1 (c1 int);
insert into t1 values (1);
commit;
create datebase d1;
use d;
create table t11 (c1 int);
insert into t11 values (11);
commit;
create datebase d2;
use d;
create table t12 (c1 int);
insert into t12 values (12);
commit;
create datebase d3;
use d;
create table t13 (c1 int);
insert into t13 values (13);
commit;
create datebase d4;
use d4;
create table t14 (c1 int);
insert into t14 values (14);
commit;
mydumper to export the full mysql

myloader -d . -s "d" -B "d15" -t 1 -o -e -v 3
** Message: 14:21:16.143: Intermediate thread ended
** Message: 14:21:16.143: Schema creation enqueing completed
** Message: 14:21:16.143: Table creation enqueing completed
** Message: 14:21:16.143: S-Thread 5: Import completed
** Message: 14:21:16.144: S-Thread 3: Import completed
** Message: 14:21:16.144: S-Thread 4: Import completed
** Message: 14:21:16.143: Intermediate thread: SHUTDOWN
** Message: 14:21:16.144: S-Thread 2: Import completed
** Message: 14:21:16.147: Thread 1: Data import ended
** Message: 14:21:16.147: SHUTDOWN last_wait_control_job_to_shutdown
** Message: 14:21:16.147: Sending start_innodb_optimize_keys_all_tables
** Message: 14:21:16.148: Thread 11: Starting post import task over table
** Message: 14:21:16.148: Thread 12: Starting post import task over table
** Message: 14:21:16.148: Thread 12: restoring trigger on `d15` from d1-schema-triggers.sql.gz. Tables 0 of 245 completed
** Message: 14:21:16.148: Thread 11: restoring trigger on `d15` from d-schema-triggers.sql.gz. Tables 0 of 245 completed
** Message: 14:21:16.149: Thread 10: Starting post import task over table
** Message: 14:21:16.149: Thread 10: restoring trigger on `d15` from d2-schema-triggers.sql.gz. Tables 0 of 245 completed
** Message: 14:21:16.149: Thread 13: Starting post import task over table
** Message: 14:21:16.150: Thread 13: restoring trigger on `d15` from d3-schema-triggers.sql.gz. Tables 0 of 245 completed
** Message: 14:21:16.155: Thread 12: restoring trigger on `d15` from d4-schema-triggers.sql.gz. Tables 0 of 245 completed
** Message: 14:21:16.160: Errors found:
- Tablespace:   0
- Schema:       0
- Data:         0
- View:         0
- Sequence:     0
- Index:        0
- Trigger:      0
- Constraint:   0
- Post:         0
Retries:        0

MariaDB [(none)]> use d15;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [d15]> show tables;
+---------------+
| Tables_in_d15 |
+---------------+
| t1            |
| t11           |
| t12           |
| t13           |
| t14           |
+---------------+
5 rows in set (0.000 sec)
`

so it accumulated all data from d to d4 into d15, which is probably not what we want.

**Comment by hubiongithub** [comment]
Hello

I know it will be a bad idea to create databases like this, but the fix might have problems with:

create database `d.`;
Query OK, 1 row affected (0.002 sec)
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| d                  |
| d.                 |

**Comment by hubiongithub** [comment]
Hello

will `&& (filename[strlen(source_db)] == '.' || filename[strlen(source_db)] == '-') )` get it right if a database is created like in my last comment?

**Comment by hubiongithub** [comment]
Hello
Just for information, the version 0.10.1-1ubuntu1 from jammy/universe does not have this problem

`myloader -d . -s d -B d15 -t 2 -o -e -v 3
** Message: 11:04:49.750: 2 threads created
** Message: 11:04:49.751: Dropping table or view (if exists) `d15`.`t1`
** Message: 11:04:49.754: Creating table `d15`.`t1`
** Message: 11:04:49.755: Thread 1 restoring `d`.`t1` part 0
** Message: 11:04:49.755: Thread 2 shutting down
** Message: 11:04:49.756: Thread 1 shutting down
`
Do not know if 0.10.0 did not have the issue, or the maintainer of that package changed that...

**Comment by davidducos** [comment]
Hi @hubiongithub, can you check with Master? 

The ways that v0.10 processed the files is very different of what we are doing nowadays.
