### ISSUE TITLE
** (myloader:13161): WARNING **: 04:31:20.731: Set session failed: SET SESSION SQL_LOG_BIN = 0 [FEATURE REQUEST]

### ISSUE THREAD

**Issue by lvtujingji** [mydumper/mydumper#1248]
ENV：
  Source: Mysql 5.7.42
  destination: RDS for mysql 5.7.42
  Mydumper  v0.15.1-3
  EC2  Amazon linux2
Describe： 
   I am trying translate Source data to RDS use mydumper 
Action： 
   mydumper -h localhost -uroot -p *** -x '^(?!(mysql\.|information_schema\.|performance_schema\.|pro\.|sys\.))' -E -G -R -o backsql
   myloader -h ***.rds.amazonaws.com -u admin -p *** -e -d backsql
Issue：
   ** (myloader:13161): WARNING **: 04:31:20.731: Set session failed: SET SESSION SQL_LOG_BIN = 0 
       I don't know the meaning of this error report
      Have someone can help me ?

**Comment by davidducos** [comment]
You can set: `  -e, --enable-binlog                   Enable binary logging of the restore data`
to avoid that warning. that is because RDS doesn't allow you to test the SQL_LOG_BIN variable to avoid inconsistencies in the read replicas.
