### ISSUE TITLE
[BUG] metadata doesn't contain master status

### ISSUE THREAD

**Issue by pupeno** [mydumper/mydumper#1265]
**Describe the bug**
The metadata file on the dump only contains:

```
Started dump at: 2023-08-15 16:56:05
Finished dump at: 2023-08-15 17:11:28
```

**To Reproduce**

The command I'm running is:

```
  mydumper \
    --host="$MYSQL_ADDRESS" \
    --user="$MYSQL_USERNAME" \
    --password="$MYSQL_PASSWORD" \
    --database="$MYSQL_DATABASE" \
    --port=3306 \
    --outputdir="$dump_dir" \
    --threads="$(nproc)" \
    --no-locks \
    --long-query-retries=1 \
    --build-empty-files \
    --rows=100000
```

What mydumper and myloader version has been used?

mydumper_0.12.3-1-zstd.bullseye_amd64.deb

**Expected behavior**

A file looking something like:

```
Started dump at: 2011-05-05 13:57:17
SHOW MASTER STATUS:
Log: linuxjedi-laptop-bin.000001
Pos: 106

Finished dump at: 2011-05-05 13:57:17
```

**Environment (please complete the following information):**
 - OS version: latest debian:stable Docker image
 - MyDumper version: mydumper_0.12.3-1-zstd.bullseye_amd64.deb

**Comment by davidducos** [comment]
Hi @pupeno, can you test with a newer version?

**Comment by pupeno** [comment]
Yes, if there's a chance that might be the issue, more than happy to try.

**Comment by pupeno** [comment]
I installed mydumper_0.15.1-3.bullseye_amd64.deb and now metadata contains a lot of information:

```
# Started dump at: 2023-08-15 19:37:02

[`dbname`.`tablename`]
real_table_name=tablename
rows = 28080006

.
.
.
# Finished dump at: 2023-08-15 19:53:14
```

but still nothing about the master/replica/binlog state.

**Comment by davidducos** [comment]
Hi @pupeno , is binlog enable in the database? Can you execute "show master status"?

**Comment by pupeno** [comment]
I figured it out, sorry to bothered. The problem was that the user I was using to make the dump didn't have replication privileges. I wonder if it's worth outputting something so that that the dump of replication data is not ignored silently. But yeah, totally my fault here.
