### ISSUE TITLE
Please describe the intention of the `defaults-file`, including some real world examples

### ISSUE THREAD

**Issue by markuslf** [mydumper/mydumper#1269]
The `--defaults-file` is "starting to be more important in MyDumper".

But why? What can I control with this file, what is its benefit? Does it allow me to omit all parameter definitions for mydumper and myloader? What else can I control with this file, for example some MySQL/MariaDB behavior?

Would be nice to get some hints on this. :-)

**Comment by davidducos** [comment]
Hi @markuslf 

you can review this file: https://github.com/mydumper/mydumper/blob/master/mydumper.cnf which has the default content of the --defaults-file, which is finally copied to /etc/mydumper.cnf when the tool is installed. 
As you might see, the defaults, usually are:
```
SQL_MODE='NO_AUTO_VALUE_ON_ZERO' /*!40101
UNIQUE_CHECKS=0 /*!40114
FOREIGN_KEY_CHECKS=0 /*!40114
```
But you can configure depending on the brand and version.
On previous version, those SET SESSION commands were hardcoded. On future releases, we are going to add the recommended setting on that file. 
Take into account that MyDumper also allows you to configure your settings with `--defaults-extra-file`.

**Comment by markuslf** [comment]
Thank you for your explanation.
