### ISSUE TITLE
[BUG] Metadata file is not backward compatible

### ISSUE THREAD

**Issue by DeLoWaN** [mydumper/mydumper#1277]
**Describe the bug**
I have my backup dumps created with the version 0.10 (version available in debian repositories). When I upgraded to 0.15.1-3, I realized I cannot load the dump anymore (it works fine with 0.10). If it is expected, is there any method to workaround it ? I cannot upgrade mydumper if I can restore my old backups. Thanks

**To Reproduce**
Command executed:
```
mydumper --user XXX --password XXX --host localhost --triggers --routines --events --lock-all-tables --threads 1 --long-query-guard 900 --kill-long-queries --chunk-filesize 100 --outputdir /tmp/lol --database source
```
```
myloader --user XXX --password XXX --host localhost --database target --source-db source --threads 1 --overwrite-tables --verbose 3 --directory /tmp/lol
```

**Expected behavior**
Dump is imported

**Log**
```
** (myloader:3392240): WARNING **: 18:13:01.626: Failed to load config file /dump/metadata: Key file contains line “Started dump at: 2023-08-20 00:05:13” which is not a key-value pair, group, or comment

** (myloader:3392240): ERROR **: 18:13:01.626: Global metadata file processing was not possible
Trace/breakpoint trap
```

**Environment (please complete the following information):**
 - OS version: Debian 11
 - MyDumper version: 0.10 and 0.15.1-3

**Additional context**

**Comment by davidducos** [comment]
There is not backward compatibility cross major versions. 
https://github.com/mydumper/mydumper/discussions/1238
