### ISSUE TITLE
备份MySQL8.0 报错

### ISSUE THREAD

**Issue by yidoa** [mydumper/mydumper#1280]
2023-08-29 09:42:43 [ERROR] - Error dumping table (scsales_prd.T_HM_HOUSEDEL) data: You have an error in your SQL syntax; check the manual that corresponds to your MySQL s
erver version for the right syntax to use near ',SALE_REASON,STATE,DESCR,NO_DISTURB,UPDATE_BY,ACTIVE_TIME,GRP_ID,CREATE_BY,price' at line 1

**Comment by liq0221** [comment]
excuse me,how to solve the problem,except to modify the table fields?

> @yidoa Please provide `SHOW CREATE TABLE scsales_prd.T_HM_HOUSEDEL`. You may have a column which uses a MySQL 8 reserved keyword.

**Comment by davidducos** [comment]
Hi, if you share the SHOW CREATE TABLE, we are going to be able to detect which query is failing and fix the issue on mydumper, so you don't need to modify the table fields.

**Comment by liq0221** [comment]
> 您好，如果您分享 SHOW CREATE TABLE，我们将能够检测哪个查询失败并修复 mydumper 上的问题，因此您无需修改​​表字段。

CREATE TABLE `test` (
    `id` int NOT NULL AUTO_INCREMENT ,
    `create_time` datetime(0) NULL DEFAULT NULL ,
    `modify_time` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) ,
    `deleted_flag` tinyint NULL DEFAULT 0,
    `name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs NULL DEFAULT NULL,
    `match_location` int DEFAULT NULL,
    `match_rule` int DEFAULT NULL,
    `match_method` int NULL DEFAULT NULL,
    `parameter` mediumtext COLLATE utf8mb4_0900_as_cs,
    `destination` int NULL DEFAULT NULL,
    `initial` int NULL DEFAULT NULL,
    `order` int NULL DEFAULT NULL, 
    PRIMARY KEY (`id`) USING BTREE
)
this is my schema,because there are mysql keywords,so the backup will report an error,please help fix it.

**Comment by davidducos** [comment]
Hi @liq0221,
In order to help you I need more info:
- Are you using --complete-insert?
- What mydumper version are you using?

I was not able to reproduce your issue as the general log is showing that mydumper is enclosing the columns with backticks:
```
2023-10-24T12:19:19.714894Z       693 Query     SELECT /*!40001 SQL_NO_CACHE */ `create_time`,`deleted_flag`,`destination`,`id`,`initial`,`match_location`,`match_method`,`match_rule`,`modify_time`,`name`,`order`,`parameter` FROM `issue_1280`.`test`
```

**Comment by liq0221** [comment]
Hi @davidducos ,
i will try the latest version 
i have a problem, how does run the mydumper docker image in the backgroud

**Comment by davidducos** [comment]
Hi @liq0221 
I think that this: https://www.percona.com/blog/backup-and-restore-with-mydumper-on-docker/
will help you
