### ISSUE TITLE
[BUG] --hex-blob not working with --csv 

### ISSUE THREAD

**Issue by pengln** [mydumper/mydumper#1285]
**Describe the bug**
--hex-blob is woring with sql format. but not working with csv format.

**To Reproduce**
Command executed: 
mydumper -h 127.0.0.1 -C -B test --less-locking --skip-tz-utc -m -e --csv --hex-blob -o /tmp/1

What mydumper and myloader version has been used?
mydumper 0.15.2-4

**Comment by davidducos** [comment]
Hi @pengln,
I think that this is not a bug, as far as I remember, hex blob are not supported if you try to use LOAD DATA.

**Comment by pengln** [comment]
Thanks for your answer, mysqldump's --tab parameter can csv data everywhere and the --hex-blob parameter is valid, I wonder if mydumper is also a technical possibility.

**Comment by pengln** [comment]
I apologize for the speculation, I looked at your excellent source code. I found that the write_load_data_column_into_string function also passes fields. If you can pass MYSQL_TYPE_BLOB type, I guess there should be a way to implement hex-blob.

**Comment by davidducos** [comment]
Hi @pengln 
I did some research on this and it is ok that when you execute with --csv, the --hex-blob is ignored. However, what we need to take into account is to build the LOAD DATA with the appropriate function, which is UNHEX, similar of what we are doing with CONVERT when JSON type is used.
