### ISSUE TITLE
[QUESTION] How to apply different conditions for different tables

### ISSUE THREAD

**Issue by BinjaFan** [mydumper/mydumper#1288]
Hello,
first of all thanks for this tool.
is it possible to set different conditions (`--where`) for different tables?

I have multiple tables where each tables needs a different condition while dumping. Right now I'm doing those tables one by one and basically I'm not using that much of multi thread option of mydumper.

I see a config file but, but unfortunately there's no documents about it and how to use it. I searched in google and didn't find any example too.

Could You please give me an example of how to do it?

Let me give You an example of what I'm doing.

Lets say I have 3 tables in database *mydb* and I want to just dump parts of the data in those tables.

conditions would be like this:
table_a: column_z > 1234
table_b: column_x > 1234
table_c: column_y > 1234

thanks in advance

**Comment by davidducos** [comment]
Hello, 
Check `Per table sections:` on https://github.com/mydumper/mydumper#defaults-file. On file my_mydumper.cnf:
```
[`schema`.`table_b`]
where = column_x > 1234

[`schema`.`table_c`]
where = column_y > 1234

[`schema`.`table_a`]
where = column_z > 1234
```
You need to set the right schema.
then you execute: `mydumper --defaults-extra-config=my_mydumper.cnf`

**Comment by BinjaFan** [comment]
Thank You very much, I'll check this and let You know if everything works well.
