### ISSUE TITLE
[Question] Why field setted to 'text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin' is exported in hexadecimal ?

### ISSUE THREAD

**Issue by jbazin30** [mydumper/mydumper#1289]
Hello,

I didn't find this problem in another issues. So I ask you.

**Contexte :**
I just migrated from mysql 5.7 and mydumper 0.9.1 (conf_1) to mysql 8.0 and mydumper 0.15.1 (conf_2)

I have one table defined like this :

```
CREATE TABLE `configuration` (
  `configuration_id` mediumint unsigned NOT NULL AUTO_INCREMENT,
  `configuration_value` text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NOT NULL,
  PRIMARY KEY (`configuration_id`),
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;
```

_I don't know why the previous developer chose this "collate"._

When I dump with conf_1 the "configuration_value" field has exported without be converted in hexadecimal like this :

`INSERT INTO `configuration_keys` VALUES (1,"IsOpened");`

With conf_2 I have this :

`INSERT INTO `configuration_keys` VALUES (1,0x49734f70656e6564);`

In both case, I dump with no specific option (like --hex-blob) :

`mydumper -T car.configuration_keys -B carsseller -u myuser -p "mypassword" --host localhost`*

I only have this case for this `text CHARACTER SET utf8mb3 COLLATE utf8mb3_bin`.
For this one for example I have no conversion problem : `text CHARACTER SET ascii COLLATE ascii_bin`

The easy solution is to change the "collate" but I have a lot of fields in a lot of tables so I think another solution might be possible. And I need to have the values in plain text in my pull request.

Is this the expected behavior ? Or i missed an option ?

Thanks in advance.

**Comment by alereca** [comment]
We had the same issue using `mydumper 0.15.1-3` and `CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`

**Comment by davidducos** [comment]
Can you try with master? or latest prerelease as I think that I already fix this bug.
