### ISSUE TITLE
adding --skip-ddl-locks (flag) for mydumper

### ISSUE THREAD

**Issue by viswaprsnl** [mydumper/mydumper#1297]
**Describe the Feature Request**
No global DDL lock while running mydumper - (Export will fail , if DDL statements are executed while running DDL on the specific DB )

**Current behaviour**
if i run a parallel import of a different database (DB A) on the same mysql server while running a export on (DB B) . the import will hang until my export is complete

**Expected behavior**
Allowing  the user to specify --skip-ddl-locks while running exports 

**Environment**
Common to all envs 

**Additional context**
The below thread lead us to to create thr new feature 
https://github.com/mydumper/mydumper/discussions/1284#discussioncomment-6948246

**Comment by viswaprsnl** [comment]
@davidducos do you have any updates or info on this feature request .

**Comment by davidducos** [comment]
Hi @viswaprsnl,
Honestly, I think that this is not going to be deliver soon, I'm focus on release v0.16.1 and this is schedule for v0.16.3. If you feel confortable to write the code, I can let you know which file you need to modify, but you will need to write and test the code.

**Comment by viswaprsnl** [comment]
Hi @davidducos I can try this , can you please let me share all the details to get started .

**Comment by davidducos** [comment]
You will need to add the option in src/mydumper_arguments.c and the new global variable no_ddl_locks was created but never used in src/mydumper_start_dump.c where you will need to review function determine_ddl_lock_function.

**Comment by viswaprsnl** [comment]
@davidducos are you speaking something like the below code ? how about data consistency ? 

`// Assuming 'no_backup_locks' is a boolean variable that is true when the user wants to skip locks
if (!no_backup_locks) {
    if (mysql_query_verbose(conn, "FLUSH TABLES WITH READ LOCK")) {
        g_critical("Couldn't acquire global lock, snapshots will not be consistent: %s",
                   mysql_error(conn));
        errors++;
    }
}
`

**Comment by davidducos** [comment]
Hi @viswaprsnl,
No, I'm talking about the assignment to acquire_ddl_lock_function, as there are just 2 ways of get DDL locks.
The FTWRL is taken to get the data.
