### ISSUE TITLE
Review negative exit codes

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1301]
@davidducos Hey! Is there a list of Return/Exit Codes and what they mean?

I'm having the same problem, and I found this Discussion while trying to find a list of exit codes.

In my case, there was a warning due to deadlock, but it SEEMS that it was able to successfully retry the failed statement.

However, RC = -1, so my script saw this "myloader" run as Failed.

> ** (myloader:1): WARNING **: 09:39:50.978: Thread 17: Error restoring 1: Deadlock found when trying to get lock; try restarting transaction
> ** (myloader:1): WARNING **: 09:39:50.978: Thread 17: Retrying last failed executed statement
> ** Message: 09:39:50.999: Writing resume.partial file
> ** Message: 09:39:51.013: Errors found:
> \- Tablespace:   0
> \- Schema:       0
> \- Data:         0
> \- View:         0
> \- Sequence:     0
> \- Index:        0
> \- Trigger:      0
> \- Constraint:   0
> \- Post:         0
> Retries:        1

_Originally posted by @ghnp5 in https://github.com/mydumper/mydumper/discussions/1296#discussioncomment-7012775_

**Comment by davidducos** [comment]
https://github.com/mydumper/mydumper/issues/1301

**Comment by ghnp5** [comment]
Hi. What is the issue that this duplicates? So I can subscribe. Thank you.
