### ISSUE TITLE
myloader fails when creating a view if it references another view that doesn't exist yet

### ISSUE THREAD

**Issue by adoom42** [mydumper/mydumper#1306]
**Describe the bug**
myloader fails to create a view if it references a view that hasn't been created yet.

**To Reproduce**
`mydumper -G -E -R --regex '^(mydb\.|myotherdb\.)' -o /data/backup`
`myloader --innodb-optimize-keys AFTER_IMPORT_ALL_TABLES -d /data/backup`

Version 0.15.1-3

**Expected behavior**
Since views can select from tables or other views, myloader should create views in the proper order.  If that is too difficult, perhaps provide an option to dump and load views in a single-threaded instead of multi-threaded manner (while still loading table data with multiple threads since at least in my case that is the main reason to use these tools).

I've never experienced this scenario when using ordinary `mysqldump` / `mysql` commands to export & import.

**Log**
This log has been trimmed to remove sensitive data.
```
** (myloader:106514): WARNING **: 11:31:19.326: Thread 13: Retrying last failed executed statement

** (myloader:106514): CRITICAL **: 11:31:19.327: Thread 13: Error restoring: CREATE ALGORITHM=UNDEFINED DEFINER=`myuser`@`localhost` SQL SECURITY DEFINER VIEW `view2` AS select `table1`.`column1` from `table1` left join `view1` on `view1`.`id` = `table1`.`id`;
 Table 'mydb.view1' doesn't exist

** (myloader:106514): CRITICAL **: 11:31:19.327: Error occurs between lines: 10 and 10 on file mydb.view2-schema-view.sql: Table 'mydb.view1' doesn't exist
```
The important part to note is that this database has multiple views, and some of the views select from other views, so they must be created in order.  myloader is attempting to create "view2" which selects from "view1" before "view1" has been created, so it fails.

It may be a coincidence, but I never experienced this problem when using mydumper 0.10.1-2.  I recently upgraded to 0.15.1-3 and saw it happen for the first time today.

**Environment (please complete the following information):**
 - RHEL 7
 - MariaDB 10.4

**Comment by davidducos** [comment]
Hi @adoom42,

You might need to set `--max-threads-for-post-actions=1` to avoid this kind of issues.

**Comment by adoom42** [comment]
Using `--max-threads-for-post-actions=1` did the trick.

Please update the docs at https://github.com/mydumper/mydumper/blob/master/docs/myloader_usage.rst

There are multiple options missing from that documentation, including `--max-threads-for-post-actions`.
