### ISSUE TITLE
Why jemalloc?

### ISSUE THREAD

**Issue by midenok** [mydumper/mydumper#1315]
Why mydumper is built against jemalloc by default? Did you do some performance measurements?

According to [this answer](https://stackoverflow.com/a/33993215/3824341) there is no notable performance difference, but there is notable memory consumption by jemalloc.

**Comment by JohnKiller** [comment]
Also the `deb` package for Bullseye doesn't work:

    mydumper: error while loading shared libraries: libjemalloc.so.2: cannot open shared object file: No such file or directory
