### ISSUE TITLE
[BUG] regarding import of dumps created with --rows and --statement-size

### ISSUE THREAD

**Issue by IZSkiSurfer** [mydumper/mydumper#1319]
I'm not a 100% sure but at first glance it's my only explanation that there is a bug in mydumper/myloader or at least a possible enhancement:

I have two servers and use mydumper and myloader for cloning databases for development from one to the other.
I create the dumps as following:
mydumper -B "foo" --use-savepoints [...] -t "${MYDUMPER_THREADS}" -r 10000 -s "${TARGET_MAX_ALLOWED_PACKET}" -o "${DUMP_FOLDER}" -x "some regex"

I recently added the -s param to get rid of the warnings.
Our max_allowed_packet size is 67108864 on both systems.

But when I load the dump with myloader I get e.g. this:
`** (myloader:3658304): WARNING **: 09:48:44.988: Thread 10: Error restoring 1: Got a packet bigger than 'max_allowed_packet' bytes
** (myloader:3658304): CRITICAL **: 09:48:44.989: Thread 10: Lost connection error
** (myloader:3658304): CRITICAL **: 09:48:44.989: Error occurs between lines: 306412 and 586760 on file foo.useractions.00000.sql: 
** (myloader:3658304): CRITICAL **: 09:49:07.753: Thread 10: issue restoring foo.useractions.00000.sql: `

So my guess is because the dumps insert multiple rows per INSERT somehow the "statement-size" param isn't checked/used/processes correctly while dumping and a single INSERT containing up to "rows" (= 10000) rows might get bigger than the "max_allowed_packet" size.

Maybe someone familiar with the code/bahaviour could have a look into it?!

Thanks in advance.

**Comment by IZSkiSurfer** [comment]
Maybe that's the problem: [https://github.com/mydumper/mydumper/blob/2cdb23b99bd2574e5a7c7b4175228c32646d0e84/src/mydumper_write.c#L451](url)
`  GString *statement = g_string_sized_new(2*statement_size);`
Why is the double of the statement_size used?

**Comment by davidducos** [comment]
Hi @IZSkiSurfer are you getting warnings like this:
```
2023-10-24 11:56:23 [WARNING] - Row bigger than statement_size for sss.ttt
```
when you export the data? you can use `-v 3` and `-L log` to get those warnings.

**Comment by IZSkiSurfer** [comment]
I've got those messages before.
Then I added (as suggested) the -s option to the export (using the max_allowed_packet set in MariaDB) so the messages are gone but the import does not work.

**Comment by IZSkiSurfer** [comment]
Sry hit the wrong comment button ^^

**Comment by davidducos** [comment]
Are you using myloader with -r ??? if so, then remove it and try again.

**Comment by IZSkiSurfer** [comment]
> Are you using myloader with -r ??? if so, then remove it and try again.

No. I don't think I've used -r when loading (only while dumping).
But I'll try it as soon as I'll find time..

**Comment by davidducos** [comment]
@IZSkiSurfer, then it doesn't make sense, as -s will report if there are rows larger than the `${TARGET_MAX_ALLOWED_PACKET}` and without -r myloader will import the file as it is. 
This are the reproducible test case on a server with max_allowed_packet 67108864 and sbtest table with almost 2M rows total uncompressed dump is higher than 350MB.
Backup with statement size higher than the max_allowed_packet
```
rm -rf data; ./mydumper -o data -v 3 -T sbtest2.sbtest1 -s 77108865
```
The myloader that fails:
```
./myloader -d data/ -v 3 -B sbtest3 -o
```
The myloader that work:
```
./myloader -d data/ -v 3 -B sbtest3 -o -r 1000
```

**Comment by IZSkiSurfer** [comment]
You are using -r when LOADING whereas I'm using -r when DUMPING.

**Comment by davidducos** [comment]
Hi @IZSkiSurfer , the -r when dumping is only to split the jobs (SELECT), which is not related to the INSERT statement size.
We need a test case to understand where is the issue.
