### ISSUE TITLE
[BUG] max-threads-per-table-hard is not being honored 

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1336]
**Describe the bug**
max-threads-per-table-hard is not being honored 

**How to repeat**
Executing:
```
# myloader  --directory=data  --queries-per-transaction=50000 --threads=8 --compress-protocol --verbose=3 --max-threads-per-table-hard=1 --overwrite-tables -T schema.table
```
We found more than 1 data thread importing data
```
| 239 | migration       | XXX | schema | Query       |    67 | executing                                                     | LOAD DATA LOCAL INFILE 'schema.table.00000.00002.dat'     REPLACE INTO TABLE `table` CHARACTE |    66944 |         0 |             0 |
| 240 | migration       | XXX | schema | Query       |     9 | executing                                                     | LOAD DATA LOCAL INFILE 'schema.table.00000.00006.dat'     REPLACE INTO TABLE `table` CHARACTE |     9178 |         0 |             0 |
```
[This line](https://github.com/mydumper/mydumper/blob/d84aac451a07413802ccbebd286abe54f3d1062b/src/myloader_control_job.c#L203) needs to be reviewed

**Comment by midenok** [comment]
What is `--max-threads-per-table-hard` anyway? Looks like some hack to me.

**Comment by flybyray** [comment]
@davidducos i do not wnat to open a new bug. it is quite similar to other tickets which are duplicates to this.

i use the latest released version `v0.16.5-1`

when is use `mydumper` with the `--rows` parameter i get additional counters `*.00000.00001.sql*`  on some table files.
myloader would not honor the `max-threads-per-table=1` in that case and will load data from this additional counter files. 
Somehow there are situations where it will have a racecondition then.

v3 output:
```txt
** Message: 07:13:47.602: Thread 3: restoring example_open_data_demo.t_consent_use part 5 of 5 from demo-live_open_data.t_consent_use.00000.00077.sql.gz | Progress 46 of 47. Tables 38 of 41 completed
** Message: 07:14:08.070: Thread 1: restoring example_open_data_demo.t_consent_use part 4 of 5 from demo-live_open_data.t_consent_use.00000.00079.sql.gz | Progress 47 of 47. Tables 38 of 41 completed
** Message: 07:14:18.070: Thread 3: Data import ended
** Message: 07:14:50.558: Thread 1: Data import ended
** Message: 07:14:50.558: Thread 0: Enqueuing index for table: example_open_data_demo.t_consent_use
** Message: 07:14:50.558: restoring index: demo-live_open_data.t_consent_use
** Message: 07:14:50.558: Thread 6: restoring indexes example_open_data_demo.t_consent_use from index. Tables 38 of 41 completed

** (myloader:3957780): WARNING **: 07:15:00.124: COMMIT failed - ERROR 1213: Deadlock found when trying to get lock; try restarting transaction

** (myloader:3957780): CRITICAL **: 07:15:00.124: Connection 2023: Error committing data: Deadlock found when trying to get lock; try restarting transaction

gzip: stdout: Broken pipe
Trace/breakpoint trap (core dumped)

gzip: stdout: Broken pipe
```

`SHOW PROCESSLIST`
```txt
2022    root    localhost       example_open_data_demo    Query   10      altering table  ALTER TABLE `t_consent_use` \n ADD  KEY `consent_use_fk1` (`consent_fk`),\n ADD  KEY `consent_use_fk2`  9778    0       0
2023    root    localhost       example_open_data_demo    Sleep   10              NULL    9779    0       0
```

mysql error log
```txt
2024-08-13T05:14:50.561792Z 2022 [Note] [MY-000000] [WSREP] cluster conflict due to high priority abort for threads:

2024-08-13T05:14:50.561804Z 2022 [Note] [MY-000000] [WSREP] Winning thread:
   THD: 2022, mode: toi, state: exec, conflict: aborted, seqno: 13803068
   SQL: ALTER TABLE `t_consent_use`
 ADD  KEY `consent_use_fk1` (`consent_fk`),
 ADD  KEY `consent_use_fk2` (`pulled_account_fk`)
                                                                                                                                                                                                                                                                                                                            2024-08-13T05:14:50.561815Z 2022 [Note] [MY-000000] [WSREP] Victim thread:
   THD: 2023, mode: local, state: exec, conflict: certifying, seqno: -1
   SQL: COMMIT
                                                                                                                                                                                                                                                                                                                            2024-08-13T05:14:50.561835Z 2022 [Note] [MY-000000] [WSREP] MDL conflict db=example_open_data_demo table=t_consent_use ticket=4 solved by abort
```

**Comment by davidducos** [comment]
Hi @flybyray 
Just to be clear, the --max-threads-per-table option is only for loader threads. We should clarify that.
On the other hand if you see deadlocks for indexes creation, you might need to set --max-threads-for-index-creation=1, as the issue might be related to [atomic ddl](https://dev.mysql.com/doc/refman/8.0/en/atomic-ddl.html) if you are using MySQL version 8.0 or above. BTW, are you using --serialized-table-creation ??

**Comment by davidducos** [comment]
Hi @flybyray, as your server seems to be a galera cluster, are you connecting to a single node? or are you connecting to a ProxySQL or HAProxy that is sending the traffic to multiple nodes? 
BTW, do you have the other query that cause the deadlock?

**Comment by davidducos** [comment]
@flybyray can you test with -q 1 to confirm what I suspect is a bug?

**Comment by flybyray** [comment]
> Hi @flybyray, as your server seems to be a galera cluster, are you connecting to a single node? or are you connecting to a ProxySQL or HAProxy that is sending the traffic to multiple nodes? BTW, do you have the other query that cause the deadlock?

no i connect directly to the socket of one node of scaled down 2 node pxc cluster (normally 3 nodes, wanted to join after successfull import)

i have a terminal session logged. can provide some insight. will sent via mail.

**Comment by flybyray** [comment]
> @flybyray can you test with -q 1 to confirm what I suspect is a bug? I think that we are not committing before releasing the connection. I will create a PR but if you can confirm, it will be helpful.

testing ...  still running.  the same process which failed and i sent before via mail

**Comment by flybyray** [comment]
> @flybyray can you test with -q 1 to confirm what I suspect is a bug? I think that we are not committing before releasing the connection. I will create a PR but if you can confirm, it will be helpful.

```shell
myloader --threads 2 --defaults-file ~some-user/.my.cnf   $(my_print_defaults -c ~some-user/.my.cnf -s client mysql)   --max-threads-per-table 1   --max-threads-for-index-creation 1   --database some-user_open_data  --source-db some-user_open_data   --serialized-table-creation --innodb-optimize-keys   --overwrite-tables   --directory /var/tmp/mydumper.uLfOpX   --verbose 3 -q 1
```

you see this `-q 1`

actually this worked:
```txt
** Message: 19:13:00.625: Errors found:
- Tablespace:   0
- Schema:       0
- Data:         0
- View:         0
- Sequence:     0
- Index:        0
- Trigger:      0
- Constraint:   0
- Post:         0
Retries:        0
```

**Comment by davidducos** [comment]
Hi @flybyray, 
The PR with the fix is already linked to this issue. I will be merging and publishing a prerelease.

**Comment by flybyray** [comment]
Hey 👋 maybe provide some info. The ‚hard‘-stuff is unavailable from help 😁 anymore
