### ISSUE TITLE
[ENHANCEMENT] Add support for packages in oracle mode

### ISSUE THREAD

**Issue by midenok** [mydumper/mydumper#1340]
### Reproduce
```sql
CREATE DATABASE test1;
USE test1;
SET @save*sql_mode=@@sql*mode;
SET sql_mode=ORACLE;

DELIMITER $$;
CREATE OR REPLACE PACKAGE pkg AS
END;
$$

DELIMITER ;$$

--let $databases= test1
--source include/mydumper_dump.inc
--source include/myloader_restore.inc
SHOW CREATE PACKAGE test1.pkg;

DROP DATABASE test1;
SET sql*mode=@save_sql*mode;
```

### Result
There is no package in dump.
```
mysqltest: At line 1634: query 'SHOW CREATE PACKAGE test1.pkg' failed: ER*SP_DOES_NOT*EXIST (1305): PACKAGE pkg does not exist
```

### Cause
mydumper doesn't dump packages. myloader does not restore `sql_mode=ORACLE`.

### Fix
If mydumper sees `ORACLE` token in `sql_mode` it saves this mode into dump, myloader restores exact mode.'* Mydumper also must dump packages themselves.

'* This is similar to PR #1339, configuration doesn't help here as it requires manual editing before restoration of different modes.

**Comment by midenok** [comment]
This also applicable to SQL_MODE=ANSI or ANSI_QUOTES. The dump should contain correct SQL_MODE used. Otherwise there can be inconsistency in settings between myloader/mydumper.

**Comment by davidducos** [comment]
Ok, so what we need to do:
On mydumper we are going to be adding `[myloader_session_variables]` to metadata file.
On myloader we need to load `[myloader_session_variables]` from the metadata file. We must load metadata at first when we read from directory and on stream, mydumper must send `[myloader_session_variables]` in the first metadata.partial that must be the first file streamed, which also means that set_session might be executed again if `[myloader_session_variables]` is found.
