### ISSUE TITLE
[FEATURE REQUEST] ARM linux compilation method

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#1343]
Is there any source code compilation method for ARM architecture?

**Comment by davidducos** [comment]
We are compiling for ARM architecture on the platforms that are available.

**Comment by peng19832** [comment]
> We are compiling for ARM architecture on the platforms that are available.

Oh, sorry, I didn’t describe it correctly. I compiled it on the centos 7 arm platform.

**Comment by peng19832** [comment]
@davidducos 
Hi, boss, can you post the compilation and installation method on the arm centos7 platform? I have actual needs here, but I am not using centos8 for the time being.

**Comment by davidducos** [comment]
Hi @peng19832 I need to finish and merge https://github.com/mydumper/mydumper/pull/1347 before test centos7 all over again... I think that I excluded for some reason that I don't remember right now. We might need to review the Github Actions to see if there is errors there.

**Comment by davidducos** [comment]
@peng19832, now I remembered why we were not doing centos7 for ARM. It is related to gcc 12 not being available on el7.
It is the time to upgrade my friend.
