### ISSUE TITLE
[BUG] Split tables with rows doesn't work in 0.15

### ISSUE THREAD

**Issue by duderuud** [mydumper/mydumper#1344]
(Pretty news to this so sorry in advance if something important is missing)

**Describe the bug**
Previously I used version 0.12 that broke down large tables in chunks without any issues. Now I'm running 0.15 (tried both 0.15.1-3 and 0.15.2-6 and large tables are just one big file, no chunks.

**To Reproduce**
Command executed:
mydumper \
  --database=$DB_NAME \
  --host=$DB_HOST \
  --user=$DB_USER \
  --password=$DB_PASS \
  --outputdir=$DB_DUMP \
  --rows=5000000 \
  --trx-consistency-only \
  --triggers \
  --routines \
  --compress \
  --build-empty-files \
  --threads=8 \
  --compress-protocol

myloader \
--directory=/backup_db \
--user=root \
--password='xxx' \
--compress-protocol \
--verbose=3

**Expected behavior**
Just like the old 0.12 version:
database.table.00000.sql.gz
database.table.00001.sql.gz
database.table.00002.sql.gz
etc...

Now it's just one big database.table.00000.sql.gz file.

**Log**
Noting weird to see in log

**Environment (please complete the following information):**
 - OS version: AlmaLinux 8 and 9
 - MyDumper version: 0.15.2-6

**Comment by davidducos** [comment]
Hi @duderuud 
That is because the value on --rows, as it has change how it is being used. I recommend you to use this:
`--rows=10000:100000:0`

**Comment by duderuud** [comment]
Ah, thanks for the heads up! Testing it out but still only one file.
The table had about 31 mln rows and compressed the .gz is 4GB.

What settings do I need to use to divide the table in about 10 different parts?

**Comment by davidducos** [comment]
Take into account that we start splitting the table with 1 thread, and then it could use more threads per table. If you want to split the file anyways, you should use also -F and the file size that you want.

**Comment by duderuud** [comment]
After a bit of tweaking the backup and restore process is more than twice as fast. Thanks!
