### ISSUE TITLE
Add --compact and set the right default and add [myloader_session_variables] to metadatafile

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1346]
Hi @midenok,
I don't want to give you the wrong impression with all my questionings. I have just realized that what we are discussing, has been already fixed on mysqldump with the option `--compact`. As it is implemented right now, --compact is the default and what you are proposing is to implement the non --compact option and set it as default. 

Does it make sense?

_Originally posted by @davidducos in https://github.com/mydumper/mydumper/issues/1339#issuecomment-1799765945_

**Comment by midenok** [comment]
@davidducos `--compact` is not default in `mysqldump` (at least in MariaDB 10.4.32)

I dumped without compact [1.sql](https://gist.github.com/midenok/92b7578fcd623845938acadc3f0ae98d#file-1-sql), with compact [2.sql](https://gist.github.com/midenok/92b7578fcd623845938acadc3f0ae98d#file-2-sql) and made diff [1-2.sql](https://gist.github.com/midenok/92b7578fcd623845938acadc3f0ae98d#file-1-2-diff)

Man page says:

```
Produce more compact output. This option enables the --skip-add-drop-table, --skip-add-locks, --skip-comments, --skip-disable-keys, and --skip-set-charset options.
```

So this is specific to mysqldump. From the output you may see this is really saves much space. I think skipping (or not skipping) just several session vars does not make much difference on dump size, so no reason for this option in mydumper.

**Comment by davidducos** [comment]
@midenok 
--compact will not be the default on new releases. 

MyDumper doesn't implement feature in the same way that are implemented in mysqldump. However, we like to take some ideas from it and I like to allow users to make changes on how they want to import the data, as migrations to other db vendors may need to change configuration.

**Comment by midenok** [comment]
@davidducos I doubt `--compact` is good feature in terabyte world. When it was made in mysqldump I guess HDD was less than 1Gb. I remember the times when I cleaned up every needless KB from 180Mb HDD drive. Now I never do such things!
