### ISSUE TITLE
[FEATURE REQUEST] add support for data type conversion

### ISSUE THREAD

**Issue by trikker** [mydumper/mydumper#1349]
**Describe the Feature Request**
For example, some DB doesn't support blob data type and I need to use text data type instead. I need to rewrite the dump SQL to not use something like 0x2D2D2042792059 dumped from a blob column because text data type cannot accept this kind of data.  I need to use "convert(blob_col using utf8)" to convert the blob column to a varchar or string type.

**Current behaviour**
I haven't found mydumper can do data type conversion.

**Expected behavior**
The blob type can be converted to varchar or text.

**Environment**
Nothing to do with environment.

**Additional context**
Maybe we can add a config file for a column in a table, it gives the hint to convert a column from one type to another.

**Comment by davidducos** [comment]
Hi @trikker,
https://github.com/mydumper/mydumper/pull/1158 does what you want. Please, check the example.

**Comment by trikker** [comment]
Thanks, good solution. This solves my problem.
