### ISSUE TITLE
[BUG] Mydumper/myloader "lock wait time out exceeded error" during restore

### ISSUE THREAD

**Issue by midenok** [mydumper/mydumper#1350]
Version:  mydumper-0.15.1-3.el8.x86_64.rpm

### Description
Restore of InnoDB with myloader threads more than 10 threads is hitting "Lock wait timeout exceeded; try restarting transaction" and loading job fails.

### Cause?
Multiple threads try to insert into same table? Is it possible with myloader?

### Sidefix
Like error message says, it should try to restart transaction instead of failing.

References: [MDEV-32735 Mydumper/myloader "lock wait time out exceeded error" during restore](https://jira.mariadb.org/browse/MDEV-32735)

**Comment by midenok** [comment]
@davidducos Is it possible for myloader to queue inserts into one table into multiple workers?

**Comment by davidducos** [comment]
myloader can queue files with inserts of a table which then are processed by workers.

**Comment by midenok** [comment]
@davidducos From your answer I cannot understand yes or no...

**Comment by davidducos** [comment]
yes
