### ISSUE TITLE
[BUG] order-by-primary - mariaDB 10.5.3

### ISSUE THREAD

**Issue by salesgroup** [mydumper/mydumper#1352]
I tried to use mydumper with "order-by-primary" option but i had always the same error, in all the tables:
[ERROR] - Error dumping table (database.table_name) data: Unknown column '(null)' in 'order clause'

Even with the internal "mysql" database i get the same error!!

After some analysis, i've discovered the SQL statement used by mydumper:
https://github.com/mydumper/mydumper/blob/master/src/mydumper_working_thread.c#L1103

```sql
SELECT k.COLUMN_NAME, ORDINAL_POSITION
FROM information_schema.table_constraints t
LEFT JOIN information_schema.key_column_usage k
USING(constraint_name,table_schema,table_name)
WHERE t.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
AND t.table_schema='database_xxx'
AND t.table_name='table_name_xxx'
ORDER BY t.constraint_type, ORDINAL_POSITION
```

Trying this query directly in mariaDB, and i always get columns with "null" values.

I replaced the USING clause by ON and it WORKED! :

```sql
SELECT k.COLUMN_NAME, ORDINAL_POSITION
FROM information_schema.table_constraints t
LEFT JOIN information_schema.key_column_usage k
ON ( t.constraint_name = k.constraint_name
AND t.table_schema=k.table_schema
AND t.table_name=k.table_name)
WHERE t.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
AND t.table_schema='database_xxx'
AND t.table_name='table_name_xxx'
ORDER BY t.constraint_type, ORDINAL_POSITION
```

Tried the same 2 queries in mysql 8 and both worked.
It seems a mariaDB 10.5 bug?
Maybe the join with "ON" in more compatible.
Can you made this change?

**Comment by davidducos** [comment]
Hi @salesgroup ,
From what you are describing, it seems to be a bug on MariaDB. 

@midenok, can you confirm?

@salesgroup you can create a branch and send the PR, as you did all the work here.

**Comment by midenok** [comment]
I checked on 10.4.32, both queries work. 10.5.3 is 20 releases behind latest 10.5! Looks it is not even GA. Why would you post bugs about it?
