### ISSUE TITLE
myloader not working when restore on master/slave replication

### ISSUE THREAD

**Issue by iovcho** [mydumper/mydumper#1353]
Hello I have two MySQL clusters master/slave replication:

ClusterA-Master -> ClusterA-Slave
ClusterB-Master -> ClusterB-Slave

I use mydumper on ClusterA-Slave and make backup with follow parameters:

``mydumper -c -t 128 --rows 0 --exec-threads 0 -h localhost -u root -a -B mydatabase --less-locking -o mydatabase
``
On ClusterB-Master I try to restore the database with following parameters:

`myloader -B mydatabase --innodb-optimize-keys AFTER_IMPORT_ALL_TABLES --max-threads-per-table 32 --max-threads-for-index-creation 32 --max-threads-for-schema-creation 32 --rows 0 --queries-per-transaction 2000000000 --threads 96 -d mydatabase`

The process finished without any errors, but If check on slave -> show databases -> the restored database is missing.
Another test:
I try to create the database manualy on ClusterB-Master, and after that I run myloader for restore the database, again finished is without any errors, the database exist (because I created it manualy) but is empty (no tables and data).

The version of the MySQL is:
ClusterA-Master: Percona-Server-shared-57-5.7.38-41.1.el7.x86_64
ClusterA-Slave: Percona-Server-shared-57-5.7.38-41.1.el7.x86_64
ClusterB-Master: Percona-Server-server-57-5.7.43-47.1.el7.x86_64
ClusterB-Slave: Percona-Server-server-57-5.7.43-47.1.el7.x86_64

Can you help about this case?
Thank you very much for this amazing tool!

**Comment by davidducos** [comment]
Hi @iovcho 

What mydumper and myloader version has been used?

**Log**
add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.

**Backup**
Add the list of content of the database path, an `ls -l` will be enough


Change `--rows 0` to `--rows 1000:10000:0`
Remove: --exec-threads 0

**Comment by iovcho** [comment]
Hello, on all servers the version of mydumper/myloader is the same:
mydumper v0.15.1-3, built against MySQL 5.7.42-46 with SSL support
Here are commands executed by me with changed settings from your previous post.
```
mydumper -v 3 -L mydumper.log -c -t 128 --rows 1000:10000:0 -h localhost -u root -a -B mydatabase --less-locking -o mydatabase
myloader -B mydatabase -v 3 -L myloader.txt --innodb-optimize-keys AFTER_IMPORT_ALL_TABLES --max-threads-per-table 32 --max-threads-for-index-creation 32 --max-threads-for-schema-creation 32 --rows 0 --queries-per-transaction 2000000000 --threads 96 -d mydatabase
```


Logfiles myloader.log and mydumper.log are sent via email, because there have confedencial information about databases. The content of backup directory also sent via email. Thank you for your help and great tool who you maintenance.

**Comment by davidducos** [comment]
Hi @iovcho !!! 
AAAHHHHH I reread the issue that you have and I realized of the problem, you are not using this option:
```
  -e, --enable-binlog                   Enable binary logging of the restore data
```
by default we are not saving in the binary logs the statements executed.

**Comment by morsik** [comment]
@davidducos I would still consider this as a bug... there is no explanation whatsoever why this weird behavior is default.

myloader source code forces to disable binlog: https://github.com/mydumper/mydumper/blob/f85bc816b855c0dbcc3919171afecf3617e738cd/src/myloader/myloader.c#L104

while default setting in mysql is enabled: https://dev.mysql.com/doc/refman/8.4/en/set-sql-log-bin.html

For me, it should be exactly the same default behavior so we can expect default behavior because it's... default one. Hence, this is still a bug. Or please explain in `--help` and other places why exactly this is opposite behavior to default :/

**Comment by davidducos** [comment]
Hi @morsik,

uufff, bug is a strong word. This is not a bug, it is a decision made many many years ago. I didn't take it, but I understand the use cases that makes sense to have it.
Honestly, I don't like it either, as I think that this is a something that could be added to the `--defaults-file` with other variables. Actually, I'm going to create a ticket to review that.

**Comment by svaroqui** [comment]
I'm sorry this not a bug , but it's a bug to deprecate this feature , now we will get issue when restoring a slave  having errant transactions on slave binary logs and failing with sql strict mode  , i don't understand why just not use  the enable-binlog =TRUE to fixe this user issue

**Comment by davidducos** [comment]
Hi @svaroqui , thank you to agree with me. The option has been removed but the use case was not, it has been migrated to https://github.com/mydumper/mydumper/blob/93505fadfba38a24fd864e18596c90afe563e8cb/mydumper.cnf#L32

**Comment by svaroqui** [comment]
Thanks David, i can clearly spot the config base design elegance, loosing parameters still will break many tools and scripting around the user  community. Could parameter overwrite the config file content like in many tools ?

**Comment by morsik** [comment]
@svaroqui this still should have same defaults as mysql defaults, and give user possibility to disable it (for your usecase). Not other way around to enable to me, because - again - enabled is default setting in MySQL so one can expect it should be the same ;)
