### ISSUE TITLE
[BUG] TEXT field dumped as hex, without --hex-blob option

### ISSUE THREAD

**Issue by tanji** [mydumper/mydumper#1354]
**Describe the bug**
LONGTEXT field gets dumped as hex instead of plain text

**To Reproduce**
Command executed:
* mydumper with all the parameters
`mydumper -v 3 --exec-per-thread="/usr/bin/zstd -c" --exec-per-thread-extension=".zst" --build-empty-files --less-locking --trx-consistency-only --outputdir ${BACKUPDIR}${BACKUPNAME} ${LOGGING}`

What mydumper and myloader version has been used?
0.15.1

**Expected behavior**
Without hex blob option the filed should be dumped as text

**How to repeat**
table schema:
```
Create Table: CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `s` int(255) NOT NULL,
  `m` varchar(255) NOT NULL,
  `f` varchar(255) NOT NULL,
  `c` varchar(255) DEFAULT '',
  `o` int(10) unsigned NOT NULL,
  `e` int(11) NOT NULL,
  `c_id` int(11) unsigned NOT NULL,
  `sc_id` int(11) NOT NULL,
  `par` longtext DEFAULT NULL,
  `pau` tinyint(1) NOT NULL,
  `ds` datetime DEFAULT NULL,
  `de` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
)
```

In the example, the `par` field gets dumped as hex

**Environment (please complete the following information):**
 - Debian 11, MariaDB 10.5
mydumper v0.15.1-1, built against MySQL 8.0.33-25 with SSL support

**Comment by midenok** [comment]
Fixed in d681aeb
