### ISSUE TITLE
Mydumper crashes on Ubuntu

### ISSUE THREAD

**Issue by npasupathi** [mydumper/mydumper#1356]
Mydumper randomly crashes Ubuntu 20.04 and Ubuntu 22.04 LTS. Backup files seem to be intact but Ubuntu has to be restarted.

Command executed:
mydumper --host=127.0.0.1 --user=xxx --password=XXXXXX --regex=(bankstates_2011\\.|bankstates_2012\\.|bankstates_2013\\.|bankstates_2014\\.|bankstates_2015\\.|bankstates_2016\\.|bankstates_2017\\.|bankstates_2018\\.|bankstates_2019\\.|bankstates_2020\\.|bankstates_2021\\.|bankstates_2022\\.|bankstates_2023\\.|clinicsys_2011\\.|clinicsys_2012\\.|clinicsys_2013\\.|clinicsys_2014\\.|clinicsys_2015\\.|clinicsys_2016\\.|clinicsys_2017\\.|clinicsys_2018\\.|clinicsys_2019\\.|clinicsys_2020\\.|clinicsys_2021\\.|clinicsys_2022\\.|clinicsys_2023\\.|campaigns\\.|chat\\.|edited_data\\.|edited_data_arc\\.|quest\\.|universaldb\\.) --set-names=utf8mb4 --triggers --less-locking --outputdir=/var/www/html/clinicsysmini/backup/autobackup10/sql/mydumper/ --rows=100000 --compress --build-empty-files --threads=3 --compress-protocol --trx-consistency-only -L /var/www/html/backup/sql/mydumper-logs.txt

What mydumper and myloader version has been used?
mydumper v0.15.1-3, built against MySQL 8.0.33-25 with SSL support

Log output:
2023-11-22 10:01:28 [WARNING] - Using trx_consistency_only, binlog coordinates will not be accurate if you are writing to non transactional tables.

This log output seems normal as it appears in normal backups that were performed without crash.

Attached is Ubuntu crash log from /var/crash and the crash screenshot.

[_usr_bin_mydumper.33 copy 2.txt](https://github.com/mydumper/mydumper/files/13445298/_usr_bin_mydumper.33.copy.2.txt)

![PHOTO-2023-11-22-10-29-52](https://github.com/mydumper/mydumper/assets/151797940/adb84735-8495-47a9-b500-9c7a3d3c4dc2)

**Comment by midenok** [comment]
There was many crash fixes since v0.15.1-3. Please post bugs against latest master revision. Please, don't supply core dumps in binary format unless requested. Thanks!
