### ISSUE TITLE
How to load table dump in order?

### ISSUE THREAD

**Issue by peterdk** [mydumper/mydumper#1364]
I have a mydumper backup of a table with 70.billion rows. It is split per billion. So I have file 0000 - 0070.sql.zst

Since I use Rocksdb engine in Mariadb, the most optimal bulk load is in primary key order. The dump is just that. However, when loading with single thread, the order of files used seems random. It's 0000 then 0064 then other random one. Myloader has no option as far as I can find to just do it in order of input files numbering.

How can I import my data sequential?

**Comment by peterdk** [comment]
Using latest 0.15.2-6 for myloader.

**Comment by davidducos** [comment]
Hi @peterdk, 
When you import the data, is always in the same "random" order? Are you using mydumper to get the data? take into account that mydumper has 2 levels of order, if you want secuencial order, you should use 0000.0000 - 0000.0070.sql.zst

Regards

**Comment by davidducos** [comment]
Hi @peterdk, I made some modification on the latest prerelease that might change the behavior of your backup. Can you test again? I'm closing as there is no feedback for more than a month.

**Comment by peterdk** [comment]
Hi David, thanks. I'll try to test this weekend to see if it works as expected.
