### ISSUE TITLE
[BUG] When I try to export a table with json fields using mydumper, an error occurs with the myloader command.

### ISSUE THREAD

**Issue by SteinsHead** [mydumper/mydumper#1365]
**Describe the bug**

I created a table with json fields for testing, and when I tried to use the myloader command, it gave me an error. This problem can be reproduced stably. The following describes how to reproduce the problem, the error content, and the version I use.

**To Reproduce**

Table creation and data insertion statements:

1. create table
```
CREATE TABLE `tb123` (
  `id` int(11) DEFAULT NULL,
  `name` text,
  `name_1` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin GENERATED ALWAYS AS (json_unquote(json_extract(`name`,'$.key1'))) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
2. generate data
insert into tb123 (id, name)value(1, '{"key1":1}');

Command executed:
* mydumper with all the parameters
    * mydumper --user root --password <password> --socket <socket_file> --build-empty-files --threads 1 --logfile test.log --verbose 3 --no-locks --database <database> --tables-list <table> --outputdir json_dir
* myloader with all the parameters
    * myloader --directore ./ --user root --password <password> --socket <socket_file> --threads 1 --verbose 3 --ask-password -o --enable-binlog

What mydumper and myloader version has been used?

0.14.5-2

**Expected behavior**

I think under normal circumstances, the whole process will not report errors.

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
```
myloader --directore ./ --user root --password <password> --socket <socket_file> --threads 1 --verbose 3 --ask-password -o --enable-binlog
** Message: Server version reported as: 5.7.43-231000-log
** Message: Initializing initialize worker schema
** Message: S-Thread 3: Starting importe
** Message: Intermediate queue: Sending END job
** Message: Thread 3: restoring create database on 'sbtest' from sbtest-schema-create.sql. Tables 0 of 1 completed
** Message: S-Thread 1: Starting import
** Message: Filename to open: /home/Ruby/json_dir/./sbtest-schema-create.sql
** Message: S-Thread 2: Starting import
** Message: S-Thread 4: Starting import
** Message: Intermediate thread ended
** Message: Schema creation enqueing completeda
** Message: Table creation enqueing completedee
** Message: S-Thread 2: Import completed
** Message: Intermediate thread: SHUTDOWN
** Message: S-Thread 4: Import completed
** Message: S-Thread 3: Import completed
** Message: Thread 1: restoring table sbtest.tb123 from /home/Ruby/json_dir/./sbtest.tb123-schema.sql
** Message: Dropping table or view (if exists) sbtest . th123
** Message: Thread 1: Creating table sbtest.th123 from content in /home/Ruby/json_dir/./sbtest.tb123-schema.sql.
** Message: Thread 1: Table sbtest.tb123 created. Tables O of 1 completed
** Message: S-Thread 1: Import completed
** Message: Thread 1: restoring sbtest.tb123 part 1 of 1 from sbtest.tb123.00000.sql. Progress 1 of 1. Tables 0 of 1 completed
** Message: Filename to open: /home/Ruby/json dir/./sbtest.tb123.00000.sql
** (myloader:22508): WARNING **: Thread 1: Error restoring 1: Cannot create a JSON value from a string with CHARACTER SET 'binary'.
** (myloader:22508): WARNING **: Thread 1: Retrying last failed executed statement
** (myloader:22508): CRITICAL **: Thread 1: Error restoring: Cannot create a JSON value from a string with CHARACTER SET 'binary'.
** (myloader:22508): CRITICAL **: Error occurs between lines: 4 and 5 on file sbtest.tb123.00000.sql: Cannot create a JSON value from a string with CHARACTER SET 'binary'
** (myloader:22508): CRITICAL **: Thread 1: issue restoring sbtest.tb123.00000.sql:
** Message: Thread 1: Data import ended
** Message: Thread 1: Starting post import task over table
** Message: Starting table checksum verification
Error in my_thread_global_end(): 8 threads didn't exit
** Message: Errors found:
- Tablespace:	0
- Schema:	0
- Data:		1
- View:		0
-  Sequence:	0
-  Index:	0
-  Trigger:	0
-  Constraint:	0
-  Post:		0
Retries:	1
```

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
Or upload a [core dump](https://github.com/mydumper/mydumper/wiki/Support#core-dump) for cases where mydumper or myloader is crashing.

It has been mentioned in the above description.

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
 - EulerOS 2.5
 - MyDumper version: [ mydumper --version ]
 - 0.14.5-2

**Additional context**

**Comment by davidducos** [comment]
Hi @SteinsHead, can you test with latest prerelease?
