### ISSUE TITLE
[BUG] ERROR **: 15:07:34.636: Disabling redologs is not supported for version 11.2.2

### ISSUE THREAD

**Issue by sla-te** [mydumper/mydumper#1366]
**Describe the bug**

**To Reproduce**
Command executed:
`myloader -h 127.0.0.1 -u root -p root -d ./export-20231211-144828 -B mydb -o --innodb-optimize-keys --disable-redo-logs`

What mydumper and myloader version has been used?
mydumper v0.15.2-6, built against MariaDB 11.2.2 with SSL support
myloader v0.15.2-6, built against MariaDB 11.2.2 with SSL support

**How to repeat**
Pull mariadb docker latest and import a mydumper backup

**Environment (please complete the following information):**
 - OS version: Linux 6.6.5-arch1-1 x86_64
 - MyDumper version: mydumper v0.15.2-6, built against MariaDB 11.2.2 with SSL support

**Comment by davidducos** [comment]
I don't know what is the issue here, afaik, MariaDB doesn't support [--disable-redo-logs](https://dev.mysql.com/doc/refman/8.0/en/innodb-redo-log.html#innodb-disable-redo-logging)
