### ISSUE TITLE
How should I use compilation scripts?

### ISSUE THREAD

**Issue by SteinsHead** [mydumper/mydumper#1367]
When I tried to use the build.sh script in the packege directory for compilation, the following error message was displayed:

+ cd mydumper-0.15.1
+ install -m 0755 -d /tmp/pkgbuild-1702369728/BUILDROOT/mydumper-0.15.1-3.aarch64/usr/bin
+ install -m 0755 -d /tmp/pkgbuild-1702369728/BUILDROOT/mydumper-0.15.1-3.aarch64/etc
+ install -m 0755 mydumper /tmp/pkgbuild-1702369728/BUILDROOT/mydumper-0.15.1-3.aarch64/usr/bin
install: cannot stat 'mydumper': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.rbgPHv (%install)

What do I need to configure to make the script work? I'm using centos 7.6.

**Comment by davidducos** [comment]
The build.sh script is used to build the packages, not to compile MyDumper. 
You have more info about how build.sh is used in https://github.com/mydumper/mydumper/blob/master/.circleci/config.yml
