### ISSUE TITLE
Hard-coded default config file location doesn't work for MacOS homebrew installation

### ISSUE THREAD

**Issue by highfalutin** [mydumper/mydumper#1369]
**Describe the bug**
`mydumper` expects a config file at `/etc/mydumper.cnf`, but when you follow [the instructions in the README](https://github.com/mydumper/mydumper/blob/master/README.md?plain=1#L57) for installing via homebrew, the config file is placed instead at `/usr/local/etc` or `/opt/homebrew/etc`, and `mydumper` runs without it.

**To Reproduce**
Follow [these instructions](https://github.com/mydumper/mydumper#macos). Then run `mydumper` with `--debug`, for example `mydumper -x '//' --debug`.

You will see "Using no configuration file".

**Expected behavior**
The `mydumper.cnf` configuration should be used.

**Environment**
 - OS version: MacOS 13.6.x
 - MyDumper version: v0.15.1-3

**Comment by davidducos** [comment]
Hi @highfalutin,
seems that https://github.com/Homebrew/homebrew-core/blob/master/Formula/m/mydumper.rb needs to be updated.

**Comment by davidducos** [comment]
Hi @highfalutin 
Readme updated https://github.com/mydumper/mydumper/commit/96131c07b35f9920468f01a7f17188caa509a294
