### ISSUE TITLE
[BUG] --defaults-extra-file remove previous values set in the default file

### ISSUE THREAD

**Issue by aqueos** [mydumper/mydumper#1380]
**Describe the bug**
i wanted to add some parameters to a mydumper launch. I added an extra file and it just stop recognize the user/password that are set in the default file in the mydumper and client sections.

**To Reproduce**

/etc/mysql/debian.cnf  have user and password set only
/usr/local/.aqadmin/home/backup/etc/mydumper.cnf  have a db.table section (see below)

`mydumper --defaults-file=/etc/mysql/debian.cnf `   =>  Works ok

when i use 
`mydumper --defaults-file=/etc/mysql/debian.cnf --defaults-extra-file=/usr/local/.aqadmin/home/backup/etc/mydumper.cnf
`
it fail saying root is not allowed to connect 
but in debian.cnf i have  user     = debian-sys-maint  and it works well if i dont add the extra file.

**Expected behavior**
extrafile should add the config and so still use the login/pass setup in [mydumper] section of /etc/mysql/debian.cnf 

I wanted to test in the extra file if i could use wildcards like

```
[*.cache*]
no-data=1
```

to not dump the data of cache tables.

best regards,
Ghislain.

**Comment by davidducos** [comment]
Hi @aqueos,
Can you share both files? as there are different ways to configure the user and password and I want to check what is the use case that you are falling into.

**Comment by aqueos** [comment]
hi,

yes here are the 2 files:/usr/local/.aqadmin/home/backup/etc/mydumper.cnf


```
[*.keyyo]
no-data=1


[mydumper_global_variables]
sync_binlog = 0
slow_query_log = OFF
```

and /etc/mysql/debian.cnf

```

[client]
host     = localhost
user     = debian-sys-maint
password = xxxxxxxxxxxxxxxxx
socket   = /var/run/mysqld/mysqld.sock
[mysql_upgrade]
host     = localhost
user     = debian-sys-maint
password = xxxxxxxxxxxxxxxxxx
socket   = /var/run/mysqld/mysqld.sock


[mydumper]
user     = debian-sys-maint
password = xxxxxxxxxxxxxxxxxxxxxx
```


best regards,
Ghislain.
