### ISSUE TITLE
Not able to use partition-regex

### ISSUE THREAD

**Issue by jkthedba** [mydumper/mydumper#1382]
HI all

Did any one used partition-regex I'm unable to take backup of single partition. The documentation doesn't list any example how to take single partition backup

I tried to take backup of tr_ord table p2311 backup using mydumper but can not, if I am doing something wrong please correct my syntax
```
mydumper -u root -p xxxxx -h xxxxx --ssl-mode=disabled  -r 20000  -o data7 --csv --partition-regex='^(?=((payment_qa\.tr_ord$\.p2311$)))'
```

**Comment by davidducos** [comment]
You should run it like this:
```
mydumper -u root -p xxxxx -h xxxxx --ssl-mode=disabled  -r 20000  -o data7 --csv --partition-regex='^(?=((p2311$)))' -T payment_qa.tr_ord
```

**Comment by jkthedba** [comment]
Thanks David as always for fast reply.. but when I try using I don't see anything created

jitender.kha ~ % mydumper -u root -p xxxx -h xxxxx --ssl-mode=disabled  -r 20000  -o data7 --csv --partition-regex='^(?=((p2311$)))' -T payment_qa.tr_ord
jitender.kha ~ % cd data7
jitender.kha data7 % ls -lart
total 16
drwx--x--x@ 66 jitender.kha  staff  2112 Jan  9 09:10 ..
-rw-r--r--   1 jitender.kha  staff    94 Jan  9 09:10 payment_qa-schema-create.sql
-rw-r--r--   1 jitender.kha  staff   223 Jan  9 09:10 metadata
drwxr-x---   4 jitender.kha  staff   128 Jan  9 09:10 .
jitender.kha data7 %

**Comment by jkthedba** [comment]
so the table name is 
mysql> select table_name,PARTITION_NAME,TABLE_ROWS from INFORMATION_SCHEMA.PARTITIONS where table_schema='payment_qa' and table_name='tr_order';

| tr_order   | p2311          |       7435 |
| tr_order   | p9999          |      34993 |
+------------+----------------+------------+
56 rows in set (0.31 sec)


but the backup that is generated with above command is taking all rows

jitender.kha@ ~ %
jitender.kha@~ % mydumper -u root -p P@ss99W0rd -h 10.14.255.1 --ssl-mode=disabled  -r 20000  -o data7 --csv --partition-regex='^(?=((p2311$)))' -T payment_qa.tr_order
jitender.kha@ ~ % cd data7
jitender.kha@ data7 % ls -alrt
total 69320
drwx--x--x@ 66 jitender.kha  staff      2112 Jan  9 09:40 ..
-rw-r--r--   1 jitender.kha  staff        94 Jan  9 09:40 payment_qa-schema-create.sql
-rw-r--r--   1 jitender.kha  staff      8799 Jan  9 09:40 payment_qa.tr_order-schema.sql
-rw-r--r--   1 jitender.kha  staff      1729 Jan  9 09:40 payment_qa.tr_order.00001.sql
-rw-r--r--   1 jitender.kha  staff      1729 Jan  9 09:40 payment_qa.tr_order.00000.sql
-rw-r--r--   1 jitender.kha  staff      1528 Jan  9 09:40 payment_qa.tr_order.00000.dat
-rw-r--r--   1 jitender.kha  staff  35261918 Jan  9 09:40 payment_qa.tr_order.00001.dat
-rw-r--r--   1 jitender.kha  staff       288 Jan  9 09:40 metadata
drwxr-x---   9 jitender.kha  staff       288 Jan  9 09:40 .
jitender.kha@ data7 % cat payment_qa.tr_order.00000.dat|wc -l
       2
jitender.kha@ data7 % view payment_qa.tr_order.00001.dat
jitender.kha@ data7 % cat payment_qa.tr_order.00001.dat|wc -l
   47470

**Comment by jkthedba** [comment]
can anyone please help on this..

**Comment by jkthedba** [comment]
Some dev purged the partition of it, have data available  only in default partition as of now

mysql> select count(1) from payment_qa.tr_order partition(p9999);
+----------+
| count(1) |
+----------+
|     2931 |
+----------+
1 row in set (0.02 sec)

**Comment by jkthedba** [comment]
thanks it worked jitender.kha@AGC-~ % mydumper -u root -p xxxxx -h xxxxx--ssl-mode=disabled  -r 20000  -o data7 --csv --partition-regex='^(?=((p9999$)))' -T payment_qa.tr_order
jitender.kha@~ % cd data7
jitender.kha@ data7 % ls -alrt
total 4384
drwx--x--x@ 73 jitender.kha  staff     2336 Jan 22 10:55 ..
-rw-r--r--   1 jitender.kha  staff       94 Jan 22 10:55 payment_qa-schema-create.sql
-rw-r--r--   1 jitender.kha  staff     8799 Jan 22 10:55 payment_qa.tr_order-schema.sql
-rw-r--r--   1 jitender.kha  staff     1729 Jan 22 10:55 payment_qa.tr_order.00000.sql
-rw-r--r--   1 jitender.kha  staff  2216016 Jan 22 10:55 payment_qa.tr_order.00000.dat
-rw-r--r--   1 jitender.kha  staff      288 Jan 22 10:55 metadata
drwxr-x---   7 jitender.kha  staff      224 Jan 22 10:55 .
jitender.kha@data7 % cat payment_qa.tr_order.00000.dat |wc -l
    2931

**Comment by jkthedba** [comment]
thanks @davidducos for help
