### ISSUE TITLE
[BUG] myloader import view error 

### ISSUE THREAD

**Issue by waittingsummer** [mydumper/mydumper#1388]
**Describe the bug**
 After exporting mysql data to sql files using mydumper, import view error when importing these sql files using myloader  

**To Reproduce**
Command executed:
* mydumper  -h 192.168.12.64 -u root -p 'xianyi1234567' -G -E -R -B scada -o /data/scada_mydumper
* myloader -h 192.168.12.64 -u root -p 'xianyi1234567' -B scada -d /data/scada_mydumper

![test-F上mydumper导出](https://github.com/mydumper/mydumper/assets/32017265/54f0aa44-6542-4924-b2ea-6dd85dd740f8)

![test-F上myloader导入](https://github.com/mydumper/mydumper/assets/32017265/51847d11-afef-4dc7-9c60-17055f18a1b6)

[error.tar.gz](https://github.com/mydumper/mydumper/files/13896409/error.tar.gz)

 Missing Views 
![image](https://github.com/mydumper/mydumper/assets/32017265/a50e7a4e-32ab-47b5-b8d3-671c82d57b28)

**Additional context**
After comparing the views that failed to be imported, find these views from the error statements and manually create them successfully.  

**Expected behavior**
 After exporting mysql data to sql files using mydumper, everything works fine when importing those sql files using myloader 

**Environment (please complete the following information):**
 - OS version: CentOS 8.2
 - MyDumper version:  0.15.1-3

**Comment by davidducos** [comment]
Hi @waittingsummer 
Please use `--max-threads-for-post-actions=1` and let me know.

This issue is strange as it should not happen as we are creating a table per view to avoid this issue. 
The only scenario that could happen is that a thread drops a table, as it needs to create the view, and at that exact moment the create view statement that needs the view doesn't find it. This scenario happens when you use multithreading for post operations that can be disable using  `--max-threads-for-post-actions=1`

**Comment by waittingsummer** [comment]
> Hi @waittingsummer Please use `--max-threads-for-post-actions=1` and let me know.
> 
> This issue is strange as it should not happen as we are creating a table per view to avoid this issue. The only scenario that could happen is that a thread drops a table, as it needs to create the view, and at that exact moment the create view statement that needs the view doesn't find it. This scenario happens when you use multithreading for post operations that can be disable using `--max-threads-for-post-actions=1`


@davidducos 
Test again according to your method, very smooth, and import speed is only a little slower than before.
![myloader导入](https://github.com/mydumper/mydumper/assets/32017265/40f34d63-addc-43b3-a440-34a9be1c8be2)
