### ISSUE TITLE
[BUG] [ERROR] - cannot open file and [ERROR] - Thread 1: issue restoring

### ISSUE THREAD

**Issue by asathvik** [mydumper/mydumper#1421]
**Describe the bug**

Getting this error very often and writing to logfile , not clear what exactly this means

```
2024-03-03 05:30:43 [ERROR] - cannot open file agent1.e.00000.00006.sql (10)
2024-03-03 05:30:43 [ERROR] - Thread 1: issue restoring agent1.e.00000.00006.sql:
2024-03-03 05:30:43 [WARNING] - FIFO file found /data/mysql01/backups/agent1.e.00000.00006.sql, removing and continuing
2024-03-03 05:31:29 [WARNING] - FIFO file found /data/mysql01/backups/agent1.e.00000.00008.sql. Skipping
```

**To Reproduce**

Command executed:
threads_dump=24
threads_restore=24

* mydumper with all the parameters
`mydumper -h $source_host -u $source_user -p $source_pass -P $source_port --outputdir=$outputdir --threads=$threads_dump --chunk-filesize=1024 --regex '^(?!(test\.|performance_schema\.|information_schema\.|common_schema\.|sys\.|mysql_innodb_cluster_metadata\.|mysql\.))' -G -E -R -c -e --less-locking --skip-definer --trx-consistency-only --no-backup-locks -v 1 --logfile $logfilepath/mydumper_${myname}_$(date -d "today" +"%Y%m%d%H%M%S").log`

No issues with backup as it is completed without any issues and you can refer metadata file info/log
```
grep "dump at"  backups/metadata
# Started dump at: 2024-03-01 18:11:06
# Finished dump at: 2024-03-02 05:37:19
```

* myloader with all the parameters

`myloader --threads=$threads_restore --max-threads-per-table=12 --queries-per-transaction=10000 -h $dest_host --port $dest_port --user=$dest_user --password=$dest_pass --socket=/db01/mysql01/admin/mysql.sock --directory $outputdir -o -v 2 --logfile $logfilepath/myloader_${myname}_$(date -d "today" +"%Y%m%d%H%M%S").log
`

```
mydumper -V
mydumper v0.15.1-3, built against MySQL 5.7.42-46 with SSL support
myloader -V
myloader v0.15.1-3, built against MySQL 5.7.42-46 with SSL support
```

**Expected behavior**
Not error expected.

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
CentOS 7.9

```
cat /etc/*release | head -1
CentOS Linux release 7.9.2009 (Core)

```

 - MyDumper version: [ mydumper --version ]
```
mydumper --version
mydumper v0.15.1-3, built against MySQL 5.7.42-46 with SSL support
```

**Comment by davidducos** [comment]
Hi @asathvik, Can you test with latest prerelease?

**Comment by asathvik** [comment]
Looks its not available yet.
https://github.com/mydumper/mydumper/releases/download/v0.16.3-1/mydumper-0.16.3-1.el7.x86_64.rpm

it still shows this `v0.15.1-3`
```
curl -Ls -o /dev/null -w %{url_effective} https://github.com/mydumper/mydumper/releases/latest | cut -d'/' -f8
v0.15.1-3
```

**Comment by davidducos** [comment]
Hi @asathvik,

This is the latest prerelease https://github.com/mydumper/mydumper/releases/tag/v0.15.2-8

**Comment by davidducos** [comment]
We are closing until we get a confirmation
