### ISSUE TITLE
Error Moving db backups from  5.5.65-MariaDB  and restoring to  10.5.16-MariaDB  Server

### ISSUE THREAD

**Issue by vamshi8** [mydumper/mydumper#1430]
**Describe the bug**
I am seeing ** (myloader:890515): ERROR **:: Global metadata file processing was not possible
Trace/breakpoint trap (core dumped)
when i took backup on 5.5.65-MariaDB and restore to 10.5.16-MariaDB  Server

**To Reproduce**
Command executed:
 nice -n 19 ionice -c 2 -n 7 mydumper --threads 3 --database abcd --compress --outputdir "/backups/"
*  myloader -d --database abcd --directory /backups/ --overwrite-tables --compress-protocol --defaults-extra-file=/tmp/.cnf

What mydumper and myloader version has been used?
mydumper 0.11.1, built against MySQL 5.7.34-37
myloader v0.15.1-3, built against MySQL 8.0.33-25 with SSL support

**Expected behavior**
to restore backups successfully on new version of MariaDB.

**Log**
** (myloader:890515): WARNING **: : FIFO file found /backups/xxx-schema-create.sql, removing and continuing

** (myloader:890515): WARNING **: Failed to load config file /backups/metadata: Key file contains line “Started dump at: 2024-03-10 09:29:51” which is not a key-value pair, group, or comment

** (myloader:890515): ERROR **: Global metadata file processing was not possible

**Environment (please complete the following information):**
Red Hat Enterprise Linux Server release 7.8 (Maipo) on mydumper
Red Hat Enterprise Linux release 9.1 (Plow) on myloader

**Additional context**
could you please provide any document performed mariadb replication for this kind of requirement .

**Comment by davidducos** [comment]
There is no cross major version compatibility.

**Comment by vamshi8** [comment]
@davidducos quick question i am working on configuring mariadb replication using mydumper , i need to do it with out locking tables , is this possible via mydumper ?

**Comment by davidducos** [comment]
Hi @vamshi8, mydumper is a backup tool that needs to take a global lock to sync all the threads to take a consistent backup, then is released. 
The replication is configure in a replica server, so no lock is send to the primary.

**Comment by vamshi8** [comment]
thank you
