### ISSUE TITLE
[MySQL8.3] Review FUNCTION columns

### ISSUE THREAD

**Issue by mmalutinde** [mydumper/mydumper#1431]
**Describe the bug**
No problem within backup process.
In the restore process MySQL server reports what "You have an error in your SQL syntax"
** (myloader:23502): CRITICAL **: 16:59:54.496: Thread 15: Error restoring: SET character_set_client = ;

**To Reproduce**
Command executed:
mydumper -h 127.0.0.1 -u root -p PASS -B dbname --checksum-all -v 3 -t 6 -R -G -E -c -o /home/user/mysql-testdata

myloader -h 127.0.0.1 -u root -p PASS --innodb-optimize-keys -B dbname2 -t 6  -d /home/user/mysql-testdata

What mydumper and myloader version has been used?

mydumper v0.16.1-1, built against MySQL 8.0.36-28 with SSL support
myloader v0.16.1-1, built against MySQL 8.0.36-28 with SSL support

**Expected behavior**
Dump should be loaded in database.

**Log**
```
** Message: 17:15:58.147: Thread 15: restoring post on `dbname2` from dbname-schema-post.sql.gz. Tables 126 of 137 completed

** (myloader:24602): WARNING **: 17:15:58.149: Thread 15: Error restoring 1: SET character_set_client = ;
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

** (myloader:24602): WARNING **: 17:15:58.150: Thread 15: Retrying last failed executed statement

** (myloader:24602): CRITICAL **: 17:15:58.150: Thread 15: Error restoring: SET character_set_client = ;
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
Trace/breakpoint trap (core dumped)
```

**Backup**
Metadata is attached
[metadata.txt](https://github.com/mydumper/mydumper/files/14562478/metadata.txt)

**Environment (please complete the following information):**
 - OS version: Ubuntu 22.04.3 LTS
 - MyDumper version: mydumper v0.16.1-1, built against MySQL 8.0.36-28 with SSL support
 - MySQL: [latest:8.3](https://hub.docker.com/_/mysql) 

**Additional context**
Content of -schema-post file

```
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION'*/;
/*!40103 SET TIME_ZONE='+00:00' */;
SET @PREV_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @PREV_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @PREV_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET character_set_client = ;
SET character_set_results = ;
SET collation_connection = utf8mb4;
```

**Comment by davidducos** [comment]
Hi @mmalutinde,
Thank you for reporting this bug, but this is related to MySQL 8.3 which is not supported yet by MyDumper.
The issue here is that column `Language` has been added to the result when we execute `SHOW FUNCTION STATUS`

**Comment by mmalutinde** [comment]
Thanks for your job! 
This problem was also with MySQL 8.2
I'm looking forward to future support of the newest versions of MySQL.
BR.

**Comment by davidducos** [comment]
Hi @mmalutinde, I will left this ticket open as a reminder that we need to implement it.
