### ISSUE TITLE
What does this mean "FIFO file found ..."

### ISSUE THREAD

**Issue by billynoah** [mydumper/mydumper#1432]
I guess this is a "feature request" for documentation or clarification on what this means and what causes it:

```
** (myloader:916704): WARNING **: 10:35:50.913: FIFO file found /path/to/backup/mytable.sql, removing and continuing
```

I ran an import today using myloader:

```
myloader --defaults-extra-file=$HOME/.my.cnf -o -t 8 -B my_database -d /path/to/backup
```

And got dozens of warnings like above. Sorry if this has been discussed elsewhere.  I searched the repo issues, wiki and Googled the message and came up with nothing.

**Comment by davidducos** [comment]
We changed the way that we work with compressed (and other external command executions). 
We use FIFO files to send to the other process to compress (or any execution). 
There are scenarios where the FIFO files are left from a previous execution, so, when we execute myloader a second time, we need to delete them before created again.

**Comment by billynoah** [comment]
Thanks for the explanation @davidducos.  That makes sense and sounds like it's nothing to be concerned about. I suspect I ctrl-z'd out of a previous myloader session some time back.  Is there a preferred way to kill the process which leaves things in a clean state?

**Comment by davidducos** [comment]
Hi @billynoah you can use `--fifodir` to avoid using the backup dir, but I don't remember if we are wiping out that directory before using it. We might need to add some `--clear` option like `--clear-fifodir` to avoid seeing those messages on the log.
