### ISSUE TITLE
[BUG] myloader is hanging

### ISSUE THREAD

**Issue by christofhaerens** [mydumper/mydumper#1434]
**Describe the bug**
When a restore is started with myloader it hangs and does nothing. Must be killed with a kill -9 before the process dies.

**To Reproduce**
Command executed:
* mydumper --compress --use-savepoints --less-locking --triggers --events --routines -v 3 --dirty --threads 4 -o /backup/20240312
* myloader -s testdb -d /backup/20240312 -B restoredb --innodb-optimize-keys 

What mydumper and myloader version has been used?
mydumper v0.16.1-1, built against MySQL 8.0.36-28 with SSL support
myloader v0.16.1-1, built against MySQL 8.0.36-28 with SSL support

**Expected behavior**
Restore should be done quick since the testdb only holds 2 tables and 2 records in each table. No indexes or anything else. When mysql is checked, we see the database and the tables. But the tables are empty. After some time we abort the myloader.

**Log**
see attached myloader.log 
[myloader.log](https://github.com/mydumper/mydumper/files/14575892/myloader.log)

**Backup**
see attached mydumper.filelist
[mydumper.filelist.txt](https://github.com/mydumper/mydumper/files/14575907/mydumper.filelist.txt)

All files are there. When checking the contents to rows of table a and b are in the backup

**How to repeat**
create database testdb;
use testdb;
create table a (name text, code int);
create table b (name text, code int);
insert into a values ('tom', 1);
insert into a values ('sam', 2);
insert into b values ('dave', 3);
insert into b values ('sarah', 4);

**Environment (please complete the following information):**
 - OS version: debian 12.5 -  6.1.0-18-amd64
 - Mysql: Server version: 8.0.36-28 Percona Server (GPL), Release '28', Revision '47601f19'$

**Additional context**
When myloader is 'hanging' we did a strace -f on the main process, which produces a continue output of:

[pid 904796] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904795] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904794] <... futex resumed>)       = 1
[pid 904793] <... futex resumed>)       = 0
[pid 904796] futex(0x56104e0d5eb0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 904795] futex(0x56104e0d5eb0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 904794] futex(0x56104e0d5eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904793] futex(0x56104e0fbd70, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 904796] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904795] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904794] <... futex resumed>)       = 0
[pid 904796] futex(0x56104e0d5eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904795] futex(0x56104e0d5eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904794] futex(0x56104e0fbd70, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904796] <... futex resumed>)       = 0
[pid 904795] <... futex resumed>)       = 0
[pid 904794] <... futex resumed>)       = 1
[pid 904793] <... futex resumed>)       = 0
[pid 904796] futex(0x56104e0d5ec0, FUTEX_WAIT_PRIVATE, 4755429, NULL <unfinished ...>
[pid 904795] futex(0x56104e0d5ec0, FUTEX_WAIT_PRIVATE, 4755429, NULL <unfinished ...>
[pid 904794] futex(0x56104e0d5ec0, FUTEX_WAIT_PRIVATE, 4755429, NULL <unfinished ...>
[pid 904793] futex(0x56104e0d5ec0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904796] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904795] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904794] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904793] <... futex resumed>)       = 0
[pid 904796] futex(0x56104e0d5eb0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 904795] futex(0x56104e0d5eb0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 904794] futex(0x56104e0d5eb0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 904793] futex(0x56104e0d5eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904796] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904795] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904794] <... futex resumed>)       = -1 EAGAIN (Resource temporarily unavailable)
[pid 904793] <... futex resumed>)       = 0
[pid 904796] futex(0x56104e0d5eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904795] futex(0x56104e0d5eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904794] futex(0x56104e0d5eb0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904793] futex(0x56104e0fbd70, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904796] <... futex resumed>)       = 0
[pid 904795] <... futex resumed>)       = 0
[pid 904794] <... futex resumed>)       = 0
[pid 904793] <... futex resumed>)       = 0
[pid 904796] futex(0x56104e0d5ec0, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid 904795] futex(0x56104e0d5ec0, FUTEX_WAIT_PRIVATE, 4755430, NULL <unfinished ...>
[pid 904794] futex(0x56104e0d5ec0, FUTEX_WAIT_PRIVATE, 4755430, NULL <unfinished ...>
[pid 904793] futex(0x56104e0d5eb0, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>

**Comment by davidducos** [comment]
I can confirm with a simpler test case:
```
create database testdb;
use testdb;
create table a (name text, code int);
create table b (name text, code int);
insert into a values ('tom', 1);
insert into a values ('sam', 2);
insert into b values ('dave', 3);
insert into b values ('sarah', 4);

create database testdb1;
use testdb1;
create table a (name text, code int);
create table b (name text, code int);
insert into a values ('tom', 1);
insert into a values ('sam', 2);
insert into b values ('dave', 3);
insert into b values ('sarah', 4);

./mydumper -v 3 --clear --threads 4 -o backup -B testdb,testdb1
./myloader -s testdb -d backup -B restoredb -v 3 -o
```
Seems that the problem shows up when -s is used.

**Comment by davidducos** [comment]
Issue found.
The information of the tables in the metadata is not being ignored.

**Comment by davidducos** [comment]
@christofhaerens 
New release with the fix will be released later today.

**Comment by christofhaerens** [comment]
Nice work, thxs a lot. Will give it a go later on.
