### ISSUE TITLE
[FEATURE REQUEST] Multiple --regex parameters

### ISSUE THREAD

**Issue by christophlehmann** [mydumper/mydumper#1440]
To ease things with the --regex parameter it would be nice when it can be applied multiple times.

**Comment by davidducos** [comment]
Hi @christophlehmann,
I'm checking if this is doable in a simple way. However, I wanted to be sure that you review https://github.com/mydumper/mydumper?tab=readme-ov-file#how-to-exclude-or-include-databases and if we have multiple --regex, it will be working as regex1 OR regex2 or regex3, and so on, right?
