### ISSUE TITLE
[BUG] Triggers are dumped when they have not been requested with -G or --triggers

### ISSUE THREAD

**Issue by mrmuskrat** [mydumper/mydumper#1451]
**Describe the bug**
mydumper is dumping triggers without -G or --triggers being specified. 

**To Reproduce**
Command executed:
We have some large tables that we skip so we perform the dumps in two phases:
```
  /usr/bin/mydumper --no-data --compress -B some_database -o /some/path
  /usr/bin/mydumper --dirty --rows 250000 -G -R -c --trx-consistency-only -t 8 -B some_database -x '^(?!(some_database\.(big_table_1|big_table_2|big_table_3)))' -o /some/path
```
The first command is producing /some/path/some_database-schema-triggers.sql.gz which then bombs out during a restore with myloader at the first duplicate trigger.

```
myloader --host=localhost --database=some_database --enable-binlog --directory=/some/path --queries-per-transaction=250000 --threads=12 --compress-protocol --verbose=3
```

What mydumper and myloader version has been used?
mydumper v0.16.1-3, built against MySQL 5.7.44-48 with SSL support
myloader v0.16.1-3, built against MySQL 5.7.44-48 with SSL support

**Expected behavior**
We expected that the behavior matched the documentation and that no triggers would be created unless explicitly requested.

The documentation says:
> .. option:: -G, --triggers
>   Dump triggers. By default, it do not dump triggers

**Environment (please complete the following information):**
 - OS version: AlmaLinux 8.9 (Midnight Oncilla)
 - MyDumper version: mydumper v0.16.1-3, built against MySQL 5.7.44-48 with SSL support

**Additional context**
This seems related to #541, #647, #665, #666, etc

**Comment by davidducos** [comment]
Hi @mrmuskrat 
this has already fixed on https://github.com/mydumper/mydumper/pull/1447/files#diff-ac6a7de40ac3f6ccf88edf992fe45c23ea461ccce592d6673daad0eebeb90e12
