### ISSUE TITLE
How to only dump the data of a subset of tables, but the schemas of all tables with only one call to mydumper?

### ISSUE THREAD

**Issue by bseiller** [mydumper/mydumper#1452]
## Question
Is there an easier way for those following 2 scenarios, perhaps with merging the two dumps in 1 directory or even nicer with just 1 call to mydumper and myloader each?

## prerequisite/constraint
a database schema containing ~170 tables, with tables A and B being kind of caches, containing to much data to be dumped fast and also taking to much storage space, thus the data of those 2 tables is being excluded. But the schemas of tables A and B are relevant and might change, so we want those still to be dumped/backuped.

## 1.scenario: cloning of the schema for testing purposes

our current solution would look like this

```console
# dump schema and data of all but 2 tables, exclude those via -x
mydumper -x '^(?!(SCHEMA.A$|SCHEMA.B$))' --outputdir /tmp/clone -h DUMP_HOST -B SCHEMA 
# import schemas and data of all tables dumped in the first step
myloader -h localhost --overwrite-tables --directory /tmp/clone
rm -rf /tmp/clone
# dump only schemas (--no-data) of the 2 previous excluded tables, only include those via -x
mydumper --no-data -x '^(SCHEMA.A$|SCHEMA.B$)' --outputdir /tmp/clone -h DUMP_HOST -B SCHEMA 
# import schemas of the 2 tables
myloader -h localhost --overwrite-tables --directory /tmp/clone
rm -rf /tmp/clone
```

## 2.scenario: creating a backup before a deployment and restoring it later on

our current solution would look like this

### creating the backup
```console
# dump schema and data of all but 2 tables, exclude those via -x
mydumper -x '^(?!(SCHEMA.A$|SCHEMA.B$))' --outputdir /tmp/backup -h DUMP_HOST -B SCHEMA 
# dump only schema (--no-data) of the 2 previous excluded tables, only include those via -x
mydumper --no-data -x '^(SCHEMA.A$|SCHEMA.B$)' --outputdir /tmp/backup_2 -h DUMP_HOST -B SCHEMA 
```
### restoring from backup
```console
# import schemas and data of all tables dumped in the first step
myloader -h DUMP_HOST --overwrite-tables --directory /tmp/backup
rm -rf /tmp/backup
# import schemas of the remaining 2 tables
myloader -h DUMP_HOST --overwrite-tables --directory /tmp/backup_2
rm -rf /tmp/backup_2
```

**Comment by davidducos** [comment]
Hi @bseiller,
The best solution of what you are proposing is to have an option per table basis if we want to export the data or not. We don't have that yet on mydumper. We implemented other options per table basis, I don't see why we can't include this one.
Anyways, it is possible to execute mydumper to get the backup as you want in a single run. If you check the documentation https://github.com/mydumper/mydumper?tab=readme-ov-file#defaults-file, you will see that it is possible to set a where clause per table basis. If the where clause is FALSE always, it will not export any data. For instance:
```
[`SCHEMA`.`A`]
where = 1 = 0
```
However, the SELECTs are going to be executed anyways, which bothers me, but it is what it is.

**Comment by bseiller** [comment]
`where = 1 = 0` in the defaults file is a creative way to handle our constraints!
Thanks you @davidducos, I'll try that!
