### ISSUE TITLE
backup all databases error

### ISSUE THREAD

**Issue by lgb861213** [mydumper/mydumper#1460]
when I use the following command to backup all mysql databases 
mydumper -uroot -h localhost -p -P 3306 -G -E -R --rows="100000" -F 64 -t 10 -o all_database_dumper  -p

 but if show the error :
** (mydumper:36889): CRITICAL **: 11:46:34.524: option parsing failed: Error parsing option -r, try --help

mydumper version that is 
mydumper v0.16.1-3, built against MySQL 8.0.36-28 with SSL support

how to fix it

**Comment by davidducos** [comment]
Hi @lgb861213 , -r doesn't expect quotes.
