### ISSUE TITLE
[BUG] Heap corruption in myloader on MacOS Sonoma 14.3 (23D56)

### ISSUE THREAD

**Issue by jgoldfar-curi** [mydumper/mydumper#1466]
**Describe the bug**
Myloader reproducibly fails when attempting to import a file generated by mydumper with a `malloc` error of this form:
```
myloader(44842,0x1700eb000) malloc: Heap corruption detected, free list is damaged at 0x6000016d0ba0
*** Incorrect guard value: 105553138166144
myloader(44842,0x1700eb000) malloc: *** set a breakpoint in malloc_error_break to debug
```

**To Reproduce**
Command executed:
* mydumper with all the parameters
```shell
mydumper --user read \
  --password $PROD_SQL_READ_USER_PASSWORD \
  --socket /tmp/cloudsql/$SC_SQL_REPLICA_CONNECTION_NAME \
  --database prod \
  --rows 250000 \
  --threads 32 \
  --outputdir $PROD_DUMP_DIR \
  --long-query-guard 7200 \
  --debug
```

* myloader with all the parameters `myloader --defaults-file=/opt/homebrew/etc/mydumper.cnf --verbose 3 -u root --database snx --directory $HOME/path/to/proddump/ --logfile failure-logs.log`

What mydumper and myloader version has been used? `mydumper v0.14.5-3`, `myloader v0.16.1-3`

**Expected behavior**
All tables are imported into `snx` database, and no heap corruption occurs

**Log**
Attached: [failure-logs.log](https://github.com/mydumper/mydumper/files/14909050/failure-logs.log)

**How to repeat**
- Export database with mydumper as described above
- Import database with myloader as described above

**Environment (please complete the following information):**
 - OS version: MacOS 14.3
 - MyDumper version: myloader v0.16.1-3, built against MySQL 8.3.0 with SSL support

**Comment by davidducos** [comment]
Hi @jgoldfar-curi, 
we don't support cross version backup. You should use same version to export and import.

**Comment by jgoldfar-curi** [comment]
Thanks for those details @davidducos; that was not clear to us from the documentation, but indeed after aligning the mydumper/myloader versions between our environments the import seems to work as expected.
