### ISSUE TITLE
Support Google Cloud mysql backup[FEATURE REQUEST]

### ISSUE THREAD

**Issue by suyanhj** [mydumper/mydumper#1471]
**Describe the Feature Request**
Want to add support for backing up Google Cloud MySQL 8.0
When I am using mydumper to backup gcloud SQL, there will be environment variable configuration when executing mydumper. At this time, there will be permission errors causing execution failure. Therefore, I checked the official documentation of Google Cloud, which pointed out that their cloud SQL has default restrictions on creating user permissions. I am using the root user, but this is still the case. Compared to using native mysqldump, these errors will not occur.

**Comment by davidducos** [comment]
Hi @suyanhj,
Can you share what is the error that you see and execute `SHOW GRANTS` of the user that you are using to take the backup?

**Comment by suyanhj** [comment]
Okay, please wait for me to execute mydumper on the error screenshot when migrating table data tomorrow.
![image](https://github.com/mydumper/mydumper/assets/95021771/5b5f7f87-fe6c-4dc2-888b-bdf669418bbc)

![image](https://github.com/mydumper/mydumper/assets/95021771/b929dfa0-5d3f-45f7-aada-ffd001cc316e)

**Comment by suyanhj** [comment]
When using the latest version today, it seems that there was no permission error in the configuration of environment variables in the last backup. The v0.16.1-1 version was used last month, but 0.16.1-3 is used today, I wonder if it is because you fixed it?

**Comment by davidducos** [comment]
Having the error will iron out any doubt.

**Comment by suyanhj** [comment]
> Having the error will iron out any doubt.有错误将消除任何疑问。

This time, I found that myloader had an error when importing the database. When initializing the environment variables, it prompted that the configuration environment was not supported. The abnormal exit was like this. The error of initializing the variables before was too much because the shell refreshed the screen, so I couldn’t see it, so I couldn’t take a screenshot.

![image](https://github.com/mydumper/mydumper/assets/95021771/4dddbb73-c75f-40aa-bb21-a055bafc7551)

**Comment by davidducos** [comment]
Hi @suyanhj 
You should read https://github.com/mydumper/mydumper/issues/1486 and https://github.com/mydumper/mydumper/pull/1494 as we already implemented --ignore-errors to avoid those issues.
