### ISSUE TITLE
[BUG] --max-threads-per-table not working in the latest version

### ISSUE THREAD

**Issue by delissonjunio** [mydumper/mydumper#1475]
**Describe the bug**
Using `--max-threads-per-table` does not work well in the latest version compiled from source.

**To Reproduce**
Command executed:
```
mydumper --defaults-file my.cnf --rows 10000 --threads 1 --triggers --verbose 3 --routines --long-query-retry-interval 60 --long-query-guard 600 --long-query-retries 5 --verbose=3 --outputdir "mybackup"
myloader --innodb-optimize-keys --purge-mode DROP --max-threads-per-table 5 --threads 35 --rows 6000 --skip-definer -e -o -v 3 --directory 'mybackup'
```

What mydumper and myloader version has been used?
Latest master (3561dfe7766b467159184bb0ee5202643881ffde) compiled from source.

**Expected behavior**
`myloader` should restore with 5 threads working any single table and all threads should be doing work. What's happening is only 5 threads are doing any work (all on the same table)

**How to repeat**
Just run any loading job with `--max-threads-per-table X` and `--threads Y` where `X < Y`

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04
 - MyDumper version: `mydumper v0.16.2-1, built against MySQL 8.0.36 with SSL support`

**Additional context**
I have a fix PR for this at https://github.com/mydumper/mydumper/pull/1468

**Comment by davidducos** [comment]
Hi @delissonjunio, I will be publishing a prerelease later today. Feel free to test it.
Thanks again!
