### ISSUE TITLE
Unable to use myloader thread in intermediate shutdown state

### ISSUE THREAD

**Issue by T-Prathyusha** [mydumper/mydumper#1488]
**I am trying to load my dump**
I see the process is running but It has been stuck and the logs say:

** Message: 07:41:26.428: Using 32 loader threads

** (myloader:3609): WARNING **: 07:41:28.857: Set session failed: SET SESSION SQL_LOG_BIN = 0
** Message: 07:41:29.257: Initializing initialize_worker_schema
** (myloader:3609): WARNING **: 07:41:31.428: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.455: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.474: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.506: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.506: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.506: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.506: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.620: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:31.676: Set session failed: SET SESSION SQL_LOG_BIN = 0
** Message: 07:41:31.820: S-Thread 36: Starting import
** Message: 07:41:31.852: S-Thread 34: Starting import
** Message: 07:41:31.906: S-Thread 33: Starting import
** Message: 07:41:32.099: S-Thread 35: Starting import
** (myloader:3609): WARNING **: 07:41:34.041: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.057: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.074: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.109: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.109: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.109: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.122: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.228: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:34.285: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.636: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.637: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.659: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.679: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.715: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.718: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.824: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.848: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:36.852: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.204: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.267: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.279: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.279: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.286: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.374: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.409: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.435: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:39.481: Set session failed: SET SESSION SQL_LOG_BIN = 0
** Message: 07:41:39.681: Reading metadata: metadata
** Message: 07:41:39.843: Intermediate queue: Sending END job
** Message: 07:41:39.844: Intermediate thread ended
** Message: 07:41:39.844: Intermediate thread: SHUTDOWN
** (myloader:3609): WARNING **: 07:41:41.765: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:41.866: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:41.866: Set session failed: SET SESSION SQL_LOG_BIN = 0
** (myloader:3609): WARNING **: 07:41:41.882: Set session failed: SET SESSION SQL_LOG_BIN = 0

What mydumper and myloader version has been used?
16.1.3

**Expected behavior**
Should finish the load

 - OS version: [e.g. Ubuntu 22.04]
 - MyDumper version: [ mydumper --version ]
    16.1.3

**Comment by T-Prathyusha** [comment]
Found the reason the dump had no schema,
But I am facing the following on load now:

**Error switching to database `database1` Restoring tables (2)**
**Trace/breakpoint trap (core dumped)**

**Comment by davidducos** [comment]
Hi @T-Prathyusha,
Can you test with the latest prerelease?

**Comment by davidducos** [comment]
Same bug found here https://github.com/mydumper/mydumper/issues/1487#issuecomment-2103287167
