### ISSUE TITLE
Add --innodb-optimize-keys=SKIP to ignore the new enabled default --innodb-optimize-keys option 

### ISSUE THREAD

**Issue by TomMettam** [mydumper/mydumper#1493]
**Describe the Feature Request**
Please consider automatically enabling  --innodb-optimize-keys for innodb tables with more than 1 index and more than 1 million records.

**Current behaviour**
I attempted to import a database which includes a table with 0.3 billion records and 10 indexes.

It very quickly slowed to an absolute crawl - after 24 hours I calculated the current velocity and it would've taken a minimum of a week to complete, but in reality much more as it was becoming slower and slower.

I used   --innodb-optimize-keys and disabled the "optimisation" in #987 (set UNIQUE_CHECKS back to 0), and the import completed in a few hours.

**Expected behavior**
Myloader should be able to identify large/complex tables and apply optimisations accordingly

**Environment**
Linux/AMD64/Gentoo

10.6.17-MariaDB-log

**Comment by TomMettam** [comment]
@davidducos  I'm not sure if making it the default is a good strategy either, for smaller imports it is slower this way.

**Comment by davidducos** [comment]
Even with --innodb-optimize-keys, we are not splitting the table on smaller tables.
