### ISSUE TITLE
[BUG] ERROR 1050: Table '...MyISAM' already exists

### ISSUE THREAD

**Issue by bato3** [mydumper/mydumper#1500]
**Describe the bug**
When importing MyISAM tables, a message (x2) appears that the table exists. I use the `-o` parameter.

Myloader creates structure and imports data but shows errors.

InnoDB import works great.

**To Reproduce**
Command executed:
*  myloader -d 20240516/ --innodb-optimize-keys --defaults-extra-file=./mydumper.cnf --threads=0 --max-threads-for-index-creation=30 -o --verbose=3 --max-threads-for-index-creation=9

What mydumper and myloader version has been used?

* mydumper v0.16.2-1, built against MySQL 8.0.35-27 with SSL support
* myloader v0.16.2-3, built against MySQL 8.0.36-28 with SSL support

**Expected behavior**
No errors

**Log**
```
** Message: 15:05:44.904: Thread 34: restoring table m1040_strona.app_unique_logs from /var/www/db-site/20240516/m1040_strona.app_unique_logs-schema.sql.gz
** Message: 15:05:44.904: Dropping table or view (if exists) m1040_strona.app_unique_logs
** Message: 15:05:44.905: Thread 34: Creating table m1040_strona.app_unique_logs from content in /var/www/db-site/20240516/m1040_strona.app_unique_logs-schema.sql.gz. On db: m1040_strona
** Message: 15:05:44.906: Thread 36: Creating table m1040_strona.relation_staff2title from content in /var/www/db-site/20240516/m1040_strona.relation_staff2title-schema.sql.gz. On db: m1040_strona
** Message: 15:05:44.907: Fast index creation will be use for table: m1040_strona.rate_stories
** Message: 15:05:44.907: Thread 35: Creating table m1040_strona.rate_total from content in /var/www/db-site/20240516/m1040_strona.rate_total-schema.sql.gz. On db: m1040_strona

** (myloader:275034): WARNING **: 15:05:44.908: Connection 105 - ERROR 1050: Table 'app_unique_logs' already exists

CREATE TABLE `app_unique_logs` (
  `add_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `unique_key` varchar(255) NOT NULL,
  `variables` text,
  `session` longtext,
  UNIQUE KEY `unique_key` (`unique_key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3

** (myloader:275034): CRITICAL **: 15:05:44.908: Connection 105 - ERROR 1050: Table 'app_unique_logs' already exists

CREATE TABLE `app_unique_logs` (
  `add_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `unique_key` varchar(255) NOT NULL,
  `variables` text,
  `session` longtext,
  UNIQUE KEY `unique_key` (`unique_key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3

** (myloader:275034): WARNING **: 15:05:44.908: Failed to execute statement: Table 'app_unique_logs' already exists (1050)

** (myloader:275034): CRITICAL **: 15:05:44.908: Thread 34: issue restoring /var/www/db-site/20240516/m1040_strona.app_unique_logs-schema.sql.gz
```

**How to repeat**
```sql

CREATE TABLE `app_unique_logs` (
  `add_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `unique_key` varchar(255) NOT NULL,
  `variables` text,
  `session` longtext
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;
```

**Environment (please complete the following information):**
 - OS version: Ubuntu 22.04
 - MyDumper version: v0.16.2-1.git
 - MyLoader version: v0.16.2-3.git

**Comment by davidducos** [comment]
Hi @bato3,
I was not able to reproduce the issue with the latest version. Can you test with the current latest prerelease?

**Comment by bato3** [comment]
In my case I have many InnoDB tables, and approx 10 MyIsam (less than treads)

I sended my database structure for your mail (just now).


I make `git bisect`, and first bad commit was:

194e4f421b92f11a657733467469a646c777acfd is the first bad commit
commit 194e4f421b92f11a657733467469a646c777acfd
Author: davidducos <david.ducos@gmail.com>
Date:   Fri May 3 21:01:44 2024 +0000

    --skip-indexes and --skip-constraints added on mydumper and myloader
