### ISSUE TITLE
[FEATURE REQUEST] auto split table by threads

### ISSUE THREAD

**Issue by LaymanWoo** [mydumper/mydumper#1516]
**Describe the Feature Request**
I have a table which has primary key id is not continued,such as 1,2,3,4,5,1000000001,100000002...
I want a feature can auto split my table.

**Current behaviour**
Current i use -r param to split,eg -r 2000,but there is many threads run with (0,2000),(2000,4000),(4000,6000)...
So it takes too log to scan 1000000001...

**Expected behavior**
First count the total rows,and divise thread to get the count of every thead, then select min(id),max(id) from table limit count offset  count to get min_id,max_id of every thread,so it can split table to threads and scan it quickly

**Comment by davidducos** [comment]
Please set -r to 2000:10000:0 and it will automatically do what you want.
