### ISSUE TITLE
[BUG] No binlog info in Metadata

### ISSUE THREAD

**Issue by if-jeremy** [mydumper/mydumper#1521]
**Describe the bug**

Metadata file does not include binlog position when dumping RDS Aurora 2 (mysql 5.7) database

**To Reproduce**
Command executed:
* mydumper with all the parameters

```
mydumper --ssl \
-h {hostname} -o /dump --verbose=3 --port=3306 \
--kill-long-queries --chunk-filesize=5120 --build-empty-files \
--events --routines --triggers --compress --less-locking \
--success-on-1146 -B db1,db2,db3 \
-u {user} -p \"{password}\""
```

What mydumper and myloader version has been used?

mydumper v0.16.3-2, built against MySQL 8.4.0 with SSL support

**Expected behavior**

Expect to see master log position in the metadata file

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
 - MyDumper version: [ mydumper --version ]

Amazon Linux 2023 for ARM64, mydumper 0.16.3-2 (within Docker container)

**Additional context**

I suspect this is because of the patch https://github.com/mydumper/mydumper/pull/1512 - SHOW MASTER STATUS is deprecated in 8.2 - but it still needs to be used for older versions that do not support show_binary_log_status

**Comment by davidducos** [comment]
Hi @if-jeremy,
I reviewed the code and I had to test it on my own and I found no issue. What I got on the log is:
```2024-06-06 16:54:27 [WARNING] - Couldn't get master position: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation
 ```
I will need a log on your end to confirm that you are not seeing that entry.

**Comment by dreamydb** [comment]
Hi, we too have this problem with later versions of mydumper: 0.16.3-3. Downgrading to 0.12.3-1 or v0.14.5-2 shows primary binlog position and file in metadata. No errors in the mydumper logfile with v0.16.3-3.

Command ran on replica:
`mydumper --rows=5000000 --compress --build-empty-files --long-query-guard=1200 --verbose=3 --threads=24 --user=root --password=removed --socket=/path/to/socket --outputdir=/path/to/outputdir --logfile=/path/to/logfile`

With `0.12.3-1` version, metadata looks like this. Dumps both primary and replica binlog info into metadata:
```
Started dump at: 2024-07-17 12:52:45
SHOW MASTER STATUS:
        Log: binlog.003340
        Pos: 113033
        GTID:

SHOW SLAVE STATUS:
        Host: <primary IP removed>
        Log: binlog.000052
        Pos: 179852465
        GTID:

Finished dump at: 2024-07-17 12:53:12
```

Same command with version `0.14.5-2`, still dumps both primary and replica binlog info into metadata, different format for the primary information. Still works.
```
# Started dump at: 2024-07-17 12:50:01
[master]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
File = binlog.003340
Position = 113033
Executed_Gtid_Set =

[replication]
# relay_master_log_file = 'binlog.000052'
# exec_master_log_pos = 179750713
# Executed_Gtid_Set =
# Slave_IO_State = 'Waiting for source to send event'
# Master_Host = '<primary IP removed>'
# Master_User = '<replication user removed>'
# Master_Port = 3306
# Connect_Retry = 60
<SNIP>
[`db_name`.`table_name`]
real_table_name=table_name
rows = 1
...
# Finished dump at: 2024-07-17 12:50:29
```

Same command with version `0.16.3-3~focal` is missing the primary binlog file/position. This backup cannot be used to setup a new replica.
```
# Started dump at: 2024-07-17 14:04:53
[config]
quote_character = BACKTICK

[myloader_session_variables]
SQL_MODE='NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION' /*!40101

[master]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
File = binlog.003340
Position = 113033
Executed_Gtid_Set =


[`db_name`.`table_name`]
real_table_name=table_name
rows = 1
....
....
# Finished dump at: 2024-07-17 14:05:22
```

**Comment by davidducos** [comment]
Hi @dreamydb / @if-jeremy,

I found the issue... actually it is a bit fun. Seems that if you run SHOW SLAVE STATUS, you get `master` and `slave` words on the headers, but if you use SHOW REPLICA STATUS, you get `source` and `replica`. I didn't know that... 

Fix will be released soon.
