### ISSUE TITLE
Need the support for take delta changes back and import changed schema

### ISSUE THREAD

**Issue by ManojKumarRamasamy** [mydumper/mydumper#1526]
**Describe the Feature Request**
Need the support for take delta changes back and import changed schema

**Current behaviour**
Explain what mydumper/myloader is doing. Add parameters if needed.

**Expected behavior**
I am taking the full back using mydumper command and create new schema load the back. after sometime I need take backup delta changes and import tne new schema which we created for import full back.
The support needed take delta changes backup from original schema and import new schema. 

**Environment**
In some cases this might apply just for some OS or kind of environments.
We need the detailed information about it.

**Additional context**

**Comment by davidducos** [comment]
Hi @ManojKumarRamasamy, 
You can use the binlogs to perform point in time recoveries. 
mydumper only takes, full/partial backups. If you want a logical increment backup, you will need to determine the where conditions per table for the data that has been added but it will not be possible to remove the data that has been deleted or modified.

**Comment by ManojKumarRamasamy** [comment]
Hi David Ducos,
Thank you for reply. Actually our requirement is the original schema is "SchemaA". We took the full backup and restore to newly created schema as "SchemaB" with help of mydumper.  Then after sometime we need to capture the delta data from "SchemaA" of after fullbackup and again restore to "SchemaB". Basically It is migration to new Schema and restore the delta changes.

We tried binlog option for delta data restore, faced below 2 issues. 
1) The binlog is capturing the all Schema data.
2)  When restore the binlog file, we unable to change schema name to new schema.

If possible can you share solution with working example it is much appreciate.

**Comment by davidducos** [comment]
Hi @ManojKumarRamasamy, 
Ah now I understand better your problem. It is not related to MyDumper use cases. You need an ad hoc solution for your situation. That is something that will require time, feel free to contact me privately if you want to pay for the time solving your issue.
BTW, what you can do is to extract the sql statement with mysqlbinlog and the use sed to replace "SchemaA" with "SchemaB". Finally, import the sql statement. 
Regards.
