### ISSUE TITLE
[Does mydumper supports differential / delta backups] 

### ISSUE THREAD

**Issue by kishoretaru** [mydumper/mydumper#1532]
**Describe the Feature Request**
A clear and concise description of what is the use case.

**Current behaviour**
Explain what mydumper/myloader is doing. Add parameters if needed.

**Expected behavior**
A clear and concise description of what you expected to happen after implementation.

**Environment**
In some cases this might apply just for some OS or kind of environments.
We need the detailed information about it.

**Additional context**
If it supports please provide example commands for delta changes which are to be executed once full backup is collected

**Comment by davidducos** [comment]
You can use the binlogs to perform point in time recoveries.

**Comment by davidducos** [comment]
https://github.com/mydumper/mydumper/issues/1533
