### ISSUE TITLE
Differential Backup support 

### ISSUE THREAD

**Issue by shubhamjaiswal2611** [mydumper/mydumper#1533]
When using mydumper to take backup and restore,once full backup and restore is done, is there an option to take differential backup after sometime eg: 30 mins, from a schema whose name was previously "A" but while restore we have to restore it in "B".
If not present can you suggest a way to take the differential backup.

**Comment by davidducos** [comment]
You can use the binlogs to perform point in time recoveries.

**Comment by davidducos** [comment]
https://github.com/mydumper/mydumper/issues/1526

**Comment by shubhamjaiswal2611** [comment]
I was able to take differential backup of Schema "A", but while restoring I have to restore it in Schema "B", which is failing because of database name change, Can you suggest a way for that?

**Comment by davidducos** [comment]
Oh, no, you need to modify the binlog and replace SchemaA with SchemaB with sed or any other tool.
