### ISSUE TITLE
Does mydumper support database backup validation?

### ISSUE THREAD

**Issue by kishoretaru** [mydumper/mydumper#1536]
I looking for some examples on how to validate database backup / dump before restore using mydumper, can you please share required commands for validating database backup.

**Comment by davidducos** [comment]
Hi @kishoretaru, 
it is not possible to validate backup without restoring it. The option that you are looking is -M when you execute mydumper command

**Comment by kishoretaru** [comment]
Thanks @davidducos , this time when i have collected the backup i can see that the checksum also being dumped 

Command -->  mydumper   --host=localhost   --user=root   --password=sample@1   --database=ExampleDB   --outputdir=/root/mydump   --triggers   --events   --routines   --threads=4   --trx-consistency-only   --less-locking   --chunk-filesize=1000   --use-savepoints -M   --verbose=3

Sample Output generated -->  Message: 10:34:22.957: Thread 1: dumping checksum for `ExampleDB`.`ExampleTable`
                                                 Message: 10:34:22.957: Thread 2: dumping checksum for `ExampleDB`.`ExampleTable`

Can you please help how to verify this checksum / backup integrity .

**Comment by davidducos** [comment]
The checksum are being checked during import stage with myloader. At the end, you will see if the checksum passes or not. You can control the behavior either with --checksum
