### ISSUE TITLE
[HELP WANTED] myloader systematically hangs with error Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by vdoyelle** [mydumper/mydumper#1537]
I have many tables to migrate from azure mysql single server (mysql 5.7) to azure mysql flexible server (mysql 8.0).
I use mydumper/muymloader  v0.16.3-3.
Dump succeed.
But when I use myloader, I get systematically this error : 
** (myloader:236887): CRITICAL **: 13:48:52.242: Error connection to database: Can't connect to MySQL server on 'az-p-xxx.mysql.database.azure.com:3306' (111)
./importagatelmollard.sh: line 4: 236887 Trace/breakpoint trap   (core dumped)
The logs ends with 2024-06-20 13:48:52 [WARNING] - Connection 1851 - ERROR 2013: Lost connection to MySQL server during query.
Command line use : 
myloader --host=az-p-xxx.mysql.database.azure.com --user=xxx --password=yyy --directory=/data/$DIR --database=$DB --queries-per-transaction=500 --threads=4 --compress-protocol --verbose=3 -e -L $DB-import-logs.txt -o --max-threads-for-schema-creation=1 #--innodb-optimize-keys=AFTER_IMPORT_ALL_TABLES
I tried with innodb-optimize-keys and without.
Hope that someone cen help me...
Regards

**Comment by davidducos** [comment]
Hi @vdoyelle,
Can you confirm the database is not crashing?

**Comment by davidducos** [comment]
Maybe related to https://github.com/mydumper/mydumper/issues/448

**Comment by vdoyelle** [comment]
Hello David.

Thanks for your feedback.
I confirm that the db did not crashed as I can display data inside.

Regards

 Vincent DOYELLE
Chef de projet Infrastructure/Cloud

Tel. +33(4)79 25 33 47 / Mob +33(6)14 65 02 99
12 Avenue du Lac d'Annecy Savoie Technolac | Campus Chambery | 73081 Le Bourget du Lac
Visitez notre site internet : https://www.omneseducation.com/

De : David Ducos ***@***.***>
Envoyé : jeudi 20 juin 2024 18:30
À : mydumper/mydumper ***@***.***>
Cc : DOYELLE Vincent(A) ***@***.***>; Mention ***@***.***>
Objet : Re: [mydumper/mydumper] [HELP WANTED] myloader systematically hangs with error Lost connection to MySQL server during query (Issue #1537)


Maybe related to #448<https://github.com/mydumper/mydumper/issues/448>

-

**Comment by davidducos** [comment]
Can you ran this command:
```
mysql> show global status like 'uptime';
```
After running myloader? it tells you the uptime in seconds.

**Comment by vdoyelle** [comment]
Hello
Sorry for the delay. Did not see your response while being in holidays.
I managed to get the server logs and saw that in fact the whole server was rebooting each time I got the error.

**Comment by davidducos** [comment]
Hi @vdoyelle, 
Ok, closing this issue then as you might be overloading the server.
