### ISSUE TITLE
[FEATURE REQUEST] Add --source-data to mydumper

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#1541]
**Describe the Feature Request**
Similar to mysqldump, --source-data will include the data to build the replica. 

**Current behaviour**
Currently, we are exporting on the metadata file this info:
```
[master]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
File = binlog.000006
Position = 1446396
Executed_Gtid_Set = 75ebc43a-2cc5-11ef-80f4-0242ac110003:1-196
```

**Expected behavior**
When --source-data=1 is used, we should be printing something like:
```
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
source_log_File = "binlog.000006"
source_log_pos = 1446396
#Executed_Gtid_Set = 75ebc43a-2cc5-11ef-80f4-0242ac110003:1-196
source_host="172.17.0.3"
source_user="root"
source_password="PaSSWoRD"
myloader_exec_reset_slave = 1
myloader_exec_change_master = 1
myloader_exec_start_slave = 1
```
When --source-data=2 is used, we should be printing something like:
```
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
source_log_File = "binlog.000006"
source_log_pos = 1446396
#Executed_Gtid_Set = 75ebc43a-2cc5-11ef-80f4-0242ac110003:1-196
source_host="172.17.0.3"
source_user="root"
source_password="PaSSWoRD"
myloader_exec_reset_slave = 0
myloader_exec_change_master = 0
myloader_exec_start_slave = 0
```

**Comment by davidducos** [comment]
I think that will be better to implement it in this way, so we can have more control on mydumper:
| --source-data | myloader_exec_start_slave | myloader_exec_change_master | myloader_exec_reset_slave |
| -----  |  --------------------------  | -------------------------------  |  --------------------------- |
| 0        | 0                                             | 0                                                     | 0                                              |
| 1         | 0                                             | 0                                                     | 1                                              |
| 2        | 0                                             | 1                                                      | 0                                              |
| 3        | 0                                             | 1                                                      | 1                                               |
| 4        | 1                                              | 0                                                     | 0                                              |
| 5        | 1                                              | 0                                                     | 1                                               |
| 6        | 1                                               | 1                                                     | 0                                              |
| 7        | 1                                               | 1                                                     | 1                                               |

**Comment by reillski** [comment]
Hi @davidducos ,
Do you think it's more beneficial to control replication configuration on the `myloader` side rather than the `mydumper` side? I'm thinking, if a user reuses logical dumps, they may want to control if replication is configured or not on the `myloader` command. Sure they can edit the metadata file, but may be easier just having it configured at load time. `mydumper` can still gather all binlog information at dump time, but whether `myloader_exec_start_slave`, `myloader_exec_change_master` or `myloader_exec_reset_slave` is executed , may be safer to control at load time.
Thanks,
Marc

**Comment by davidducos** [comment]
Hi @reillski,
The idea of --source-data is to have the control when you take a backup to avoid writing the metadata, in case that you are using --stream where you are not able to change the metadata.
If you don't want to change the values of mloader_exec_% variables in the metadata file, then you should not use --source-data, as you will get the coordinates anyways. Just to be clear, --source-data only controls if the commands are going to be executed on myloader side. 
Are you requesting that myloader should implement --source-data, ignoring what the metadata says? as this might be a good idea... now we need to decide if it was your idea or my idea...😁

**Comment by reillski** [comment]
> Are you requesting that myloader should implement --source-data, ignoring what the metadata says? as this might be a good idea... now we need to decide if it was your idea or my idea...😁

Yes, exactly! :) I'm thinking up nightmare scenarios where a user may unintentionally reset or reconfigure a replica due to "unsafe" defaults in a metadata file.(maybe multi tenant ends with/without channels?) Having explicit control on the load side may be a safer option to override. :)

Thanks,
Marc
