### ISSUE TITLE
[BUG] Dump from replica with --no-locks option stop the replication and cannot restart it.

### ISSUE THREAD

**Issue by sarswei** [mydumper/mydumper#1547]
**Describe the bug**
Using mydumper v0.16.3-3 and later version.
When I dump my database with --no-locks option from replica,
the slave SQL thread was killed and not reinitialized.
Using mydumper v0.16.3-2 and executing the same command, 
the slave SQL thread was killed and Slave SQL thread initialized, starting replication.

**To Reproduce**
Command executed:
mydumper -u fusion -p ******** -h ******** -P **** -B test-db -F 100 -t 12 -G -E -R -v 3 --no-locks --skip-tz-utc --complete-insert -o dir/

**Expected behavior**
slave SQL thread was killed and slave SQL thread reinitialized, starting replication.

**Environment (please complete the following information):**
 - OS version: CentOS 7.9
 - MyDumper version: 0.16.3-3

**Comment by davidducos** [comment]
Hi @sarswei, 
Fixed version will be released soon.
