### ISSUE TITLE
[FEATURE REQUEST] nix development environment (and build system)

### ISSUE THREAD

**Issue by michaelglass** [mydumper/mydumper#1559]
**Describe the Feature Request**
I'd like to setup the dev environment using a nix flake. I've done this myself and [updated the nix package](https://github.com/NixOS/nixpkgs/pull/325566) with the latest version, and I'd add some of the work to this repo if y'all were interested in it / didn't think the maintenance burden was annoying.

**Comment by davidducos** [comment]
Hi @michaelglass,
I don't mind to add the Github Actions or CircleCI needed to update the nix package. Please, let me know how to integrate them and I will do.

**Comment by michaelglass** [comment]
I've updated the package on nix's side to automatically update correctly from your github issues, however I wonder if you want me to add a status check / notification / something if changes in this package break the nixpkg update?

**Comment by davidducos** [comment]
@michaelglass,
Can you share the link where I can see if the status of the nixpkg? or the link to the Github action? I want to check how we can check it on MyDumper side...

**Comment by davidducos** [comment]
Hi @michaelglass,
Ok, I will review it. 
Sorry about the docs submodule change, that is the last change releated to submodule that I'm going to do.

**Comment by davidducos** [comment]
@michaelglass,
I'm thinking, why don't we compile mydumper on a nix docker container on MyDumper side? I have a script that builds everything for me, just let me know the docker image and I will do it.

**Comment by michaelglass** [comment]
Don't be sorry! Thank you for mydumper!

What exactly do you want? a docker image from which you can run the `nix-shell maintainers/scripts/update.nix --argstr package mydumper` script?

FWIW nix does its own sandboxing so you could just as easily do it without docker, but happy to help out however I can.

(also if you want to pair a bit on some of the pieces I can always make some free time, especially European mornings.)

**Comment by davidducos** [comment]
Hi @michaelglass, sorry, I have been working on other issues and I was not able to review this anymore. 
I review this issue and you repo, I think that there is no need for me to do anything on my side, as you already did all the hard work. You will need to let me know if there is any issue on your end, so I can fix it on MyDumper, as I don't know if there is any tool that can get the result of the checks on your repo.

**Comment by michaelglass** [comment]
added a github action to check if the nixpkgs update failed just to know when / why it's happening. Feel free to close this (and the PR if you want)

**Comment by michaelglass** [comment]
just a note: ever since https://github.com/NixOS/nixpkgs/pull/325566 was merged, the github action has gone green
https://github.com/mydumper/mydumper/actions/runs/12334843229

**Comment by davidducos** [comment]
Hi @michaelglass I reviewed latest log https://r.ryantm.com/log/mydumper/2024-12-24.log and seems that you are compiling also MyDumper's submodules, there is no need to do that.

**Comment by michaelglass** [comment]
Howdy. If memory serves: It's compiling the docs submodule in order to include the man page and docs

**Comment by davidducos** [comment]
Hi @michaelglass, 
Then you will need the Pythong sphinx_copybutton module on the box to compile it.

**Comment by michaelglass** [comment]
got it working, thanks again!

**Comment by michaelglass** [comment]
(https://github.com/NixOS/nixpkgs/pull/371781/files)

**Comment by michaelglass** [comment]
merged now, should be fixed once the update script is run again. I hope the noise in the CI check is okay!
