### ISSUE TITLE
[BUG] When `SOURCE_AUTO_POSITION = 1`, change master should not include file/pos in `CHANGE MASTER` command

### ISSUE THREAD

**Issue by reillski** [mydumper/mydumper#1585]
**Describe the bug**
When loading a dump with the following metadata, myloader will execute `CHANGE MASTER` with auto position enabled. The `CHANGE MASTER` command will also include the filename and position which is not supported. In MySQL you should use file/pos or auto position.

Metadata file
```
[ec2-user@i-0632fb0841566589e msb_8_0_37]$ cat /home/ec2-user/sandboxes/dump_binlog/metadata
# Started dump at: 2024-08-05 18:58:12
[config]
quote_character = BACKTICK

[myloader_session_variables]
SQL_MODE='NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' /*!40101

[source]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
SOURCE_HOST = "10.0.8.190"
SOURCE_PORT = 8039
SOURCE_USER = "user"
SOURCE_PASSWORD = "password"
SOURCE_LOG_FILE = "binlog.000002"
SOURCE_LOG_POS = 203619680
executed_gtid_set = "00008039-0000-0000-0000-000000008039:1-7730"
SOURCE_SSL = 0
SOURCE_AUTO_POSITION = 1
myloader_exec_reset_replica = 0
myloader_exec_change_source = 1
myloader_exec_start_replica = 1
```

**To Reproduce**
Command executed:
* mydumper with all the parameters
```
~/mydumper/mydumper --user=user --password=password \
--host=10.0.8.190 --port=8039 \
--outputdir=/home/ec2-user/sandboxes/dump_binlog/ \
--threads=10 --chunk-filesize=100 --verbose=3 \
--order-by-primary --csv --load-data \
--database=test --clear --source-data=6
```
* myloader with all the parameters
```
~/mydumper/myloader --user=user --password=password \
--host=10.0.8.190 --port=8037 \
--database=test \
--directory=/home/ec2-user/sandboxes/dump_binlog/ --threads=20 \
--verbose=2 --source-control-command=traditional \
--set-gtid-purged
```

What mydumper and myloader version has been used?
master branch

**Expected behavior**
When `SOURCE_AUTO_POSITION = 1` in metadata file, don't specify binlog file/pos in change master command. 

Example of manually running these commands:
myloader command:
```
mysql [localhost:8037] {msandbox} ((none)) > CHANGE REPLICATION SOURCE TO SOURCE_HOST = "10.0.8.190", SOURCE_PORT = 8039, SOURCE_USER = "user", SOURCE_PASSWORD = "password", SOURCE_LOG_FILE = "binlog.000002", SOURCE_LOG_POS = 203619680, SOURCE_SSL = 0, SOURCE_AUTO_POSITION = 1 FOR CHANNEL '';
ERROR 1776 (HY000): Parameters SOURCE_LOG_FILE, SOURCE_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when SOURCE_AUTO_POSITION is active.
```

Correct command:
```
mysql [localhost:8037] {msandbox} ((none)) > CHANGE REPLICATION SOURCE TO SOURCE_HOST = "10.0.8.190", SOURCE_PORT = 8039, SOURCE_USER = "user", SOURCE_PASSWORD = "password", SOURCE_SSL = 0, SOURCE_AUTO_POSITION = 1 FOR CHANNEL '' ;
Query OK, 0 rows affected, 2 warnings (0.01 sec)
```

**Log**
```
(myloader:50869): GLib-CRITICAL **: 20:05:02.825: g_key_file_get_groups: assertion 'key_file != NULL' failed

** (myloader:50869): WARNING **: 20:05:13.248: Sending CHANGE MASTER: CHANGE REPLICATION SOURCE TO SOURCE_HOST = "10.0.8.190", SOURCE_PORT = 8039, SOURCE_USER = "user", SOURCE_PASSWORD = "password", SOURCE_LOG_FILE = "binlog.000002", SOURCE_LOG_POS = 203619680, SOURCE_SSL = 0, SOURCE_AUTO_POSITION = 1 FOR CHANNEL ''; - ERROR 1776: Parameters SOURCE_LOG_FILE, SOURCE_LOG_POS, RELAY_LOG_FILE and RELAY_LOG_POS cannot be set when SOURCE_AUTO_POSITION is active.

** (myloader:50869): WARNING **: 20:05:13.257: Sending CHANGE MASTER: START REPLICA; - ERROR 1200: The server is not configured as replica; fix in config file or with CHANGE REPLICATION SOURCE TO
```

MySQL general log:
```
2024-08-05T20:05:13.234908Z	   84 Query	RESET MASTER
2024-08-05T20:05:13.246828Z	   84 Query	SET GLOBAL gtid_purged="00008039-0000-0000-0000-000000008039:1-7730"
2024-08-05T20:05:13.248527Z	   84 Query	CHANGE REPLICATION SOURCE TO SOURCE_HOST = '10.0.8.190', SOURCE_USER = 'user', SOURCE_PASSWORD = <secret>, SOURCE_PORT = 8039, SOURCE_LOG_FILE = 'binlog.000002', SOURCE_LOG_POS = 203619680, SOURCE_AUTO_POSITION = 1, SOURCE_SSL = 0 FOR CHANNEL ''
2024-08-05T20:05:13.248663Z	   84 Query	START REPLICA
```

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
see above

Thanks,
Marc

**Comment by davidducos** [comment]
Hi @reillski feel free to test https://github.com/mydumper/mydumper/releases/tag/v0.16.6-2

**Comment by reillski** [comment]
Yes, its now set correctly when dump is taken with `--source_data=31` (think this is the full matrix[1])

```
~/mydumper/mydumper --user=username --password=password --host=10.0.8.190 --port=8039 --outputdir=/home/ec2-user/sandboxes/dump_binlog/ --threads=10 --chunk-filesize=100 --verbose=3 --order-by-primary --csv --load-data --database=test --clear --source-data=31
```

Note I added port to [this line](https://github.com/mydumper/mydumper/blob/0e433a8c930c0cd6abb6c7c29d78aa5807d3b3f4/src/mydumper_working_thread.c#L563) locally
```
       fprintf(file, "#SOURCE_HOST = \"%s\"\n#SOURCE_PORT = \n#SOURCE_USER = \"\"\n#SOURCE_PASSWORD = \"\"\n", hostname);
```
TO:
```
      fprintf(file, "#SOURCE_HOST = \"%s\"\n#SOURCE_PORT =  %d \n#SOURCE_USER = \"\"\n#SOURCE_PASSWORD = \"\"\n", hostname, port);
```

**Resulting metadata:**
```
[source]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
#SOURCE_HOST = "10.0.8.190"
#SOURCE_PORT =  8039
#SOURCE_USER = ""
#SOURCE_PASSWORD = ""
SOURCE_SSL = 1
executed_gtid_set = "00008039-0000-0000-0000-000000008039:1-16476"
SOURCE_AUTO_POSITION = 1
#SOURCE_LOG_FILE = "binlog.000002"
#SOURCE_LOG_POS = 218820510
myloader_exec_reset_replica = 1
myloader_exec_change_source = 1
myloader_exec_start_replica = 1
```

Then I edited & removed comments and edited the following, is there anyway to uncomment as part of the dump?
```
SOURCE_HOST = "10.0.8.190"
SOURCE_PORT =  8039
SOURCE_USER = "username"
SOURCE_PASSWORD = "password"
```

Then load/repl setup was successful!
```
$ myloader --user=username --password=password --host=10.0.8.190 --port=8037 --database=test --directory=/home/ec2-user/sandboxes/dump_binlog/ --threads=20 --verbose=2 --source-control-command=traditional --set-gtid-purged

$ /home/ec2-user/sandboxes/msb_8_0_37/use -e "show slave status\G"
*************************** 1. row ***************************
               Slave_IO_State: Waiting for source to send event
                  Master_Host: 10.0.8.190
                  Master_User: reinvent
                  Master_Port: 8039
                Connect_Retry: 60
              Master_Log_File: binlog.000002
          Read_Master_Log_Pos: 218820510
               Relay_Log_File: i-0632fb0841566589e-relay-bin.000002
                Relay_Log_Pos: 411
        Relay_Master_Log_File: binlog.000002
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 218820510
              Relay_Log_Space: 635
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: Yes
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 1
                  Master_UUID: 00008039-0000-0000-0000-000000008039
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Replica has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set: 00008039-0000-0000-0000-000000008039:1-16476
                Auto_Position: 1
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
       Master_public_key_path:
        Get_master_public_key: 0
            Network_Namespace:
```

General log:
```
2024-08-09T17:34:32.162666Z	  118 Query	RESET MASTER
2024-08-09T17:34:32.175915Z	  118 Query	SET GLOBAL gtid_purged="00008039-0000-0000-0000-000000008039:1-16476"
2024-08-09T17:34:32.177714Z	  118 Query	STOP REPLICA
2024-08-09T17:34:32.177774Z	  118 Query	RESET REPLICA
2024-08-09T17:34:32.178185Z	  118 Query	CHANGE REPLICATION SOURCE TO SOURCE_HOST = '10.0.8.190', SOURCE_USER = 'reinvent', SOURCE_PASSWORD = <secret>, SOURCE_PORT = 8039, SOURCE_AUTO_POSITION = 1, SOURCE_SSL = 1 FOR CHANNEL ''
2024-08-09T17:34:32.195745Z	  118 Query	START REPLICA
```

Thanks @davidducos !

======
[1]
Expanded from https://github.com/mydumper/mydumper/issues/1541#issuecomment-2247808329 , think its right!

| source_data | SOURCE_LOG_FILE | SOURCE_AUTO_POSITION | myloader_exec_start_replica | myloader_exec_change_source | myloader_exec_reset_replica |
|-------------|-----------------|----------------------|-----------------------------|-----------------------------|-----------------------------|
|           0 | Printed         |                    0 |                           0 |                           0 |                           0 |
|           1 | Printed         |                    0 |                           0 |                           0 |                           1 |
|           2 | Printed         |                    0 |                           0 |                           1 |                           0 |
|           3 | Printed         |                    0 |                           0 |                           1 |                           1 |
|           4 | Printed         |                    0 |                           1 |                           0 |                           0 |
|           5 | Printed         |                    0 |                           1 |                           0 |                           1 |
|           6 | Printed         |                    0 |                           1 |                           1 |                           0 |
|           7 | Printed         |                    0 |                           1 |                           1 |                           1 |
|           8 | Printed         |                    0 |                           0 |                           0 |                           0 |
|           9 | Printed         |                    0 |                           0 |                           0 |                           1 |
|          10 | Printed         |                    0 |                           0 |                           1 |                           0 |
|          11 | Printed         |                    0 |                           0 |                           1 |                           1 |
|          12 | Printed         |                    0 |                           1 |                           0 |                           0 |
|          13 | Printed         |                    0 |                           1 |                           0 |                           1 |
|          14 | Printed         |                    0 |                           1 |                           1 |                           0 |
|          15 | Printed         |                    0 |                           1 |                           1 |                           1 |
|          16 | Commented       |                    1 |                           0 |                           0 |                           0 |
|          17 | Commented       |                    1 |                           0 |                           0 |                           1 |
|          18 | Commented       |                    1 |                           0 |                           1 |                           0 |
|          19 | Commented       |                    1 |                           0 |                           1 |                           1 |
|          20 | Commented       |                    1 |                           1 |                           0 |                           0 |
|          21 | Commented       |                    1 |                           1 |                           0 |                           1 |
|          22 | Commented       |                    1 |                           1 |                           1 |                           0 |
|          23 | Commented       |                    1 |                           1 |                           1 |                           1 |
|          24 | Commented       |                    1 |                           0 |                           0 |                           0 |
|          25 | Commented       |                    1 |                           0 |                           0 |                           1 |
|          26 | Commented       |                    1 |                           0 |                           1 |                           0 |
|          27 | Commented       |                    1 |                           0 |                           1 |                           1 |
|          28 | Commented       |                    1 |                           1 |                           0 |                           0 |
|          29 | Commented       |                    1 |                           1 |                           0 |                           1 |
|          30 | Commented       |                    1 |                           1 |                           1 |                           0 |
|          31 | Commented       |                    1 |                           1 |                           1 |                           1 |

**Comment by davidducos** [comment]
Hi @reillski ,
Why don't we add an option on the mydumper.cnf file to set this variables? In that way we don't need to relay on specific setting on mydumper.
On a configuration file that you could use in --defaults-extra-file, we could add the source section and the variables like:
```
[source]
SOURCE_HOST = "10.0.8.190"
SOURCE_PORT =  8039
SOURCE_USER = "username"
SOURCE_PASSWORD = "password"
SOURCE_SSL = 1
SOURCE_AUTO_POSITION = 1
```
which mydumper will load and then it will include on the metadata file.
