### ISSUE TITLE
[BUG] Authentication plugin 'mysql_native_password' cannot be loaded

### ISSUE THREAD

**Issue by im-Amitto** [mydumper/mydumper#1590]
**Describe the bug**
for brew mydumper depends on `mysql-client` which is a 9.0 version and thus there is no `mysql_native_password` with it anymore and myloader fails when trying to access the same.

**To Reproduce**
Command executed:
brew install mydumper

myloader -h <host> -u <user> -p <pwd> -d <path/to/files>

What mydumper and myloader version has been used?
mydumper v0.16.5-1, built against MySQL 9.0.1 with SSL support

**Expected behavior**
Don't looks for the file if we already know it does not exist. If old plugin are still supported then one might need to ship it with mydumper.

**Log**
 Error connection to database: Authentication plugin 'mysql_native_password' cannot be loaded: dlopen(/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so, 0x0002): tried: '/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so' (no such file), '/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so' (no such file)

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**Environment (please complete the following information):**
 - OS X
 - mydumper v0.16.5-1, built against MySQL 9.0.1 with SSL support

**Comment by alextanhongpin** [comment]
how did you solved this?

**Comment by im-Amitto** [comment]
@alextanhongpin You can load the `mysql_native_password` dynamically for 9.0+ or simply use an older version of mysql client. 
In case you are using brew then, below hack should work just fine

```bash
  brew install mysql-client@8.4
  rm -rf /opt/homebrew/opt/mysql-client
  mv /opt/homebrew/opt/mysql-client@8.4 /opt/homebrew/opt/mysql-client
```

It's preferred to load `mysql_native_password` dynamically

**Comment by alextanhongpin** [comment]
@im-Amitto thanks for taking the time to explain the solution. I also faced this error today.
