### ISSUE TITLE
[BUG] daemon mode; snapshot count option not valid

### ISSUE THREAD

**Issue by MikeCockrem** [mydumper/mydumper#1597]
The [documentation](https://mydumper.github.io/mydumper/docs/html/mydumper_usage.html#:~:text=%2DX%2C%20%2D%2Dsnapshot%2Dcount) indicates I can use -X to set the number of snapshots: 

> -X, --snapshot-count
number of snapshots, default 2

however including this option (for me at least) stops mydumper running with the following error: 

> **option parsing failed: Unknown option -X, try --help**

> option parsing failed: Unknown option --snapshot-count, try --help

**Command executed:**
`/bin/mydumper -D -c --build-empty-files --regex '^(Client_)' -u $USER -p $PASS --less-locking --threads=1 -I 30 -X 3 --outputdir=/data/backups/ -L /var/log/mydumper`

**Expected behavior**
I expected I could set the number of backups to keep to a custom value (in my testing, '3')

**Log**
Log file empty (even at -v 3)

**Environment:**
 - OS version: Debian 12 Bookworm.  (Linux debian12 6.10.2-x86_64)
 - MyDumper version:  mydumper 0.10.0, built against MySQL 10.5.8  (Debian package: mydumper 0.10.1-1 amd64 )

This could well be a mistake or misunderstanding on my part, as I'm still getting familiar with this, but please let me know.

**Comment by davidducos** [comment]
Hi @MikeCockrem, you are using a very old version of mydumper. Can you try with a newer one?
