### ISSUE TITLE
[FEATURE REQUEST] I could not understand my loader resume option

### ISSUE THREAD

**Issue by litianzhong** [mydumper/mydumper#1598]
**Describe the Feature Request**
How do I generate the resume file? Do I need to create it manually? 
If we have a lot of tables, and dumper files,  could I use dumper file name instead of table name?
Dose anyone give me some suggestion.

**Current behavior**
Explain what mydumper/myloader is doing. Add parameters if needed.

**Expected behavior**
A clear and concise description of what you expected to happen after implementation.

**Environment**
In some cases this might apply just for some OS or kind of environments.
We need the detailed information about it.

**Additional context**

**Comment by davidducos** [comment]
Hi @litianzhong ,
The resume file is created automatically when you cancel a backup. It is not intended users create it but it is possible. It is a file called resume located in the backup dir with the list (one file per line) of the files that you want to import.

**Comment by litianzhong** [comment]
Thank you for your reply. you mean is that the resume file was created when I manually cancel the load job？ I would like to know if the load job throw an error, the job was stopped automatically, then how to generate the resume file.

**Comment by davidducos** [comment]
Hi @litianzhong,
When you send ctrl+c to myloader, it will ask you if you want to cancel, if you say YES, then it will create the resume file in the backup dir. If the load job throw an error, you will need to manually create the a resume file, as myloader is not able to identify what when wrong and what has been successfully done.

**Comment by litianzhong** [comment]
Thanks a lot, I got it.
