### ISSUE TITLE
Documentation for consistent backups

### ISSUE THREAD

**Issue by bebehei** [mydumper/mydumper#1608]
I want to replace my current `mysqldump` setup with a parallel mydumper/myloader setup. Mainly because the SQL load in disater recovery would be super slow.

The speed seems to be very fine for `mydumper`. But I'm rather worried about the consistency.

As I understand, I'm currently dumping everything in a single thread with `mysqldump ... --single-transaction ...`. Since I only have InnoDB tables in my databases, I can assume a consistent backup, even while writes are hitting the production database.

How is a consistent backup possible with mydumper/myloader? How are the threads consistent in each other?

---

I've read the docs but I did not get enlightened:

[It claims to be consistent](https://github.com/mydumper/mydumper_docs/blob/68a53c70fb394a4550c0507d82356d899920c298/mydumper_usage.rst?plain=1#L21):

> Consistency - maintains snapshot across all threads, provides accurate master and slave log positions, etc

Since it mentions "snapshots" there, the relevant option I can find is [`--snapshot-interval` and `--snapshot-count`](https://github.com/mydumper/mydumper_docs/blob/68a53c70fb394a4550c0507d82356d899920c298/mydumper_usage.rst?plain=1#L389)

> Interval between each dump snapshot (in minutes), requires --daemon, default 60

Which on the other hand requires `--daemon`.

So, do I need to run it as a daemon to have consistency at all?

**Comment by davidducos** [comment]
Hi @bebehei, seems that you are looking for [this documentation](https://github.com/mydumper/mydumper/wiki/Locks).

The snapshot and daemon options is when you want to leave mydumper running in the background. AFAIK, it is not being used very often.

**Comment by davidducos** [comment]
The short answer is yes, we need to fully lock the database for a short period of time to sync all the threads, but there other things to take into account that could make the period of time shorter or larger and options that could be used in case that you are using Percona Server and still get a consistent backup without using FTWRL.

**Comment by davidducos** [comment]
You should find more information in https://mydumper.github.io/mydumper/docs/html/locks.html
