### ISSUE TITLE
Not splitting

### ISSUE THREAD

**Issue by Ciao121** [mydumper/mydumper#1613]
I'm trying to backup a mariadb table (~3.583.540.320 rows) trying to use --rows or --chunk-filesize but the backup is running without creating new files.
Right now, for testing I used --chunk-filesize 5
I'm at 30% and I have 9 files (one for working thread) named
dbname.tablename.00000.sql.gz
dbname.tablename.00001.sql.gz
......
dbname.tablename.00008.sql.gz
and their size is from 53M to 900M (and growing).
Should I expect that when a file reaches Mb (or the value I specify) a new file is created?
What am I missing?

**Comment by davidducos** [comment]
#1613
