### ISSUE TITLE
[BUG] ENCRYPTION keyword in CREATE TABLE breaks myloader for MariaDB entirely

### ISSUE THREAD

**Issue by bashgeek** [mydumper/mydumper#1624]
**Describe the bug**
The change added about 2 weeks ago with #1605 breaks myloader to be used with MariaDB entirely. MariaDB does NOT use the `ENCRYPTION` option, but `ENCRYPTED` (and also `YES/NO` instead of `Y/N`), so the import will fail.

If not possible to detect automatically what version to use, please add an option to disable the ENCRYPTION=N inclusion.

We had to revert back to a previous version for now to get around this bug.

**To Reproduce**
Command executed:
- Use MariaDB (we use 11.4 LTS) and 0.16.7-5, create a dump with mydumper and try to load it again with myloader, no special arguments used

**Log**
** (myloader:11742): WARNING **: 13:41:34.917: Connection 8 - ERROR 1911: Unknown option 'ENCRYPTION'

**Environment (please complete the following information):**
 - OS version: Debian 12.7 amd64
 - MyDumper version: mydumper v0.16.7-5, built against MySQL 8.0.37-29 with SSL support

**Comment by davidducos** [comment]
https://github.com/mydumper/mydumper/pull/1623/commits/ab6b65ae42436a3ed4bdcf9606ed9026cb7f20bc

**Comment by bashgeek** [comment]
Thanks!

**Comment by davidducos** [comment]
Tables which engine is MEMORY doesn't accept the ENCRYPTED option.
```
MariaDB [sakila]> CREATE TABLE IF NOT EXISTS `table_view_1_b`(
    -> `id` int,
    -> `val` int
    -> ) ENGINE=MEMORY ENCRYPTED=NO;
ERROR 1911 (HY000): Unknown option 'ENCRYPTED'
MariaDB [sakila]> CREATE TABLE IF NOT EXISTS `table_view_1_b`( `id` int, `val` int ) ENCRYPTED=NO;
Query OK, 0 rows affected (0.056 sec)
```
