### ISSUE TITLE
[BUG] since v0.16.7-5 - dump on RDS Servless v2 - Error executing SHOW REPLICA STATUS - ERROR 1227: Access denied

### ISSUE THREAD

**Issue by anthosz** [mydumper/mydumper#1626]
**Describe the bug**
During a dump, we have this error: Error executing SHOW REPLICA STATUS - ERROR 1227: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation (we don't use replica, all is managed dynamically by AWS)

It worked with v0.16.7-4

**To Reproduce**
Command executed:
mydumper --threads 8 --dirty --exit-if-broken-table-found --defaults-extra-file=${CONFILE} --disk-limits '500:800' --skip-definer --compress ZSTD --trx-consistency-only --lock-all-tables --verbose 2 --outputdir tmp/

What mydumper and myloader version has been used?
v0.16.7-5

**Expected behavior**
Dump works

**Log**
** (mydumper:47): CRITICAL **: 12:20:20.384: Error executing SHOW REPLICA STATUS - ERROR 1227: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation

**Environment (please complete the following information):**
 - OS version: bottlerocket via EKS
 - DB: RDS Servless V2 (Mysql v8.0)
 - MyDumper version: v0.16.7-5

**Comment by anthosz** [comment]
I guess it's related to https://github.com/mydumper/mydumper/pull/1612

I tried to use --source-control-command and both options fail:

- AWS: SHOW SLAVE STATUS - ERROR 1227
- TRADITIONNAL: SHOW REPLICA STATUS - ERROR 1227

There is a way to disable replica management?

**Comment by davidducos** [comment]
Hi @anthosz, can you grant `REPLICATION CLIENT` to the user that you are using to take backups?

**Comment by davidducos** [comment]
We could add an option like --skip-replica-info, but currently there is nothing like that.

**Comment by davidducos** [comment]
Hi @anthosz ,
Now, you can use --source-data=-1 to skip the replica info

**Comment by anthosz** [comment]
Thank you very much @davidducos , so fast!

Granting replication client was not really an option on my side (because we don't use it in fact)

**Comment by davidducos** [comment]
@anthosz prerelease v0.16.8-1 will be published soon.

**Comment by anthosz** [comment]
> @anthosz prerelease v0.16.8-1 will be published soon.

Confirmed, it works! thank you!

**Comment by lkraav** [comment]
> Hi [@anthosz](https://github.com/anthosz) , Now, you can use --source-data=-1 to skip the replica info

Mid-2025: thanks, this also worked in 0.18.2.7.
