### ISSUE TITLE
[FEATURE REQUEST] Checksums for release files

### ISSUE THREAD

**Issue by kepi** [mydumper/mydumper#1629]
**Describe the Feature Request**
In older versions, there where always checksums for release files. It would be great to have them back.

**Current behavior**
There are no checksums for released files.

**Expected behavior**
To have checksums for every file in release.

**Environment**
not relevant

I tried to dig through issues and didn't find any reason for removing them. I suppose maybe different tooling. It would be ofc great to have checksums on different site then github so there is better protection against potential repo manipulation.

Thanks for considering.

**Comment by davidducos** [comment]
Hi @kepi,
We changed how we were creating the packages, that is why you are not seeing the checksums of the file. Nowadays, we are signing the packages, more info in: https://github.com/mydumper/mydumper_repo
I will review if we can easily add the checksum back.

**Comment by davidducos** [comment]
We should be adding -b to ghr according to https://github.com/tcnksm/ghr on https://github.com/mydumper/mydumper/blob/master/.circleci/circleci_config_builder.sh#L562
