### ISSUE TITLE
Add min and max chunk detection when `--rows` is used

### ISSUE THREAD

**Issue by zyoneg** [mydumper/mydumper#1641]
Hi, @davidducos ,I found that I cannot skip gap data that does not exist in the table when exporting data using mydumper  I have a table named t1, in which id is the primary key, and 1-1000000 are all continuous and valid data. Then I insert a piece of data with the id 1843931943963660289 and execute mydumper to export it. Then I found that mydumper was executing some useless selects.

```shell
MySQL [test1]> show create table t1;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `id` bigint NOT NULL,
  `name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test1]> select * from t1 where id >= 1000000;
+---------------------+------------+
| id                  | name       |
+---------------------+------------+
|             1000000 | 7DF2FY60H2 |
| 1843931943963660289 | hello      |
+---------------------+------------+
2 rows in set (0.00 sec)

```

And I found that mydumper was doing these queries:

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/cf147832-f6c9-484c-a1df-cbba56ed02eb">

Command executed:
```shell
./mydumper  -h 127.0.0.1 -P 3306 -u user -p password -T test1.t1 -o ./backup  --rows 1000:1000:10000 -v 3 -L ./mydumper.log
```

Mydumper version:

`mydumper v0.16.8-2, built against MySQL 5.7.40 with SSL support`

If you need any other information, please get in touch with me. Thanks!

**Comment by davidducos** [comment]
Hi @zyoneg, the latest versions of mydumper automatically configure `--rows` and increases exponentially the chunk size reducing the amount of SELECTs. You are forcing the max chunk size to 10000 causing the issue that you are reporting. 
The option `--rows` should be used if you want specific chunk size as we removed the automatic min and max detection. 

Oh! now that I'm thinking it, we could add it if `--rows` is used.

**Comment by davidducos** [comment]
Take into account that the automatic detection will be triggered only if the chunk is splitted, which means that if `--max-threads-per-table` is set to 1, then the chunk will not be splitted.

**Comment by zyoneg** [comment]
In my application scenario, I need to use the `--rows` parameter, so how can I skip the empty data after 1000000 when using `--rows`? I tried using `--max-threads-per-table` but it doesn't solve my problem.

**Comment by zyoneg** [comment]
Ok, thanks for the fix, and you!
