### ISSUE TITLE
[BUG] mydumper core dumped randomly

### ISSUE THREAD

**Issue by darkelf21cn** [mydumper/mydumper#1647]
**Describe the bug**

mydumper randomly core dumped on the same instance with same backup arguments. The failure rate is about 1 of 3 without any pattern that I can follow. Sometimes it fails in several seconds just after the backup command was issued and sometimes it happens minutes later.

**To Reproduce**
Command executed:

```bash
mydumper --user user --password pass -v 4 -B nsfocus -K -G -E -R --hex-blob --skip-definer -o ${BASE_DIR}/output/ --clear -c
```

What mydumper and myloader version has been used?

```bash
root@db:/data/backup# mydumper --version
mydumper v0.16.7-5, built against MySQL 8.4.2 with SSL support
root@db:/data/backup# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
mysql> select @@version;
+-------------------------+
| @@version               |
+-------------------------+
| 8.0.39-0ubuntu0.24.04.2 |
+-------------------------+
1 row in set (0.00 sec)
```

**Core dump file**
[core-mydumper.107894.db.1729240484.zip](https://github.com/user-attachments/files/17431838/core-mydumper.107894.db.1729240484.zip)

**Comment by davidducos** [comment]
Hi @darkelf21cn, 
Can you test with the latest prerelease? I think that this is related to https://github.com/mydumper/mydumper/pull/1643
