### ISSUE TITLE
[BUG] Ubuntu install command not working

### ISSUE THREAD

**Issue by ylluminate** [mydumper/mydumper#1652]
I use Zsh and while that might be part of the problem, even fixing it for that doesn't seem to resolve the issue, so I've modified it a bit more to work with the GitHub releases better so that you might update the command you suggest in the readme:
```
release=$(curl -Ls -o /dev/null -w '%{url_effective}' https://github.com/mydumper/mydumper/releases/latest | cut -d'/' -f8)
deb_url=$(curl -s https://api.github.com/repos/mydumper/mydumper/releases/tags/${release} \
  | grep -oP '"browser_download_url": "\K[^"]*' \
  | grep "$(lsb_release -cs)_amd64.deb")

curl -LO "$deb_url" && sudo dpkg -i "$(basename "$deb_url")"
```

**Comment by davidducos** [comment]
Hi @ylluminate, 
please, review the latest documentation https://mydumper.github.io/mydumper/docs/html/installing.html
