### ISSUE TITLE
[BUG] mydumper g_rand_int_range: assertion failed 'end > begin' failed when single value in file

### ISSUE THREAD

**Issue by flamein** [mydumper/mydumper#1654]
**Describe the bug**
When using random_format to replace a field with a single 'fake' in username.txt, mydumper throws `(mydumper:608883): GLib-CRITICAL **: 08:52:54.512: g_rand_int_range: assertion 'end > begin' failed`
but column values get replaced with `fake`

The same happens with this username.txt
```
1
2
3
4
```
but in this case, it does seem to use random numbers in the dump

when using:
```
fake
fake1
fake2
```
The GLib-CRITICAL error disappears, but these remain:

```
free(): invalid pointer
Aborted (core dumped)
```
but all column values are `fake`

**To Reproduce**
Command executed:
```
root@hostname:~# cat randomise.cnf
[`database`.`data`]
`date`=random_format <file username.txt>

root@hostname:~# cat username.txt
fake
```

command:
```
root@hostname:~# rm -rf dump; mydumper --csv -h 127.0.0.1 -u root -a -o dump --defaults-extra-file=randomise.cnf
Enter MySQL Password:

(mydumper:610205): GLib-CRITICAL **: 09:26:07.848: g_rand_int_range: assertion 'end > begin' failed

(mydumper:610205): GLib-CRITICAL **: 09:26:07.849: g_rand_int_range: assertion 'end > begin' failed

(mydumper:610205): GLib-CRITICAL **: 09:26:07.849: g_rand_int_range: assertion 'end > begin' failed

(mydumper:610205): GLib-CRITICAL **: 09:26:07.849: g_rand_int_range: assertion 'end > begin' failed

(mydumper:610205): GLib-CRITICAL **: 09:26:07.849: g_rand_int_range: assertion 'end > begin' failed
....

free(): invalid pointer
Aborted (core dumped)
```

result for files, first 10, but the full file has no other values than `fake`:
```
root@hostname:~# head -n10  dump/database.data.00000.dat
"fake"
"fake"
"fake"
"fake"
"fake"
"fake"
"fake"
"fake"
"fake"
"fake"
```

What mydumper and myloader version has been used?
```
root@hostname:~# mydumper --version
mydumper v0.16.7-5, built against MySQL 8.0.37-29 with SSL support
```

**Expected behavior**
The date column being replaced with line from username.txt

**Log**
file attached 

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
single date column with some dates in there

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
 ```
 root@hostname:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
 
 - MyDumper version: [ mydumper --version ]
```
root@hostname:~# mydumper --version
mydumper v0.16.7-5, built against MySQL 8.0.37-29 with SSL support
```

**Additional context**

**Comment by davidducos** [comment]
Hi @flamein ,
Thanks for reporting this bug and for using masquerade, as it is a interesting use case that I don't see the community to use it very often. Let me know if you want me to package a prerelease for you! 
Best regards
