### ISSUE TITLE
[BUG] Apt package versioning breaks packages

### ISSUE THREAD

**Issue by saz** [mydumper/mydumper#1657]
**Describe the bug**
Installing `mydumper` via APT repo fails to install the proper version, as versions include the distro codename:
```
0.16.7-5~bookworm
0.16.7-5~buster
```

Due to alphabetic sorting, APT sees `buster` newer as `bookworm`.

Installing the matching package with `apt install mydumper=0.16.7-5~bookworm` will do a downgrade of the package:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be DOWNGRADED:
  mydumper
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
Need to get 1,727 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 https://mydumper.github.io/mydumper/repo/apt/debian ./ mydumper 0.16.7-5~bookworm [1,727 kB]
Fetched 1,727 kB in 0s (6,740 kB/s)
dpkg: warning: downgrading mydumper from 0.16.7-5~buster to 0.16.7-5~bookworm
(Reading database ... 69895 files and directories currently installed.)
Preparing to unpack .../mydumper_0.16.7-5~bookworm_amd64.deb ...
Unpacking mydumper (0.16.7-5~bookworm) over (0.16.7-5~buster) ...
Setting up mydumper (0.16.7-5~bookworm) ...
```

**To Reproduce**
* add APT repo on Debian Bookworm
* apt install mydumper
* apt --installed list|grep mydump

The last command will result in the following output:
```
mydumper/unknown,now 0.16.7-5~buster amd64 [installed]
```

**Expected behavior**
The proper package will be installed depending on the distro release:
```
bookworm => 0.16.7-5~bookworm
buster => 0.16.7-5~buster
```

**Comment by davidducos** [comment]
I think that this is related to https://github.com/mydumper/mydumper_repo/issues/1

**Comment by davidducos** [comment]
Hi @saz, no worries! that is a relative new repository and that was the first issue... I will be working on this and let you know when I fix it

**Comment by saz** [comment]
@davidducos Looks like the apt sources.list must be changed:
```
deb [signed-by=/etc/apt/keyrings/mydumper.asc] https://mydumper.github.io/mydumper/repo/apt/debian/bookworm  ./
```
