### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by flamein** [mydumper/mydumper#1670]
**Describe the bug**

Thanks for the fix for the `free` in #1654, that seems to be fixed now.

I still see the problem with regard to the fakes though, I might have misunderstood the format for the file though.

**To Reproduce**

```
root@hostname:~# cat fakes.txt
fake
fake1
fake2
```
```
root@hostname:~# cat randomise.cnf
[`legacy_microservice_development`.`data`]
`date`=random_format <file fakes.txt>
```
output from `rm -rf dump; mydumper --verbose 3 -L log --csv -B legacy_microservice_development -h hostname -u root -a -o dump --defaults-extra-file=randomise.cnf`
```
root@hostname:~# cat dump/legacy_microservice_development.data.00000.dat
"fake"
"fake"
"fake"
"fake"
"fake"
"fake"
"fake"
....
```

What mydumper and myloader version has been used?

root@gc-dev-legacy-microservice-db1:~# mydumper --version
mydumper v0.16.9-1, built against MySQL 8.0.39-30 with SSL support

**Expected behavior**
I would expect a semi-random replacement of the date column with the options from fakes.txt

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
just a single column with a bunch of datetime data

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04
 - MyDumper version: v0.16.9-1

**Additional context**

**Comment by flamein** [comment]
some more tests:
```
root@hostname:~# cat fakes.txt
fake
faker
fakest

root@hostname:~# cat randomise.cnf
[`legacy_microservice_development`.`data`]
`date`=random_format <file fakes.txt>

root@hostname:~# rm -rf dump; mydumper --verbose 3 -L log --csv -B legacy_microservice_development -h 10.25.0.22 -u root -a -o dump --defaults-extra-file=randomise.cnf
Enter MySQL Password:
root@hostname:~# sort dump/legacy_microservice_development.data.00000.dat | uniq -c
    146 "fake"
    144 "faker"
```

and this:
```
root@hostname:~# cat fakes.txt
fake
faker
fakest
fakestest

root@hostname:~# rm -rf dump; mydumper --verbose 3 -L log --csv -B legacy_microservice_development -h 10.25.0.22 -u root -a -o dump --defaults-extra-file=randomise.cnf
Enter MySQL Password:

** (mydumper:664483): ERROR **: 15:50:37.952: The file file fakes.txt shouldn't have gaps: 15 | 4 | 9
Trace/breakpoint trap (core dumped)
root@hostname:~#
```

**Comment by davidducos** [comment]
Hi @flamein, 
Columns will be replaced with the words of the same size that are found in the file, this means that if you column date has only strings of size 4, the only word in your file that fit is "fake"
The fakes.txt file must not contain empty lines.

**Comment by flamein** [comment]
But it's date time columns in the database and it's dumping to CSV... So not sure how this selected only 2 out of the 3 options.

**Comment by davidducos** [comment]
Hi @flamein 
https://github.com/mydumper/mydumper/issues/1670#issuecomment-2486572886 is the most incorrect comment that I have written in this repository. Apologize! 

The file must contain all the string length between the min length and the max length, in your example, you are missing string length 7 and 8, which means that this:
```
root@hostname:~# cat fakes.txt
fake
faker
fakest
fakeste
fakestes
fakestest
```
must work.
I will be pushing a PR shortly
