### ISSUE TITLE
[BUG] After upgrading to the latest version, it became very slow and almost stuck!

### ISSUE THREAD

**Issue by designinlife** [mydumper/mydumper#1688]
**Describe the bug**
After upgrading the version, the mydumper backup process became stuck.
When I used *v0.16.7-5* version, everything was normal.

**To Reproduce**
Command executed:
/usr/bin/mydumper --defaults-extra-file=/usr/local/etc/mydumper.cnf --regex '^(?!(mysql\.|sys\.|test\.|information_schema\.|performance_schema\.))' -o /data/backup/mydumper/

What mydumper and myloader version has been used?

**Expected behavior**
It should finish in less than 10 seconds, but now it is very slow! It seems to be stuck. However, SHOW PROCESSLIST still shows that the SELECT statement is executing.

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
Or upload a [core dump](https://github.com/mydumper/mydumper/wiki/Support#core-dump) for cases where mydumper or myloader is crashing.

**Environment (please complete the following information):**
 - OS version: AlmaLinux 8.10
 - MyDumper version: v0.16.11-2

**Additional context**

**Config**

```conf
[mydumper]
host = 127.0.0.1
port = 3306
user = root
password = 123456
rows = 10000

[myloader]
host = 127.0.0.1
port = 3306
user = root
password = 123456
innodb-optimize-keys = AFTER_IMPORT_PER_TABLE

[mydumper_session_variables]
wait_timeout = 300
# sql_mode = ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

[mydumper_global_variables]
sync_binlog = 0
slow_query_log = OFF

[myloader_session_variables]
long_query_time = 300

[myloader_global_variables]
sync_binlog = 0
innodb_flush_log_at_trx_commit = 0
```

**Comment by davidducos** [comment]
Hi @designinlife , Can you share the SELECTs that you see in the processlist and the CREATE TABLE of the table that is in the processlist?

**Comment by designinlife** [comment]
I just upgraded again from v0.16.7-5 to v0.16.11-2 and added the mydumper -v 3 parameter and it works fine again. @davidducos

**Comment by davidducos** [comment]
Yes! the best is to use the latest release.
