### ISSUE TITLE
[BUG] Mydumper configures multiple threads but only 1 thread is executed during data dump

### ISSUE THREAD

**Issue by bac-nt** [mydumper/mydumper#1691]
Describe the bug
I run mydumper with `--stream` mode and I configure `--threads 10` but when I check the log I find that there is only 1 thread running at a time.

Command executed:

`mydumper --threads 10 --host HOST --user USER --password PASS --trx-consistency-only --verbose 3 --no-locks --debug --rows 10000:50000:500000 --outputdir data/backup --logfile data/backup.log --stream NO_DELETE | myloader --threads 10 --host HOST_DES --user USER_DES --password PASS_DES --verbose 3 --debug --disable-redo-log --directory data/restore --logfile data/restore.log --overwrite-unsafe --stream NO_DELETE`

What mydumper and myloader version has been used?

used version: `v0.16.11-2`
working version: v`0.15.1-1` all works fine while I use this version.

Expected behavior
run with the correct number of configured threads

Environment (please complete the following information):

OS version: `Ubuntu - 24.04 LTS (Noble Numbat)`
MyDumper version: `v0.16.11-2`

log is being written sequentially in stream

> 2024-12-06 14:46:48 [INFO] - testdb8.sbtest26 has ~961055 rows
> 2024-12-06 14:46:48 [DEBUG] - [0x5847c98f3b50] Integer PK found on `testdb8`.`sbtest26`
> 2024-12-06 14:46:48 [INFO] - Thread 8: `testdb8`.`sbtest26` [ 0% ] | Tables: 308/454
> 2024-12-06 14:46:49 [INFO] - Thread 8: `testdb8`.`sbtest26` [ 5% ] | Tables: 308/454
> 2024-12-06 14:46:49 [INFO] - Thread 8: `testdb8`.`sbtest26` [ 15% ] | Tables: 308/454
> 2024-12-06 14:46:49 [INFO] - Thread 8: `testdb8`.`sbtest26` [ 36% ] | Tables: 308/454
> 2024-12-06 14:46:51 [INFO] - Thread 8: `testdb8`.`sbtest26` [ 78% ] | Tables: 308/454
> 2024-12-06 14:46:53 [INFO] - File data/backup/testdb8.sbtest3.00000.sql transferred in 4 seconds at 22 MB/s | Global: 18 MB/s
> 2024-12-06 14:46:53 [DEBUG] - [0x5847c9875e70] Streaming data/backup/testdb8.sbtest3.00001.sql
> 2024-12-06 14:46:53 [INFO] - testdb8.sbtest21 has ~987165 rows
> 2024-12-06 14:46:53 [DEBUG] - [0x5847c98f4940] Integer PK found on `testdb8`.`sbtest21`
> 2024-12-06 14:46:53 [INFO] - Thread 6: `testdb8`.`sbtest21` [ 0% ] | Tables: 307/454
> 2024-12-06 14:46:53 [INFO] - Thread 6: `testdb8`.`sbtest21` [ 5% ] | Tables: 307/454
> 2024-12-06 14:46:53 [INFO] - Thread 6: `testdb8`.`sbtest21` [ 15% ] | Tables: 307/454
> 2024-12-06 14:46:54 [INFO] - Thread 6: `testdb8`.`sbtest21` [ 35% ] | Tables: 307/454
> 2024-12-06 14:46:55 [INFO] - Thread 6: `testdb8`.`sbtest21` [ 75% ] | Tables: 307/454
> 2024-12-06 14:46:56 [INFO] - File data/backup/testdb8.sbtest3.00001.sql transferred in 3 seconds at 27 MB/s | Global: 18 MB/s
> 2024-12-06 14:46:56 [DEBUG] - [0x5847c9875e70] Streaming data/backup/testdb8.sbtest6.00000.sql
> 2024-12-06 14:46:56 [INFO] - testdb8.sbtest25 has ~986400 rows
> 2024-12-06 14:46:56 [DEBUG] - [0x5847c98e7a20] Integer PK found on `testdb8`.`sbtest25`
> 2024-12-06 14:46:56 [INFO] - Thread 2: `testdb8`.`sbtest25` [ 0% ] | Tables: 306/454
> 2024-12-06 14:46:57 [INFO] - Thread 2: `testdb8`.`sbtest25` [ 5% ] | Tables: 306/454
> 2024-12-06 14:46:57 [INFO] - Thread 2: `testdb8`.`sbtest25` [ 15% ] | Tables: 306/454
> 2024-12-06 14:46:57 [INFO] - Thread 2: `testdb8`.`sbtest25` [ 35% ] | Tables: 306/454
> 2024-12-06 14:46:59 [INFO] - Thread 2: `testdb8`.`sbtest25` [ 76% ] | Tables: 306/454
> 2024-12-06 14:47:01 [INFO] - File data/backup/testdb8.sbtest6.00000.sql transferred in 4 seconds at 25 MB/s | Global: 18 MB/s
> 2024-12-06 14:47:01 [DEBUG] - [0x5847c9875e70] Streaming data/backup/testdb8.sbtest6.00001.sql
> 2024-12-06 14:47:01 [INFO] - testdb8.sbtest23 has ~987628 rows
> 2024-12-06 14:47:01 [DEBUG] - [0x5847c98e70b0] Integer PK found on `testdb8`.`sbtest23`
> 2024-12-06 14:47:01 [INFO] - Thread 1: `testdb8`.`sbtest23` [ 0% ] | Tables: 305/454
> 2024-12-06 14:47:01 [INFO] - Thread 1: `testdb8`.`sbtest23` [ 5% ] | Tables: 305/454
> 2024-12-06 14:47:02 [INFO] - Thread 1: `testdb8`.`sbtest23` [ 15% ] | Tables: 305/454
> 2024-12-06 14:47:02 [INFO] - Thread 1: `testdb8`.`sbtest23` [ 35% ] | Tables: 305/454
> 2024-12-06 14:47:03 [INFO] - Thread 1: `testdb8`.`sbtest23` [ 75% ] | Tables: 305/454
> 2024-12-06 14:47:05 [INFO] - File data/backup/testdb8.sbtest6.00001.sql transferred in 4 seconds at 22 MB/s | Global: 18 MB/s
> 2024-12-06 14:47:05 [DEBUG] - [0x5847c9875e70] Streaming data/backup/testdb8.sbtest29.00000.sql
> 2024-12-06 14:47:05 [INFO] - testdb8.sbtest2 has ~986993 rows
> 2024-12-06 14:47:05 [DEBUG] - [0x5847c98f5260] Integer PK found on `testdb8`.`sbtest2`
> 2024-12-06 14:47:05 [INFO] - Thread 10: `testdb8`.`sbtest2` [ 0% ] | Tables: 304/454
> 2024-12-06 14:47:06 [INFO] - Thread 10: `testdb8`.`sbtest2` [ 5% ] | Tables: 304/454
> 2024-12-06 14:47:06 [INFO] - Thread 10: `testdb8`.`sbtest2` [ 15% ] | Tables: 304/454
> 2024-12-06 14:47:07 [INFO] - Thread 10: `testdb8`.`sbtest2` [ 35% ] | Tables: 304/454
> 2024-12-06 14:47:08 [INFO] - Thread 10: `testdb8`.`sbtest2` [ 75% ] | Tables: 304/454

**Comment by davidducos** [comment]
Hi @bac-nt 
I prepared a sysbech environment like yours with this command on a Nobel container:
```
./src/sysbench /usr/share/sysbench/oltp_read_write.lua --table-size=1000000 --tables=4 --mysql-user=root --threads=4 --mysql-host=172.17.0.5 prepare
```
And then run this command:
```
./mydumper -B sbtest --threads 10 --trx-consistency-only --verbose 3 --no-locks --debug --rows 10000:50000:500000 --outputdir data --logfile backup.log --stream NO_DELETE --clear > data.sql
```
Over a cloned repository from master, and the log shows:
```
2024-12-07 14:04:40 [INFO] - Thread 10: `sbtest`.`sbtest1` [ 0% ] | Tables: 4/4
2024-12-07 14:04:40 [INFO] - Thread 7: `sbtest`.`sbtest1` [ 0% ] | Tables: 4/4
2024-12-07 14:04:40 [INFO] - Thread 2: `sbtest`.`sbtest1` [ 0% ] | Tables: 4/4
2024-12-07 14:04:40 [INFO] - Thread 5: `sbtest`.`sbtest1` [ 0% ] | Tables: 4/4
```
I have 4 tables and 4 threads, but if I set 2 threads I get:
```
2024-12-07 14:13:21 [INFO] - Thread 1: `sbtest`.`sbtest3` [ 0% ] | Tables: 4/4
2024-12-07 14:13:21 [INFO] - Thread 2: `sbtest`.`sbtest3` [ 0% ] | Tables: 4/4
2024-12-07 14:13:21 [INFO] - Thread 1: `sbtest`.`sbtest3` [ 8% ] | Tables: 4/4
2024-12-07 14:13:21 [INFO] - Thread 2: `sbtest`.`sbtest3` [ 11% ] | Tables: 4/4
2024-12-07 14:13:21 [INFO] - Thread 1: `sbtest`.`sbtest3` [ 27% ] | Tables: 4/4
2024-12-07 14:13:21 [INFO] - Thread 2: `sbtest`.`sbtest3` [ 32% ] | Tables: 4/4
```
If I set back to threads 4 and I add --max-threads-per-table 1, I get:
```
2024-12-07 14:11:47 [INFO] - Thread 8: `sbtest`.`sbtest2` [ 0% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 10: `sbtest`.`sbtest4` [ 0% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 3: `sbtest`.`sbtest3` [ 0% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 10: `sbtest`.`sbtest4` [ 5% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 7: `sbtest`.`sbtest1` [ 5% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 3: `sbtest`.`sbtest3` [ 5% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 8: `sbtest`.`sbtest2` [ 5% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 10: `sbtest`.`sbtest4` [ 15% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 3: `sbtest`.`sbtest3` [ 15% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 7: `sbtest`.`sbtest1` [ 15% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 8: `sbtest`.`sbtest2` [ 15% ] | Tables: 4/4
2024-12-07 14:11:47 [INFO] - Thread 10: `sbtest`.`sbtest4` [ 35% ] | Tables: 4/4
2024-12-07 14:11:48 [INFO] - Thread 3: `sbtest`.`sbtest3` [ 35% ] | Tables: 4/4
2024-12-07 14:11:48 [INFO] - Thread 7: `sbtest`.`sbtest1` [ 35% ] | Tables: 4/4
2024-12-07 14:11:48 [INFO] - Thread 8: `sbtest`.`sbtest2` [ 35% ] | Tables: 4/4
2024-12-07 14:11:48 [INFO] - Thread 10: `sbtest`.`sbtest4` [ 76% ] | Tables: 4/4
2024-12-07 14:11:48 [INFO] - Thread 3: `sbtest`.`sbtest3` [ 76% ] | Tables: 4/4
2024-12-07 14:11:48 [INFO] - Thread 7: `sbtest`.`sbtest1` [ 76% ] | Tables: 4/4
2024-12-07 14:11:48 [INFO] - Thread 8: `sbtest`.`sbtest2` [ 76% ] | Tables: 4/4
```
Can you test again with `-v 4` or `--verbose=4` ??

**Comment by bac-nt** [comment]
When running --stream with myloader there will be only 1 thread of execution
Please run exactly as I command:
`mydumper --threads 10 --host HOST --user USER --password PASS --trx-consistency-only --verbose 3 --no-locks --debug --rows 10000:50000:500000 --outputdir data/backup --logfile data/backup.log --stream NO_DELETE | myloader --threads 10 --host HOST_DES --user USER_DES --password PASS_DES --verbose 3 --debug --disable-redo-log --directory data/restore --logfile data/restore.log --overwrite-unsafe --stream NO_DELETE`

**Comment by bac-nt** [comment]
If I run separate commands, it can still be multi-threaded. 
Is there a way for me to execute both mydumper and myloader at the same time instead of my command?
my command: `mydumper --threads 10 --host HOST --user USER --password PASS --trx-consistency-only --verbose 3 --no-locks --debug --rows 10000:50000:500000 --outputdir data/backup --logfile data/backup.log --stream NO_DELETE | myloader --threads 10 --host HOST_DES --user USER_DES --password PASS_DES --verbose 3 --debug --disable-redo-log --directory data/restore --logfile data/restore.log --overwrite-unsafe --stream NO_DELETE`

**Comment by bac-nt** [comment]
Hi @davidducos,
I did it your way and mydumper did multithreading however Myloader only does 1 sequential thread when restoring right?
`myloader --threads 15 --max-threads-per-table 15 --host HOST --user USER --password PASS --verbose 3 --disable-redo-log --directory data/restore --logfile data/restore.log --overwrite-unsafe --stream NO_DELETE < backup.sql`

Myloader log:
> 2024-12-09 14:23:38 [INFO] - Reading metadata: metadata.partial.23
> 2024-12-09 14:23:48 [INFO] - Thread 4: restoring testdb8.sbtest6 part 1 of 1 from testdb8.sbtest6.00000.sql | Progress 34 of 34. Tables 0 of 354 completed
> 2024-12-09 14:23:57 [INFO] - Thread 5: restoring testdb8.sbtest5 part 1 of 1 from testdb8.sbtest5.00000.sql | Progress 35 of 35. Tables 0 of 354 completed
> 2024-12-09 14:23:57 [INFO] - Reading metadata: metadata.partial.24
> 2024-12-09 14:24:06 [INFO] - Thread 6: restoring testdb8.sbtest4 part 1 of 1 from testdb8.sbtest4.00000.sql | Progress 36 of 36. Tables 0 of 354 completed
> 2024-12-09 14:24:16 [INFO] - Thread 7: restoring testdb8.sbtest30 part 1 of 1 from testdb8.sbtest30.00000.sql | Progress 37 of 37. Tables 0 of 354 completed
> 2024-12-09 14:24:16 [INFO] - Reading metadata: metadata.partial.25
> 2024-12-09 14:24:25 [INFO] - Thread 8: restoring testdb8.sbtest3 part 1 of 1 from testdb8.sbtest3.00000.sql | Progress 38 of 38. Tables 0 of 354 completed
> 2024-12-09 14:24:34 [INFO] - Thread 9: restoring testdb8.sbtest29 part 1 of 1 from testdb8.sbtest29.00000.sql | Progress 39 of 39. Tables 0 of 354 completed
> 2024-12-09 14:24:34 [INFO] - Reading metadata: metadata.partial.26
> 2024-12-09 14:24:44 [INFO] - Thread 10: restoring testdb8.sbtest28 part 1 of 1 from testdb8.sbtest28.00000.sql | Progress 40 of 40. Tables 0 of 354 completed
> 2024-12-09 14:24:44 [INFO] - Reading metadata: metadata.partial.27
> 2024-12-09 14:24:53 [INFO] - Reading metadata: metadata.partial.28
> 2024-12-09 14:24:53 [INFO] - Thread 11: restoring testdb8.sbtest27 part 1 of 1 from testdb8.sbtest27.00000.sql | Progress 41 of 41. Tables 0 of 354 completed
> 2024-12-09 14:25:02 [INFO] - Thread 12: restoring testdb8.sbtest26 part 1 of 1 from testdb8.sbtest26.00000.sql | Progress 42 of 42. Tables 0 of 354 completed
> 2024-12-09 14:25:12 [INFO] - Reading metadata: metadata.partial.29
> 2024-12-09 14:25:12 [INFO] - Thread 13: restoring testdb8.sbtest25 part 1 of 1 from testdb8.sbtest25.00000.sql | Progress 43 of 43. Tables 0 of 354 completed
> 2024-12-09 14:25:12 [INFO] - Reading metadata: metadata.partial.30
> 2024-12-09 14:25:21 [INFO] - Thread 14: restoring testdb8.sbtest24 part 1 of 1 from testdb8.sbtest24.00000.sql | Progress 44 of 44. Tables 0 of 354 completed
> 2024-12-09 14:25:30 [INFO] - Reading metadata: metadata.partial.31
> 2024-12-09 14:25:30 [INFO] - Thread 15: restoring testdb8.sbtest23 part 1 of 1 from testdb8.sbtest23.00000.sql | Progress 45 of 45. Tables 0 of 354 completed
> 2024-12-09 14:25:39 [INFO] - Reading metadata: metadata.partial.32
> 2024-12-09 14:25:39 [INFO] - Thread 2: restoring testdb8.sbtest22 part 1 of 1 from testdb8.sbtest22.00000.sql | Progress 46 of 46. Tables 0 of 354 completed
> 2024-12-09 14:25:49 [INFO] - Reading metadata: metadata.partial.33
> 2024-12-09 14:25:49 [INFO] - Thread 3: restoring testdb8.sbtest21 part 1 of 1 from testdb8.sbtest21.00000.sql | Progress 47 of 47. Tables 0 of 354 completed
> 2024-12-09 14:25:58 [INFO] - Thread 1: restoring testdb8.sbtest20 part 1 of 1 from testdb8.sbtest20.00000.sql | Progress 48 of 48. Tables 0 of 354 completed
> 2024-12-09 14:26:08 [INFO] - Reading metadata: metadata.partial.34
> 2024-12-09 14:26:08 [INFO] - Thread 4: restoring testdb8.sbtest2 part 1 of 1 from testdb8.sbtest2.00000.sql | Progress 49 of 49. Tables 0 of 354 completed
> 2024-12-09 14:26:17 [INFO] - Reading metadata: metadata.partial.35
> 2024-12-09 14:26:17 [INFO] - Thread 5: restoring testdb8.sbtest19 part 1 of 1 from testdb8.sbtest19.00000.sql | Progress 50 of 50. Tables 0 of 354 completed
> 2024-12-09 14:26:27 [INFO] - Reading metadata: metadata.partial.36
> 2024-12-09 14:26:27 [INFO] - Thread 6: restoring testdb8.sbtest18 part 1 of 1 from testdb8.sbtest18.00000.sql | Progress 51 of 51. Tables 0 of 354 completed
> 2024-12-09 14:26:36 [INFO] - Thread 7: restoring testdb8.sbtest17 part 1 of 1 from testdb8.sbtest17.00000.sql | Progress 52 of 52. Tables 0 of 354 completed

**Comment by davidducos** [comment]
Hi @bac-nt, 
First, I was able to reproduce the behavior that  you witness. 
Now, let me explain why this is not a bug. When we change the code since the previous version to latest one, my reasoning was, `why are we going to speed up mydumper if myloader is going to slow down everything? let's some kind of sync mydumper and myloader`. This was good when you have large databases and a limited disk cache for mydumper (remember that --stream uses disk cache!!). 
However, I like to give users options when they use MyDumper, that is why I will change the code and add an option to work in async mode.
