### ISSUE TITLE
[FEATURE REQUEST] Optimize the performance of refresh_table_list_without_table_hash_lock  

### ISSUE THREAD

**Issue by ylgeeker** [mydumper/mydumper#1698]
# Code
https://github.com/mydumper/mydumper/blob/master/src/myloader/myloader_common.c#L490

# Question

When there are 500,000 tables to be loaded, the execution of the refresh_table_list_without_table_hash_lock method can be very time-consuming, blocking the import of data by myloader. 

Could the g_list_insert_sorted function be replaced with g_list_append ?

I have reviewed the code of myloader and didn't find any business scenarios where the g_list_insert_sorted method would be needed.

**Comment by davidducos** [comment]
Hi @ylgeeker,
We are ordering the tables by size, as we consider that it is better to insert largest tables first, so we can start creating indexes earlier on the largest tables. However, as this is affecting performance in some cases, we could add an option to make it optional.

**Comment by ylgeeker** [comment]
@davidducos   Thank you.
Can I understand it this way? 
In fact, g_list_append can replace g_list_insert_sorted here without causing data loss or any other errors.

**Comment by davidducos** [comment]
Hi @ylgeeker, 
Yes, you can replace it. BTW there is a mutex `conf->table_list_mutex` a few lines before the insert that prevents the misusage of that list.
