### ISSUE TITLE
Add support for chunking by partition name

### ISSUE THREAD

**Issue by stoty** [mydumper/mydumper#170]
One of the reasons for using partitioned tables is the ability to independently handle the data in the partitions.

Currently mydumper is not partition aware, and there is no way to dump (or load) specific partitions of a table.

I propose adding an option that chunks the dump files by partition name. Apart from having similar advantages to the existing chunking options, this makes it possible to pre-process the dump directory, and pare it down to the desired partitions before loading.

**Comment by druud** [comment]
In addition to that, I would like to see an option that adapts to the partitioning of a pre-created restore-target. Probably needs a new issue-report.

This to create dump-files that can be loaded much faster into the new target-partitions, using exactly one child process per partition. These dump-files then need to be in perfect new-PK-order.

This is useful for migrations related to changed partitioning.

"Share anything on the (constant) reading side, share nothing on the (dynamic) writing side."

**Comment by Andor** [comment]
Seems like it is almost the same feature request as this old one https://bugs.launchpad.net/mydumper/+bug/1262706

**Comment by stoty** [comment]
Thanks a lot for getting the feature in!
