### ISSUE TITLE
[BUG] Docker container DOA - libssl.so.10

### ISSUE THREAD

**Issue by GElkayam** [mydumper/mydumper#1706]
**Describe the bug**
When trying to use mydumper from docker container, it is missing ssl lib, as it seems linked to old lib.

/usr/bin/mydumper: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory

ldd
        libssl.so.10 => not found
        libcrypto.so.10 => not found

On v0.16.9-1 - it works as expected.

**To Reproduce**
Command executed:
```
$ docker run -ti mydumper/mydumper:latest ldd /usr/bin/mydumper
Unable to find image 'mydumper/mydumper:latest' locally
latest: Pulling from mydumper/mydumper
e60c9fe2676d: Pull complete
cb07eb393b82: Pull complete
72ad408552dc: Pull complete
b22ead666e96: Pull complete
Digest: sha256:3d936b32ee50fcc6628cb1ccd3cc51db3c7bc50426fb94094c9d8e79f07d24cd
Status: Downloaded newer image for mydumper/mydumper:latest
        linux-vdso.so.1 (0x00007ffea67de000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5485e98000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f5485dbd000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f5485db8000)
        libssl.so.10 => not found
        libcrypto.so.10 => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f5485db3000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f5485c76000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f5485c71000)
        libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00007f5485a9a000)
        libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f5485a3f000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f54859c7000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f54859ad000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f5485782000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f5485767000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f548555f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5485ea1000)
        libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f5485559000)
        libmount.so.1 => /lib64/libmount.so.1 (0x00007f5485513000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f54854e6000)
        libffi.so.8 => /lib64/libffi.so.8 (0x00007f54854d8000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f54854a1000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f5485405000)
```
```
$ docker run -ti mydumper/mydumper:latest /usr/bin/mydumper --version
/usr/bin/mydumper: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
```

```
# docker run -ti mydumper/mydumper:v0.16.9-1 mydumper --version
mydumper v0.16.9-1, built against MySQL 8.4.3 with SSL support
# docker run -ti mydumper/mydumper:v0.17.0-3 mydumper --version
mydumper: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
```

What mydumper and myloader version has been used?
Latest - v0.17.0-3 and v0.16.11-2

**Expected behavior**

**How to repeat**
```
docker run -ti mydumper/mydumper:v0.16.11-2 /usr/bin/mydumper --version
docker run -ti mydumper/mydumper:latest /usr/bin/mydumper --version
```

**Environment (please complete the following information):**
 - OS version: Amazon Linux 2 or Windows (Docker)
 - MyDumper version: [ mydumper --version ] v0.16.11-2 / v0.17.0-3

**Additional context**
just using docker image published

**Comment by davidducos** [comment]
Hi @GElkayam,
Thanks! this was a bug that I didn't realize before as I'm using arm64 instead of amd64 locally where I was performing the tests, as this was already reported by another user. 
Now that I was able to reproduce it locally, I realized a mistake on the repo, so I have to reorganize that, but I need to rebuild the repo all over again. Right now, testing is working, main it is not. I will try to fix it soon.

**Comment by davidducos** [comment]
@GElkayam 
It is finally fixed:
```
$ docker run --platform linux/arm64 --rm -ti mydumper/mydumper:v0.17.0-14 mydumper --version
Unable to find image 'mydumper/mydumper:v0.17.0-14' locally
v0.17.0-14: Pulling from mydumper/mydumper
Digest: sha256:609e801646e094852cb5e150099403283b7b6dbcfaeabb50835ad933c1521ac8
Status: Downloaded newer image for mydumper/mydumper:v0.17.0-14
mydumper v0.17.0-14, built against MySQL 8.4.3 with SSL support
$ docker run --platform linux/amd64 --rm -ti mydumper/mydumper:v0.17.0-14 mydumper --version
Unable to find image 'mydumper/mydumper:v0.17.0-14' locally
v0.17.0-14: Pulling from mydumper/mydumper
e60c9fe2676d: Already exists
1d95b2c60c6a: Pull complete
1803713a6ca5: Pull complete
8d8655c74b2d: Pull complete
Digest: sha256:609e801646e094852cb5e150099403283b7b6dbcfaeabb50835ad933c1521ac8
Status: Downloaded newer image for mydumper/mydumper:v0.17.0-14
mydumper v0.17.0-14, built against MySQL 8.0.39-30 with SSL support
```
$ docker run --rm -ti mydumper/mydumper:v0.17.1-1 mydumper --version
Unable to find image 'mydumper/mydumper:v0.17.1-1' locally
v0.17.1-1: Pulling from mydumper/mydumper
5286574881d2: Already exists
add2490bcbd4: Pull complete
bec56d2d8611: Pull complete
ec5f1c94ca57: Pull complete
Digest: sha256:503f6fd0e4eaf57a05834711553898dc505885f3e874f1ed8a2ad6b853131dd2
Status: Downloaded newer image for mydumper/mydumper:v0.17.1-1
mydumper v0.17.1-1, built against MySQL 8.4.3 with SSL support
$ docker run --platform linux/amd64 --rm -ti mydumper/mydumper:v0.17.1-1 mydumper --version
Unable to find image 'mydumper/mydumper:v0.17.1-1' locally
v0.17.1-1: Pulling from mydumper/mydumper
e60c9fe2676d: Pull complete
7b542dd848e5: Pull complete
719acf1cdf17: Pull complete
1b71caad2f26: Pull complete
Digest: sha256:503f6fd0e4eaf57a05834711553898dc505885f3e874f1ed8a2ad6b853131dd2
Status: Downloaded newer image for mydumper/mydumper:v0.17.1-1
mydumper v0.17.1-1, built against MySQL 8.0.39-30 with SSL support
```
There were bugs on multiple places, due to optimizations on how we build the docker container which now is smaller.

**Comment by GElkayam** [comment]
Fix confirmed. Thanks @davidducos !
```
# docker run -ti --pull always mydumper/mydumper:latest /usr/bin/mydumper --version
latest: Pulling from mydumper/mydumper
Digest: sha256:503f6fd0e4eaf57a05834711553898dc505885f3e874f1ed8a2ad6b853131dd2
Status: Image is up to date for mydumper/mydumper:latest
mydumper v0.17.1-1, built against MySQL 8.0.39-30 with SSL support
```
