### ISSUE TITLE
[FEATURE REQUEST] Continue after oom kill

### ISSUE THREAD

**Issue by jbrahy** [mydumper/mydumper#1712]
**Describe the Feature Request**
OOM keeps killing the mydumper process after ~ 2400 seconds. I'd like to run it in a loop where it picks up after it is killed and reads the max primary key and continues the dump after that record. 

**Current behavior**
Currently I have to use the --where command to filter the records and start where I left off. It isn't something I can use in a loop where I could have a --continue command and the mydumper will do the work on it's own.  

**Expected behavior**
I'd like it to get the max primary key value and add a where statement so the select is similar to "select * from table where primary_key > max_primary_key_from_export" 

**Environment**
It should apply to all environments

**Additional context**
There may be some tables that don't have autoincrement ids and more complicated logic would be required to continue.

**Comment by davidducos** [comment]
Hi @jbrahy 
Just to clarify, is this on mydumper or myloader? 
In case that that the OOM killer is on myloader, you already have an option --resume.
If this is in mydumper, then it will not be possible to kept the last position, as mydumper doesn't keep it on a disk file. What you want can be achieved with --defaults-extra-file, the format will be:
```
[`schema`.`table1`]
where= id > 123456

[`schema`.`table2`]
where= id > 654321
``` 
You can easily create the file with a bash script or any other language:
```
for table in $(echo "show tables" | mysql sakila -AN); do echo "[\`sakila\`.\`${table}\`]" ; echo "where=address_id > "$(echo "select address_id from address order by 1 limit 1" | mysql sakila -AN); done
```
The only issue with that script is that I need to get the primary key, but it should be simple enough for you to understand that it is doable.

**Comment by jbrahy** [comment]
ok, thanks. It's only happening on two multi-terabyte tables I'm exporting, so I should be able to make that work.

**Comment by davidducos** [comment]
Hi @jbrahy 
I'm wondering why the OOM killer is selecting mydumper, do you see a memory leak?

**Comment by jbrahy** [comment]
There were no errors reported, just "Killed" and the command ended. I've updated the command to this and it hasn't been killed yet yet. There are 43569491523 total rows so I'm breaking it into ~ 4 exports using this command

 mydumper -u dbuser -a -h prod-database  -l 30 -W -c -B publishing -t 16 -T publishing.post_data -o post_data_1 --where "post_data_id > 0 and post_data_id < 10000000000"
 
 mydumper v0.17.1-1, built against MySQL 5.7.44-48 with SSL support
 
top shows this so far with a load average of about 20.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
23674 root      20   0 2797596   1.6g   4772 S  10.2 44.8  97:58.53 mydumper

only output once it's running is this which is fine.

** (mydumper:23674): CRITICAL **: 00:33:51.708: Couldn't acquire global lock, snapshots will not be consistent: Access denied for user 'dbuser'@'%' (using password: YES)

**Comment by jbrahy** [comment]
It completed this time.

**Comment by jbrahy** [comment]
@davidducos hey, thanks for your time with this. I've worked with you before through Percona and you were the only guy that could get my db migrated. Thank you again!
