### ISSUE TITLE
Enhancement request: myloader filtering options

### ISSUE THREAD

**Issue by Andor** [mydumper/mydumper#228]
It would be very handful if myloader will support the same set of filtering options mydumper has: `--omit-from-file`, `--tables-list`, `--no-data`, `--no-schemas`, `--regex`, `--triggers`, `--events` and `--routines`.

Use case: I want to myload full schema of the database but some tables are unnecessary for this specific use case and I will restore schema-only at the first stage and restore tables data with some exceptions at the second stage.

**Comment by maxbube** [comment]
Hi @Andor thanks for the feedback, I guess that would require a lot of effort we it won't happen soon unless someone want to do a PR with this. In the meantime what I do in those cases is to just symlink the dump file I want to restore to a diff path (plus metadata file) and restore from it.

**Comment by davidducos** [comment]
Some of those options are simple to implement, but it will be really interesting to move from mydumper.c to common.c .

**Comment by davidducos** [comment]
For myloader, we are going to implement, --skip-triggers and --skip-post, as mydumper is storing store procedure, functions and events to the same file. If we want to store routines and events in different files, we will need to change mydumper and add/change the current file definitions.
