### ISSUE TITLE
Question: does mydumper threads worked on rows=10w, thread=16 but only one big table?

### ISSUE THREAD

**Issue by dayuanyuan1989** [mydumper/mydumper#235]
mydumper to dumper a big table with params  threads=16, row=10w agaist TiDB

It seems very slow

Does the mul-threads worked, or only a thread can work in a table?

**Comment by davidducos** [comment]
@morgo could be possible for you to help me on this? 
BTW, what I would like to do, is to start testing on tidb too, but I don't have a testing env for tidb, do you have an easy way to deploy a tidb environment with vagrant? if there is another alternative, please share with me and I will try to sort it out. 

@dayuanyuan1989, I will be able to help, as soon as I have a testing environment. If you can help me with the request to @morgo, please do! 

thanks both!

**Comment by morgo** [comment]
I recommend deploying TiDB with tiup: https://tiup.io/ (you can think of it as similar to dbdeployer, but TiDB specific)

Multi-threads will work against TiDB the same as MySQL, since this is a feature entirely inside mydumper. The TiDB server is just a regular server speaking the mysql protocol.

**Comment by davidducos** [comment]
@dayuanyuan1989 were you able to see multiple connection to the TiDB server? Can you test with -t 1 and -t 16 to see if there is some difference in time?

**Comment by davidducos** [comment]
TiDB testings are being added to CircleCI

**Comment by davidducos** [comment]
I will close this for now.
