### ISSUE TITLE
Couldn't acquire LOCK BINLOG FOR BACKUP on MariaDB 10.3

### ISSUE THREAD

**Issue by simenbm** [mydumper/mydumper#254]
When I initiate a dump to my MariaDB 10.3 server I get a critical warning as follows:

    Couldn't acquire LOCK BINLOG FOR BACKUP, snapshots will not be consistent: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BINLOG FOR BACKUP' at line 1

This is with the newest release .deb.
`mydymper --version`

    mydumper 0.9.5, built against MySQL 5.7.21-21

I tried it on a different installation of MariaDB running version `10.4.12` (Fedora), and the warning was not issued.

**Comment by lehn-etracker** [comment]
@simenbm have you tried with option `--no-backup-locks` as workaround?

**Comment by davidducos** [comment]
@simenbm,

mydumper is using `SELECT @@have_backup_locks` to determine if we can use LOCK BINLOG FOR BACKUP. Do you know what is the query that we need to execute on MariaDB?

**Comment by Ernest0x** [comment]
@davidducos there is no have_backup_locks variable in MariaDB. In fact, MariaDB has a different implementation for supporting backup procedures, with a different set of [BACKUP](https://mariadb.com/kb/en/backup-commands/) commands that a tool can use to create backups safely. So, adding efficient MariaDB support in mydumper means understanding these commands and using them specifically when connecting to MariaDB server instances. As you understand, that would be a great feature, adding even more value to mydumper.

**Comment by Ernest0x** [comment]
Imporant note related to my post above:
The BACKUP commands are available since version 10.4.1 (BACKUP STAGE commands) and 10.4.2 (BACKUP LOCK commands) of MariaDB. So, mydumper could use the BACKUP commands if connecting to instances of these versions or above.

**Comment by davidducos** [comment]
We implemented the locking mechanism that MariaDB implemented and tested for version 10.5 and 10.6
