### ISSUE TITLE
OpenSSL not included in CMakeLists.txt

### ISSUE THREAD

**Issue by todd-richmond** [mydumper/mydumper#308]
OpenSSL does not exist on all systems or might be out-of-date so the package needs to be found like other CMake packages. Also need to use the include paths
find_package(OpenSSL QUIET REQUIRED)

**Comment by davidducos** [comment]
Hi @todd-richmond, nice catch, could be possible for yo to push a pull request with the changes to add this feature?

**Comment by davidducos** [comment]
@todd-richmond or put me in the right track to sort this issue out?

**Comment by fredricj** [comment]
How to do would likely depend on whether or not openssl is to be considered a required or optional dependency. On my system (Centos7) openssl-devel is already required by the percona-server-devel package but there is an option to disable support for ssl.

Making it required would be simpler. Thoughts?

**Comment by davidducos** [comment]
Hi @todd-richmond, 

I did a quick review and we need to download:
```
wget https://raw.githubusercontent.com/Kitware/CMake/master/Modules/FindOpenSSL.cmake
wget https://raw.githubusercontent.com/Kitware/CMake/master/Modules/FindPackageHandleStandardArgs.cmake
wget https://raw.githubusercontent.com/Kitware/CMake/master/Modules/FindPackageMessage.cmake
```
on cmake/modules/ and add `find_package(OpenSSL)` to the CMakeLists.txt plus other changes. 
We also might need to add some logic to automatically disable SSL when OpenSSL package is not found. 

I might not be able to do it for release 0.10.9, but I will for 0.10.11. I will keep you posted.

**Comment by todd-richmond** [comment]
find_package(OpenSSL) has existed since cmake 3.4 so you can either require cmake 3.4 or put an if() version check around that
Requiring it seems ok as long as it will work with both OpenSSL 1.0 and 1.1. The issue is that old 1.0 is still required for FIPS compliance and 1.1 compliance keeps getting delayed

**Comment by davidducos** [comment]
@todd-richmond 
I added the find_package OpenSSL and as we discussed, it is disabling when it is not found. However, when the SSL package is not installed, I encountered another issue:
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 

-- ------------------------------------------------
-- MYSQL_CONFIG = /usr/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- WITH_ZSTD = OFF
-- OpenSSL_FOUND = FALSE
-- WITH_SSL = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
-- 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQL_LIBRARIES_crypto
    linked by target "myloader" in directory /root/issue_308/mydumper
    linked by target "mydumper" in directory /root/issue_308/mydumper
MYSQL_LIBRARIES_ssl
    linked by target "myloader" in directory /root/issue_308/mydumper
    linked by target "mydumper" in directory /root/issue_308/mydumper
```
I was able to workaround it in 2 ways:
1- with -DMYSQL_LIBRARIES_ssl="/dev/null" -DMYSQL_LIBRARIES_crypto="/dev/null" 
2- if I edit the CMakeCache.txt and remove the reference to those variables and remove the -NOFOUND value

So, what do I need from @todd-richmond ? do you know how can I add a command in the `IF (NOT OpenSSL_FOUND)` to set those tow variables to a non -NOFOUND value? I tried with set, unset and option and didn't work, but feel to try it again.

**Comment by todd-richmond** [comment]
here is a is a simpler diff for OpenSSL. You might want QUIET for other optional find_package() call too. 

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 50ebd69..b70b925 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,7 +9,9 @@ find_package(MySQL)
 find_package(ZLIB)
 find_package(GLIB2)
 find_package(PCRE)
+find_package(OpenSSL QUIET)
 
+option(WITH_SSL "Build SSL support" ${OpenSSL_FOUND})
 option(BUILD_DOCS "Build the documentation" ON)
 
 if (BUILD_DOCS)
@@ -17,7 +19,6 @@ if (BUILD_DOCS)
 endif (BUILD_DOCS)
 
 option(WITH_BINLOG "Build binlog dump options" OFF)
-option(WITH_SSL "Build SSL support" ON)
 option(WITH_ZSTD "Build ZSTD support" OFF)

```
as for MYSQL warnings, I think you can set these in the OpenSSL check 
```
if (NOT OpenSSL_FOUND)
    unset(MYSQL_LIBRARIES_crypto CACHE)
    unset(MYSQL_LIBRARIES_ssl CACHE)
endif()
```
This is the values that you are ending up linking to
```
execute_process(COMMAND mysql_config --cflags
    OUTPUT_VARIABLE MYSQL_CFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND mysql_config --libs
    OUTPUT_VARIABLE MYSQL_LIBS OUTPUT_STRIP_TRAILING_WHITESPACE)
