### ISSUE TITLE
[loader] store failed quieries in file

### ISSUE THREAD

**Issue by bato3** [mydumper/mydumper#357]
I propose to save the unsuccessful queries to the file (with commented error description).
I believe this would easily solve the proposal to [re-execute failed queries](https://github.com/maxbube/mydumper/issues/342#issuecomment-855952166) as well as the [character encoding issues on the console](https://github.com/maxbube/mydumper/issues/354).

**Comment by davidducos** [comment]
@bato3, 
I'm assuming that  you want to save the failed queries because you want to resume an import. I'm going to also assume that the backup that you are restoring is ok, so, if you save the failed queries in a new place, you are going to be saving queries that you already have in your backup, which means saving the same data twice. What I think that we need to do is to keep the state of each piece of the restore so we can resume after it was cancelled for any reason.

**Comment by bato3** [comment]
Yes you are right. However, not all `INSERT` queries are necessarily invalid. I can quickly list the 0-date (`0000-00-00 00:00:00`) problem in certain configurations. So in the log you have to save the `n` query from the file` y`.
Also (in my case) the error occurs with a dynamically created query (`--innodb-optimize-keys`)

**Comment by davidducos** [comment]
@bato3, in that INSERT failed cases, you can use INSERT IGNORE and re run the whole file. 

If this happens on a CREATE TABLE, myloader could keep the status when recreate the ALTER TABLE statement and if it failed the last time, just execute that stage.

We also need to take into account that we will need to implement a signal management at os level in case that user is killing the myloader process.

**Comment by davidducos** [comment]
This can be achieved using -N on mydumper to export with INSERT IGNORE and in myloader you can use --resume with the files that had failed. So, we only need to save the files that failed in the resume file.

**Comment by davidducos** [comment]
There are other things to consider, for instance, nowadays we need the schema-create and schema files per table to be able to execute any data file, so, the --resume should be smart enough to read those files from the backup directory and do not expect from the resume file. An alternative is to add the schema names but not the extra info that could be loaded later on.
