### ISSUE TITLE
[ENHANCEMENT] option to create only a single sql file per table

### ISSUE THREAD

**Issue by klemens-u** [mydumper/mydumper#422]
It would be nice to have an option to dump the table schema and data into a single file per table.
This is of course a matter of preference, but it would make custom scripts easier which iterate over the output directory.

Example: mydumper --combined-output   Dump all table data (schema and data) into a single sql file.

**Comment by klemens-u** [comment]
How about leaving the dump process with multiple files as is, and add an option which combines the files into a single per-table file afterwards.

**Comment by davidducos** [comment]
You will need more disk space and if it compressed files, you will be using more cpu and at the end it will take more time. myloader will need modifications anyway if you want to keep concurrency and performance. 
If you don't need concurrency per table, just run mydumper without chunks and you will get a single file.

**Comment by davidducos** [comment]
I had been thinking about it and I think that we could end up in a solution, but first we need to understand the differences between https://dev.mysql.com/doc/c-api/5.7/en/mysql-store-result.html and the function that we are using https://dev.mysql.com/doc/c-api/5.7/en/mysql-use-result.html. 
So, mysql_store_result will get the data from the mysql server and buffer it where you run mydumper, but, what about if we enqueue the mysql_result in a writer_thread and reuse the connection even before the whole mysql_result has been processed. Not sure, it this is possible, but worthy to test it. 
I will try to develop this solution asap to determine if it is a good a idea or if it is not possible.

**Comment by davidducos** [comment]
Uh! I think that I found an amazing function that we could use since MySQL 8: https://dev.mysql.com/doc/c-api/8.0/en/mysql-store-result-nonblocking.html.
We might be able to decide how many results do we want to enqueue... further testings are needed, but this will open a lot of opportunities!

**Comment by aashishmahajan** [comment]
@davidducos : question: in mydumper, 
is there a way to create 1 single dump data file for the complete schema(assuming there are 600 tables in the schema)
and is it vice versa possible to load to db schema using a single file ?

**Comment by davidducos** [comment]
Hi @aashishmahajan , you can use --stream. Take into account that current version doesn't support compress but it will be available in v0.12.3.

**Comment by davidducos** [comment]
As you can see from my previous comments, I had been thinking on a solution to this for a long time. However, I end up with the same conclusion: "create a single file in mydumper per table will add complexity, will require more memory, is not the idea of the project..." and so on... 
But, (yes!! there is a "but", you are a lucky man!), after merging #709, we can do something similar to:
`
root@ubuntu-focal:~/issue_621/mydumper# rm -rf data; ./mydumper --threads 2 --less-locking --use-savepoints --database sitemanager --outputdir data --exec '/root/issue_621/mydumper/david.sh FILENAME' -v 3 --no-delete
root@ubuntu-focal:~/issue_621/mydumper# ls data/ -l
total 12
-rw-r--r-- 1 root root 141 Jun  3 12:31 metadata
-rw-r--r-- 1 root root  97 Jun  3 12:31 sitemanager
-rw-r--r-- 1 root root 555 Jun  3 12:31 sitemanager.tutorials_tbl
root@ubuntu-focal:~/issue_621/mydumper# cat data/sitemanager.tutorials_tbl
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

/*!40103 SET TIME_ZONE='+00:00' */;
CREATE TABLE `tutorials_tbl` (
  `tutorial_id` int(11) NOT NULL AUTO_INCREMENT,
  `tutorial_title` varchar(100) NOT NULL,
  `tutorial_author` varchar(40) NOT NULL,
  `submission_date` date DEFAULT NULL,
  PRIMARY KEY (`tutorial_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `tutorials_tbl` VALUES(1,"lala","lelel",NULL)
;
root@ubuntu-focal:~/issue_621/mydumper# cat david.sh
#!/bin/bash
filename=$1
target_filename=$( echo "$filename" | cut -d'-' -f1)
if [ "$filename" == "$target_filename" ]
then
  target_filename=$( echo "$filename" | cut -d'.' -f1,2)
fi
if [ "$filename" != "$target_filename" ]
then
  cat $filename >> ${target_filename}
  rm $filename
fi
`
At the end we end up with a single file, I didn't check the timings, that is up to you!
