### ISSUE TITLE
Resume functionality

### ISSUE THREAD

**Issue by richardjharris** [mydumper/mydumper#424]
I accidentally Ctrl+C'd a myloader process (after 3-4 days of loading!), and I can't easily resume it. The dump uses INSERT not INSERT IGNORE so if I run myloader again, it will output an error for every single SQL statement that has a duplicate key, including all of the SQL, which is very slow.

I am surprised that myloader does not keep metadata on which chunks/tables have already been loaded, so it does not repeat them? Is there functionality for that somewhere?

Should I rewrite all of the dumps to use 'INSERT IGNORE' and re-run again?

Or would it be better to run myloader on individual tables, and keep track of the table load status myself?

Thanks,

Rich

**Comment by davidducos** [comment]
@richardjharris :man_facepalming: sorry to hear that!! 

So, no, it is no resume functionality, and will it be awesome to have it. For sure, nowadays will be much easier than before as we can easily keep track of the while process.
At this point in time, it is not also possible to change in myloader from INSERT to INSERT IGNORE, we might be able to do it in the future, you could change it manually, it should work, but it might be the same than start from scratch. 
What version are you using? latest version keep better track of the file executed.

**Comment by davidducos** [comment]
For this feature, what I was thinking, is when myloader catches ctrl+c:
1- leave the threads to finish the current job but stop taking new ones
2- creates a `resume` file with all the files that has been executed so far

Then if you executes the myloader again and finds this `resume` file in the backup dir, it will filter out all the entries there. Mmmmm it might be another way of filtering out files from a backup dir... similar to --omit-from-file from mydumper!! oh, wait, why don't we use the same idea than --omit-from-file (we move it to common) and by default we set `resume`.
We need to take into account that in mydumper it will be a list of database.table and in myloader it will be filenames.

mydumper could catch ctrl+c, but it would ask if you want to continue or stop, there is no resume capabilities, as the backup will not be consistent.

**Comment by richardjharris** [comment]
Thank you for your comment. Unfortunately (fortunately?) I had no further problems with mydumper/myloader, they worked first time, so I did not get a chance to test the resume functionality. But I will always be sure to use INSERT IGNORE mode to make resuming easier if there is a problem. Thanks.

**Comment by davidducos** [comment]
I found this https://github.com/mydumper/mydumper/commit/6884faeefec0268bffefc750d10d1bacc0532dee that I'm not sure so far what is doing, so I will be reviewing and see how we can use it.

**Comment by davidducos** [comment]
> For this feature, what I was thinking, is when myloader catches ctrl+c: 
> 1- leave the threads to finish the current job but stop taking new ones 
In mydumper, we have a variable called `shutdown_triggered`. I will keep that idea, the threads are going to take the new jobs and if it is true, the file is not going to be processed, it is going to be enqueued in a `resume.partial` file
> 2- creates a `resume` file with all the files that has been executed so far
When all the files had been processed, we are going to move the `resume.partial` file to `resume`.
> 
> Then if you executes the myloader again and finds this `resume` file in the backup dir, it will filter out all the entries there. Mmmmm it might be another way of filtering out files from a backup dir... similar to --omit-from-file from mydumper!! oh, wait, why don't we use the same idea than --omit-from-file (we move it to common) and by default we set `resume`. We need to take into account that in mydumper it will be a list of database.table and in myloader it will be filenames.
We are going to process only the files in the resume file if exists.
> 
> mydumper could catch ctrl+c, but it would ask if you want to continue or stop, there is no resume capabilities, as the backup will not be consistent.
