### ISSUE TITLE
[BUG] Can not restore database into RDS

### ISSUE THREAD

**Issue by speller** [mydumper/mydumper#435]
I have a big local database that I want to migrate to RDS. I dumped it well. But when I restore it, I'm getting the following error:

```
** (myloader:8262): CRITICAL **: 03:48:14.327: Error restoring ***.*** from file ****-schema-view.sql.gz: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `***` AS (select `soi`.`ID` ... group by `soi`.`ID`);
```

A CLI key to strip the DEFINER=`root`@`localhost` part should be enough for successful import.

**Comment by davidducos** [comment]
@speller I'm going to close this as the --skip-definer option has been already added to main and will be release on v0.12.1
