### ISSUE TITLE
ppa repo

### ISSUE THREAD

**Issue by str** [mydumper/mydumper#439]
I see the latest version installed via the official Ubuntu repository is 0.10.0.  Is there a way to add a ppa repo so we can stay up to date?

Thank you for your great work!

**Comment by str** [comment]
Hi @davidducos !

Something like this?  https://github.com/yuezk/publish-ppa-package

**Comment by davidducos** [comment]
If we can add a line here:
https://github.com/mydumper/mydumper/blob/6c113dc099749c0ccf46012cc9832de2672ae079/.circleci/config.yml#L1869
would be awesome. Is it possible for you to develop the command that I need to execute?
