### ISSUE TITLE
What's the difference between --database and --source-db?

### ISSUE THREAD

**Issue by str** [mydumper/mydumper#443]
1. If --database is where the data will be loaded,  --source-db sounds like where the database comes from.  It sounds like you can skip mydumper and clone a database in a single step with  

```
myloader --source-db  live --database my-copy
```
2. Mixing lower/upper cases is weird too.  Why -B instead of -b?  

3. And why would you need to define a flag if the param is not optional?   Why can't we just do:

```
mydumper  database-name target-folder
myload  target-folder database-name
```

4. Can you imagine using params for all cli?  

```
cp --from=origin --to=destiny
mv  --from=origin --to=destiny
```

Anyways, again, thank you for the great work and useful tool.

**Comment by str** [comment]
Hi @davidducos 

1. I still don't follow the need for defining `--source-db`.  If I `mydumper --database foo` and then `myloader --database bar`, I was able to import to a different name without knowing the original name.   Maybe there is something I'm not seeing.  Can you help me better understand where do you need the `--source-db` param?
2. -B comes from mysqdump, now it makes sense to me. It's better to keep using the same flags as the other tools used before. Thank you.
3. I'm exited to hear about the stream feature 
4. Yea, keeping aligned to mysqldump would make it easier to new adopters. I can totally see myself using `mydumper <from_db> | pbzip > backup.bz2` for example.  You either `--stream` or `--outputdir`.

> But I don't want to change the default behavior avoid complains from other users.

The version convention says that everything before 1.0 may change. BUT you can still be backward compatible. If you use `mysqldumper mydb` or `mysqldumper -B mydb` they both can work (until 1.0-beta where you will show a deprecation warning and for 1.0 remove legacy flags).

The deprecation is just an example to show how things can be handled, not saying that's how it has to be.

**Comment by davidducos** [comment]
Closing it as all the doubts has been iron out.
