### ISSUE TITLE
[BUG] checksum error

### ISSUE THREAD

**Issue by huangyan203316** [mydumper/mydumper#447]
**Describe the bug**
I hava a table named checksum 
```
** (myloader:48758): WARNING **: 09:51:20.642: Checksum mismatch found for `xxxxx`.`checksums-schema`. Got '(null)', expecting '/*!40101 SET NAMES binary*/;
```

**To Reproduce**
Command executed:
./myloader --host 'xxx.xxx.xxx.xxx' --port 7891 --user 'root' --password 'xxxxx' --directory 'antData2/' --enable-binlog --threads 8 --verbose 3 --overwrite-tables

**Comment by davidducos** [comment]
Ah that explains it. You need to use latest version.
