### ISSUE TITLE
[ Enhancement ] Chunk by char and varchar

### ISSUE THREAD

**Issue by ronylei** [mydumper/mydumper#487]
At present, the single table int type can be parallelized, and you can consider exporting the single table of char and varchar types in parallel

**Comment by davidducos** [comment]
Hi @ronylei , yes indeed! Any pull request will be welcome!!

**Comment by davidducos** [comment]
Ok, long time that I didn't review this. Sadly I don't think that I will be able to implement for this release, but at least I developed a viable solution. 
I found that we have 2 functions char and ascii that we can use to splits the char/varchar primary keys, this is an example:
```
mysql> select char(ascii(left(max(id),1))+1) from table_varchar_pk;
+--------------------------------+
| char(ascii(left(max(id),1))+1) |
+--------------------------------+
| f                              |
+--------------------------------+
1 row in set (0.00 sec)
```
for an initial version we could develop to split by the first character, and in future releases we could develop a smarter split that could go deeper depending the amount of rows found in the branch of the that tree.

**Comment by ronylei** [comment]
pingcap dumping

**Comment by ronylei** [comment]
How pingcap's dumping uses secondary indexes
<img width="796" alt="image" src="https://user-images.githubusercontent.com/37681093/175316958-a4626e76-e658-4ba6-b283-7677b39c3b63.png">

**Comment by ronylei** [comment]
In the actual test, it was found that dumping has a good effect on exporting large tables. mydumper can learn from this scheme

**Comment by ronylei** [comment]
@davidducos This requirement is very necessary, and you can consider raising the priority
