### ISSUE TITLE
[BUG] Report ERROR[ It was not possible to process file: (null) ] when has only data file

### ISSUE THREAD

**Issue by yifei1024** [mydumper/mydumper#496]
**Describe the bug**
step1:

/usr/bin/mydumper -h 127.0.0.1 -P 3306 -u root -p pwd-t 10 -F 256 --skip-tz-utc --no-schemas -B d1 -x "^(d1.t1)$" -o /home/t1/

step2:

/usr/bin/myloader -h 127.0.0.1 -P 3306 -u root -p pwd -d /home/t1/

then report It was not possible to process file: (null)

it means loss -schema-create.sql file

but why mydumper wont create it?

how can i resolve it？

**To Reproduce**
Command executed:
step1:

/usr/bin/mydumper -h 127.0.0.1 -P 3306 -u root -p pwd-t 10 -F 256 --skip-tz-utc --no-schemas -B d1 -x "^(d1.t1)$" -o /home/t1/

step2:

/usr/bin/myloader -h 127.0.0.1 -P 3306 -u root -p pwd -d /home/t1/

**Expected behavior**
then report It was not possible to process file: (null)

**Log**

** (myloader:1290): CRITICAL **: 03:47:50.666: It was not possible to process file: (null)

**Backup**

**Environment (please complete the following information):**
 - OS version: [CentOS 7.9,]
 - MyDumper version: [mydumper-0.11.3-1.el7.x86_64.rpm ]

**Additional context**

**Comment by davidducos** [comment]
@yifei1024 You are using --no-schema, why do you expect to find the schema files if you are telling mydumper to not create them?

**Comment by yifei1024** [comment]
ths situation is backup and then recovery, i dump data from one server , and then loader to another server

so i dont need schema.

And if has schema when i dump, then execute myloader it will report Table already exists then failed.

**Comment by yifei1024** [comment]
> ths situation is backup and then recovery, i dump data from one server , and then loader to another server
> 
> so i dont need schema.
> 
> And if has schema when i dump, then execute myloader it will report Table already exists then failed.

ths situation is backup and then recovery, i dump data from one server , and then loader to another server

so i dont need schema.

And if has schema when i dump, then execute myloader it will report Table already exists then failed.

**Comment by davidducos** [comment]
Hi @yifei1024 

Looks like you hit with: https://github.com/maxbube/mydumper/pull/489. I might need to release v0.11.3-2 with the proper fix.

**Comment by davidducos** [comment]
Please, check with: https://github.com/mydumper/mydumper/releases/tag/v.0.11.3-2
