### ISSUE TITLE
[BUG] myloader 0.11.3-2 ignores the -B $database param

### ISSUE THREAD

**Issue by str** [mydumper/mydumper#504]
When loading a dump into a different datasaename, no data is imported.

db exported as:  `mydumper --database $ORIGINALDBNAME --outputdir $DBNAME-$DATE` 

db imported as:  `myloader -B $NEWDBNAME -d $DBNAME-$DATE

Got the following errors:
```
** (myloader:39063): CRITICAL **: 17:25:18.649: Thread 2 issue restoring [...].sql: No database selected
...
** (myloader:39063): CRITICAL **: 17:25:48.960: Thread 1 issue restoring $ORIGINALDBNAME.[...].sql:
```

**Comment by davidducos** [comment]
Hi @str , there is a known issue when -B is used. Does the database $NEWDBNAME exist before executing myloader? if not, what happen if you re execute myloader?

**Comment by carlosmuller** [comment]
Hi,  I had this exact same issue our solution was to create the database with new name before hand. If the new database not exists the whole process will fail with this message  `Thread X issue restoring $DBNAME-$DATE/$DBNAME-$DATE.file.sql: No database selected` for all files create and import data.
