### ISSUE TITLE
When I use myloader,Log display Invalid JSON text: "Invalid escape character in string." at position 130 in value for column

### ISSUE THREAD

**Issue by xiaobing0508** [mydumper/mydumper#509]
- MyDumper version: 0.9.5
 - what is postion?
 - How should I find that sql?

**Comment by davidducos** [comment]
Hi @xiaobing0508,

You are using a very old version of MyDumper. Can you upgrade to a newer? There a lot of bugs that has been fixed.

**Comment by xiaobing0508** [comment]
@davidducos This is a bug?

**Comment by davidducos** [comment]
yes...

**Comment by xiaobing0508** [comment]
@davidducos I can't upgrade to a newer,because my operating system is centos 6.

**Comment by davidducos** [comment]
Why don't you take the backup from another server with a newer operating system? I would like to test the newer version to confirm or discard the bug

**Comment by xiaobing0508** [comment]
Solved for newer version,thank you.
