### ISSUE TITLE
[BUG] mydumper/myloader from  v0.11.3-3.zip shows wrong versionnumber

### ISSUE THREAD

**Issue by hubiongithub** [mydumper/mydumper#514]
** Bug description **
Downloaded v0.11.3-3.zip
Compiled on focal against Percona Server 8 Libs (installed libperconaserverclient21-dev instead of ...20-dev)

mydumper-0.11.3-3# ./mydumper -V
mydumper 0.11**.2**, built against MySQL 8.0.26-16
(same for myloader)

installed from provided .deb shows correct version:

/usr/bin/mydumper -V
mydumper 0.11.3, built against MySQL 5.7.33-36

**Expected behavior**
Show the correct version number

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04

** Additional information
Just for my understanding, is it important to have the correct clientlibs compiled into mydumper/myloader
e.g. 
- running the provided focal .deb (built against MySQL 5.7.33-36) to dump/restore a Percona 8.0.x Server
- running the provided focal .deb (built against MySQL 5.7.33-36) to dump/restore a MariaDB 10,x (x = 4/5/6) Server

If so, the Readme.md should clearly state this, and automated builds against newer/more clientlibs would be wonderful.

Thanks for the great work, mydumper is awesome.

**Comment by davidducos** [comment]
Hi @hubiongithub, we are in the process of accomplish what you are requesting. Just you to know, nowadays I'm compiling in my local environment, so I have 20 VMs up and running each time that I create a new release. Compile for different client libs will force me to maintain more environments. As I don't want to maintain that infrastructure, we are going to start using cloud base services, which is going to be paid with: https://geekswag.co/collections/mydumper.

**Comment by hubiongithub** [comment]
Hi
v0.12.1.tar.gz compiled show v0.11.6

**Comment by davidducos** [comment]
Hi @davidducos, totally my fault!
