### ISSUE TITLE
[BUG] myloader core dumps (from  v0.11.3-3.zip)

### ISSUE THREAD

**Issue by hubiongithub** [mydumper/mydumper#515]
**Describe the bug**
myloader -d . -s sakila -B sakila2 -o -e -v3 -L ttt.log
*** stack smashing detected ***: terminated
Aborted (core dumped)

**To Reproduce**
downloaded  v0.11.3-3.zip, installed requirements for focal, but compiled against libperconaserverclient**21**-dev
instead of libperconaserverclient20-dev ( which would be 5.7.35-38-1.focal not 8.0 which I wanted to use)
Command executed:
* mydumper  -v 3 -o <dir> -c -e -E -G -R -L <log.file> against a Percona Server 8.0.26
* cd <backupdir>
* myloader -d . -s sakila -B sakila2 -o -e -v3 -L ttt.log

**Expected behavior**
import sakila objects into sakila2

**Log**
cat ttt.log 
2021-12-07 12:09:48 [DEBUG] - Thread 1: Starting import
2021-12-07 12:09:48 [DEBUG] - Thread 2: Starting import
2021-12-07 12:09:48 [DEBUG] - Thread 3: Starting import
2021-12-07 12:09:48 [DEBUG] - Thread 4: Starting import

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04
 - MyDumper version: [ mydumper --version ]   
 mydumper 0.11.2, built against MySQL 8.0.26-16 (its 11.3-3 see bug 514)
 myloader 0.11.2, built against MySQL 8.0.26-16  (its 11.3-3 see bug 514)

**Additional context**

Self compiled version, build on the maschine were I run the dump and import.
Is it a problem to compile against the 8.0 libs?

**Comment by hubiongithub** [comment]
strace -d ./2021-12-07_1200 -s sakila -B sakila2 -o -e -v3 -L ttt.log

ended up here:

access("./2021-12-07_1200//sakila-schema-create.sql", F_OK) = 0
openat(AT_FDCWD, "./2021-12-07_1200/sakila-schema-create.sql", O_RDONLY) = 9
fstat(9, {st_mode=S_IFREG|0600, st_size=155, ...}) = 0
read(9, "CREATE DATABASE /*!32312 IF NOT "..., 8192) = 155
sendto(4, "\236\0\0\0\3\0\1CREATE DATABASE /*!32312 "..., 162, 0, NULL, 0) = 162
recvfrom(4, "\7\0\0\1\0\1\0\2\0\1\0", 16384, 0, NULL, NULL) = 11
read(9, "", 8192)                       = 0
close(9)                                = 0
openat(AT_FDCWD, "./2021-12-07_1200/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 9
fstat(9, {st_mode=S_IFDIR|0700, st_size=36864, ...}) = 0
getdents64(9, /* 383 entries */, 32768) = 22472
writev(2, [{iov_base="*** ", iov_len=4}, {iov_base="stack smashing detected", iov_len=23}, {iov_base=" ***: terminated\n", iov_len=17}], 3*** stack smashing detected ***: terminated
) = 44
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb09852f000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 2886793
gettid()                                = 2886793
tgkill(2886793, 2886793, SIGABRT)       = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2886793, si_uid=0} ---
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)

**Comment by davidducos** [comment]
@hubiongithub, I made a mistake. I will be fixing it later today and releasing a patch.

**Comment by hubiongithub** [comment]
Hello 
I also tried the version from the provided mydumper_0.11.3-3.focal_amd64.deb
(myloader 0.11.3, built against MySQL 5.7.33-36):

myloader -d ./2021-12-07_1200/ -s sakila -B sakila2 -o -e -v 3 -L ttt.log 
*** stack smashing detected ***: terminated
Aborted (core dumped)
