### ISSUE TITLE
[BUG] myloader --stream not working (yet?)

### ISSUE THREAD

**Issue by str** [mydumper/mydumper#527]
I created a dump using

```
mydumper --database $DBNAME --stream | pbzip2 -r > $DBNAME-$DATE.mydumper.bzip2
```

And then I tried loading it using

```
mysqladmin drop -f $DBNAME_$DATE
mysqladmin create  $DBNAME_$DATE
bunzip2  $DBNAME-$DATE.mydumper.bz2 | myloader -B  $DBNAME_$DATE
```

And I get the following error message:

`** (myloader:80184): CRITICAL **: 09:45:19.592: a directory needs to be specified, see --help`

I'm using version 0.11.3-5

Am I missing something?

**Comment by davidducos** [comment]
Hi @str , you need to use --stream on myloader.

**Comment by str** [comment]
Sorry,   that's what I tried, 

```
mysqladmin drop -f $DBNAME_$DATE
mysqladmin create  $DBNAME_$DATE
bunzip2  $DBNAME-$DATE.mydumper.bz2 | myloader -B  $DBNAME_$DATE --stream
```

and get 

`** (myloader:86916): CRITICAL **: 10:36:19.069: a directory needs to be specified, see --help`



I wrote it wrong here the first time.

**Comment by davidducos** [comment]
Oh sorry @str in master I already implemented that dir is optional but in the version that you are using, you need to set the location where the files will be temporary stored.

**Comment by str** [comment]
Thank you for your hard work. I'll use that workaround whule waiting for the next release :)
