### ISSUE TITLE
Unable to build with ZSTD support with zlib-ng

### ISSUE THREAD

**Issue by todd-richmond** [mydumper/mydumper#530]
Unable to compile with WITH_ZSTD=ON support on Linux with gcc 11.2, latest zstd libraries and zlib-ng (newer release than zlib which is no longer developed)

3 defines are missing
STDC=1
FAR=
Z_SOLO=1 (not sure if this is required, but it gets around errors with undefined z_off64_t

Defining those 3 then fails because gzFile is unknown

In file included from /var/tmp//mydumper-0.11.5/zstd/zstd_z
libwrapper.c:25:
/tools/arch/Linux_3.10.0-x86_64/zlib-ng/include/zlib.h:178
1:31: error: unknown type name ‘gzFile’

**Comment by davidducos** [comment]
Hi @todd-richmond, 
What OS and what ZSTD version are you testing?

**Comment by todd-richmond** [comment]
CentOS 7 and zstd 1.5.1 with zlib-ng 2.0.5. I build a complete toolchain starting with gcc 11 and so no OS components - but this works for over 150 opensource components. Mydumper w/o ZSTD support and zlib-ng compiles cleanly - I was just trying to update releases today and add zstd support

**Comment by davidducos** [comment]
@todd-richmond, 

At this point, I'm not sure how I can help. Your case if very difficult for me to reproduce. Feel free to open a Pull Request with the changes that you want to make if that solves an issue at your end and I will be testing on my environment. 

Please, let me know if you need anything from me or if we can close this issue.
