### ISSUE TITLE
support exporting to json format

### ISSUE THREAD

**Issue by gao0926** [mydumper/mydumper#532]
Can mydumper support exporting to json format?
Many times we need to export data to json format,  we have to use single-thread mysql shell to achieve。
like this：
echo "select * from t_xx" | mysqlsh --sql --result-format=json --uri=[username]@localhost/[schema_name]

**Comment by davidducos** [comment]
Hi @gao0926, can you elaborate a bit more your proposal? What's the goal?

**Comment by 3eka** [comment]
HI,
I guess it does, check  ```--set-names``` switch. What is unclear to me, is it safe to apply to all database tables (ones which contain JSON data and ones which does not)?

```
:; mydumper --version
mydumper 0.11.5, built against MySQL 10.3.24

:; mydumper --help | grep set-names
  --set-names                     Sets the names, use it at your own risk, default binary
```
What is risk there?
