### ISSUE TITLE
[BUG] Segmentation fault when using defaults-file option

### ISSUE THREAD

**Issue by zj5220924** [mydumper/mydumper#533]
/usr/bin/mydumper --defaults-file=/data/mysql/3306/my.cnf -u test -p test -e -c -v 3 -r 5000 -l 10 -K -G -E -R -t 5 --regex='^(?!(sys\.|mysql\.|test\.))' -o /data/dump/2021-12-29T16:07:05 -L /data/dump/2021-12-29T16:07:05/mydumper.log

** (mydumper:29000): WARNING **: Failed to load config file: Key file contains line 'skip-name-resolve' which is not a key-value pair, group, or comment
Segmentation fault

**Comment by zj5220924** [comment]
mydumper --version
mydumper 0.11.5, built against MySQL 5.7.34-37

**Comment by davidducos** [comment]
Hi @zj5220924, thank you for reporting this bug! Can you share the content of the file?

**Comment by zj5220924** [comment]
[client]
port = 3306
socket = /data/mysql/3306/mysql.sock
default-character-set = utf8mb4
max_allowed_packet = 512M

[mysqld]
user = mysql
port = 3306
server-id = 1
socket = /data/mysql/3306/mysql.sock
pid-file = /data/mysql/3306/mysql.pid
basedir = /usr/local/mysql
datadir = /data/mysql/3306/data

## Basic Settings
default_storage_engine = InnoDB
character-set-server = utf8mb4
init_connect='SET NAMES utf8mb4'
skip-name-resolve
#skip-networking
explicit_defaults_for_timestamp = 0
skip-external-locking
back_log = 300
max_connections = 1000
max_connect_errors = 6000
open_files_limit = 65535
table_open_cache = 128
max_allowed_packet = 512M
max_heap_table_size = 8M
tmp_table_size = 16M
read_rnd_buffer_size = 4M
sort_buffer_size = 4M
join_buffer_size = 4M
thread_cache_size = 8
query_cache_size = 0
ft_min_word_len = 4
sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
performance_schema = 0
lower_case_table_names = 1
interactive_timeout = 31536000
wait_timeout = 31536000
log_timestamps = 1
#read_only = 0
secure_file_priv = 
binlog_checksum =  NONE

## Binlog Settings
log_bin = /data/mysql/3306/binlog/mysql-bin
log_bin_index = /data/mysql/3306/binlog/mysql-bin.index
relay_log = /data/mysql/3306/relaylog/mysql-relay
relay_log_index = /data/mysql/3306/relaylog/mysql-relay.index
binlog_format = row
sync_binlog = 1
expire_logs_days = 7
binlog_cache_size = 2M

## GTID
gtid-mode = ON
enforce_gtid_consistency = on

## Log Settings
slow_query_log = 1
long_query_time = 1
slow_query_log_file = /data/mysql/3306/slowlog/mysql-slow.log
general_log = 0
general_log_file = /data/mysql/3306/mysql-general.log
log_error = /data/mysql/3306/mysql-error.log

## Innodb Settings
innodb_data_file_path = ibdata1:2048M:autoextend
innodb_file_per_table = 1
innodb_open_files = 5000
innodb_buffer_pool_size = 2G
innodb_write_io_threads = 4
innodb_read_io_threads = 4
innodb_thread_concurrency = 0
innodb_purge_threads = 1
innodb_flush_log_at_trx_commit = 2
innodb_log_buffer_size = 16M
innodb_log_file_size = 128M
innodb_log_files_in_group = 3
innodb_max_dirty_pages_pct = 90
innodb_lock_wait_timeout = 120

## MyISAM Settings
bulk_insert_buffer_size = 8M
myisam_sort_buffer_size = 8M
myisam_max_sort_file_size = 10G
myisam_repair_threads = 1
key_buffer_size = 2M
read_buffer_size = 2M

[mysql]
prompt="(\u@\h) [\d]>\_"
no-auto-rehash

[mysqldump]
quick
max_allowed_packet = 512M

**Comment by zj5220924** [comment]
> Hi @zj5220924, thank you for reporting this bug! Can you share the content of the default config file?

Yes, I put the defaults config file into my note:

url：http://note.youdao.com/noteshare?id=37964ac81e1e80deb29c6446fe3bd69a&sub=44DF81CEE2B5496E9098E9A23FC1796D

my test version: 5.7.27

**Comment by fliespl** [comment]
@davidducos  
I had segmentation fault when I executed like this:

`mydumper -o dump -c -e -h 127.0.0.1 -u $DB_USER -p $DB_PASS $DB_NAME`

instead of:

`mydumper -o dump -c -e -h 127.0.0.1 -u $DB_USER -p $DB_PASS -B $DB_NAME` (missing -B switch).

Probably related?

**Comment by davidducos** [comment]
Oh!!! I found the problem, currently --stream which is being set by default when you use DB_NAME doesn't support compression!! 
This should work:
```
mydumper -o dump  -e -h 127.0.0.1 -u $DB_USER -p $DB_PASS $DB_NAME
```
