### ISSUE TITLE
[BUG] myloader missing of 1st sql file 00000  part  when using --rows resulting in myloader error.

### ISSUE THREAD

**Issue by maxstainer** [mydumper/mydumper#535]
missing "part" number on file, and then is impossible to import using mydumper.
this problem seems to occur when the table to be exported contains fewer records than the --rows parameter so that the part "00000" in the file name is not inserted in the first sql table records file.

backup command I am using 
	 mydumper   -u $DB_USER -p $DB_PASS --rows=100000   --triggers  --routines  --events  -v 1  -B database  -o directory_output 

restore command: 	 
 myloader   -u xxxx -p xxxx  -d .  --database database  --verbose 3
** Message: 18:26:38.077: Server version reported as: 5.5.5-10.5.13-MariaDB-log
** (myloader:117212): CRITICAL **: 18:26:38.101: It was not possible to process file: database.table.sql (3)
[mondobet@node1-140 database]$ mv database.table.sql  database.table.00000.sql

renaming the 1st tables name adding part-number and problem is solved.

**Environment (please complete the following information):**
 - OS version: [CentOS 7.9]
 - myloader 0.11.5, built against MySQL 5.7.34-37

**Comment by davidducos** [comment]
Hi @maxstainer, are you using same mydumper and myloader versions?

**Comment by maxstainer** [comment]
it should be possible that the versions are different, as it may happen that you receive a backup from another person who wants to use a different version. 
The problem could be solved with a small fix where you  get the name of the db and the table and also the part number. You could check that if you don't exist the part string on filename  assume as default value "00000" instead of sending a generic error message (3).

**Comment by davidducos** [comment]
Hi @maxstainer, we provide packages for most of the OS versions, you can simply install the version of the backup. Until version 1 we might change the backup filename, as we need to establish the best format possible. 
There are already some ticket complaining about it, so, I tried to be more flexible with it but in this case, the workaround that you presented is the current "solution".
Take into account that allowing any .sql in the backup directory could end up in other issues. For instance, I remember an issue where someone was leaving the output of pt-show-grants in the backup directory, then myloader was trying to load it and failing.
