### ISSUE TITLE
[BUG] Restoring trigger in AWS

### ISSUE THREAD

**Issue by galenspikes** [mydumper/mydumper#536]
**Describe the bug**
Restoring triggers to AWS RDS MySQL fails with syntax error.

**To Reproduce**
Command executed:
* mydumper --host ${source_rhel7_mysql} -u ${user} -p "password" -v 1 --use-savepoints --no-locks --long-query-guard=10800 -B ${database_name} -o ${download_path} --threads 10 --routines --events --triggers --no-views
* myloader -o -h ${AWS_RDS_MYSQL_HOST} -u ${user} -p "password" -B ${database_name} -d ${download_path} -v 3

**Expected behavior**
Schema trigger files load successfully

**Log**
** (myloader:15068): CRITICAL **: 13:41:33.165: Error restoring ro_prod_factotum.dashboard_rawchem from file prod_factotum.dashboard_rawchem-schema-triggers.sql: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET character_set_client = @PREV_CHARACTER_SET_CLIENT;
SET character_set_results' at line 61

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**Environment (please complete the following information):**
 - OS version: RHEL7 MySQL 5.7.36, AWS RDS MySQL 5.7.34
 - MyDumper version: mydumper 0.10.7, built against MySQL 5.7.34-37

**Additional context**
There seems to be a problem with AWS RDS when it comes to this, because I dump/load across different normal MySQL servers in our environment all the time and the triggers load successfully. It's only happening with RDS.

**Comment by davidducos** [comment]
Hi @galenspikes ,

What is the output of show variables like 'character_set_results'; on your rds instance?

**Comment by galenspikes** [comment]
mysql>  show variables like 'character_set_results';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| character_set_results | utf8  |
+-----------------------+-------+
1 row in set (0.02 sec)

**Comment by davidducos** [comment]
@galenspikes Can you share the content of the file?

**Comment by galenspikes** [comment]
[prod_factotum.dashboard_rawchem-schema-triggers.zip](https://github.com/mydumper/mydumper/files/7790444/prod_factotum.dashboard_rawchem-schema-triggers.zip)

**Comment by davidducos** [comment]
@galenspikes 
Are you using the same myloader version in all the cases?

**Comment by davidducos** [comment]
No feedback provided.
