### ISSUE TITLE
[Enhancement ]myloader can resume from breakpoints when connection is invalid for some reason

### ISSUE THREAD

**Issue by conanwang** [mydumper/mydumper#537]
Currently,  if the connection to mysql is invalid with something wrong  when myloader is working,  we have to start again from the sratch, it will take a long time  especially a mass amount of data.

In the light of this, if myloader can continue work from the breakpoint, it will gain time.

If necessary i can offer the pull request :blush: :)  @davidducos

**Comment by davidducos** [comment]
Hi @conanwang, this was already requested in #424.

YES! I will be glad to review any pull request!!

**Comment by conanwang** [comment]
thanks for your quick reply, I really appreciate it, I will make the PR for #424 in a few weeks.
