### ISSUE TITLE
Add option to skip adding "00000" to filenames when using unlimited rows

### ISSUE THREAD

**Issue by fliespl** [mydumper/mydumper#538]
Or even make it default and only append those if rows is defined?

**Comment by davidducos** [comment]
Hi @fliespl,
We are trying to establish a new file format, removing the 00000 might break it and adding exceptions will make difficult to maintain. 
We are releasing every 2 months and I have the intention to release v1 this year, but until that point in time, we might be changing several things that breaks backwards compatibility.

**Comment by fliespl** [comment]
Okay, that's understandable. What would you propose in following scenario:
I need to only restore some tables (by knowing their name). Is that supposed to be supported across future versions?



    - zcat dump/db.user-schema.sql.gz | mysql --defaults-extra-file=my.cnf test
    - zcat dump/db.user.*.sql.gz | mysql --defaults-extra-file=my.cnf test -> notice dot star after table name.

**Comment by davidducos** [comment]
Hi @fliespl, why don't just change the filename and use myloader?

**Comment by fliespl** [comment]
@davidducos but does myloader support scenario in which I do full database dump and then want to restore only some tables?

Didn't notice any switch like that...

**Comment by davidducos** [comment]
@fliespl , 
I don't think that I received that request... but if you copy or link only the files that you want to restore, you will restore only some tables. I don't think that will be hard to implement --regex on myloader.

**Comment by fliespl** [comment]
Thanks, I have no idea if that's actually a valuable request for anyone else :) We just need to do some data manipulation during dump and since our tables are big we only restore required ones.

Leaving up to you decision if that's something you feel like worth adding,

**Comment by davidducos** [comment]
@fliespl, --regex has been implemented on myloader, so you are able to restore just some tables. I'm going to close this now as we are not going to implement what you originally requested. 
Best regards!

**Comment by fliespl** [comment]
Thanks! Which version will it be included?

**Comment by tersmitten** [comment]
We would also really like a way of preventing the `00000` being added. It breaks an unknown amount of automation for us :-(

**Comment by tersmitten** [comment]
I also found out that there're "schema create" files (`example_com_www-schema-create.sql`) now`.
