### ISSUE TITLE
Move MyDumper from C to C++

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#540]
This is an idea that I had for a while now... Do you think that will be better to move MyDumper from current C coding to C++?
Use reactions 👍 👎 or you can also give your opinion with a comment.
From my point of view:
Pros: 
- will be simpler to implement some features 
- I'm not an expert on c++ but I think that it will be easier to maintain.
Cons:
- The main one is that it will require a lot of effort to complete and we will need to live with both worlds for more than a year. 
- no rollback possible... as there will be a lot of feature that are going to be added it will be very hard to implement them again.

**Comment by aadrian** [comment]
@davidducos in theory C++ is better, but in practice I've yet to see a project where the migration/upgrade was really an improvement :( .

From what I've seen so far in projects that did the move to C++:
- the number of bugs greatly increased
- the required maintenance effort was much higher (even when not counting for the migration effort itself)
- the complexity of the projects grew greatly (totally unproportional with the number of new features) 
- many new unnecessary abstractions were introduced, "obfuscating" further the logic.
- eventually less users were able to participate

The only exception I've seen so far were for projects that migrated also to QT, and also made extensive use of UI  and the QT provided APIs.

For projects **without UI**, the kind of migrations that I've seen however doing extremely well was from C directly to Golang.

Also worth mentioning is PGLoader https://pgloader.io/ https://github.com/dimitri/pgloader  - very fast and useful tool similar in scope but for PG (they did several rewrites tcl->python->lisp )
