### ISSUE TITLE
myloader not restoring all indexes and no triggers

### ISSUE THREAD

**Issue by AnonJo** [mydumper/mydumper#541]
MyDumper/Loader version: 0.11.3, built against MySQL 5.7.33-36

I have created a backup of an ca. 330 GB MySQL 8.0.25 database with the following commands:

```
ulimit -n 999999
mydumper -t 10 \
 --no-data \
 --regex '^(db_prefix\.*)' \
 --compress \
 --outputdir /srv/mysql/backup
mydumper -t 10 \
 --rows=100000 \
 --compress \
 --triggers \
 --routines \
 --events \
 -v 3 \
 --trx-consistency-only \
 --outputdir /srv/mysql/backup \
 --logfile /tmp/mydumper.log \
 --regex '^(db_prefix\.*)' \
 --no-schemas
```

And restored it in into Percona XtraDB Cluster 8.0.25 with the following commands:

```
ulimit -n 999999
myloader --directory /srv/mysql/backup \
  --queries-per-transaction=50000 \
  --threads=10 \
  --compress-protocol \
  --verbose=3 \
  --max-threads-per-table=10 \
  --disable-redo-log \
  --innodb-optimize-keys \
  --logfile=/tmp/myloader.log
```

After restoring the database was really slow, so I compared the count of indexes and foreign keys to an older backup. Of approx. 1300 indexes there where 300 missing and also all of the triggers (approx. 190). 

The indexes were missing on alot of different tables with various sizes, luckily the biggest tables were not impacted.

I have checked the logfiles and there wasnt any errors.

Is this a bug or was there something wrong in my command options?

**Comment by davidducos** [comment]
Hi @AnonJo, 

Can you execute `ls -l /srv/mysql/backup`?

**Comment by AnonJo** [comment]
Hi @davidducos,

I have to check this with the customer if I can publish this information here.

What do you want to know?

There are at a minimum three files per table:

db_name.table_name-metadatadb_name.table_name-metadata

**Comment by davidducos** [comment]
Hi @AnonJo, 

If there are not -schema-trigger.sql files, then they were not going to be restored. Can you check if the user that you are using can execute the show trigger command?

**Comment by AnonJo** [comment]
I have created the backup using the root user, so there shouldnt be any permission problems.

The triggers are not originally created by the root user, he is not the DEFINER. Can this be a problem?

Still I am wondering why only some of the indexes are created.

**Comment by davidducos** [comment]
Lets resolve one issue at a time. 
Triggers: 
do you have any errors/warnings when you execute mydumper ?
Can you execute SHOW TRIGGERS FROM `<DATABASE>` like '<TABLE>'  for any <DATABASE>.<TABLE> where a trigger exist?

Indexes:
Do you have FULLTEXT indexes in the tables that failed? can you share a table structure where it is failing?

**Comment by AnonJo** [comment]
Sorry, had a hard week restoring the indexes in production ;).

So regarding the triggers:

The only warning in the mydumper log is:

[WARNING] - Using trx_consistency_only, binlog coordinates will not be accurate if you are writing to non transactional tables.

Except that no more errors / warnings.

The output from  SHOW TRIGGERS FROM database_name;
...
191 rows in set (0.01 sec)

Regarding the indexes:

No, all indexes are normal B-Trees.

Here is an example structure:

mysql> show create table ttg_zeiten\G
*************************** 1. row ***************************
       Table: ttg_zeiten
Create Table: CREATE TABLE `ttg_zeiten` (
  `ttg_zeit_id` int NOT NULL AUTO_INCREMENT,
  `datum` date NOT NULL DEFAULT '0000-00-00',
  `depot_id` int NOT NULL DEFAULT '0',
  `mac` int NOT NULL DEFAULT '0',
  `arbeitsart_id` int NOT NULL DEFAULT '0',
  `zube_id` int NOT NULL DEFAULT '0',
  `dauer` double NOT NULL DEFAULT '0',
  `tvgg_prozentsatz` double NOT NULL DEFAULT '0',
  `tvgg_dauer` double NOT NULL DEFAULT '0',
  `tvgg_dauer_round` decimal(5,2) DEFAULT NULL,
  `ts_changed` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `kategorie` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`ttg_zeit_id`),
  KEY `datum_mac` (`datum`,`mac`),
  KEY `idx_kategorie` (`kategorie`,`datum`,`mac`)
) ENGINE=InnoDB AUTO_INCREMENT=338572186 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
1 row in set (0.00 sec)

After restoring the indexes datum_mac and idx_kategorie are missing.

**Comment by davidducos** [comment]
@AnonJo ,
I found the bug on the index creation, a release will be patching it later today.

**Comment by AnonJo** [comment]
Wow, that was fast :).

What was the bug? Did it hat to do with` innodb-optimize-keys` parameter?

**Comment by AnonJo** [comment]
Ok, I am not a C developer, but does this explain why only some indexes are created?

**Comment by davidducos** [comment]
The indexes of the tables with more than 1 index were discarded.

**Comment by davidducos** [comment]
If no -schema-trigger file is found, then the problem is in mydumper. I need a test case as you gave me with the create table statement. Do you have a trigger definition that I can use for testing?

**Comment by AnonJo** [comment]
Great that you found the bug for the indexes so fast, here is an example for the non restored triggers:

```
             Trigger: tap_spring_konditionen_details_DELETE
               Event: DELETE
               Table: tap_spring_konditionen_details
           Statement: trig: BEGIN
DECLARE disable BOOLEAN DEFAULT 0;
DECLARE user VARCHAR(250);
DECLARE uid CHAR(40);
DECLARE last_insert_id INT;
SELECT @my_mac INTO user;
SELECT @disable_trigger INTO disable;
SELECT SHA1(CONCAT(ROUND(RAND()*1000000, 0), NOW())) INTO uid;
SET @session_mysql_user = SESSION_USER();
IF disable THEN LEAVE trig; END IF;
IF user IS NULL THEN SET user = 0; END IF;
INSERT INTO log (datum_erstellt, mac_ersteller, mysql_user, tabelle, typ, hash) VALUES (NOW(), user, @session_mysql_user, 'tap_spring_konditionen_details', 'DELETE', uid);
SELECT MAX(log_id) INTO last_insert_id FROM log WHERE hash=uid;
INSERT INTO log_primary (log_id, primary_spalte, primary_value) VALUES (last_insert_id, 'kondition_id', OLD.kondition_id);
INSERT INTO log_primary (log_id, primary_spalte, primary_value) VALUES (last_insert_id, 'produkt_id', OLD.produkt_id);
INSERT INTO log_eintraege (log_id, spaltenname, wert_alt, wert_neu) VALUES (last_insert_id, 'kilopreis', OLD.kilopreis, 'DELETE');
INSERT INTO log_eintraege (log_id, spaltenname, wert_alt, wert_neu) VALUES (last_insert_id, 'kondition_id', OLD.kondition_id, 'DELETE');
INSERT INTO log_eintraege (log_id, spaltenname, wert_alt, wert_neu) VALUES (last_insert_id, 'produkt_id', OLD.produkt_id, 'DELETE');
INSERT INTO log_eintraege (log_id, spaltenname, wert_alt, wert_neu) VALUES (last_insert_id, 'stckpreis', OLD.stckpreis, 'DELETE');
END
              Timing: AFTER
             Created: 2022-01-11 21:11:08.24
            sql_mode:
             Definer: username@ip/255.255.255.255
character_set_client: utf8
collation_connection: utf8_general_ci
  Database Collation: utf8_bin
```

**Comment by davidducos** [comment]
@AnonJo, 
Oh I know that is your trigger issue. You are using --no-schemas that for some reason is disabling the trigger output:
```
root@ubuntu-focal:~/issue_541/mydumper# rm -rf dump; ./mydumper -o dump -B issue_541 -R -E -G --trx-consistency-only --no-schemas ; ls dump

** (mydumper:534570): WARNING **: 17:41:46.327: Using trx_consistency_only, binlog coordinates will not be accurate if you are writing to non transactional tables.
issue_541.david.00000.sql  metadata
root@ubuntu-focal:~/issue_541/mydumper# rm -rf dump; ./mydumper -o dump -B issue_541 -R -E -G --trx-consistency-only ; ls dump

** (mydumper:534581): WARNING **: 17:41:49.600: Using trx_consistency_only, binlog coordinates will not be accurate if you are writing to non transactional tables.
issue_541-schema-create.sql  issue_541.david_2-metadata    issue_541.tap_spring_konditionen_details-metadata             issue_541.ttg_zeiten-schema.sql
issue_541.david-metadata     issue_541.david_2-schema.sql  issue_541.tap_spring_konditionen_details-schema-triggers.sql  metadata
issue_541.david-schema.sql   issue_541.david_3-metadata    issue_541.tap_spring_konditionen_details-schema.sql
issue_541.david.00000.sql    issue_541.david_3-schema.sql  issue_541.ttg_zeiten-metadata
```

**Comment by davidducos** [comment]
I think that you are causing the whole problem splitting the execution in 2 stages, why do you execute mydumper twice? doesn't makes sense to me. Why don't you just execute this:
```
mydumper -t 10 \
 --rows=100000 \
 --compress \
 --triggers \
 --routines \
 --events \
 -v 3 \
 --trx-consistency-only \
 --outputdir /srv/mysql/backup \
 --logfile /tmp/mydumper.log \
 --regex '^(db_prefix\.*)' \
```
??

**Comment by davidducos** [comment]
Clarification has been added to Master.

**Comment by AnonJo** [comment]
Hi @davidducos,

ok understood. I did it because of old habit with mysqldump and didnt realize that it makes no sense with mydumper.

But wouldnt it make sense to include the triggers while using one of the two options (either with `--no-schema` or with `--no-data)`? 

So if someone does both as I did, you would still have a complete backup of all database objects.

**Comment by davidducos** [comment]
Yes! For sure is weird! But not a bug abs it will need some work to fix it. I will create an enhancement ticket to develop the real solution.
Thanks for all the feedback you gave me!

**Comment by AnonJo** [comment]
Ok, sounds good to me. Thanks for your fast response and help!

**Comment by davidducos** [comment]
The linked PR fixed it

**Comment by davidducos** [comment]
Hi @AnonJo,
Sorry about the confusion, I thought that it was ok that --no-schema ignore the triggers, but after reviewing, I realized that we should implement it in a better way. 
Please, check with master and let me know if you find further issues.

**Comment by aloks2019** [comment]
@davidducos 
i can still notable to dump triggers with or without —no-schemas option in 0.12.3 release.  

I am just creating separate backups of data and triggers to make sure that triggers don’t impact data loading while running myloader utility. Please suggest if there would be any impact on data loading  if I create trigger routines and events backup along with data and schemas; and load them using single myloader command.

**Comment by davidducos** [comment]
We are going to follow this in https://github.com/mydumper/mydumper/issues/665
