### ISSUE TITLE
binlog.c:168：对‘my_net_read’未定义的引用

### ISSUE THREAD

**Issue by liubixia55** [mydumper/mydumper#542]
**Describe the bug**
mydumper-master/binlog.c:168：对‘my_net_read’未定义的引用

**To Reproduce**
Command executed:
[root@localhost mydumper-master]# cmake .  -DCMAKE_INSTALL_PREFIX=/data/app/mydumper -DWITH_BINLOG=ON
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL: /usr/include/mysql, /usr/lib64/mysql/libmysqlclient.so;/usr/lib64/libpthread.so;/usr/lib64/libz.so;/usr/lib64/libm.so;/usr/lib64/libdl.so;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- checking for one of the modules 'glib-2.0'
-- checking for one of the modules 'gthread-2.0'
-- checking for one of the modules 'gio-2.0'
-- checking for one of the modules 'gobject-2.0'
-- checking for module 'libpcre'
--   found libpcre, version 8.32
-- Found PCRE: /usr/include  
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 

CMake Warning at docs/CMakeLists.txt:9 (message):
  Unable to find Sphinx documentation generator

-- ------------------------------------------------
-- MYSQL_CONFIG = /usr/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /data/app/mydumper
-- BUILD_DOCS = ON
-- WITH_BINLOG = ON
-- WITH_ZSTD = OFF
-- OpenSSL_FOUND = 
-- WITH_SSL = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /data/app/mydumper/mydumper-master
[root@localhost mydumper-master]# make 
Scanning dependencies of target mydumper
[  6%] Building C object CMakeFiles/mydumper.dir/mydumper.c.o
[ 12%] Building C object CMakeFiles/mydumper.dir/binlog.c.o
[ 18%] Building C object CMakeFiles/mydumper.dir/server_detect.c.o
[ 25%] Building C object CMakeFiles/mydumper.dir/g_unix_signal.c.o
[ 31%] Building C object CMakeFiles/mydumper.dir/connection.c.o
[ 37%] Building C object CMakeFiles/mydumper.dir/getPassword.c.o
[ 43%] Building C object CMakeFiles/mydumper.dir/logging.c.o
[ 50%] Building C object CMakeFiles/mydumper.dir/set_verbose.c.o
[ 56%] Building C object CMakeFiles/mydumper.dir/common.c.o
Linking C executable mydumper
CMakeFiles/mydumper.dir/binlog.c.o：在函数‘get_binlog_file’中：
/data/app/mydumper/mydumper-master/binlog.c:168：对‘my_net_read’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [mydumper] 错误 1
make[1]: *** [CMakeFiles/mydumper.dir/all] 错误 2
make: *** [all] 错误 2
[root@localhost mydumper-master]#

**Comment by davidducos** [comment]
Hi @liubixia55 , the bin log feature is going to be deprecated. Please do not use it. Use mysqlbinlog instead.

**Comment by davidducos** [comment]
I will keep this open, as I will be removing binlog.c file for the next release.

**Comment by liubixia55** [comment]
> Hi @liubixia55 , the bin log feature is going to be deprecated. Please do not use it. Use mysqlbinlog instead.

**Comment by liubixia55** [comment]
thanks for your quick reply
