### ISSUE TITLE
enhance documentation with default values

### ISSUE THREAD

**Issue by str** [mydumper/mydumper#544]
When I'm checking the new flags with the --help option, I don't know if I should turn something on or off because I don't know if it's on or off by default, for example:

```
  -G, --triggers                  Dump triggers
  -E, --events                    Dump events
  -R, --routines                  Dump stored procedures and functions
```
Should I turn them on or are they on by default?

**Comment by davidducos** [comment]
Hi @str , by default they are off. I will add the default value to the doc.

**Comment by davidducos** [comment]
Already on Master

**Comment by str** [comment]
Awesome! Always thankful for your great work!
