### ISSUE TITLE
mydumper stopping dump at an particular memory usage

### ISSUE THREAD

**Issue by Gokul-Rams** [mydumper/mydumper#548]
I am trying to take dump of db with over 115gb of data, mydumper gets stuct at this particular VSZ-318668 and RSS-211748. Is there any resolution for this ,why this happens, I do not see any io reads spikes after this particular memory limit on db side it suddenly drops and stuck at this stage for long time. my machine is good enough with around 128 gigs of RAM and I tried this multiple times the same issue persists

**To Reproduce**
Command executed:
mydumper --host=*** \
--user=*** \
--password=*** \
--outputdir=./dbdump \
--rows=100 \
-G -E -R -z \
--trx-consistency-only \
--compress \
--build-empty-files \
--threads=16 \
--compress-protocol \
--ssl \
--regex '^(?!(innodb\.|mysql\.|performance_schema\.|relationals\.|sys\.|tmp\.|information_schema\.))' \
--lock-all-tables \
--long-query-guard 600 \
--long-query-retries 1 \
--kill-long-queries \
-v 3
-L mydumper-logs.txt

What mydumper and myloader version has been used?
mydumper Version: 0.11.5, built against MySQL 5.7.33-36

**Expected behavior**
mydumper to take an proper dump

**Log**
No exceptional log even in verbose mode other that connection sucessful message and some long query killed message 
** Message: 12:49:35.636: MyDumper backup version: 0.11.5
** Message: 12:49:35.645: Server version reported as: 5.7.33-log
** Message: 12:49:35.647: Connected to a MySQL server
** (mydumper:2199): WARNING **: 12:49:35.649: Killed a query that was running for 1139s
** (mydumper:2199): WARNING **: 12:49:35.650: Killed a query that was running for 856s

**Environment (please complete the following information):**
 - OS version: Ubuntu 18.04.6 LTS
 - mydumper Version: 0.11.5, built against MySQL 5.7.33-36

**Comment by davidducos** [comment]
Hi @Gokul-Rams, Can you try again with a higher value in --rows? like 1000 o 5000 ?

**Comment by Gokul-Rams** [comment]
> Hi @Gokul-Rams, Can you try again with a higher value in --rows? like 1000 o 5000 ?

Hi @davidducos Thanks for the reply, 
mydumper --host=*** \
--user=*** \
--password=*** \
--outputdir=./backup \
--rows=1000 \
-G -E -R -z \
--trx-consistency-only \
--compress \
--build-empty-files \
--threads=16 \
--compress-protocol \
--ssl \
--regex '^(?!(innodb.|mysql.|performance_schema.|relationals.|sys.|tmp.|information_schema.))' \
--lock-all-tables \
--long-query-guard 600 \
--long-query-retries 1 \
--kill-long-queries \
-L mydumper-logs.txt

Before running this last attempt I tried with 1000 rows and resulted with same problem

**Comment by davidducos** [comment]
Are you running this against TIDB server?

**Comment by Gokul-Rams** [comment]
> Are you running this against TIDB server?

Nope AWS RDS with innodb engine

**Comment by davidducos** [comment]
I need you to upload the log file to understand at what stage is stopping

**Comment by Gokul-Rams** [comment]
Hi @davidducos 
adding all my observations..

** Message: 17:30:26.587: MyDumper backup version: 0.11.5
** Message: 17:30:26.724: Server version reported as: 5.7.33-log
** Message: 17:30:26.726: Connected to a MySQL server

the above three lines is the only log I can get in verbose 3 mode 
![image](https://user-images.githubusercontent.com/69314159/149994259-ccb9f410-2182-4857-b9cf-3ffccb12332b.png)
above is the readIO of the mysql server for the specific amount of time

318676 KB - VSZ
211488 KB - RSS
above is the memory consumption where the process exactly goes into halt or stuck state

another observation when I kill the process and start it again the process suddenly reaches the above mentioned memory limit within 1 or 2  mins Is this expected behaviour 

              total        used        free      shared  buff/cache   available
Mem:      130415832      497176   129501648         808      417008   128872904
Swap:             0           0           0
above is the total memory availabe stat in the machine

To add furthur more details here is the contents of process status file
Name:   mydumper
Umask:  0022
State:  S (sleeping)
Tgid:   2089
Ngid:   0
Pid:    2089
PPid:   1788
TracerPid:      0
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 256
Groups: 0
NStgid: 2089
NSpid:  2089
NSpgid: 2089
NSsid:  1773
VmPeak:   318676 kB
VmSize:   318668 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:    211504 kB
VmRSS:    211488 kB
RssAnon:          202364 kB
RssFile:            9124 kB
RssShmem:              0 kB
VmData:   248884 kB
VmStk:       132 kB
VmExe:      3464 kB
VmLib:     13292 kB
VmPTE:       580 kB
VmSwap:        0 kB
HugetlbPages:          0 kB
CoreDumping:    0
THP_enabled:    1
Threads:        1
SigQ:   0/509323
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000001000
SigCgt: 0000000180000000
CapInh: 0000000000000000
CapPrm: 0000003fffffffff
CapEff: 0000003fffffffff
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
NoNewPrivs:     0
Seccomp:        0
Speculation_Store_Bypass:       vulnerable
Cpus_allowed:   ffff
Cpus_allowed_list:      0-15
Mems_allowed:   00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:      0
voluntary_ctxt_switches:        2388
nonvoluntary_ctxt_switches:     5

I can also see the thread count as 1, but 16 threads is specified. I don't know how mydumper creates thread Is it an child process ?

**Comment by fredricj** [comment]
The memory usage is just a symptom of where mydumper get stuck. To diagnose this you need to check if it is waiting for the result of a query (SHOW FULL PROCESSLIST in mysql) or if it is stuck somewhere else with gdb and/or strace.

**Comment by Gokul-Rams** [comment]
Hi @fredricj Thanks for the clue I can see this query "SELECT TABLE_SCHEMA, TABLE_NAME FROM information_schema.TABLES WHERE TABLE_TYPE ='BASE TABLE' AND TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'data_dictionary') AND NOT (TABLE_SCHEMA = 'mysql' AND (TABLE_NAME = 'slow_log' OR TABLE_NAME = 'general_log'))" goes into "checking permissions" state and came to know that AWS RDS mysql in addition to global lock also do not support table level locks also for users, that why mydumper was not able to start the dump and thread also remained as 1 

**Info for AWS RDS user --lock-all-tables which omits global lock and put table locks do not work in RDS you have to dump with --no-locks. you can optionally stop replication to an read replica (if there is one) using AWS RDS stored procedures and take an dump for the read replica for an consistent dump**

@davidducos this is specific to RDS there is no issues with mydumper this was an misunderstanding.......Thanks :)

**Comment by Gokul-Rams** [comment]
Can I know the maximum number of threads supported by mydumper and myloader and is it recommended to keep the rows count to higher or an lower value ?

**Comment by davidducos** [comment]
The rows will depend in what you want, a high number will end up in larger queries and bigger files, a lower number will be more files and fastest queries.
Take into account https://github.com/mydumper/mydumper/pull/522 if you are worried about memory usage.
There is no limit to the amount of threads.

**Comment by jaboboyw** [comment]
Be careful with the type of RDS instances, especially if they have credits in CPUs and storage, without credits the IOS fall and the problems begin.

**Comment by davidducos** [comment]
@Gokul-Rams it is not clear for me if you need more help on this or if it is possible to close this issue now?
