### ISSUE TITLE
Master and Server data stored in same medatdata file, difficult to distinguish

### ISSUE THREAD

**Issue by nkadel-skyhook** [mydumper/mydumper#55]
The format of the master and slave status in the "metadata" file is very similar. This can cause confusion: I wrote tools to read metadata for the slave status, and reload it for a replicated host, and ran into trouble because of the similarity.

SHOW MASTER STATUS:
        Log: mysql-bin.000001
        Pos: 100
        GTID:(null)

SHOW SLAVE STATUS:
        Host: slavehost.localdomain
        Log: mysql-bin.1000000
        Pos: 2000000
        GTID:(null)

This makes it a bit awkward to post. Please switch the slave "Log:" and "Pos:" fields to match what MySQL actually reports, namely:

* mysql -e 'show slave status\G' | grep Master_log
             Master_Log_File: mysql-bin.1000000
          Read_Master_Log_Pos: 2000000

**Comment by maxbube** [comment]
Hi @nkadel-skyhook metadata file format had been that way for long time and I know is being used for several automation scripts in production, if I change that now I will break them all. So is not good to do it unless a new major realese. I would close this issue for now and keep it mind when for the next major release.

**Comment by nkadel-skyhook** [comment]
Is there a schedule on the next major release?

**Comment by maxbube** [comment]
Hi @nkadel-skyhook , 

I made a minor release a few days ago, but I don't have scheduled release dates.

**Comment by davidducos** [comment]
This will be merge on Release 1.0.1

**Comment by davidducos** [comment]
Related to https://github.com/mydumper/mydumper/issues/779
