### ISSUE TITLE
[BUG] After restoring data with myloader, some tables are empty

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#562]
**Describe the bug**
After restoring data with myloader, some tables are empty, and there is no warning or error for the table in the log.
e.g. :
jwell_fms.ac_at_account

options:
-v 3 --set-names utf8 -e -o --purge-mode=TRUNCATE -t 8 --max-threads-per-table 8 -r 50000 --innodb-optimize-keys -B  jwell_fms -L /tmp/impdata.log -d <DIR>

**Log**
2022-01-28 09:44:32 [INFO] - Thread 1 restoring table `jwell_fms`.`ac_at_account` from /data/dumpdir/20220128020001/jwell_fms.ac_at_account-schema.sql.gz
2022-01-28 09:45:37 [INFO] - Thread 1 restoring `jwell_fms`.`ac_at_account` part 0 of 0 from jwell_fms.ac_at_account.00000.sql.gz. Progress 72 of 445 .
2022-01-28 09:47:43 [INFO] - Thread 1 restoring indexes `jwell_fms`.`ac_at_account`
![image](https://user-images.githubusercontent.com/9590209/151479737-26710303-f3c5-43c6-885c-07d1d25b7df4.png)
[impdata.log](https://github.com/mydumper/mydumper/files/7955404/impdata.log)

**Backup**
ls -l file:
[root@mysqldevtest02 20220128020001]# ls -lhrt jwell_fms.ac_at_account.*
-rw-rw-r-- 1 mysql mysql 14M 1月  28 02:03 jwell_fms.ac_at_account.00000.sql.gz
[root@mysqldevtest02 20220128020001]# ls -lhrt jwell_fms.ac_at_account-schema.sql.gz 
-rw-rw-r-- 1 mysql mysql 1.8K 1月  28 02:00 jwell_fms.ac_at_account-schema.sql.gz
[ls-lhrt.txt](https://github.com/mydumper/mydumper/files/7955443/ls-lhrt.txt)

**Environment (please complete the following information):**
 - OS version: [ CentOS Linux release 7.5.1804 (Core), 3.10.0-862.el7.x86_64 ]
 - MyDumper version: [ mydumper 0.11.5, built against MySQL 5.7.34-37 ]
 - MySQL version: [ 8.0.25-15 ]

**Comment by samiahlroos** [comment]
Hi,
I just saw something similar when using --rows (-r) parameter with myloader. Try without `-r 50000`.
More details of what I saw are in https://github.com/mydumper/mydumper/issues/564.
