### ISSUE TITLE
[BUG] Error when building with clang

### ISSUE THREAD

**Issue by yelkarama** [mydumper/mydumper#563]
**Describe the bug**
When building with clang, I got this error:

```
/build/mydumper/myloader.c:1264:10: error: cast to smaller integer type 'enum file_type' from 'gpointer' (aka 'void *') [-Werror,-Wvoid-pointer-to-enum-cast]
    ft = (enum file_type )g_async_queue_pop(td->conf->stream_queue);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

What mydumper and myloader version has been used?
latest

**Expected behavior**
Successful build (same as when using gcc)

**Environment (please complete the following information):**
 - OS version: Linux Alpine Edge
 - MyDumper version: Latest

**Comment by yelkarama** [comment]
Workaround is to add -Wno-void-pointer-to-enum-cast  to the clang commands but it may hide a real bug.

**Comment by davidducos** [comment]
Hi @64kramsystem @yelkarama , Thanks for reporting and fixing the issue!! you made possible to release this on v0.12.3-1 instead of v0.12.5-1.

Cheers!!
