### ISSUE TITLE
[BUG] innodb-optimize-keys didn't restore all secondary indexes

### ISSUE THREAD

**Issue by matthewlenz** [mydumper/mydumper#572]
mydumper --version
mydumper 0.11.5, built against MySQL 5.7.33-36

DB1:
`mydumper -B db_name -G -E -R -c`

Later both DB1 and DB2:
`myloader -d export-20220208-231522/ -o -s db_name --innodb-optimize-keys --disable-redo-log`

Result:
All secondary indexes restored properly on DB1 and about half the tables on DB2 were missing all of their secondary indexes.

**Comment by matthewlenz** [comment]
I just realized that DB2 was running 0.11.3.  Ooof.

**Comment by matthewlenz** [comment]
myloader0.13.1-1, built against MySQL 5.7.40-43 with SSL support with GZIP

Had this happen again.

```
myloader -d test_reload_cleaned -B dbname --innodb-optimize-keys AFTER_IMPORT_ALL_TABLES --max-threads-for-index-creation 1 --skip-definer -v 3
```

It failed to restore all the secondary indexes on the last table that was still restoring when all the other threads had finished.

**Comment by davidducos** [comment]
@matthewlenz can you test with the latest released version?

**Comment by davidducos** [comment]
@matthewlenz, I will be closing this until we have a test case on the latest pre/release.

**Comment by shiazen** [comment]
Hi.
--optimize-keys consistently fails to create secondary indexes for me.
Using v0.15.1-3 right now.
Logs look like:
`[ERROR] - Thread 14: Error switching to database dbname Restoring index`
