### ISSUE TITLE
Not able to get procedures even if I am passing -B

### ISSUE THREAD

**Issue by Saurabh-704** [mydumper/mydumper#575]
Hey All!

I am running command:

mydumper -p qwwrty -u qpg -P 3307 -h 109.118.19.90 -B employees  -o mysql_dump  --regex '^(?!(mysql\.|information_schema\.))'

But I am not able to get procedures even tho I am passing -B option that should dump all the things in databases.

Can anyone please help me with this?

Thanks in advance!

**Comment by davidducos** [comment]
Hi @Saurabh-704 you need to use -R to get the routing. Why you think that using -B you will get the store procedures? -B is to specify the database that you are going to dump. Please, check --help to know what the correct parameters to get the data that you need.
Cheers!
