### ISSUE TITLE
[BUG] changing the export folder name after mydumper --load-data will result in myloader failing to find the .dat files

### ISSUE THREAD

**Issue by matthewlenz** [mydumper/mydumper#576]
When building the corresponding files:

db_name.table_name.00000.dat.gz & db_name.table_name.00000.sql.gz

db_name.table_name.00000.sql.gz will contain something like the following:

```
LOAD DATA LOCAL INFILE 'export-20220210-105303/db_name.table_nbame.00000.dat.gz' REPLACE INTO TABLE `table_name` LINES TERMINATED BY '\n' (`id`,`some_col`);
```

If you rename the original folder from export-20220210-105303 to "some_folder" and then attempt to use myloader it will create the schema but then fail to load the data because the directory no longer exists.  Instead mydumper should forgo placing the original export directory name in the .sql file and instead myloader should chdir into the dump --directory.

Unfortunately this fix will break myloader compatibility with previous dumps that used mydumper --load-data

**Comment by davidducos** [comment]
Ok, nice catch! I will be reviewing why I took the decision of doing in that way and if I don't find any good reason, I will be create a pull request to fix it.
