### ISSUE TITLE
[BUG] mydumper --load-data --compress are not compatible

### ISSUE THREAD

**Issue by matthewlenz** [mydumper/mydumper#584]
Using mydumper --load-data and --compress will generate a .sql.gz file which contains something like the following:

```
LOAD DATA LOCAL INFILE 'export-20220210-105303/db_name.table_name.00000.dat.gz' ...
```

Mysql does not support loading gzipped files.

**Comment by davidducos** [comment]
Hi @matthewlenz , yes, --load-data and --compress and not fully compatible. What do you think that we should be doing? I offer a couple of options:
1. When these options are selected, give an error message and exits
2. Set the name as .dat (without .gz) in the load data statement. Then we can myloader to decompress the file temporary and deletes after it is loaded. The dat.gz file will stay there all the time.
3. Set the name as .dat (without .gz) in the load data statement, but you need to decompress the files not myloader.

What do you think about them? Do you have other options?

**Comment by matthewlenz** [comment]
@davidducos I'd think #2.  But I think it would need to only uncompress the temp files that are needed and immediately removing them after the data is loaded.  The reason I personally use --compress is because our primary production db is pretty huge and with text files --compress reduces the size by 90%.

Alternatively one of the very clever ways people get around this shortcoming in mysql 'load data' is by by creating a fifo on disk (mkfifo), gunzip'ing to that fifo (seperate process) and the pointing load data local infile at that fifo to read from it.

**Comment by davidducos** [comment]
I'm not a fan of LOAD DATA, that is why I'm going to ask, why don't you use ZSTD and INSERT statements?

Ok! so, we have a fourth way of doing it:
4. write the load statement as .dat. but if it sees that the LOAD data is a .sql.gz file (aka compressed file) will assume that a .dat.gz file exists and it will create a fifo and gunzip to it in a different thread.
