### ISSUE TITLE
It was not possible to process file missing debug information

### ISSUE THREAD

**Issue by WebKenth** [mydumper/mydumper#588]
**Describe the bug**
Using version 0.11.5 i've attempted to restore a backup
I have 1 folder containing all schema information and one containing all the data split into 5mb chunks

When attempting to restore the data it simply breaks on first .sql file and gives no explanation other than 

The first command with importing executes flawlessly
```
myloader --overwrite-tables \
--directory="use-this-one-schema" \
--verbose="3" \
--defaults-file="mydumper/myloader.ini" \
--threads="1";
```

**To Reproduce**
Command executed:
```
myloader --directory="use-this-one" \
--defaults-file="mydumper/myloader.ini" \
--verbose="3" \
--threads="8";
```
myloader.ini
```
[myloader_variables]
sql_mode='NO_AUTO_VALUE_ON_ZERO'
[myloader]
user=root
password=root
database=app
host=127.0.0.1
```

When running the following output happens:

```
** Message: 08:54:46.862: Config file loaded
** Message: 08:54:46.902: Server version reported as: 8.0.26-17
** (myloader:61050): CRITICAL **: 08:54:47.158: It was not possible to process file: XXX.sql (3)
```

What mydumper and myloader version has been used?
`myloader 0.11.5, built against MySQL 8.0.27`

**Expected behavior**

When setting a verboose level of 3 all information should be made available
a simple CRITICAL error is not enough to debug why this is not working as intended

I expected some SQL error to be thrown if it was invalid or atleast the myloader to throw an internal error when it hits something unexpected

For reference manually doing a `mysql < XXX.sql` works so it is highly unlikely to be a sql error

**Environment (please complete the following information):**
 - OS version: Mac - macOS Monterey 12.2.1
 - MyDumper version: mydumper 0.11.5, built against MySQL 8.0.27 | myloader 0.11.5, built against MySQL 8.0.27

**Comment by WebKenth** [comment]
Running an older version of mydumper `myloader 0.10.0, built against MySQL 10.5.8` works however then i love the --defaults-file functionality that i require for creating tables ( sql mode )

**Comment by davidducos** [comment]
Hi @WebKenth , can you try with the absolute location of the default file?

**Comment by davidducos** [comment]
I will need the content of the file that is failing

**Comment by WebKenth** [comment]
> Hi @WebKenth , can you try with the absolute location of the default file?

No change, and since it prints `Config file loaded` i doubt that's where the underlying issue lies

I can add different flags and it prints additional checks, but the SQL import itself is not reporting why it is failing which is this issues primary concern

> I will need the content of the file that is failing

I cannot give you the contents of the file as it contains sensitive data

it is a simple `INSERT INTO `XXX` VALUES ()` query

I can use `mysql < xxx.sql` and it works without any issues albeit slower than myloader
it works on version 0.10.0 

Just for reference it is for a magento 2 application import

First i take a schema dump with no views or data which produces this create table:


```mysql
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

/*!40103 SET TIME_ZONE='+00:00' */;
CREATE TABLE `amasty_audit_log_entry` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Id',
  `date` datetime DEFAULT NULL COMMENT 'Log Entry Date',
  `username` text COMMENT 'Username',
  `type` text COMMENT 'Type',
  `category` text COMMENT 'Category',
  `category_name` text COMMENT 'Category Name',
  `parameter_name` text COMMENT 'Log Entry Parameter Name',
  `element_id` int unsigned NOT NULL COMMENT 'Element Id',
  `item` text COMMENT 'Item',
  `store_id` int DEFAULT NULL COMMENT 'Store Id',
  `ip` text COMMENT 'Log Entry User Ip Address',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=80277 DEFAULT CHARSET=utf8 COMMENT='amasty_audit_log';
```

I then run another mydumper for data one which produces a .sql file containing

```mysql
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `amasty_audit_log_entry` VALUES (....)
```

When using myloader to import the schemas are run using a single thread and executes without issues
```
** Message: 09:17:14.026: Thread 1 restoring table `app`.`amasty_audit_log_entry` from x-schema/x.amasty_audit_log_entry-schema.sql
** Message: 09:17:14.026: Dropping table or view (if exists) `app`.`amasty_audit_log_entry`
** Message: 09:17:14.049: Creating table `app`.`amasty_audit_log_entry` from x-schema/maulund.amasty_audit_log_entry-schema.sql
```
(Side note: in version 0.10 the schema creation does not print the "restoring table..." line)

 I verify the tables are created and they are infact empty with autoincrement reset
 
 but when i run the myloader for the data folder i get the error:
 
 `It was not possible to process file: x.amasty_audit_log_entry.sql`


If it was a mysql error it would surely also happen when you run `mysql < x.sql` right? or am i confused here


We had an issue where Magento third party modules sometimes provide a `00-00-0000 00:00:00` default datetimestamp for their table schema's and we had to use `NO_AUTO_VALUE_ON_ZERO ` to filter out these values

Could this be a hint on why it is not working when importing?

**Comment by davidducos** [comment]
Aha! what version of mydumper did you use to take that backup?!?!! This filename: x.amasty_audit_log_entry.sql is not supported in newer versions. If I'm not mistaking since v0.11.x, we changed the backup format.

**Comment by WebKenth** [comment]
> Aha! what version of mydumper did you use to take that backup?!?!! This filename: x.amasty_audit_log_entry.sql is not supported in newer versions. If I'm not mistaking since v0.11.x, we changed the backup format.

Ohh my god i never considered looking at the server version

It is a whooping old `mydumper 0.9.5.1, built against MySQL 10.3.23`

Thank you!

**Comment by WebKenth** [comment]
> ok, try with newer version and close it if it is working properly.

Unfortunately that requires a larger process as i do not have access to system administration tools on our production servers 

I'ved tested locally using same version to dump and import and it works ;)
