### ISSUE TITLE
[BUG] Improper processing of defaults-file format

### ISSUE THREAD

**Issue by fliespl** [mydumper/mydumper#589]
**Describe the bug**
--defaults-file=my.cnf doesn't support quotes options

**To Reproduce**

```
      [mydumper]
      user = "root"
      password = "${MYSQL_ROOT_PASSWORD}"
      host = "mariadb"
```

Mydumpper tries to login to host "mariadb" (with double quotes) as well using user "root" (with double quotes).

**Expected behavior**
Connecting properly using unquoted values as mysql/mariadb does.

From docs:

```
The value optionally can be enclosed within single quotation marks or double quotation marks, which is useful if the value contains a # comment character.
```

**Environment (please complete the following information):**
 - Debian 11
 - MyDumper version: 0.11.5-2

**Comment by davidducos** [comment]
Hi @fliespl, 

Just to clarification, when you said: "From docs: ..." what docs are you referring to? as it is mysql/mariadb docs, we try to follow guidelines from them but MyDumper is an open source tool developed by the community. 
There is a function that we are using to parse the config file for internal usage. The mydumper/myloader section is used by the driver that you decided to use when you compiled it. So, it might be a MyDumper bug or from your driver. We need to investigate a bit more about it. I will review it and let you know what I found.

**Comment by fliespl** [comment]
It's from mysql / mariadb docs - sorry about not being clear about it.

I have used debian 11 + packaged deb file. I didn't compile on my own.

**Comment by davidducos** [comment]
Hi @fliespl, 

Finally, it was what I thought it was. The PR linked to this ticket will fix the bug. If it is not clear for you, just check line 68 of [src/common.c](https://github.com/mydumper/mydumper/pull/590/files#diff-f6c5883a603e481644b9ef028b158acace9eabf59598f164dbec7b97d8da231f)

**Comment by fliespl** [comment]
@davidducos wow! What a speed :) Appreciate it!
