### ISSUE TITLE
Myloader won't load files which are symlink

### ISSUE THREAD

**Issue by fliespl** [mydumper/mydumper#597]
**Describe the bug**
Tried to use myloader to only load some of the tables from main dump. To do is I symlinked necessary tables in another dir and tried to load from there. 

Myloader failes with following:

```
** Message: 07:46:06.446: Config file loaded

** (myloader:58): CRITICAL **: 07:46:06.454: cannot open file dump-temp/xxx.user-schema.sql.zst (2)

** (myloader:58): CRITICAL **: 07:46:06.454: cannot open file dump-temp/xxx.branch-schema.sql.zst (2)

** (myloader:58): CRITICAL **: 07:46:06.454: cannot open file xxx.branch.00000.sql.zst (2)

** (myloader:58): CRITICAL **: 07:46:06.454: Thread 1 issue restoring xxx.branch.00000.sql.zst: 

** (myloader:58): CRITICAL **: 07:46:06.454: cannot open file xxx.user.00000.sql.zst (2)

** (myloader:58): CRITICAL **: 07:46:06.455: Thread 4 issue restoring xxx.user.00000.sql.zst:
```

```
ls -al dump-temp
total 12
drwxr-xr-x 2 root root 4096 Feb 28 07:46 .
drwxrwxrwx 7 root root 4096 Feb 28 07:46 ..
-rw-r--r-- 1 root root  148 Feb 28 07:46 metadata
lrwxrwxrwx 1 root root   43 Feb 28 07:46 xxx.branch-schema.sql.zst -> dump/xxx.branch-schema.sql.zst
lrwxrwxrwx 1 root root   42 Feb 28 07:46 xxx.branch.00000.sql.zst -> dump/xxx.branch.00000.sql.zst
lrwxrwxrwx 1 root root   41 Feb 28 07:46 xxx.user-schema.sql.zst -> dump/xxx.user-schema.sql.zst
lrwxrwxrwx 1 root root   40 Feb 28 07:46 xxx.user.00000.sql.zst -> dump/xxx.user.00000.sql.zst
```

Everything works fine if I simply move/copy files.

**To Reproduce**
Command executed:
myloader dump-temp

What mydumper and myloader version has been used?
v0.11.5-2

**Expected behavior**
Properly load from symlinks as well.

**Comment by davidducos** [comment]
@fliespl 
Error 2 means:
`
# perror 2
OS error code   2:  No such file or directory
`
is the file correctly linked?
I was able to link and import a testing database with zstd compression. 
Please, provide a test case, so I can check it again

**Comment by fliespl** [comment]
@davidducos you are totally right. I had relative link without going one dir up. Stupid me! Thanks...
