### ISSUE TITLE
[BUG] mydumper zstd doesn't run on CentOS due to missing libzstd package dependency

### ISSUE THREAD

**Issue by michaelcoburn** [mydumper/mydumper#602]
**Describe the bug**
Installation of the zstd package succeeds on CentOS 7 however when you run the mydumper binary you get an error that it is missing libzstd files:
```
$ mydumper --help
mydumper: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory

$ myloader --help
myloader: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
```

We should create a package dependency to `libzstd`:
```
Requires: libzstd
```
**To Reproduce**
Command executed:
* mydumper --help
* myloader --help
To get it to work you need to install libzstd.
```
Name        : libzstd
Arch        : x86_64
Version     : 1.5.0
Release     : 1.el7
Size        : 370 k
Repo        : epel/x86_64
Summary     : Zstd shared library
URL         : https://github.com/facebook/zstd
License     : BSD and GPLv2
Description : Zstandard compression shared library.
```

What mydumper and myloader version has been used?
`mydumper-0.12.1-1-zstd.el7.x86_64`
**Expected behavior**
We should see normal output for running of the binary, for example:
```
$ mydumper --help | head -5
Usage:
  mydumper [OPTION…] multi-threaded MySQL dumping

Help Options:
  -?, --help                      Show help options
```
**Environment (please complete the following information):**
 - OS version: CentOS Linux release 7.9.2009 (Core)
 - MyDumper version: mydumper 0.12.1, built against MySQL 5.7.34-37

**Additional context**
David Ducos has great hair

**Comment by davidducos** [comment]
Hi @michaelcoburn 
I rewrote the building scripts, I will be creating the mydumper-builder repo in the future to share with the community as it was the old builder. I added the dependency for rpm and also for deb packages.
It will be a requirement from the next release.
