### ISSUE TITLE
[BUG] --regex Mismatched database creation statements were exported

### ISSUE THREAD

**Issue by Fanduzi** [mydumper/mydumper#612]
**Describe the bug**
`--regex` Mismatched database creation statements were exported

**To Reproduce**
Command executed:
mydumper
```
mydumper --ask-password --user=superuser --host=172.16.21.x --port=3306 --regex='^(processengine\.|organization\.|pctp\.|yfund\.|pay\.)' --outputdir=/data/dump/k8s/ok --verbose=3 --compress --threads=4 --triggers --events --routines --use-savepoints --logfile=/data/dump/k8s/ok.log
```
then mydumper exported some schema create sql that I didn't need
```
-rw-r--r-- 1 root root       107 Mar 15 16:00 account-schema-create.sql.gz
-rw-r--r-- 1 root root       120 Mar 15 16:00 accumulus_account-schema-create.sql.gz
-rw-r--r-- 1 root root       114 Mar 15 16:00 activiti2-schema-create.sql.gz
-rw-r--r-- 1 root root       112 Mar 15 16:00 activiti-schema-create.sql.gz
-rw-r--r-- 1 root root       134 Mar 15 16:00 agreement-schema-create.sql.gz
-rw-r--r-- 1 root root       104 Mar 15 16:00 ali-schema-create.sql.gz
-rw-r--r-- 1 root root       109 Mar 15 16:00 anony-schema-create.sql.gz
-rw-r--r-- 1 root root       112 Mar 15 16:00 antispam-schema-create.sql.gz
-rw-r--r-- 1 root root       116 Mar 15 16:00 apollo_lint-schema-create.sql.gz
-rw-r--r-- 1 root root       117 Mar 15 16:00 approve_risk-schema-create.sql.gz
-rw-r--r-- 1 root root       111 Mar 15 16:00 atx_uitest-schema-create.sql.gz
```
When I used myloader to import, these databases were also created
>I don't remember much about it, but I don't think the previous version was like this

myloader
```
myloader --ask-password --user=superuser --host=172.16.22.x --port=3306 --compress-protocol --verbose=3 --enable-binlog --threads=4 -d /data/dump/k8s/ok --logfile=/data/dump/k8s/loader/ok.log
```

version
```
mydumper  --version
mydumper 0.12.1, built against MySQL 5.7.34-37

myloader --version
myloader 0.12.1, built against MySQL 5.7.34-37
```

**Expected behavior**
I want only the databases and data matched by regex to be exported

If I have an instance with hundreds of databases, I only want to export a few databases and import them into another instance. How should I do this? Use `--database` to export them one by one?

**Environment (please complete the following information):**
```
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

**Comment by davidducos** [comment]
Hi @Fanduzi,

--database accepts a list of databases since 0.12.1, please, test it and let me know. We might need to change the documentation. Even though, this is a bug that we need to fix. I was aware of this but I was not able to focus. Thanks for reporting and I will be working on it for the next release.

**Comment by Fanduzi** [comment]
> Hi @Fanduzi,
> 
> --database accepts a list of databases since 0.12.1, please, test it and let me know. We might need to change the documentation. Even though, this is a bug that we need to fix. I was aware of this but I was not able to focus. Thanks for reporting and I will be working on it for the next release.

thank you! I will try `--database`

**Comment by Fanduzi** [comment]
`--database` works fine

**Comment by davidducos** [comment]
Hi @Fanduzi , looks like this was fixed on a PR. I'm not sure which one, sorry!
