### ISSUE TITLE
[ myloader ] Include tables even if the -schema files are not found

### ISSUE THREAD

**Issue by balusarakesh** [mydumper/mydumper#617]
Hi,

**Describe the bug**
 - We have a huge DB with tables consisting of millions of rows so, we used mydumper to dump tables (data ONLY without schema) one-by-one
 - here's the command we used to dump tables:
 ```
 mydumper --complete-insert --trx-consistency-only --less-locking --lock-all-tables --rows 100000 --max-rows 300000 --compress-protocol --compress  --no-schemas --events --user=USERNAME --host=HOST --threads=1 --password=PASSWORD -B DB_NAME -T TABLE_NAME  --outputdir=OUTPUT_DIR
 ```
 - example OUTPUT_DIR consists of the following files (ls -l):
 ```
 - metadata
 - DB_NAME.TABLE_NAME.00000.sql.gz
 ```

**To Reproduce**
 - When we try to run the following myloader command we get errors saying it is not able to process file:

```
myloader --verbose 3 --compress-protocol --threads 12 --no-delete -h HOST -u root --password PASSWORD --source-db DB_NAME -d OUTPUT_DIR

** Message: 20:17:50.024: Server version reported as: 5.7.30-log

** (myloader:95805): CRITICAL **: 20:17:50.481: It was not possible to process file: (null)
```

 - We also tried to empty the contents of the metadata file and we still get the same error
 - if we completely remove the `metadata` file we get `OUTPUT_DIR is not a mydumper backup`

**What mydumper and myloader version has been used?**
we used the packages `mydumper_0.12.1-1.focal_amd64.deb` and `mydumper_0.11.5-2.focal_amd64.deb`
mydumper version: `0.21.1`
myloader version: `0.21.1` and `0.11.5` (tried both versions and getting the same error for both versions)

**Expected behavior**
 - Able to import .sql files using myloader

**Environment (please complete the following information):**
```
/etc/lsb_release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```
**Additional context**
metadata contents:
```
Started dump at: 2022-03-15 15:40:43
SHOW MASTER STATUS:
        Log: mysql-bin-changelog.150438
        Pos: 111274119
        GTID:0b275d9c-01fb-11eb-a8a1-12f64dbb8fb7:1-38967286804:38967286806-38967286858,
269dd99a-02b2-11eb-8fe8-0ab104c3b841:1-1722,
2d33bce2-af00-38c8-85cb-b5e281ccf8c5:1-489140615,
3a8187c7-7bfe-312f-b054-6f35390da6a3:1-5529620,
76ce9d84-ceeb-36d2-bc67-236e1445c37c:1-317574103,
99da4460-df30-30e3-8fca-a3ea5ea05079:1-330841891,
fbe5aaec-94ba-3079-b429-827e7dea4b8f:1

SHOW SLAVE STATUS:
        Host: 10.1.4.59
        Log: mysql-bin-changelog.959844
        Pos: 109584092
        GTID:0b275d9c-01fb-11eb-a8a1-12f64dbb8fb7:1-38967286804:38967286806-38967286858,
269dd99a-02b2-11eb-8fe8-0ab104c3b841:1-1722,
2d33bce2-af00-38c8-85cb-b5e281ccf8c5:1-489140615,
3a8187c7-7bfe-312f-b054-6f35390da6a3:1-5529620,
76ce9d84-ceeb-36d2-bc67-236e1445c37c:1-317574103,
99da4460-df30-30e3-8fca-a3ea5ea05079:1-330841891,
fbe5aaec-94ba-3079-b429-827e7dea4b8f:1

Finished dump at: 2022-03-15 15:40:43
```

**Comment by balusarakesh** [comment]
nevermind, I had to include the schema files in the folder

**Comment by balusarakesh** [comment]
I'm not an expert but I think we can fix this easily by updating the table schema to `IF TABLE NOT EXISTS`....right?

**Comment by davidducos** [comment]
Hi @balusarakesh , I already requested to mysql https://bugs.mysql.com/bug.php?id=103791

**Comment by davidducos** [comment]
Hi @balusarakesh , I analyzed again and I realized that make no sense. So I added a better logging to let you know know what is the issue.
