### ISSUE TITLE
[BUG] Ctrl+c detected but process not stopped

### ISSUE THREAD

**Issue by str** [mydumper/mydumper#622]
**Describe the bug**
When running, if I want to cancel an import, I try to [ctr] + [c], which usually stops the process. 

myloader tries to ask me to confirm, but after I confirm, nothing happens.

![image](https://user-images.githubusercontent.com/123817/159583150-7f467a12-bdae-4ba3-a67f-9d58bfa4f512.png)

**Comment by davidducos** [comment]
Hi @str , yes! sorry about that, there are some scenarios that I'm still investigating that cause the situation that you mention.

I'm not sure when I'm going to be able to tackle this as I'm working on another important issue.

**Comment by davidducos** [comment]
#625

**Comment by davidducos** [comment]
On release v0.12.7-1, we change several things in myloader which will allow us to fix easily this kind of issues. Could you test again after release v0.12.7-1 and let us know if you still have issues?
BTW, take into account that jobs that are already running are not stoped, just know jobs are not processed, this means that, if you have a 2 GB files that is being imported, then you will need to wait til that file finish and then myloader will stop.
