### ISSUE TITLE
Missing column in dump file

### ISSUE THREAD

**Issue by samujob** [mydumper/mydumper#624]
- I am using mydumper to dump one table from a database
- The database that I am dumping from is a replica (I have setup replication from the master to this database)
- The sql_mode has ALLOW_INVALID_DATES
- This table has a composite primary key - say col1 (varchar), col2 (datetime) and col3 (varchar)
- The col2 (datetime) has default value CURRENT_TIMESTAMP

When I restored the dump on the target, I found that all values in col2 were default value generated by CURRENT_TIMESTAMP. I then investigated the dump file and found that the col2 is not in the insert statement at all.

Any idea as to why mydumper would not include this column in the dump?

**Comment by davidducos** [comment]
Hi @samujob , i need the table structure and what version are you using?

**Comment by samujob** [comment]
> Hi @samujob , i need the table structure and what version are you using?

Version - mydumper 0.9.5
Below is the table structure, I have removed some columns. The column that is missing from the dump is d_date

Create Table: CREATE TABLE `TABLE1` (
  `c_c2_code` varchar(20) NOT NULL,
  `c_br_code` varchar(45) DEFAULT NULL,
  `c_ucode` varchar(45) DEFAULT NULL,
  `d_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `c_item_code` varchar(100) NOT NULL,
  `c_item_name` varchar(100) DEFAULT NULL,
  `c_vendor_item_code` varchar(100) DEFAULT NULL,
  `c_rep_item_name` varchar(200) DEFAULT NULL,
  `c_mfac_code` varchar(100) DEFAULT NULL,
  .......
  PRIMARY KEY (`c_c2_code`,`d_date`,`c_item_code`),
  KEY `date` (`d_date`),
  KEY `C2code` (`c_c2_code`,`c_item_code`,`c_mfac_code`),
  KEY `mfac` (`c_mfac_code`),
  KEY `stkidx` (`c_c2_code`,`c_br_code`,`c_item_code`,`d_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

**Comment by davidducos** [comment]
Hi @samujob , you need to test with newer version of mydumper.

**Comment by samujob** [comment]
Thanks @davidducos I was able to use the latest version and successfully dump and restore the table I mentioned earlier. But am facing another problem now, when I started the dump for full database, the dumper just stops after few minutes with the following on console:

mydumper --host=**** --user=**** --password=**** --rows=25000 -v 3 --compress --build-empty-files --threads=4 --compress-protocol --complete-insert --trx-consistency-only --kill-long-queries --outputdir /dumpdrive/mydumper/qadump/fulldb --logfile /dumpdrive/mydumper/qadump/fulldb.log

Killed

real 21m15.928s
user 6m20.536s
sys 0m33.825s


The log file only has [INFO] and there is no error or warning logged in the log files. Any pointers about what the issue could be here.

**Comment by davidducos** [comment]
Looks like an OOM issue, check the syslog to confirm

**Comment by samujob** [comment]
You are right @davidducos - the process is being killed by kernel because of OOM issue. Do you have any recommendation to tune/change the parameter we are using in the mydumper command above? There are couple of very large tables to migrate > 200 million rows.

**Comment by davidducos** [comment]
Hi @samujob , it is weird to see that latest version of mydumper causes an OOM scenario as it is not creating all jobs at once. Check or share the log file, to see how many jobs are in the queue. You might also want to try with jemalloc with LD_PRELOAD, but I never tested it.

**Comment by davidducos** [comment]
Or increase de value of --rows

**Comment by samujob** [comment]
@davidducos  - I tried again bumping up the VM running mydumper to 128GB RAM and 32 vCPU's and increasing the rows to 100000. It ran a little longer this time but again failed with OOM error.
[log.txt](https://github.com/mydumper/mydumper/files/8368309/log.txt)

**Comment by davidducos** [comment]
Hi @samujob can you share the OMM killer entry in the syslog? It is strange to see an oom kill with such small amount of jobs in the queue.

**Comment by samujob** [comment]
> Hi @samujob can you share the OMM killer entry in the syslog? It is strange to see an oom kill with such small amount of jobs in the queue.

@davidducos 

[ 2032.756816] [   8816]     0  8816 32748911 32409361 260108288        0             0 mydumper
[ 2032.756818] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice,task=mydumper,pid=8816,uid=0
[ 2032.756872] Out of memory: Killed process 8816 (mydumper) total-vm:130995644kB, anon-rss:129637444kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:254012kB oom_score_adj:0
[ 2032.767904] mydumper: page allocation failure: order:0, mode:0x100cca(GFP_HIGHUSER_MOVABLE), nodemask=(null),cpuset=/,mems_allowed=0
[ 2032.767908] CPU: 4 PID: 8816 Comm: mydumper Not tainted 5.4.0-1073-azure #76~18.04.1-Ubuntu

**Comment by davidducos** [comment]
I will need the metrics of the memory usage to understand at what moment is starting to reserve that amount of memory as it is reaching to 130GB.
