### ISSUE TITLE
[new idea, maybe] create table -> load data -> create PK -> create Indexs (will be better)

### ISSUE THREAD

**Issue by firdibasri** [mydumper/mydumper#628]
Hi,

Based my experiencing using MyDumper/Loader is very fast. Very good tool!

But, I have a table:
PK: column ID
Index: some columns
Total data: more than 10 million

MyDumper:
Yes this is very fast to load to file (some minutes and done)

MyLoader:
No, this is very slow, needs hours and NOT FINISH until I kill the process :(

My suggestion ( I don't know this is good or not):
The tool should have these steps:
1. Step 1, Create table without PK and without Indexing table
2. Next, load the data into table
3. Alter table to add the PK (if exists from source DB)
4. Finally, Create index(s) 

Maybe this method almost the same with "mysqldump --disable-keys" but this woks only with MyISAM, not for the InnoDB which is InnoDB now the default for mysql/mariadb

I try create a small script (shell script) to apply the method (step 1-4) and the result takes only a few minutes to be done.

Why do I create own script file? Because mydumper/myloader create the table to the destination DB is including PK+indexes (if exists, and CMIIW), so when the data (example 50k row) trying to input to the table, the PK and Indexes is involved, next 50k row it take longer, next 50k row more longer than before, and so on.... maybe this why MyLoader takes very long time to finish upload the data

Because I already love with this tool (mydumper/myloader), I hope the developer have solution better for this, 

Thank you very much,

**Comment by davidducos** [comment]
Hi @firdibasri, love to hear that you like the tool. Myloader has several options to run faster, but before tuning myloader, there are some options for mydumper that affects myloader. Are you using -r and/or -F in mydumper? That will split the dump in several files allowing myloader to import with multiple threads. 
Myloader has the option of --innodb-optimize-keys to import the data first and then the indexes. And depending your database, there are others options. Please recién --help for more info about them.
