### ISSUE TITLE
[myloader] 

### ISSUE THREAD

**Issue by fany9999** [mydumper/mydumper#630]
hello, when I use myloader, the speed is fast at first, but then it becomes slower and slower, why is this?, 
here is my command:
mydumper -u test -p test -h xxx -P xxx -B mysql_db -o /mysql_file -c -k -F 50 --skip-tz-utc -t 10 --order-by-primary
myloader -u test -p test -h xxx -P xxx -C -o -t 10 -v 3 -q 5000 --max-threads-per-table 10 --innodb-optimize-keys -B mysql_db -d /mysql_file

**Comment by davidducos** [comment]
Hi @fany9999 I need the log file to be able to answer you

**Comment by fany9999** [comment]
> 


Thanks, I solved the problem by replacing hdd with ssd

**Comment by fany9999** [comment]
@davidducos 
Thanks, I solved the problem by replacing hdd with ssd
