### ISSUE TITLE
[BUG] Long-running table loads don't report time correctly in myloader

### ISSUE THREAD

**Issue by swechsler** [mydumper/mydumper#632]
**Describe the bug**
Table loads running for multiple days report incorrectly-formatted import timing values in end-of-load summary:

```
** Message: 06:16:37.025: Import timings:
** Message: 06:16:37.025: Data          | Index         | Total         | Table
** Message: 06:16:37.025: 2 03:2766:7113        | 0 04:56:29    | 2 08:2763:7083        | `database`.`tablename`
```

**To Reproduce**
Load a table that takes longer than one day

**Command executed:**
`myloader -d ~/datadir/dumper.11534/ --innodb-optimize-keys -o -h instancename -t 16 -v 3`

**What mydumper and myloader version has been used?**
`myloader 0.12.1, built against MySQL 5.7.34-37`

**Expected behavior**
two-digit hours, minutes and seconds should be printed

**Environment (please complete the following information):**
`CentOS Linux release 7.9.2009 (Core)`
`myloader 0.12.1, built against MySQL 5.7.34-37`

**Comment by davidducos** [comment]
Hi @swechsler you can test with master and compile it yourself or wait until v0.12.3 release
