### ISSUE TITLE
[BUG] Broken tables should not be marked as warning 

### ISSUE THREAD

**Issue by boukandouramhamed** [mydumper/mydumper#635]
**Describe the bug**
When dumping database mydumper should fail or mark broken table as critical and not warning 

**To Reproduce**
Command executed:
* First we need a broken table we can simulate this by running the following
`systemctl stop mysql`
`cat /dev/null > /var/lib/mysql/database/table.ibd`
`systemctl start mysql`

* We can check the broken table by running 
`mysqlcheck database` 

* Now if we want to dump our database mydumper will throw a warning for all broken tables
`mydumper --database database  --threads 4  --routines --outputdir restore`

**Expected behavior**
mydumper should throw an error or give option to mark it as critical or warning.

**Log**
** (mydumper:607): WARNING **: 05:28:41.156: Broken table detected, please review: database.table

**Environment:**
 - OS version: [ Debian 10 ]
 - MyDumper version: [ mydumper 0.9.5, built against MySQL 10.3.22]

**Comment by davidducos** [comment]
Hi @boukandouramhamed , usually after ERROR, we stop mydumper execution, do you want mydumper to stop if broken table has been found?
From my point of view, we can take a full backup even if broken tables has been found.

**Comment by boukandouramhamed** [comment]
Hey @davidducos, yes right @davidducos I want to stop mydumper execution on broker table just like mysqldump. 
I think it will be nice to have an option to control this. (whether to mark it as critical or warning)
