### ISSUE TITLE
[BUG] mydumper with Engine = Federated, in MariaDB doesnt create the table with Federated engine

### ISSUE THREAD

**Issue by firdibasri** [mydumper/mydumper#638]
Hi

Sorry if there were reports like this before

**Describe the bug**
Exec mydumper with table(s) engine=federated, but keep collect full of data/records. Should keep create the table only with engine=federated

**To Reproduce**

* mydumper with all the parameters
mydumper -u root -p D8r00t@DWH -h localhost --regex '^(fed_collection_1|fed_collection_2)' --routines --triggers --events --outputdir=non_core --threads=8 --compress -F 10

(Because the proses takes to long, I stop it)

* myloader with all the parameters
(not tested yet)

What mydumper and myloader version has been used?
Version: 0.12.1 (latest)

**Expected behavior**
Should just create table(s) with engine=federated and without any data include dump to file

**Log**

**Backup**

**Environment (please complete the following information):**
 - OS version: [Ubuntu 20.04]
 - MyDumper version: [ 0.12.1 ]
 - MariaDB 10.6.x

**Additional context**

Or is there any missing step from me to execute the mydumper? Or mydumper not yet support for this engine (federated)?

thank you for your attention

**Comment by davidducos** [comment]
Hi @firdibasri, Please, review [how to use regex](https://github.com/mydumper/mydumper#how-to-exclude-or-include-databases) as you are missing the database name.
