### ISSUE TITLE
Why the option -DWITH_BINLOG=ON doesn't work?

### ISSUE THREAD

**Issue by SZDRZ** [mydumper/mydumper#642]
Hi! I'm so sorry to disturb you so late. I would like to ask why the new version of mydumper no longer uses the binlog option?

![image](https://user-images.githubusercontent.com/103322931/162578873-7c472a63-1d66-4d67-9157-e4c72c9ebf5e.png)

**Comment by davidducos** [comment]
Hi @SZDRZ we stopped supporting binlog and removed the code for 2 reasons:
1- we had to move c++ our binlog implementation
2- there is no need. You can do the same with mysqlbinlog

**Comment by SZDRZ** [comment]
Thanks! I see.
