### ISSUE TITLE
[enhancement] Add option to myloader to load tables from largest to smallest

### ISSUE THREAD

**Issue by swechsler** [mydumper/mydumper#645]
Suppose you have four large tables of 300GB each, let's call them A, B C and D, and one massive table of 1TB; we'll call this E. With the current configuration (ASCII order) and a 16 thread (4 per table) load, the E table will not start loading until one of A, B, C or D have finished. At some point you will have many closed threads, and the total run time is ( {A or B or C or D}+E ). If E is started first, the total load time is only E. The problem is compounded with more tables of differing sizes.

**Comment by davidducos** [comment]
Hi @swechsler,
I working on the loading rules for a while now... there are different approaches which depend on mydumper options too. 
For instance, if you dumped the table in chunks or not.
Currently, the import order should be from largest to smallest, you can also set --max-threads-per-table to determine the amount of threads per table. We take the table size from the .metadata files per table. 

MySQL is using a different approach to load data concurrently, they are using just one thread per table. I want myloader to give users different options and I would like to measure in which scenarios MySQL is doing faster and in which others are faster.

**Comment by swechsler** [comment]
Hmm, you're right, I just examined the output afterwards. Not sure why I thought it was different. OK, you may as well close this.
