### ISSUE TITLE
[BUG] myloader always uses socket to connect to db

### ISSUE THREAD

**Issue by DerFels** [mydumper/mydumper#650]
**Describe the bug**
I am running a restore job with myloader in a gitlab ci/cd pipeline.
However, myloader is always trying to connect via `/var/run/mysqld/mysqld.sock` no matter how much I tell it to use a TCP connection instead.

More background:
According to the gitlab [documentation](https://docs.gitlab.com/ee/ci/services/#accessing-the-services), the service container can be reached via the name that you specify for the service in the `.gitlab-ci.yml`
When I tried that, I immediately ran into the error
`** (myloader:3798): CRITICAL **: 08:45:42.336: Error connection to database: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

I thought that because I had not specified an IP Address in the `-h` parameter for myloader, it chose to go the sock route.
So I found out the IP Address and handed it over inside my bash script
```
#!/bin/bash

set -e
.....

MYSQL_IP=$(grep 'percona-percona' /etc/hosts | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
myloader \
    -d ${db} \
    -v 3 \
    -t 5 \
    -h ${MYSQL_IP} \
    -u root \
    -p ${MYSQL_ROOT_PASSWORD} \
    -s $db
....
```
But again myloader used the socket.
Then I tried to circumvent this behaviour, by specifying a `defaults-file` and force it to use TCP
```
....
MYSQL_IP=$(grep 'percona-percona' /etc/hosts | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=${MYSQL_IP}
echo ${MYSQL_IP}
cat <<EOT >> my.cnf
[client]
user="root"
password="${MYSQL_ROOT_PASSWORD}"
host="${MYSQL_IP}"
protocol=tcp
EOT

myloader \
    -d ${db} \
    -v 3 \
    -t 5 \
    -s $db \
    --defaults-file=my.cnf
```
**To Reproduce**
Command executed:
* mydumper with all the parameters
* myloader with all the parameters

What mydumper and myloader version has been used?

**Expected behavior**

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
`** (myloader:3798): CRITICAL **: 08:45:42.336: Error connection to database: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04
 - MyDumper version: 0.12.1-1

**Additional context**
I'm losing my mind about this :) 
Am I blind or is there a bug in the myloader code?

**Comment by davidducos** [comment]
Hi @DerFels , can you change [client] to [myloader] in the configuration file and let me know if that works?

**Comment by DerFels** [comment]
Sadly that changes nothing, I still get
`** (myloader:3798): CRITICAL **: 12:48:26.992: Error connection to database: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

**Comment by DerFels** [comment]
Yep I'm doing that already, here is some log output
```
mysql: [Warning] Using a password on the command line interface can be insecure.
OK
OK
172.17.0.2
let's check what's inside my.cnf
[myloader]
user="root"
password="blabla123"
host="172.17.0.2"
protocol=tcp
```

**Comment by davidducos** [comment]
Hi @DerFels, can you try with dirname and filename when you define the path to the --defatuls-file? for instance /root/my.cnf instead of just my.cnf ?

**Comment by DerFels** [comment]
Hi @davidducos your idea was correct, but even when I specify the exact path it doesn't work
`echo "we are in: $(pwd)"` -> we are in: /builds/sys/ci/mysql-backup-test

```
...
mkdir ./backup
cat <<EOT >> ./backup/my.cnf
[myloader]
user="root"
password="${MYSQL_ROOT_PASSWORD}"
host="${MYSQL_IP}"
protocol=tcp
EOT

echo "let's check what's inside my.cnf"
cat ./backup/my.cnf

  myloader \
    -d ${db} \
    -v 3 \
    -t 5 \
    -s $db \
    --defaults-file=/builds/sys/ci/mysql-backup-test/backup/my.cnf
```
Output
```
let's check what's inside my.cnf
[myloader]
user="root"
password="blabla123"
host="172.17.0.2"
protocol=tcp

** (myloader:3803): CRITICAL **: 13:27:24.292: Error connection to database: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by davidducos** [comment]
Can you upload the log file?

**Comment by DerFels** [comment]
This is the log
```
mysql: [Warning] Using a password on the command line interface can be insecure.
OK
OK
172.17.0.2
we are in: /builds/sys/ci/mysql-backup-test
let's check what's inside my.cnf
[myloader]
user="root"
password="blabla123"
host="172.17.0.2"
protocol=tcp
##########################
# download finished @ Fri Apr 22 13:27:24 UTC 2022
blog-schema-create.sql.gz
blog.article-metadata
blog.article-schema.sql.gz
blog.article.00000.sql.gz
blog.article_element-metadata
blog.article_element-schema.sql.gz
blog.article_element.00000.sql.gz
blog.articles_to_elements-metadata
blog.articles_to_elements-schema.sql.gz
blog.articles_to_elements.00000.sql.gz
blog.board-metadata
blog.board-schema.sql.gz
blog.board.00000.sql.gz
blog.image-metadata
blog.image-schema.sql.gz
blog.image.00000.sql.gz
blog.image_galleries_to_images-metadata
blog.image_galleries_to_images-schema.sql.gz
blog.image_galleries_to_images.00000.sql.gz
blog.image_gallery_element-metadata
blog.image_gallery_element-schema.sql.gz
blog.image_gallery_element.00000.sql.gz
blog.migration_versions-metadata
blog.migration_versions-schema.sql.gz
blog.migration_versions.00000.sql.gz
blog.step_element-metadata
blog.step_element-schema.sql.gz
blog.step_element.00000.sql.gz
blog.text_element-metadata
blog.text_element-schema.sql.gz
blog.text_element.00000.sql.gz
blog.text_with_image_element-metadata
blog.text_with_image_element-schema.sql.gz
blog.text_with_image_element.00000.sql.gz
blog.user_group-metadata
blog.user_group-schema.sql.gz
blog.user_group.00000.sql.gz
blog.user_to_group-metadata
blog.user_to_group-schema.sql.gz
blog.user_to_group.00000.sql.gz
metadata
my.cnf
# checking size
 Starting restore-process
 Restoring blog now!
** (myloader:3803): CRITICAL **: 13:27:24.292: Error connection to database: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by davidducos** [comment]
Hi @DerFels , why don't we see the myloader header log?

**Comment by DerFels** [comment]
I don't know
myloader is started like this
```
myloader \
    -d ${db} \
    -v 3 \
    -t 5 \
    -s $db \
    --defaults-file=/builds/sys/ci/mysql-backup-test/backup/my.cnf
```
But the Critical error is all I see in the logs :(

**Comment by davidducos** [comment]
With this:
```
myloader \
    -d ${db} \
    -v 3 \
    -t 5 \
    -h ${MYSQL_IP} \
    -u root \
    -p ${MYSQL_ROOT_PASSWORD} \
    -s $db
```
you should get more lines than just the error. Can you test one more time?

**Comment by DerFels** [comment]
do I have to specify -h -u and -p? I thought it takes the values from the default file?

**Comment by DerFels** [comment]
I ran it with
```
myloader \
    -d ${db} \
    -v 3 \
    -t 5 \
    -h ${MYSQL_IP} \
    -u root \
    -p ${MYSQL_ROOT_PASSWORD} \
    -s $db \
    --defaults-file=/builds/sys/ci/mysql-backup-test/backup/my.cnf
```
now all I get is
`option parsing failed: Unknown option --protocol, try --help`

**Comment by davidducos** [comment]
Why don't you remove protocol from the file?

**Comment by DerFels** [comment]
Ok by removing the protocol from the config file, I get back to the problem in my other open issue
```
** Message: 17:03:31.601: Config file loaded
** Message: 17:03:31.607: Server version reported as: 5.7.37-40
** (myloader:3803): CRITICAL **: 17:03:31.624: It was not possible to process file: blog.article_element-schema.sql.gz (2) because real_db_name isn't found
```

I guess this relates to https://github.com/mydumper/mydumper/issues/613

**Comment by davidducos** [comment]
are you using non zstd packages on both cases?

**Comment by DerFels** [comment]
Sorry I have no idea what those packages are.
I use ubuntu:20.04 as the image and only install these packages on top: awscli mysql-client libatomic1 libglib2.0-0 curl

**Comment by davidducos** [comment]
I added the solution to this on #613
