### ISSUE TITLE
Feature request `--replace` option

### ISSUE THREAD

**Issue by kuba-lilz** [mydumper/mydumper#658]
mysqldump offers a `--replace` option that
`--replace           Use REPLACE INTO instead of INSERT INTO.`

This is useful when one wants to overwrite existing records on restore.
Any plan to offer this option in `mydumper`?

Currently even if I manually edit backups created with `mydumper` to use `RESTORE INTO` command instead of `INSERT INTO`, `myloader` fails to process them. Importing such files with other tools (I tried Sequel Ace) works just fine.

**Comment by davidducos** [comment]
Hi @kuba-lilz , 
Seems to be something really simple to implement, but I already close v0.12.3, so it will be on v0.12.5. In master will be before as I will be able to implement it in a few weeks, after releasing v0.12.3.
