### ISSUE TITLE
[BUG] myloader 0.12.1 restoring data Segmentation fault when using --skip-definer

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#659]
**Describe the bug**
myloader 0.12.1 use option(--skip-definer) restore data, will trigger a segmentation fault, after removing this option it works fine

**To Reproduce**
myloader -S /data/mysql80/p_cwpt_3300/run/my_3300.sock -u root -a -v 3 --set-names utf8 **--skip-definer** -o --purge-mode=TRUNCATE --disable-redo-log  -t 8 --max-threads-per-table 8 -r 50000 --innodb-optimize-keys -L import_cwpt.log -d 20220427020001/

What mydumper and myloader version has been used?
0.12.1

**Log**
![image](https://user-images.githubusercontent.com/9590209/165461758-751aca00-a0a0-4dc1-8bbe-f98fb4d5024e.png)
![image](https://user-images.githubusercontent.com/9590209/165461878-ace83fe7-a54c-4500-a079-8e9ef9b270cc.png)

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough
![image](https://user-images.githubusercontent.com/9590209/165462119-877c86dd-e177-4744-a500-7eaa2bc17d83.png)

**Environment (please complete the following information):**
 - OS version: CentOS 7
 - MyDumper version: 0.12.1

**Comment by davidducos** [comment]
Hi @peng19832 can you narrow the test case to just dump the CREATE statement that is failing and paste here the header of that statement?

**Comment by fredricj** [comment]
https://github.com/mydumper/mydumper/blob/736b55135246d402d60bba6b4cf3201effddc5ae/src/myloader_restore.c#L162
The issue occurs when there is a no definer for a procedure. from=NULL +1 will cause a segfault 2 lines later. Also of note is that this code doesn't work with username with spaces.

**Comment by davidducos** [comment]
@fredricj Thanks!!! I was able to fix the issue based on your comment!! And i also found a bug that I fixed too.
