### ISSUE TITLE
[Feature request] Would it be possible to provide a rpm for fedora?

### ISSUE THREAD

**Issue by NavidSassan** [mydumper/mydumper#667]
Would be greatly appreciated :)

**Comment by davidducos** [comment]
Mmmm... why not? not sure how hard would it be... have you ever try to compile it in Fedora?

**Comment by NavidSassan** [comment]
No, if its helpful i can try to find some time to do that

**Comment by NavidSassan** [comment]
I quickly tried to use your https://github.com/mydumper/mydumper_builder repo and the https://github.com/mydumper/mydumper/blob/master/package/build.sh script, however I got some errors. Before I run off into the wrong direction, is that still how you compile and build your packages? Can you point me in the right direction?

**Comment by davidducos** [comment]
That is not the repo that we are using currently, I need to update it. I will try to work on this on June. Meanwhile, can you try if it is possible to compile in Fedora?

**Comment by NavidSassan** [comment]
I wanted to use the existing automation to try that, but I will try it manually then

**Comment by davidducos** [comment]
Hi @NavidSassan, I understand your issues. I recommend you to use one of the OS that we already support or compile it on your own. MyDumper is quite simple to compile even with MariaDB. There is documentation is our Readme. I'm closing this now as there is nothing else that we can do. Please, open another issue if you have compilation issues related to MyDumper.
