### ISSUE TITLE
Get dump data from query executed inside a view and insert it into a different table

### ISSUE THREAD

**Issue by danilobarion1986** [mydumper/mydumper#669]
Hey there!

I'd like to know if there's some way to get all the data from a view when dumping them with `mydumper`, I couldn't find any option/parameter in the CLI to do that.

And besides that, after getting that data, I wish I could import it (with `myloader`) to a table with a specific name.

Is any of that possible?

Thanks for the great tool!

**Comment by davidducos** [comment]
Hi @danilobarion1986 , 
Makes no sense to use mydumper to export a view, as there is no pk to split the table into chunks, to export the data, you will need to use -F to get chunks.
Now, myloader will help you to speed up the import.
Let me see how hard will it be to allow view exports. 
About the table rename will be harder as we need to modify the string... might be simpler if you use --load and modify the LOAD DATA statement.

**Comment by danilobarion1986** [comment]
Hi! Thanks for the reply!
I'm trying to export a view, because I need to export the data that is the result of a join between two tables.
Then, I want to import that joined data into a different table, which has the schema equal to the result of that previous join.
