### ISSUE TITLE
[BUG] 0.12.3, Waiting for binlog lock, block large write transactions

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#670]
**Describe the bug**
In the process of exporting data using version 0.12.3, a large number of write transactions were blocked by binlog lock.
It is recommended to add the judgment of whether it is a stand-alone instance. If it is a stand-alone instance, then do not use the binlog lock.

**To Reproduce**
mydumper -h  -P 4100 -u backup -p password  --set-names=utf8 --less-locking --skip-tz-utc --use-savepoints --complete-insert --trx-consistency-only -R -G -c  -v 3 -r 100000 -L dump_20220509.log -o 20220509020001

What mydumper and myloader version has been used?
0.12.3
![image](https://user-images.githubusercontent.com/9590209/167332667-89e6d056-ef07-43a4-a2b6-81b0aeb50286.png)

**Environment (please complete the following information):**
 - OS version: CentOS 7
 - MyDumper version: 0.12.3

**Comment by davidducos** [comment]
Hi @peng19832 
What is your database version?

**Comment by peng19832** [comment]
> Hi @peng19832 What is your database version?

percona 5.7.35 and percona 8.0.25

**Comment by davidducos** [comment]
I'm confirming this bug, I will have to release a patch for fixing it.

**Comment by davidducos** [comment]
Hi @peng19832, as a workaround you should use: --no-backup-locks to take your backups.

**Comment by peng19832** [comment]
> 
OK, thanks for the reply.
That means, with this option, the backup will fall back to using FTWRL, right?

**Comment by peng19832** [comment]
> FTWRL needs to be used anyways as we need to sync the threads to dump the data. Take into account that --less-locking is only needed if you have non-innodb tables. BTW not sure why you are using --trx-consistency-only and --use-savepoints as it doesn't make sense to me...

Ah....
Because I did not find the coverage relationship between these options in the following usage help, I used them at the same time. Leave it to mydumper to choose the final option, and try to reduce the conflict of backup locks while ensuring transaction consistency.
https://github.com/mydumper/mydumper/blob/master/docs/mydumper_usage.rst
