### ISSUE TITLE
mydumper is generating *metadata file for each table

### ISSUE THREAD

**Issue by aloks2019** [mydumper/mydumper#674]
Mydumper is generating *metadata file for each table. This file contains number of imsert statements mentioned in file *.SQL.gz ; however there are separate files *sql.gz having actual insert statements.

However, myloader is not able to process those file and error is “cannot open file /database name.tablename-metadata.

backup command
mydumper —user —ask-password —compress —compress-protocol—triggers—events —routines —build-empty-files —try-consistency-only —kill-long-queries —outputdir

**Comment by aloks2019** [comment]
I couldn’t try latest version as rpm of mydumper for RHEL8 is not available

**Comment by davidducos** [comment]
As a workaround, just remove them.

**Comment by aloks2019** [comment]
Yeah!! Doing same for now.. I have deleted all the *-metadata files except “metadata” file.

**Comment by davidducos** [comment]
Can you prepare a test case? it was impossible for me to reproduce your issue.

**Comment by aloks2019** [comment]
I don’t see this issue in latest version
