### ISSUE TITLE
Cannot dump `mysql`.`innodb_index_stats` table ?

### ISSUE THREAD

**Issue by SZDRZ** [mydumper/mydumper#675]
Hello! I now have a requirement to export the table structure from "mysql" database. When I try to export, it is missing several tables...

mydumper version: 0.12.3-1
mysql version: MySQL 5.7.37
cmd to run:
`mydumper -h 127.0.0.1 -u root -p 123456 --database=mysql --no-data -e -G -R -o ./ -v 3`

# mysql system database:
![image](https://user-images.githubusercontent.com/103322931/168007733-cd4bcabf-b7f8-47fd-bd94-302561a3d05f.png)

# dump after
![image](https://user-images.githubusercontent.com/103322931/168007244-b1998c10-c91f-4dc5-9aab-573bca836069.png)

**Comment by davidducos** [comment]
Hi @SZDRZ , those are consider `special tables` and they are not being dumped https://github.com/mydumper/mydumper/blob/876846e8ee19fb6b735a2eea7c0a520e30342ef8/src/mydumper_working_thread.c#L923
