### ISSUE TITLE
[BUG] stream + csv crashing

### ISSUE THREAD

**Issue by str** [mydumper/mydumper#676]
**Describe the bug**
When using both csv + stream flags, the system crashes

**To Reproduce**
` mydumper --database myDB  --csv --stream > /dev/null`

**What mydumper and myloader version has been used?**
mydumper 0.12.3-1, built against MySQL 5.7.37-40

**Expected behavior**
system should not crash, but I get the following error message:

`** (mydumper:24354): CRITICAL **: 01:02:11.362: Backup directory not removed: export-20220513-010153`

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.

```
** Message: 01:02:05.179: Opening: export-20220513-010153/myDB.users.00000.sql
** Message: 01:02:05.179: File export-20220513-010153/myDB.users.00000.sql transfered | Global: 0 MB/s
** Message: 01:02:05.551: Opening: export-20220513-010153/myDB.gm_dynforms2_questions.00000.sql
** Message: 01:02:05.551: File export-20220513-010153/myDB.gm_dynforms2_questions.00000.sql transfered | Global: 0 MB/s
** Message: 01:02:10.439: Opening: export-20220513-010153/myDB.gm_docs_policy.00000.sql
** Message: 01:02:10.439: Non-InnoDB dump complete, unlocking tables
** Message: 01:02:10.439: File export-20220513-010153/myDB.gm_docs_policy.00000.sql transfered | Global: 0 MB/s
** Message: 01:02:10.439: Shutdown jobs enqueued
** Message: 01:02:10.439: Waiting jobs to complete
** Message: 01:02:10.439: Thread 1 shutting down
** Message: 01:02:10.439: Thread 4 shutting down
** Message: 01:02:10.439: Thread 3 shutting down
** Message: 01:02:11.361: Thread 2 shutting down
** Message: 01:02:11.361: Opening: export-20220513-010153/myDB.gm_docs_security.00000.sql
** Message: 01:02:11.361: Releasing DDL lock
** Message: 01:02:11.361: File export-20220513-010153/myDB.gm_docs_security.00000.sql transfered | Global: 0 MB/s
** Message: 01:02:11.361: Main connection closed
** Message: 01:02:11.361: Finished dump at: 2022-05-13 01:02:11
** Message: 01:02:11.361: Opening: export-20220513-010153/metadata
** Message: 01:02:11.362: File export-20220513-010153/metadata transfered | Global: 0 MB/s
** Message: 01:02:11.362: All data transfered was 290520 at a rate of 0 MB/s

** (mydumper:24354): CRITICAL **: 01:02:11.362: Backup directory not removed: export-20220513-010153
```

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**Environment (please complete the following information):**
 - OS version: ubuntu 22.04
 - MyDumper version: mydumper 0.12.3-1, built against MySQL 5.7.37-40

**Additional context**

**Comment by davidducos** [comment]
Hi @str , what is the content of export-20220513-010153 ???

Take into account that the backup if finishing, the only issue is that the temporary backup directory was not removed because there might be files in it.

**Comment by str** [comment]
The content in the export folder contains the data files in CSV format.

The stream only contains the `CREATE table`  scripts, no data.

**Comment by davidducos** [comment]
Oooooohhhh seems that we are forgetting to delete those files 🤦.

**Comment by str** [comment]
Well, not deleting the files is not a big issue. The CSV not being included in the stream is a major issue.

**Comment by davidducos** [comment]
checking both things...

**Comment by davidducos** [comment]
ups... they are not...

**Comment by str** [comment]
Seems I have to wait yet another version to test the CSV feature :(
