### ISSUE TITLE
Implement --skip-definer in mydumper

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#680]
@davidducos ah, my bad, I didn't mean any other databases (please just discard that part and sorry for the confusion). I meant any other tools, like just piping a dump into `mysql` in another environment that doesn't have all the users from the environment the data was dumped from.

My points for keeping `DEFINER` out of a dump are the following:
1. This way dump is portable: it can be just used without any further assumptions (e.g. loading with `myloader` with a certain option).
2. It's easier to diff dumps from different envs.
3. It plays nicer with version control for the same reason: if the schema and data are the same, the dump won't appear changed if it's from another env that has different set of users.

My case, in the essence, is the following. We have a database with application configuration (it's assumed to be fairly small and portable), and due to a view in the schema, I can't just take a dump from production and load it into a preproduction environment, so I ended up grepping out `/*!50013 DEFINER=...*/`. This `DEFINER` difference is the only thing I know that breaks portability of dumps, so I thought that discarding `DEFINER` would be a nice thing to have.

_Originally posted by @kamazee in https://github.com/mydumper/mydumper/issues/378#issuecomment-1126030080_

**Comment by matthewlenz** [comment]
@davidducos --skip-definer isn't removing definer from triggers.
