### ISSUE TITLE
[BUG] "real_db_name" isn't found for schema SQLs

### ISSUE THREAD

**Issue by Razican** [mydumper/mydumper#683]
**Describe the bug**
I'm getting the following critical error:
```
** (myloader:3509885): CRITICAL **: 08:45:41.129: It was not possible to process file: int1_16011.a8n_pipeline_command_s7e-schema.sql (2) because real_db_name isn't found. Restore without schema-create files is not supported
```

It says that a restore without schema-create files is not supported, but the file it mentions is the schema file itself, generated by mydumper (same version as myloader), so might be related to something else.

**To Reproduce**
The mydumper command I'm using:
```
mydumper -S /var/mysql/mysql.sock -B int1_16011 --events --less-locking -o /db_backups/int1_16011 --trx-consistency-only --threads 8 --statement-size 5000000 --chunk-filesize 500 --build-empty-files
```

And the myloader command I'm using:
```
myloader -S /var/mysql/mysql.sock -B int1_16011 -d /db_backups/int1_16011_replicator --threads 8 -e
```

Using mydumper & myloader:
```
myloader 0.12.3-2, built against MySQL 5.7.37-40
```

**Expected behavior**
I would expect the load to work without any critical error that stops the load.

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file:

```
2022-05-16 08:56:16 [INFO] - Server version reported as: 5.5.5-10.2.30-5-MariaDB-enterprise-log
2022-05-16 08:56:16 [DEBUG] - Thread 1: Starting import
2022-05-16 08:56:16 [DEBUG] - Thread 2: Starting import
2022-05-16 08:56:16 [DEBUG] - Thread 3: Starting import
2022-05-16 08:56:16 [DEBUG] - Thread 4: Starting import
2022-05-16 08:56:16 [DEBUG] - Thread 5: Starting import
2022-05-16 08:56:16 [DEBUG] - Thread 6: Starting import
2022-05-16 08:56:16 [DEBUG] - Thread 7: Starting import
2022-05-16 08:56:16 [DEBUG] - Thread 8: Starting import
2022-05-16 08:56:16 [DEBUG] - Adding database: int1_16011 -> int1_16011
2022-05-16 08:56:16 [ERROR] - It was not possible to process file: int1_16011.a8n_p6e_filter_table_column-schema.sql (2) because real_db_name isn't found. Restore without schema-create files is not supported
```

**Additional context**
These commands were working fine in mydumper/myloader 0.9 and 0.10, we are testing to upgrade to 0.12, but we just got this error with the same commands. Checking the usage file, I could not find that something changed in the commands.

**Comment by Razican** [comment]
Finally, I was able to make it work. It seems that if I use the `-B` parameter, it will fail (it doesn't matter if I put the `-s` parameter or not. If I don't use the `-B` parameter, then it works, and it doesn't matter if I put the `-s` parameter or not. So this might be something to be checked.

**Comment by davidducos** [comment]
I was not able to reproduce your issue, if you can develop a reproducible test case, please share and I will be reviewing it, meanwhile I will set this as invalid. Feel free to share more info or close it.

**Comment by sebastienbarre** [comment]
I can see that error as well.

I "accidentally" upgraded to 0.12.3-2 and kept seeing the same errors:
```
myloader(2238,0x102364580) malloc: *** error for object 0x600002dfc180: pointer being freed was not allocated
myloader(2238,0x102364580) malloc: *** set a breakpoint in malloc_error_break to debug
```
I just upgraded to  0.12.3-3 to hopefully fix it, and now pretty much all I see is the same:
```
** (myloader:5446): CRITICAL **: 19:14:47.966: It was not possible to process file: kwik.contracts_employees-schema.sql.gz (2) because real_db_name isn't found. Restore without schema-create files is not supported
```
Nothing else in my usage has changed, I've used the same scripts for eons.
The file `kwik.contracts_employees-schema.sql.gz` exists, tho I don't know what the `(2)` refers to.

**Comment by sebastienbarre** [comment]
OK for MacOS/homebrew users finding this, I got it working by reverting to the latest 0.11. Something was introduced in 0.12 that is breaking.
The steps are:
- unlink your current mydumper using: `brew unlink mydumper`
- manually download the `mydumper.rb` formula you wish to install instead. For example, head to [homebrew-core/mydumper.rb at HEAD · Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mydumper.rb), then click on the History button, and look for the commit that introduced the version you want (in my case, 0.11.5-2) then click on the "View at this point in history" button:
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/329967/169743564-b83651e6-f58c-4056-b52c-5501651251af.png">

* Click on the "Raw" button to see the raw `mydumper.rb` file, and download it to your drive ([this file](https://raw.githubusercontent.com/Homebrew/homebrew-core/b6383d612b63e2a3ba8bcb786849329e53cb90f7/Formula/mydumper.rb)).
* Build this formula from source using `brew install --build-from-source ~/Downloads/mydumper.rb`
* Test the version:
```
$ mydumper --version
mydumper 0.11.5, built against MySQL 8.0.29
```
* Enjoy `mydumper` working again :)

**Comment by YogSottot** [comment]
I have the same issue

**Describe the bug**
If target and source db have the same name, then if we use --database option in myloader we have this error.
If i remove --database in myloader command, then it is work.

**To Reproduce**
Command executed:
in mysql-console:
* create database sitemanager;
* use sitemanager;
* create table tutorials_tbl(
   tutorial_id INT NOT NULL AUTO_INCREMENT,
   tutorial_title VARCHAR(100) NOT NULL,
   tutorial_author VARCHAR(40) NOT NULL,
   submission_date DATE,
   PRIMARY KEY ( tutorial_id )
);

Then in bash-console:
* mydumper --threads 2 --compress --less-locking --use-savepoints --database sitemanager --outputdir /opt/backup/mydumper
* myloader  --verbose 3 --database sitemanager --directory /opt/backup/mydumper --overwrite-tables --threads 2


What mydumper and myloader version has been used?
mydumper 0.12.3-3, built against MySQL 5.7.37-40
myloader 0.12.3-3, built against MySQL 5.7.37-40

**Expected behavior**
Restore dump without error.

**Log**
```
myloader  --verbose 3 --database sitemanager --directory /opt/backup/mydumper --overwrite-tables --threads 2
** Message: 09:26:12.840: Server version reported as: 5.7.37-40

** (myloader:23677): CRITICAL **: 09:26:12.847: It was not possible to process file: sitemanager.tutorials_tbl-schema.sql.zst (2) because real_db_name isn't found. Restore without schema-create files is not supported
```

**How to repeat**
Create new empty db with test table:
```
create database sitemanager;
use sitemanager;
create table tutorials_tbl(
   tutorial_id INT NOT NULL AUTO_INCREMENT,
   tutorial_title VARCHAR(100) NOT NULL,
   tutorial_author VARCHAR(40) NOT NULL,
   submission_date DATE,
   PRIMARY KEY ( tutorial_id )
);
```


**Environment:**
 - OS version: CentOS Linux release 7.9.2009
 - MyDumper version: 0.12.3-3, (zstd)

**Comment by sebastienbarre** [comment]
Thanks @YogSottot, you beat me to it. 
Sorry @davidducos, we had a production emergency, I really needed `mydumper`, so I focused my efforts on finding (and sticking to) a working version. Hopefully you find the bug.

**Comment by davidducos** [comment]
@sebastienbarre sorry to hear that you had an emergency, hope that went ok. 
I found the bug, It has already fixed in #708 and merged to master, it will be released in the next version. The test case helped me to understand where to find and I was able to add another test case to avoid this kind of issues in the future. 
Thanks for all the help @YogSottot @Razican @sebastienbarre !!!

**Comment by tersmitten** [comment]
I (still) see the message above in `0.12.7-3`, but now as a warning. And restore seems to work. What am I doing wrong. I'm making the backup using:

```
/usr/local/bin/mydumper \
  --threads 24 \
  --build-empty-files \
  --outputdir '/data/backup/mydumper' \
  --verbose 2 \
  --regex '^(?!(information_schema\.|common_schema\.|mysql\.|percona\.|performance_schema\.|sysbench\.|sys\.))' \
  --triggers \
;
```

And I'm restoring like this (on another machine):

```
/usr/local/bin/myloader \
  --threads 8 \
  --overwrite-tables \
  --directory '/data/backup/mydumper-restore' \
  --verbose 2 \
;
```

`/data/backup/mydumper-restore` contains the backup of 3 databases. `*-schema-create.sql` files are present, so are `*.*-metadata`.

**Comment by tersmitten** [comment]
```
** (myloader:4046535): WARNING **: 04:04:00.079: It was not possible to process file: example_com.foo-metadata (2) because real_db_name isn't found. We might renqueue it, take into account that restores without schema-create files are not supported
** (myloader:4046535): WARNING **: 04:04:00.079: It was not possible to process file: example_com.bar-schema.sql (1) because real_db_name isn't found. We might renqueue it, take into account that restores without schema-create files are not supported
```

**Comment by tersmitten** [comment]
```
/usr/local/bin/myloader \
  --threads 8 \
  --overwrite-tables \
  --directory '/data/backup/mydumper-restore' \
  --verbose 2 \
  --database "${database}" \
  --source-db "${database}" \
;
```

Does not omit the warning, but of course I don't want to run `myloader` in a loop.

**Comment by tersmitten** [comment]
@davidducos 

Thanks in advance

**Comment by davidducos** [comment]
Why don't you use a newer version of MyDumper?

**Comment by davidducos** [comment]
forgot to mention: @tersmitten

**Comment by tersmitten** [comment]
I'm planning to upgrade to the latest version, but I was afraid that that would change "too much" (config files, deprecated options) for me. I have a bunch of scripts / pipelines around `mydumper` / `myloader` and need to keep them up and running. So I just upgraded to `0.12.7-3`, because that worked for me in some other environment.

**Comment by davidducos** [comment]
Hi @tersmitten, yes, a lot of things has changed.

**Comment by tersmitten** [comment]
I just tried the latest version in my test machine, but it cannot even connect the the mysql server 🙃.

**Comment by tersmitten** [comment]
`0.13.1-2` seems to fix it for me. Next up migrate to the latest version :-)
