### ISSUE TITLE
dump with the special database name

### ISSUE THREAD

**Issue by SZDRZ** [mydumper/mydumper#685]
Hi! I have a question about the special database name.
Now I have a database named "DBA.Test", But the name derived from mydumper is not the same as the original one.
Is mydumper does not support special characters in database name ?

mydumper version:mydumper 0.12.3-1, built against MySQL 5.7.37-40
MySQL Server version:   8.0.29 MySQL Community Server

![image](https://user-images.githubusercontent.com/103322931/168600261-3020b283-c98a-4d79-954f-ade0a490f615.png)

![image](https://user-images.githubusercontent.com/103322931/168600511-ece593c3-37f3-4538-8e6c-324bf99cb883.png)

**Comment by SZDRZ** [comment]
Thank you. I see.
And another question is: When option -B and option -T used together in mydumper, it will show an error message... But the data was dumped out.
Is this a bug ?

Error message:
![image](https://user-images.githubusercontent.com/103322931/168713157-14652e81-10ba-4de2-9f6a-b286d8145755.png)

![image](https://user-images.githubusercontent.com/103322931/168713190-ad798a56-2173-4f03-ad35-e2b5354fac75.png)

**Comment by davidducos** [comment]
Hi @SZDRZ ,
-T receives a list of <schema>.<table> that is why you get that error message.

**Comment by SZDRZ** [comment]
understood! Thanks!
