### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by lhyx** [mydumper/mydumper#698]
Hi,

Why are the latest releases compiled without ssl support ? 
Is there still an rpm you can download where ssl support is enabled ?

I tested [mydumper-0.12.3-3.el7.x86_64.rpm](https://github.com/mydumper/mydumper/releases/download/v0.12.3-3/mydumper-0.12.3-3.el7.x86_64.rpm)

**Comment by davidducos** [comment]
Seems that someone change the name of a variable in CMake from OpenSSL_FOUND to OPENSSL_FOUND, that is why our script is not able to find the library
