### ISSUE TITLE
[BUG] parameter --set-names

### ISSUE THREAD

**Issue by shijiunv** [mydumper/mydumper#714]
**Describe the bug**
--set-names is partially invalid when using --steam

**To Reproduce**

Command executed:
mydumper --set-names=utf8mb4 --stream --no-delete > backup.sql

What mydumper and myloader version has been used?
mydumper 0.12.3-3

**Expected behavior**
-- ***.***.00000.sql
/*!40101 SET NAMES utf8mb4*/;

backup.sql
/*!40101 SET NAMES binary*/;

**Comment by davidducos** [comment]
Hi @shijiunv , I was not able to reproduce your issue:
```
root@ubuntu-focal:~/issue_714/mydumper# rm -rf data; ./mydumper --regex '^(percona\.item1$)' --outputdir data --stream --no-delete  --set-names=utf8mb4 > backup.sql
root@ubuntu-focal:~/issue_714/mydumper# grep "SET NAMES" backup.sql
/*!40101 SET NAMES utf8mb4*/;
/*!40101 SET NAMES utf8mb4*/;
```
