### ISSUE TITLE
[BUG] Skip FTWRL if other DDL lock is found

### ISSUE THREAD

**Issue by banananjiz** [mydumper/mydumper#717]
**Describe the bug**
FLUSH TABLES (FT *unofficial acronym*) and FTWRL (FLUSH TABLES WITH READ LOCK) runs even if another DDL lock function is found. In the case of a MySQL (or Percona) 8 servers where the function `determine_ddl_lock_function` determines LOCK INSTANCE FOR BACKUP (LIFB *unofficial acronym*), mydumper runs first FT, then FTWRL and then LIFB.
As stated in the [backup locks documentation by Percona](https://www.percona.com/doc/percona-server/8.0/management/backup_locks.html), LIFB is  "a lightweight alternative to" FTWRL making this a redundant locking procedure.

Following the code snippet [from mydumper_start_dump.c](https://github.com/mydumper/mydumper/blob/7891b49ba5c1b8caeaca7a95b074a4ebad0c4353/src/mydumper_start_dump.c):

```
// line 717 - Start determine_ddl_lock_function
void determine_ddl_lock_function(MYSQL ** conn, void (**acquire_lock_function)(MYSQL *), void (** release_lock_function)(MYSQL *), void (** release_binlog_function)(MYSQL *)) {
...
// line 736-741 - determine lock functions for MySQL
    if (g_str_has_prefix(ver[0], "MySQL")){
      if (g_str_has_prefix(ver[1], "8.")) {
        *acquire_lock_function = &send_lock_instance_backup; // defined in line 692-699
        *release_lock_function = &send_unlock_instance_backup; // defined in line 709-711
        break;
      }
...
// line 1000-1022 - Backup lock procedure if argument --no-backup-locks is not set
 if (!no_backup_locks)
        determine_ddl_lock_function(&second_conn,&acquire_ddl_lock_function,&release_ddl_lock_function, &release_binlog_function);

  		if (lock_all_tables) {
        send_lock_all_tables(conn);
      } else {
        g_message("Sending Flush Table");
        if (mysql_query(conn, "FLUSH TABLES")) {
          g_warning("Flush tables failed, we are continuing anyways: %s",
                   mysql_error(conn));
        }
        g_message("Acquiring FTWRL");
        if (mysql_query(conn, "FLUSH TABLES WITH READ LOCK")) {
          g_critical("Couldn't acquire global lock, snapshots will not be "
                   "consistent: %s",
                   mysql_error(conn));
          errors++;
        }
        if (acquire_ddl_lock_function != NULL) {
          g_message("Acquiring DDL lock");
          acquire_ddl_lock_function(second_conn);
        }
      }
```

**To Reproduce**
Use any DB supporting another lock mechanism and run any mydumper command as long as `-k|--no-locks`, `--no-backup-locks` or `--lock-all-tables` is not set. 

Example with a MySQL 8 server:
`mydumper -c -B mydb -o /tmp/mydbdump`

**Expected behavior**
If a DB specific DDL lock is found like LOCK INSTANCE FOR BACKUP do not run FTWRL before.

**Log**
```
** Message: 14:36:12.586 Connected to a MySQL server
** Message: 14:36:12.587 Acquiring FTWRL
** Message: 14:36:12.597 Acquiring DDL LOCK
** Message: 14:36:12.597 Started dump at: 2022-06-09 14:36:12
```

**Environment:**
 - OS version: Any
 - MyDumper version: Code from master branch and tested with v0.12.3-3

**Possible solution**
Possible solution is to move the if statement on [line 1018](https://github.com/mydumper/mydumper/blob/7891b49ba5c1b8caeaca7a95b074a4ebad0c4353/src/mydumper_start_dump.c#L1018):
```
if (!no_backup_locks)
        determine_ddl_lock_function(&second_conn,&acquire_ddl_lock_function,&release_ddl_lock_function, &release_binlog_function);

  		if (lock_all_tables) {
        send_lock_all_tables(conn);
      } else {
        if (acquire_ddl_lock_function != NULL) {
          g_message("Acquiring DDL lock");
          acquire_ddl_lock_function(second_conn);
        } else {
          g_message("Sending Flush Table");
          if (mysql_query(conn, "FLUSH TABLES")) {
            g_warning("Flush tables failed, we are continuing anyways: %s",
                     mysql_error(conn));
          }
          g_message("Acquiring FTWRL");
          if (mysql_query(conn, "FLUSH TABLES WITH READ LOCK")) {
            g_critical("Couldn't acquire global lock, snapshots will not be "
                     "consistent: %s",
                     mysql_error(conn));
            errors++;
          }
        }
      }
```

**Comment by davidducos** [comment]
Hi @banananjiz, 
LTFB lock at DDL, the doc says: `the LOCK TABLES FOR BACKUP is not applicable to the INSERT, REPLACE, UPDATE, DELETE statements`, which is not a problem in a single threaded backup, but we need to sync all the threads, that is why we still need the FTWRL, if not, we end up in inconsistent backups. 
Mostly of the documentation related to locks, doesn't consider our scenario. 
Let's say that you have 3 connection:
- main connection: MC
- Thread 1 connection: T1C
- Thread 2 connection: T2C
What we are doing is:
MC: FTWRL
T1C and T2C: START TRANSACTION...
MC: LTFB
MC: UNLOCK TABLES
which guarantees the sync across all the threads
If we trust on LTFB, could be insert between START TRASACTIONS... like this: 
MC: LTFB
T1C: START TRANSACTION...
Other connection: INSERT INTO... 
T2C: START TRANSACTION...

Cheers
