### ISSUE TITLE
[BUG]I use low version backup and high version recovery error

### ISSUE THREAD

**Issue by dxl3811051** [mydumper/mydumper#721]
**version**
mydumper-0.10.7-2.el7.x86_64
mydumper-0.12.3-3.el7.x86_64

**Describe the bug**
I have use mydumper-0.10.7-2.el7.x86_64 backup my database, and use mydumper-0.12.3-3.el7.x86_64 to recovery it, But something went wrong.
I need help！！！！

![微信截图_20220610153724](https://user-images.githubusercontent.com/34296773/173025499-26b3bb94-4c07-4912-aedb-e65e724aa622.png)

**Comment by davidducos** [comment]
We don't support cross secondary version backups.
