### ISSUE TITLE
Mydumper for Centos/RHEL 9

### ISSUE THREAD

**Issue by Yoskaldyr** [mydumper/mydumper#722]
RHEL 9 is released in May 19
Will you provide binary release for this version?

**Comment by davidducos** [comment]
I'm not seeing any centos9 in https://app.vagrantup.com/centos...

**Comment by Yoskaldyr** [comment]
https://www.centos.org/centos-stream/
https://centos.org/stream9/
https://access.redhat.com/articles/3078
RHEL 9.0 General Availability Date 2022-05-17

**Comment by davidducos** [comment]
Hi @Yoskaldyr , do you know if the centos team is going to maintain the Vagrant cloud VMs? as that is what we are using to build in MyDumper

**Comment by davidducos** [comment]
Hi @Yoskaldyr, I configured that vm. Btw, do you recommend to use almalinux for rhel7 and rhel8?

**Comment by Yoskaldyr** [comment]
I didn't check it in detail.
But it must be RH linux recompiled from the sources like Centos, but classic Centos 8 is dead now. Only Centos 8 stream with pros and cons of stream release.
But because of binary compatibility with RHEL/Centos I think Almalinux is good for compiling purpose.

Right now community use both Alma linux and Rocky linux, but on hosting companies side I saw Alma linux more often than Rocky linux.

**Comment by Yoskaldyr** [comment]
@davidducos If you have a compiled version of mydumper for RHEL9 I can test it. Or when it will be available.

**Comment by davidducos** [comment]
@Yoskaldyr sorry to inform you that MySQL, Percona nor MariaDB currently support RHEL9. We will need to wait to v0.12.7-1

**Comment by Yoskaldyr** [comment]
> @Yoskaldyr sorry to inform you that MySQL, Percona nor MariaDB currently support RHEL9. We will need to wait to v0.12.7-1

ahhhh. ok. I thought that mysql is enough.

**Comment by Yoskaldyr** [comment]
> @Yoskaldyr sorry to inform you that MySQL, Percona nor MariaDB currently support RHEL9. We will need to wait to v0.12.7-1

Also RHEL9 has mariadb in own repos, `mysql  Ver 15.1 Distrib 10.5.13-MariaDB`

**Comment by Yoskaldyr** [comment]
For own needs I compiled mydumper from the source on Centos 9 Stream using devel libraries of mariadb. Everything works like a charm.

**Comment by davidducos** [comment]
My testing using almalinux/9 and mysql_80 worked fine. We are good to go on next release.
