### ISSUE TITLE
[BUG] Hangs with Thread 1 dumping SP and VIEWs for `database`

### ISSUE THREAD

**Issue by ak370** [mydumper/mydumper#735]
**Describe the bug**
I was able to dump previously ok this database, but possibly something changed and now it stops and Hangs with verbosity 3 showing only "Thread 1 dumping SP and VIEWs for `database`".

**To Reproduce**
Command executed:
* mydumper with all the parameters
Options I use rows=5000, -G -E -R --compress --build-empty-files --threads=8 --compress-protocol
mydumper --host=localhost --user=root --password= --outputdir=mydumper-files --rows=5000 -G -E -R --compress --build-emptyfiles --threads=8 --compress-protocol --regex '^(?!(mysql|performance_schema|information_Schema))' --verbose=3 -L mydumper-logs.txt

What mydumper and myloader version has been used?
0.12.3-3.x86_64 on Centos7

**Expected behavior**
I expected mydumper to complete.

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
Already added.

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
Applicable only to a particular database. If I exclude this database, others are fine.

**Environment (please complete the following information):**
Centos 7 latest updates 7.9.2009

**Additional context**
Would like to know how to enable further debugging to see where exactly it gets stuck, but I understand the v3 level I am using is already the highest? Thanks

**Comment by davidducos** [comment]
Hi @ak370 , can you share a test case? Is this related to another issue already reported?

**Comment by davidducos** [comment]
Can you test with the current master branch? We might already fix this issue

**Comment by ak370** [comment]
Yeah with latest master branch works.
Had to disable SSL as it was giving error btw.
Will close ticket and report if any problems further.
Thanks for the prompt one.

**Comment by ak370** [comment]
Actually I was too quick and not sure what it was first time I ran after compiling from master branch.

After trying few more attempts I am still getting the same hanging at the end of the job:

Thread 5 dumping SP and VIEWs for `database`.

How could I debug further?

Thanks

**Comment by ak370** [comment]
I rolled back from 0.12-3-3.el7 to 12 0.12.1-1.el7 and it seems its working. So something about final steps of database dump, around SP and VIEWs stage..

**Comment by davidducos** [comment]
Is it possible for you to develop a test case?

**Comment by davidducos** [comment]
Moving this to Release 1.0.1-1 but we are going to close it if after release 0.12.7-1 we don't get more info about the issue
