### ISSUE TITLE
DDL statements are often blocked by backup metadata locks for a long time

### ISSUE THREAD

**Issue by xiaoxuanfeng** [mydumper/mydumper#752]
> We often encounter a problem. During the backup, DDL statements are blocked by the metadata lock of the backup, and the lock is not released until the end of the backup. To speed up the backup process, we use the parameter --rows, but if we use the parameter --use savepoints, it will be automatically disabled. Can these two parameters coexist to achieve both performance and quick release of metadata lock, so as not to block DDL statements

**--use-savepoints disabled code:**
```
  /* savepoints workaround to avoid metadata locking issues
     doesnt work for chuncks */
  if (rows_per_file && use_savepoints) {
    use_savepoints = FALSE;
    g_warning("--use-savepoints disabled by --rows");
  }
```

### Optimization opinions:
Since the backup tasks of each table are placed in the shared queue in sequence, in multi-threaded backup, as long as it is ensured that each thread completes the backup task of a table, the savepoint of this table can be released, and then a new savepoint can be opened for the backup task of the next table, and so on
### Optimize code
```
switch (job->type) {
                        case JOB_DUMP:  
                             ......
                             ......

                              if(g_ascii_strcasecmp(prev_tast_database->str, tj->database)==0 &&  g_ascii_strcasecmp(prev_task_table->str, tj->table)==0){
                                      dump_table_data_file(thrconn, tj->database, tj->table, tj->where, tj->filename);
                              
                              }else 
                                   {
                                   if(use_savepoints && mysql_query(thrconn, "ROLLBACK TO SAVEPOINT mydumper")){
                                         g_critical("Rollback to savepoint failed: %s",mysql_error(thrconn));
                                   }
                              
                                   if(use_savepoints && mysql_query(thrconn, "SAVEPOINT mydumper")){
                                         g_critical("Savepoint failed: %s",mysql_error(thrconn));
                                   }
                                   dump_table_data_file(thrconn, tj->database, tj->table, tj->where, tj->filename);
                              }
                              
                              g_string_printf(prev_tast_database, "%s", tj->database);
                              g_string_printf(prev_task_table, "%s", tj->table);
```

**Comment by davidducos** [comment]
Please, share the command that you are executing. BTW, not sure why you are using savepoints or the benefit of using it, new and better locking mechanism has been implemented.

**Comment by xiaoxuanfeng** [comment]
hi davidducos:
The advantage of using savepoints is that the metadata lock of the table can be released quickly without blocking DDL statements

**Execute command:**
mydumper -h XXXX -P 3306 -u XXX -p XXX  -s 50000000  -r 100000 --use-savepoints -c -l 1 -K -t 6  -G -E -R -o 20220915-084104

**Comment by davidducos** [comment]
Hi @xiaoxuanfeng, 
The metadata locks of the tables are there because we want a consistent backup, you can disable DDL locks with --no-locks.
On the other hand, I will need to test if what you are saying, which I think is:
`
Executing savepoint before executing SELECTs on a table will cause metadata locks per table
`
I will be testing and let you know if this is true, as honestly, I never tested it.

**Comment by davidducos** [comment]
@xiaoxuanfeng, 
savepoints are not locking DDL.

**Comment by davidducos** [comment]
@xiaoxuanfeng 
I think that we can improve mydumper if we have metadata locks per table, but we will still need the DDL locks. 
This will be the idea for transactional engines:
- Send FTWRL
- Send DDL locks
- Sync threads with START TRANSACTION WITH CONSISTENT SNAPSHOT
- Release FTWRL
- Execute SAVEPOINT, CREATE TABLE and some dummy SELECT per table 
- Release DDL locks
- start dumping data
- release savepoints when a table finishes

**Comment by xiaoxuanfeng** [comment]
@davidducos 
I tested that the table metadata lock will be released after the savepoint is released
The function of savepoint is described in mydumper, as follows
{"use-savepoints", 0, 0, G_OPTION_ARG_NONE, &use_savepoints,
"Use savepoints to reduce metadata locking issues, needs SUPER privilege",
NULL}

**Comment by davidducos** [comment]
I'm reviewing this issue again and I think that we might be able to re implement this in a better way. 

Every time that a thread start on a different table name, it will send a ROLLBACK TO SAVEPOINT and then a new SAVEPOINT, causing old table locks are released and new select will block the new table. 
WARNING!! We must not send the ROLLBACK if we are starting on a new chunk of the same table, as could be possible that all threads have released the locks.
