### ISSUE TITLE
[BUG] myloader uses wrong order with views and functions

### ISSUE THREAD

**Issue by godvoigt** [mydumper/mydumper#755]
**Describe the bug**
When restoring a mydumper backup using myloader, there is an error when restoring views that use functions which are part of the dump. The functions are only created after the views, namely in the schema-post.sql.

**To Reproduce**

Configuration:

```
cat /etc/my-db.cnf:
[client]
default-character-set=utf8mb4
ssl=1
ssl-ca=/run/secrets/ca_cert
ssl-cert=/run/secrets/mysql_client_cert
ssl-key=/run/secrets/mysql_client_key
database=mydb
host=dbhost
port=3306
user=user
password=pass
compress=1

[mydumper]
compress-protocol=1
events=1
triggers=1
routines=1
build-empty-files=1
lock-all-tables=1

[myloader]
compress-protocol=1
serialized-table-creation=1
```

Command executed:

```
mydumper -v 3 \
	--outputdir=/data/database/mydb \
	--defaults-file=/etc/my-db.cnf
```
Note that in between the database has been cleared, e.g. all objects (tables, views, functions etc.) have been dropped.

```

myloader -v 3 \
      --directory=/data/database/mydb \
      --defaults-file=/etc/my-db.cnf
```

What mydumper and myloader version has been used?

```
root@backup-client:/# mydumper --version
mydumper 0.12.1, built against MySQL 5.7.33-36
root@backup-client:/# myloader --version
myloader 0.12.1, built against MySQL 5.7.33-36
```

**Expected behavior**
myloader should have restored finished without error and functions as well as views should be loaded successfully.

**Log**

```
** Message: 09:40:22.207: Config file loaded
** Message: 09:40:22.216: Server version reported as: 8.0.24
[...]
** Message: 09:40:24.797: Thread 1 restoring view on `mydb` from mydb.task_change_set-schema-view.sql

** (myloader:6090): CRITICAL **: 09:40:24.808: Error occours between lines: 10 and 13 on file mydb.task_change_set-schema-view.sql: FUNCTION mydb.check_bits does not exist
[...]
** Message: 09:40:24.889: Thread 1 restoring post on `mydb` from mydb-schema-post.sql
** Message: 09:40:25.003: Starting table checksum verification
```

The function is there, but in a sql that is applied after the views (?):

```
root@backup-client:/# grep -n 'FUNCTION `check_bits`' /data/database/mydb/*.sql
/data/database/mydb/mydb-schema-post.sql:110:CREATE  FUNCTION `check_bits`(mask INT, bits INT) RETURNS int
```

**Environment (please complete the following information):**
 - OS version: Ubuntu 18.04
 - MyDumper version: 0.12.1

**Additional context**
-

**Comment by mgmuk** [comment]
We are also experiencing this issue.

**Comment by tom10271** [comment]
Is this fixed? We are still suffering from the same issue.

**Comment by davidducos** [comment]
Hi @tom10271,
What version are you using? Latest version is v0.16.1-3 and latest prerelease is v0.16.2-1.
