### ISSUE TITLE
[BUG] Regular Expression is Too Large

### ISSUE THREAD

**Issue by brileyd** [mydumper/mydumper#761]
**Describe the bug**
I am trying to dump over 2000 databases of about 3500.  I see no way to provide it a file with a list of databases, so I built a very long string of regex.  When I try to execute mydumper I immediately get an error:
** (mydumper:1779213): CRITICAL **: 16:26:42.675: Regular expression fail: regular expression is too large

My command looks like the following, only I will leave out many of the databases:
mydumper --user myuser --password mypass --host mydb.server.com --verbose 3 --compress --triggers --routines \
--events --build-empty-files --rows 100000 --threads 4 --outputdir mydumps --statement-size 4194304 --regex \
'(a190003\.|a190031_2\.|a190033\.|a190041\.|a190044\.|a190046\.|a190046_2\.|  ...  z18122_1\.|z190400\.|z200038\.)' \
2>&1 | tee mydumps/dump.log

**To Reproduce**
Command executed:
Run the command show above with a very log regex.

What mydumper and myloader version has been used?
mydumper 0.9.5, built against MySQL 8.0.19

**Expected behavior**
Executes without error.

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.

** Message: 16:26:41.760: Connected to a MySQL server
** Message: 16:26:41.815: Started dump at: 2022-07-15 16:26:41

** Message: 16:26:41.817: Thread 1 connected using MySQL connection ID 151843
** Message: 16:26:41.819: Thread 2 connected using MySQL connection ID 151844
** Message: 16:26:41.821: Thread 3 connected using MySQL connection ID 151845
** Message: 16:26:41.823: Thread 4 connected using MySQL connection ID 151846

** (mydumper:1779213): CRITICAL **: 16:26:42.675: Regular expression fail: regular expression is too large

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04
 - MyDumper version: See version question above.

Thanks!

**Comment by davidducos** [comment]
Hi @brileyd ,
Newer version of mydumper has been released which allow you to give -B a list of databases.
Can you test it and let me know?

**Comment by brileyd** [comment]
Thank you, David, that worked!  I wonder if the same option used to take a file for tables could be adapted for databases as well?
mydb1.mytable:  - table
mydb2                - database

Just a thought. :)

Thanks again!
