### ISSUE TITLE
myloader supports breakpoint resuming

### ISSUE THREAD

**Issue by ronylei** [mydumper/mydumper#767]
When the import of myloader is interrupted, there is no breakpoint to resume the upload, which is very bad

**Comment by davidducos** [comment]
Hi @ronylei, There is a resume functionality on myloader, if a myloader execution receives a kill.

**Comment by ronylei** [comment]
Is it possible to consider recording all the time during the load process? In this way, the abnormal exit can also be resumed from a breakpoint.

**Comment by ronylei** [comment]
At present, the effect of using the --resume parameter is not very good.

**Comment by davidducos** [comment]
@ronylei, you have the log to know what are the files that had failed and which one had completed successfully, you can use edit the file that resume uses to import the missing files.
