### ISSUE TITLE
[FEATURE] supply arm64 pkg in release

### ISSUE THREAD

**Issue by lusson-luo** [mydumper/mydumper#772]
i want mydumper to run on arm server. now i clone code on my arm server and build it. 
i want official supply arm64. 
i can exec this to install mydumper

```
release=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/mydumper/mydumper/releases/latest | cut -d'/' -f8)
yum install https://github.com/mydumper/mydumper/releases/download/${release}/mydumper-${release:1}.el7.arm64.rpm
yum install https://github.com/mydumper/mydumper/releases/download/${release}/mydumper-${release:1}.el8.arm64.rpm
```

**Comment by bboysoulcn** [comment]
I want to have this feature too

**Comment by matthieume** [comment]
@lusson-luo could you share your solution, I am not having success: https://github.com/mydumper/mydumper/discussions/754

**Comment by davidducos** [comment]
As I stated on #754, only MySQL is releasing ARM packages, Percona and MariaDB is not doing it yet. MyDumper has not the resources yet to deploy ARM packages. This is one of the goals of https://geekswag.co/collections/mydumper

**Comment by lusson-luo** [comment]
@matthieume run int docker.io/bitnami/minideb:buster container
```
git clone https://github.com/mydumper/mydumper.git && cd mydumper

apt-get update && apt-get install libatomic1 -y
apt-get install cmake g++ git -y

apt-get install libglib2.0-dev zlib1g-dev libpcre3-dev libssl-dev libzstd-dev
apt-get install default-libmysqlclient-dev -y
apt-get install libmariadbclient-dev -y
cmake . -DWITH_SSL=OFF
make

```

**Comment by davidducos** [comment]
I'm reviewing https://circleci.com/blog/publishing-to-github-releases-via-circleci/ and I think that in the future we could start using it to draft the releases, which is going to allow us to get multiple versions, even arm64 packages.

**Comment by davidducos** [comment]
Hi, as we close #835, we are going to be able to continue with this. We need to build docker images for arm and then continue with it.

**Comment by oliver-schulz** [comment]
As far as i understand we should extend the build.sh script wird a `arch` parameter and should pass this into the RMP and DEB build functions. Then the `.circleci/circleci_config_builder.sh` should be extended with the ARM targets to build the config.yaml in the same directory. Never did something like this before. How can i help here?

**Comment by davidducos** [comment]
Hi @oliver-schulz,

I had been reviewing this and I found that: https://circleci.canny.io/cloud-feature-requests/p/support-arm-resource-class-on-docker-executor

That means that CircleCI doesn't allow yet ARM containers in Docker. The offer AMD Linux VM and ARM Linux VM but, we develop everything under Docker.

So, we need to wait a bit longer to get packages on ARM, unless we move this to a GitHub Action... I will think about it.

**Comment by oliver-schulz** [comment]
Hey guys, i am checking on this topic again and found that there is ARM support is available in CircleCI, so there is no blocking issue for having a prebuild package in at the releases page?

https://circleci.com/docs/using-docker/#arm

Thx so much!

**Comment by davidducos** [comment]
Hi @oliver-schulz, we have ARM packages for centos/rhel 8 and 9 which are the only OS with ARM libraries on MySQL/Percona.
We are not going to support ARM on other OS until MySQL/Percona/MariaDB support them.

**Comment by oliver-schulz** [comment]
Is see, thank you for your quick answer!
