### ISSUE TITLE
unable to change the field delimiter for mydumper csv export. 

### ISSUE THREAD

**Issue by vidyullathat** [mydumper/mydumper#773]
mydumper --host=xxxxxxxx --user=root --password=xxxxxxx --outputdir=$DumperDir --threads=8 --verbose=3 -F 1024 --port=3306 --trx-consistency-only --long-query-guard=600 --regex='(default_workrelease)' --tables-list=default_workrelease.WR_ALLOCATION --csv --fields-terminated-by='|' --logfile mydump.log

this does not seem to be working.  we have a table with longtext/json fields and the default delimiter "," is causing issues as json data also has commas in them.  I am trying to change to pipe "|", but it is not working.

**Comment by vidyullathat** [comment]
mydumper --version
mydumper 0.12.5-3, built against MySQL 5.7.38-41

**Comment by davidducos** [comment]
I was not able to reproduce your issue, can you share a .sql file with table structure and a couple of INSERT statements? I would like to test with your data. BTW, be careful missing --csv and other --load options like --fields-terminated-by, as I'm not sure (as I didn't check it right now) which option is loaded first.

**Comment by vidyullathat** [comment]
Hi David,
I can create csv using pipe delimiter now.  Last time when I tested, I haven’t deleted previously generated files using default delimiter and when I re-run the mydumper after changing delimiter to “|”, same files have been appended instead of override.  I just checked “head -1” to see the first record and each time it was displaying the line with comma separated values itself.

Nevertheless, deleting the files and re-running the mydumper solved the issue.  Thanks for your response on this case.

Logfiles size with default delimiter “,”
-rw-r--r-- 1 root root   1072658124 Jul 29 20:47 default_workrelease.WR_ALLOCATION.00000.dat
-rw-r--r-- 1 root root         2521 Jul 29 20:47 default_workrelease.WR_ALLOCATION.00000.00001.sql
-rw-r--r-- 1 root root   1073586966 Jul 29 20:47 default_workrelease.WR_ALLOCATION.00000.00001.dat
-rw-r--r-- 1 root root         2521 Jul 29 20:47 default_workrelease.WR_ALLOCATION.00000.00002.sql
-rw-r--r-- 1 root root    909107431 Jul 29 20:47 default_workrelease.WR_ALLOCATION.00000.00002.dat
-rw-r--r-- 1 root root            1 Jul 29 20:48 default_workrelease.WR_ALLOCATION-metadata

Logfiles size with after changing delimiter “|”
-rw-r--r-- 1 root root   2145316248 Jul 29 20:48 default_workrelease.WR_ALLOCATION.00000.dat
-rw-r--r-- 1 root root         5042 Jul 29 20:49 default_workrelease.WR_ALLOCATION.00000.00001.sql
-rw-r--r-- 1 root root   2147173932 Jul 29 20:49 default_workrelease.WR_ALLOCATION.00000.00001.dat
-rw-r--r-- 1 root root         5042 Jul 29 20:49 default_workrelease.WR_ALLOCATION.00000.00002.sql
-rw-r--r-- 1 root root   1818214862 Jul 29 20:49 default_workrelease.WR_ALLOCATION.00000.00002.dat
-rw-r--r-- 1 root root            1 Jul 29 20:49 default_workrelease.WR_ALLOCATION-metadata


Thanks ,
Vidyu
Vidyullatha Thadagonda | Sr. Principal Database Engineer - R&D-DBA
Manhattan Associates, Inc.
Phone +1 678.597.6145
***@***.******@***.***>
www.manh.com<http://www.manh.com/>


From: David Ducos ***@***.***>
Date: Thursday, July 28, 2022 at 7:08 PM
To: mydumper/mydumper ***@***.***>
Cc: Vidyullatha Thadagonda ***@***.***>, Author ***@***.***>
Subject: Re: [mydumper/mydumper] unable to change the field delimiter for mydumper csv export. (Issue #773)
[CAUTION: This email originated outside of Manhattan Associates.]

I was not able to reproduce your issue, can you share a .sql file with table structure and a couple of INSERT statements? I would like to test with your data. BTW, be careful missing --csv and other --load options like --fields-terminated-by, as I'm not sure (as I didn't check it right now) which option is loaded first.
