### ISSUE TITLE
[BUG] Job counter resets after WARNING is printed

### ISSUE THREAD

**Issue by swechsler** [mydumper/mydumper#774]
**Describe the bug**
After getting the warning `Too many jobs in the queue. We are pausing the jobs creation for 5 seconds`, the `Remaining jobs:` counter resets.

Example:
```
** Message: 21:02:30.903: Thread 4 dumping data for `contributorstats`.`image_stats` WHERE (`image_id` >= 149348000001 AND `image_id` < 149349000001) | Remaining jobs: 199496
** Message: 21:02:30.907: Empty table contributorstats.image_stats
** Message: 21:02:30.907: Thread 1 dumping data for `contributorstats`.`image_stats` WHERE (`image_id` >= 149349000001 AND `image_id` < 149350000001) | Remaining jobs: 199761

** (mydumper:20480): WARNING **: 21:02:30.908: Too many jobs in the queue. We are pausing the jobs creation for 5 seconds.
** Message: 21:02:30.909: Empty table contributorstats.image_stats
** Message: 21:02:30.909: Thread 2 dumping data for `contributorstats`.`image_stats` WHERE (`image_id` >= 149350000001 AND `image_id` < 149351000001) | Remaining jobs: 200000
** Message: 21:02:30.909: Empty table contributorstats.image_stats
** Message: 21:02:30.909: Thread 3 dumping data for `contributorstats`.`image_stats` WHERE (`image_id` >= 149351000001 AND `image_id` < 149352000001) | Remaining jobs: 199999
** Message: 21:02:30.916: Empty table contributorstats.image_stats

```

**To Reproduce**
`mydumper -h <source_instance> --regex ^<some_regex> -o <workdir> -R -G -r 10000000 -t 4 --set-names utf8mb4 -v 3`

What mydumper and myloader version has been used?
```
$ mydumper --version
mydumper 0.11.5, built against MySQL 5.7.34-37
```
**Environment (please complete the following information):**
Centos 7

**Comment by xiaoxuanfeng** [comment]
If the number of queue tasks exceeds 200000, it will sleep for 5 seconds before adding tasks to the queue
Maintaining jobs should be the number of tasks in the queue. I also encountered a similar problem, causing the SQL work thread to wait for hours for flush tables with read lock to release lock resources;

**Comment by davidducos** [comment]
@swechsler, the amount of jobs printed are the amount of elements in the queue, it will pause when it reaches to 200k to avoid OOM kills, but it doesn't reset the counter. So, the counter should not be reset, actually it could increase after the WARNING and reach again to 200k which will cause another pause.

@xiaoxuanfeng, it is not clear for me if this is the same issue or a different one. The FTWRL should be released after START TRANSACTION WITH READ LOCK has been completed, unless you are using MyISAM tables. Please, open another issue if this is not related to what @swechsler is reporting.

**Comment by davidducos** [comment]
Closing til we get more info
