### ISSUE TITLE
[Feature]  Setup replication on myloader based on metadata file

### ISSUE THREAD

**Issue by brileyd** [mydumper/mydumper#779]
Would it be possible to add the mysqldump option --master-data (--source-data depending on version)?

Thanks for maintaining this awesome tool!

**Comment by davidducos** [comment]
Hi @brileyd 
The information that you get from --master-data is in metadata. However, and just to clarify, do you want myloader to configure the replication channel? As that will be something really useful for some cases and I thought about it but I never created the FR. 
Let me know what are your thoughts on this.

**Comment by brileyd** [comment]
Hi David,

Yes, that is what I would like and, if possible, the reduced lock time you get when using --master-data with --single-transaction.

**Comment by davidducos** [comment]
I think that we can create a new kind of file with the `CHANGE MASTER` command on mydumper and we can create 2 files, one with the info of `SHOW MASTER STATUS` and another file with the info of `SHOW SLAVE STATUS`, and other files if you have multi threaded replication.
On myloader, we need to select which is/are file/s that are going to be executed. User will need to edit the files if credentials or hosts needs to be added or modified.

**Comment by davidducos** [comment]
I'm thinking in a a medatafile with more information, as we can add the table information:
```
[`schema`.`table`]
rows=234
data_checksum=3036305396
schema_checksum=4036305396
index_checksum=5036305396

[`schema`]
schema_checksum=4136305396
post_checksum=4536305396
```
which will remove the need of having metadata files per table and checksum per object. 
Then for binary logs and replication:
```
[master]
File=mydumper1-bin.000016
Position=4178810
Executed_Gtid_Set=7b166a41-65a2-11ed-9de3-0800275ff74d:1-23432

[replication]
Master_Host=192.168.10.10
Master_Log_File=mydumper1-bin.000016
Exec_Master_Log_Pos=4178810
Executed_Gtid_Set=7b166a41-65a2-11ed-9de3-0800275ff74d:1-23432

[replication.ANamedChannel(AKA: Channel_Name)] 
Master_Host=192.168.10.12
Master_Log_File=mydumper1-bin.000016
Exec_Master_Log_Pos=4178810
Executed_Gtid_Set=7b166a41-65a2-11ed-9de3-0800275ff74d:1-23432
```
