### ISSUE TITLE
[FR] Add --init-command so we can set variables for the myloader sessions

### ISSUE THREAD

**Issue by markusalbe** [mydumper/mydumper#780]
**Describe the bug**
It's not possible to set variables for the session level through myloader; This makes use of things like Galera streaming replication impossible, as this requires setting a session-level-only variable (wsrep_trx_fragment_size).  Other things like unique checks and foreign key checks also can be disabled for faster loading, and it might be desirable to set only at the session level for myloader threads.

**To Reproduce**
Try to set a session variable for a myloader thread; Verify it's impossible.

**Expected behavior**
The expected is a --init-command like mysql command line client has, so that one can do the SET SESSION commands through that; This is a simple string containing semi-colon separated SQL statements that will be executed when each myloader thread starts

**Log**
n/a

**Backup**
n/a

**How to repeat**
n/a

**Environment (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by davidducos** [comment]
Hi @markusalbe !! 
We already implemented what you are requesting in https://github.com/mydumper/mydumper/pull/370.
You need to use the configuration file with [mydumper_variables] or [myloader_variables] sections and they will be automatically loaded. Please, let me know if that works for you.

**Comment by davidducos** [comment]
@markusalbe, please, let me know if this works for you, so I can close this issue.

**Comment by markusalbe** [comment]
Hey David! Yes, absolutely. Thanks for the info! :)
