### ISSUE TITLE
[BUG] MyDumper missed some tables since MySQL-8.0 when using --updated-since

### ISSUE THREAD

**Issue by hustegg** [mydumper/mydumper#784]
**Describe the bug**
By default, MySQL retrieves cached (1 day) values for some columns (include TABLES.UPDATE_TIME) since MySQL8.0;
[information_schema_stats_expiry](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_information_schema_stats_expiry)

However, UPDATE_TIME may be stale in cache, MyDumper would filter more not updated tables than practical, some table updated recently may be retrieved mistakenly as not updated, according following SQL:
```SQL
SELECT CONCAT(TABLE_SCHEMA,'.',TABLE_NAME)
FROM information_schema.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' 
AND UPDATE_TIME < NOW() - INTERVAL %d DAY
```

**To Reproduce**
Command executed:
* mydumper with all the parameters
./mydumper -h 127.0.0.1 -P 3306 -u test -p test -v 3 --updated-since 1 -o data -L dump.log -B test

What mydumper and myloader version has been used?
mydumper 0.12.3-5 and before

**Expected behavior**
Dump all tables updated recently days specified with --updated-since

**Log**
2022-07-29 11:44:24 [INFO] - NO UPDATED TABLE: test.t1

**Backup**
drwxr-x--- 2 mysql mysql     32 Jul 29 12:06 .
drwxr-xr-x 7 mysql mysql   4096 Jul 29 11:43 ..
-rw-r----- 1 mysql mysql 114688 Jul 28 23:28 t1.ibd

**How to repeat**
CREATE TABLE `t1` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `ts` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

Day 1: create table `test`.`t1`, insert some data;
Day 2: insert some data into `test`.`t1`, dump database `test`, `test`.`t1` missed in output directory;

**Environment (please complete the following information):**
 - OS version: CentOS Linux release 7.2 (Final)
 - MyDumper version: mydumper 0.12.3-5, built against MySQL 5.7.30

**Additional context**
We can fix it just bypass table statistics cache with session variable information_schema_stats_expiry which introduced since 8.0.3:
/*!80003 SET SESSION information_schema_stats_expiry=0 */

**Comment by davidducos** [comment]
Hi @hustegg
As I told @markusalbe on https://github.com/mydumper/mydumper/issues/780 it is possible to set session variables like yours information_schema_stats_expiry=0 by the configuration file. Can you test it and if you can do a PR with the documentation that is missing? that will help other users!

**Comment by hustegg** [comment]
I'd love to document functionality of set session variables, but I'm not sure how to deal with some variables incompatible between different MySQL version.
At my first glance of refresh_set_session_from_hash, /*!{version} */ is not the way when execute_gstring set_session, 
and then I tested adding information_schema_stats_expiry = 0 in [mydumper_variables], it works fine on MySQL-8.0, but get warnings on MySQL 5.7:
2022-07-29 23:31:11 [WARNING] - Set session failed: SET SESSION information_schema_stats_expiry = 0

I think user who uses --defaults-file exactly know what "SET SESSION" he wants, session variables in config file is specified proactively, but when using --updated-since, he may not be aware of cached table statistics, so should we document it with --updated-since like "when specified on MySQL-8.0 or above, please add information_schema_stats_expiry = 0 to defaults-file"?

**Comment by davidducos** [comment]
Yes, I think that we can warning and add it automatically to the set session hash, but not as you did. I will review your commit when I have the change and make the proper changes

**Comment by davidducos** [comment]
Explanation about variables usage has been added to https://github.com/mydumper/mydumper/blob/master/README.md
