### ISSUE TITLE
Mydumper slowness

### ISSUE THREAD

**Issue by aloks2019** [mydumper/mydumper#787]
We are trying to take backup of 1.6 TB database instances with more than 12 millions of objects. How we can speed up the performance of mydumper. It has been running for 3days. We are using below command:
mydumper -compress-protocol -trigger -routines -events -kill-long-queries -thread=15

**Comment by aloks2019** [comment]
@davidducos any recommendation to take super fast backup using mydumper in mentioned situation

**Comment by davidducos** [comment]
Hi @aloks2019,
you should be using --rows and ZSTD release.
