### ISSUE TITLE
[BUG] mydumper csv option is missing records while dumping 

### ISSUE THREAD

**Issue by vidyullathat** [mydumper/mydumper#790]
**Describe the bug**
mydumper is not dumping all the data and data discrepancies are seen post restore.

**To Reproduce**
Command executed:
* mydumper with all the parameters

DumperDir=/mnt/disks/mysqldmp/mydumperdir
mydumper --host=xxxxx --user=root --password=xxxxx --outputdir=$DumperDir --threads=8 --verbose=3 -F 1024 --port=3306 --trx-consistency-only --long-query-guard=600 --regex='(default_dcorder)' --tables-list=default_dcorder.DCO_ORDER_LINE --csv --fields-terminated-by='\t' --logfile mydump.log

What mydumper and myloader version has been used?

mydumper --version
mydumper 0.12.5-3, built against MySQL 5.7.38-41

**Expected behavior**
data exported using mydumper should match with actual table row count, but it does not seems to be case.  

Data count on the MySQL table.
mysql> select count(*) from default_dcorder.DCO_ORDER_LINE;
+----------+
| count(*) |
+----------+
|  6053986 |
+----------+

files generated post mydumper command:

 ls -rlt  default_dcorder.DCO_ORDER_LINE.*.dat
-rw-r--r-- 1 root root 1072333501 Aug  2 15:00 default_dcorder.DCO_ORDER_LINE.00000.dat
-rw-r--r-- 1 root root 1072342166 Aug  2 15:01 default_dcorder.DCO_ORDER_LINE.00000.00001.dat
-rw-r--r-- 1 root root 1072313290 Aug  2 15:01 default_dcorder.DCO_ORDER_LINE.00000.00002.dat
-rw-r--r-- 1 root root 1078352480 Aug  2 15:02 default_dcorder.DCO_ORDER_LINE.00000.00003.dat
-rw-r--r-- 1 root root 1074306027 Aug  2 15:02 default_dcorder.DCO_ORDER_LINE.00000.00004.dat
-rw-r--r-- 1 root root 1072335615 Aug  2 15:02 default_dcorder.DCO_ORDER_LINE.00000.00005.dat
-rw-r--r-- 1 root root 1072325906 Aug  2 15:03 default_dcorder.DCO_ORDER_LINE.00000.00006.dat
-rw-r--r-- 1 root root  155144842 Aug  2 15:03 default_dcorder.DCO_ORDER_LINE.00000.00007.dat

cat default_dcorder.DCO_ORDER_LINE.*.dat | wc -l
6050526

count mysql table: 6,053,986
count from mydumper csv file: 6,050,526
Total difference: 3,460

when we export using traditional mysql approach, csv count is matching with table count.
mysql> select * from default_dcorder.DCO_ORDER_LINE
    ->        INTO OUTFILE '/mnt/disks/log/DCO_ORDER_LINE_0803.csv'
    ->        FIELDS TERMINATED BY ','
    ->        ENCLOSED BY '"'
    ->        LINES TERMINATED BY '\n';
Query OK, 6053986 rows affected (3 min 5.49 sec)

cat DCO_ORDER_LINE_0803.csv | wc -l
6053986

**Environment (please complete the following information):**
 - OS version:
    Ubuntu 20.04.4 LTS
 - MyDumper version:
    mydumper 0.12.5-3, built against MySQL 5.7.38-41

**Comment by davidducos** [comment]
Hi @vidyullathat is this happening only with --csv ? can you export and import without --csv and count at mysql level?

**Comment by vidyullathat** [comment]
Yes. this seems to be happening with --csv option.  i tried without csv option and data restored using myloader is matching with original table count.

mydumper --version
mydumper 0.12.5-3, built against MySQL 5.7.38-41

#export without csv
DumperDir=/mnt/disks/mysqldmp/
mydumper --host=xxxxx --user=root --password=xxxxx --outputdir=$DumperDir --threads=8 --verbose=3 -F 1024 --port=3306 --trx-consistency-only --long-query-guard=600 --regex='(default_dcorder)' --tables-list=default_dcorder.DCO_ORDER_LINE --logfile mydump.log


#import sql files 
DumperDir=/mnt/disks/mysqldmp/
myloader --host=xxxxxx --user=root --password=xxxxx --threads=8 --verbose=3 --port=3306 --database=default_dcorder --directory=$DumperDir 2>myloader$datetime.log

mysql> select count(*) from default_dcorder.DCO_ORDER_LINE;
+----------+
| count(*) |
+----------+
|  6053986 |
+----------+
1 row in set (11.26 sec

**Comment by davidducos** [comment]
Hi @vidyullathat, 
We are already checking for --csv in our internal tests. I'm wondering if this issue is related to the usage of -F. Can you test one more time using --csv and removing -F 1024 ?

**Comment by vidyullathat** [comment]
Hi David,
yes -F chunk size seems to be causing the issue. i have tested mydumper csv without -F and the data counts are matching post restore.  do you suggest me to use rows instead ?  are there any known bugs with rows option ?

**Comment by davidducos** [comment]
Hi @vidyullathat, 
At this point I suggest you to don't use any of -r and -F. There are 2 reasons:
1- We are in the process to change -r as it is causing several issues, I have a couple of bugs to fix there. This means that it is not estable enough after the last releases
2- A new implementation for --load-data (--csv is just a wrapper of --load-data) has been implemented, but seems that I didn't notice this bug. 
For non --load-data or --csv, you will be fine to run mydumper with -F and you can use -r if you use a high number as on low values it might cause OOM kills.

**Comment by vidyullathat** [comment]
David,
mydumper without csv is also getting killed after creating schema files.  i just see "killed" and do not see any info about the failure in mydumper.log 

/mnt/disks/mysqldmp/mydumper202208022328# ls -lrt | wc -l
106
/mnt/disks/mysqldmp/mydumper202208022328# ls -lrt *schema-create.sql* | wc -l
104
/mnt/disks/mysqldmp/mydumper202208022328# cat default_monitor-schema-create.sql
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `default_monitor` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */

mydumper \
> --host=$DATABASE_MYSQL_HOST \
> --user=$DATABASE_MYSQL_USER \
> --password=$DATABASE_MYSQL_PWD \
> --outputdir=$MYDUMPER_DIR \
> --regex '^(?!(mysql|performance_schema|information_schema|sys))' \
> --build-empty-files \
> --threads=$DATABASE_MYDUMPER_THREADS \
> --rows=100000 \
> --verbose=3  \
> --port=$DATABASE_MYSQL_PORT \
> --trx-consistency-only \
> --long-query-guard=$DATABASE_LONG_QUERY_GUARD  \
> --logfile mydumper.log
Killed

root@mysql-vid-8-temp:/mnt/disks/mysqldmp# tail -10 mydumper.log
2022-08-03 22:16:55 [INFO] - Thread 3 dumping schema create for `default_mltrainer`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping db information for `default_mltrainer`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping schema create for `default_mltrainerproxy`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping db information for `default_mltrainerproxy`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping schema create for `default_mlvpt_tool`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping db information for `default_mlvpt_tool`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping schema create for `default_modelerui_facade`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping db information for `default_modelerui_facade`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping schema create for `default_monitor`
2022-08-03 22:16:55 [INFO] - Thread 3 dumping db information for `default_monitor`

**Comment by vidyullathat** [comment]
David,
This issue doesn’t seem to be resolved in the latest release. We are still getting the mismatch in data counts post dumping the data into csv.
 
mydumper --version
mydumper 0.12.7-3, built against MySQL 5.7.39-42
 
DumperDir=/mnt/disks/mysqldmp/mydumperdir
TABLE_SCHEMA=default_dcorder
TABLE_NAME=DCO_ORDER_LINE
rm /mnt/disks/mysqldmp/mydumperdir/$TABLE_SCHEMA.$TABLE_NAME*.dat 2>/dev/null
mydumper --host=<> --user=root --password=<> --outputdir=$DumperDir --threads=8 --verbose=3 -F 1024 --port=3306  --tables-list=$TABLE_SCHEMA.$TABLE_NAME --csv  --fields-terminated-by='^'  --logfile mydump.log
 
#csv extracts count:
cat default_dcorder.DCO_ORDER_LINE.*.dat | wc -l
6050526
 
# table count
 mysql --host=<> --user=root --p
mysql> select count(*) from default_dcorder.DCO_ORDER_LINE;
+----------+
| count(*) |
+----------+
|  6053986 |
+----------+
1 row in set (8.89 sec)
 
 
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by davidducos** [comment]
@vidyullathat,

I have just tested the patch and seems it is working:
```
[root@mydumper1 mydumper]# zstdcat data/sbtest.sbtest1.*.dat.zst | wc -l
10758423
[root@mydumper1 mydumper]# mysql -e 'select count(*) from sbtest.sbtest1'
+----------+
| count(*) |
+----------+
| 10758423 |
+----------+
```
Can you rerun your script changing this?
```
rm /mnt/disks/mysqldmp/mydumperdir/$TABLE_SCHEMA.$TABLE_NAME*.dat
```
I want to see if that remove is failing

**Comment by vidyullathat** [comment]
David,
We tested #838 and the chunk size and rows parameter is working as expected.  Thanks for your assistance.

https://github.com/mydumper/mydumper/tree/fix_838


Thanks ,
Vidyu
Vidyullatha Thadagonda | Sr. Principal Database Engineer - R&D-DBA
Manhattan Associates, Inc.
Phone +1 678.597.6145
***@***.******@***.***>
www.manh.com<http://www.manh.com/>


From: David Ducos ***@***.***>
Date: Tuesday, October 11, 2022 at 8:42 AM
To: mydumper/mydumper ***@***.***>
Cc: Vidyullatha Thadagonda ***@***.***>, Mention ***@***.***>
Subject: Re: [mydumper/mydumper] [BUG] mydumper csv option is missing records while dumping (Issue #790)
[CAUTION: This email originated outside of Manhattan Associates.]

@vidyullathat<https://github.com/vidyullathat>,

I have just tested the patch and seems it is working:

***@***.*** mydumper]# zstdcat data/sbtest.sbtest1.*.dat.zst | wc -l

10758423

***@***.*** mydumper]# mysql -e 'select count(*) from sbtest.sbtest1'

+----------+

| count(*) |

+----------+

| 10758423 |

+----------+

Can you rerun your script changing this?

rm /mnt/disks/mysqldmp/mydumperdir/$TABLE_SCHEMA.$TABLE_NAME*.dat

I want to see if that remove is failing
