### ISSUE TITLE
[FAQ] exit code 1

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#795]
**Describe the bug**
Boss, after my mydumper task ends normally, its exit code is 1, is this normal?

**To Reproduce**
Command executed:
* mydumper with all the parameters
* myloader with all the parameters
--set-names=utf8 --no-backup-locks --less-locking --skip-tz-utc --complete-insert --trx-consistency-only -R -G -c -v 3 -r 100000   -x '^(?!(test\.|information_schema\.|performance_schema\.|sys\.))' -L dump_20220816.log -o 20220816153749

What mydumper and myloader version has been used?
mydumper 0.12.5-3, built against MySQL 5.7.38-41

**Expected behavior**

![image](https://user-images.githubusercontent.com/9590209/184829238-594317e8-62f5-4d85-8aff-0e11dd93f077.png)

**Comment by davidducos** [comment]
Hi @peng19832 can you share the complete log, as we need to understand better the scenario. Take into account that might be situations, like warnings and errors that increments the internal error counter. When mydumper finishes it exits returning the error counter.

**Comment by peng19832** [comment]
Hi @davidducos,  there are indeed some ERRORs in the log, but these DBs do not exist:
[dump_20220816.log](https://github.com/mydumper/mydumper/files/9355812/dump_20220816.log)
![image](https://user-images.githubusercontent.com/9590209/185020261-0ecca493-1086-4013-972b-d2b6e06a25a5.png)

**Comment by davidducos** [comment]
Hi @peng19832 ,
If there are errors in the log, then you can not expect a clean exit.
We use show databases to get the database names, so you might need to get rid of those databases or filter them out or filter in the databases that you want with -B.

**Comment by peng19832** [comment]
Oh, sorry boss , the inspection found that there are two dbs (.config and .cache) in the slave instance. Since mydumper exports data from the slave instance, this problem occurs. At the moment, it is unclear why there are these two dbs.

**Comment by peng19832** [comment]
In addition, there is another question, when I use myloader, after the data is imported, why is the last line in the log always: Starting table checksum verification。
![image](https://user-images.githubusercontent.com/9590209/185359529-155817d7-bb65-45ad-b1d4-2438755dbfcf.png)

**Comment by davidducos** [comment]
During the export you can get checksum table structure and data so in myloader can check if everything was imported correctly.
Please let me know if we can close this issue or if you need anything else.

**Comment by peng19832** [comment]
> During the export you can get checksum table structure and data so in myloader can check if everything was imported correctly. Please let me know if we can close this issue or if you need anything else.

Did the "starting table checksum..." here end normally?
After the data import is completed, is it possible to add a clear completion flag to the log, like the last "Finished..." in the mydumper log.This makes it easy to capture via script.

**Comment by peng19832** [comment]
In addition, can you add a function to check whether the DB is abnormal? It is convenient to know which dbs have problems before exporting data, so that these dbs can be automatically captured and excluded in the automatic script.

**Comment by davidducos** [comment]
@peng19832,
The "starting table checksum..." is shown always even if you didn't set to checksum the table on export phase.
We can add a last message with "Finished..."
I think you want some kind of categorization of the errors, for instance:
```
Data errors: 0
Index errors: 2
Post errors: 0
Other errors: 10
```
At the end of the script. Am I right?

**Comment by peng19832** [comment]
> 

yes,yes, thks boss ☺

**Comment by peng19832** [comment]
Problem solved, close post
