### ISSUE TITLE
[BUG] mydumper escape character is not working other than default (backslash)

### ISSUE THREAD

**Issue by vidyullathat** [mydumper/mydumper#796]
**Describe the bug**
Looks like mydumper is not honoring any other escape character other than default '\\'(backslash).   i tried with '"' but it is not honoring and still using the default '\\'(backslash) escape character.

**To Reproduce**
Command executed:
mydumper --host=<> --user=<> --password=<> --outputdir=$DumperDir --threads=8 --verbose=3 --port=3306 --trx-consistency-only --long-query-guard=600  --tables-list=$TABLE_SCHEMA.$TABLE_NAME --csv  --fields-terminated-by='|'  --fields-escaped-by='"' --logfile mydump.log

What mydumper and myloader version has been used?
mydumper --version
mydumper 0.12.5-3, built against MySQL 5.7.38-41

**Expected behavior**
we would expect mydumper to honor the passed  --fields-escaped-by='"'

**Environment (please complete the following information):**
 - OS version: Ubuntu 20.04.4 LTS
 - MyDumper version: mydumper 0.12.5-3, built against MySQL 5.7.38-41

**Additional context**
we are seeing errors like below when loading data into BigQuery as  \" is unfortunately not the proper way to escape in CSV  according to the RFC standard [1]

[1] https://www.rfc-editor.org/rfc/rfc4180#:~:text=7.%20%20If%20double%2Dquotes%20are%20used%20to%20enclose%20fields%2C%20then%20a%20double%2Dquote%0A%20%20%20%20%20%20%20appearing%20inside%20a%20field%20must%20be%20escaped%20by%20preceding%20it%20with%0A%20%20%20%20%20%20%20another%20double%20quote.%20%20For%20example%3A

 "errors": [
      {
        "location": "gs://xxxxxxx/mydumper202208111803/default_fulfillment.FUL_FULFILLMENT_ADDRESS.00000.dat",
        "message": "Error while reading data, error message: Error detected while parsing row starting at position: 276694512. Error: Data between close double quote (\") and field separator. File: gs://xxxxxxx/mydumper202208111803/default_fulfillment.FUL_FULFILLMENT_ADDRESS.00000.dat",
        "reason": "invalid"
      },

These issues are due to quote char not being escaped with a double quote in our CSV files. In our case quote char are escaped with a backslash.

below is the example of data in csv:
one of the field "ADDRESS_CITY" is having the value as "\\"Boynton Beach\\""

"xxxxx"|"c37a233af3c311d90534876cf629d93"|"US"|"xxxxxx"|"xxxx"|xxxxx|"xxxx"|\N|"2022-08-11 06:37:31.434000"|"Austin"|"\\"Boynton Beach\\""|"FL"|"xxxxxx"|"Shipping"|"xxxxx"|"3cdb7459-eef0-4917-b9db-39dea8c94b61"|"xxxxx"|1|\N|"xxxxxxx"|6601998514343544663|\N|"xxxxxx"|"2022-08-11 06:37:31.434000"|0|"1"|"CustomerShipToAddress"|\N

Data in MySQL looks like below:
mysql> select ADDRESS_CITY from default_fulfillment.FUL_FULFILLMENT_ADDRESS where PK=6601998512172695926;
"Boynton Beach"

**Comment by davidducos** [comment]
Bug confirmed, here is the test case:
```
mysql> create database default_fulfillment;
Query OK, 1 row affected (0.00 sec)
mysql> use default_fulfillment;
Database changed
mysql> create table FUL_FULFILLMENT_ADDRESS (PK bigint auto_increment primary key, ADDRESS_CITY varchar(30));
Query OK, 0 rows affected (0.01 sec)
mysql> insert into FUL_FULFILLMENT_ADDRESS values (6601998512172695926, '"Boynton Beach"');
Query OK, 1 row affected (0.00 sec)
mysql> select * from FUL_FULFILLMENT_ADDRESS;
+---------------------+-----------------+
| PK                  | ADDRESS_CITY    |
+---------------------+-----------------+
| 6601998512172695926 | "Boynton Beach" |
+---------------------+-----------------+
1 row in set (0.00 sec)
[root@mydumper1 mydumper]# rm -rf data; ./mydumper --outputdir=data --verbose=3 --trx-consistency-only -B default_fulfillment -T default_fulfillment.FUL_FULFILLMENT_ADDRESS --csv --fields-terminated-by='|' --fields-escaped-by='"' --logfile mydump.log
[root@mydumper1 mydumper]# cat data/default_fulfillment.FUL_FULFILLMENT_ADDRESS.00000.dat
6601998512172695926|"\"Boynton Beach\""
```

**Comment by davidducos** [comment]
We are going to implement this function https://github.com/percona/percona-server/blob/8.0/mysys/charset.cc#L778 in src/mydumper_common.c

**Comment by vidyullathat** [comment]
David,
how soon the fix will be available ?

**Comment by davidducos** [comment]
@vidyullathat,
why don't you test https://github.com/mydumper/mydumper/tree/fix_796 ? please let me know if works as I PR is not complete.

**Comment by davidducos** [comment]
Take into account that the PR merged doesn't support utf8mb4

**Comment by vidyullathat** [comment]
all of our tables are created with utf8mb4. you mean this fix is not applicable and we still continue to have same issues even on the latest mydumper when it gets released ?

**Comment by davidducos** [comment]
From the code:
```
    /*
 *      If the next character appears to begin a multi-byte character, we
 *      escape that first byte of that apparent multi-byte character. (The
 *      character just looks like a multi-byte character -- if it were actually
 *      a multi-byte character, it would have been passed through in the test
 *      above.)
 *      Without this check, we can create a problem by converting an invalid
 *      multi-byte character into a valid one. For example, 0xbf27 is not
 *      a valid GBK character, but 0xbf5c is. (0x27 = ', 0x5c = \)
 *      */
```
Take into account that I wanted to provide a solution to the escape character issue. Full fix is not complete, but I considered more important to fix the escape character issue.
