### ISSUE TITLE
Avoid 'Could not read data from db.table: Table definition has changed, please retry transaction' errors

### ISSUE THREAD

**Issue by grypyrg** [mydumper/mydumper#8]
MyDumper might get the following error in certain scenarios:

```
** Message: Thread 2 dumping data for `db`.`table`
** (mydumper:11031): CRITICAL **: Could not read data from db.table: Table definition has changed, please retry transaction
```
# Tests

Let's do some tests to see when in what situation we get this error...
## Environment

tests were done on the following env:

```
session2> select @@global.tx_isolation;
+-----------------------+
| @@global.tx_isolation |
+-----------------------+
| REPEATABLE-READ       |
+-----------------------+
1 row in set (0.00 sec)

session2> select version();
+-----------------+
| version()       |
+-----------------+
| 5.6.31-77.0-log |
+-----------------+
1 row in set (0.00 sec)
```
## 1. table already exists before backup starts and we read from it:

```
session1> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

session2> start transaction with consistent snapshot;
Query OK, 0 rows affected (0.00 sec)

session2> select * from t;
Empty set (0.00 sec)

session1> drop table t;
...

session2> show processlist;
+----+------+-----------+------+---------+------+---------------------------------+------------------+-----------+---------------+
| Id | User | Host      | db   | Command | Time | State                           | Info             | Rows_sent | Rows_examined |
+----+------+-----------+------+---------+------+---------------------------------+------------------+-----------+---------------+
| 23 | root | localhost | test | Query   |    0 | init                            | show processlist |         0 |             0 |
| 24 | root | localhost | test | Query   |    1 | Waiting for table metadata lock | drop table t     |         0 |             0 |
+----+------+-----------+------+---------+------+---------------------------------+------------------+-----------+---------------+
2 rows in set (0.00 sec)

```

The drop table will wait until this transaction has finished (metadatalock)
## 2: table already exists before backup starts and we did not yet read from it:

```
session1> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

session2> start transaction with consistent snapshot;
Query OK, 0 rows affected (0.00 sec)

session1> drop table t;
Query OK, 0 rows affected (0.00 sec)

session2> select * from t;
ERROR 1146 (42S02): Table 'test.t' doesn't exist
```

The drop table will just work, selecting from `t` will just show as if the table does not exist
## 3: table didn't exist before backup and we wanted to read from it (backup it):

```
session2> start transaction with consistent snapshot;
Query OK, 0 rows affected (0.00 sec)

session1> create table t (a int);
Query OK, 0 rows affected (0.00 sec)

session2> select * from t;
ERROR 1412 (HY000): Table definition has changed, please retry transaction
```

This is what fails, the table didn't exist before the backup started.
## 4: table existed before backup started and we altered the table before trying to backup the table

```
session1> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

session2> start transaction with consistent snapshot;
Query OK, 0 rows affected (0.00 sec)

session1> alter table t change a a bigint;
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

session2> select * from t;
ERROR 1412 (HY000): Table definition has changed, please retry transaction
```

This also fails, the alter happened during the transaction and there was no metadatalock on it yet so it succeeded
## 5: table existed before backup started and we altered the table after opening the table before backupping it

```

session1> create table t (a int);
Query OK, 0 rows affected (0.01 sec)

session2> start transaction with consistent snapshot;
Query OK, 0 rows affected (0.00 sec)

session2> select * from t;
Empty set (0.00 sec)


session1> alter table t change a a bigint;
...

session2> show processlist;
+----+------+-----------+------+---------+------+---------------------------------+---------------------------------+-----------+---------------+
| Id | User | Host      | db   | Command | Time | State                           | Info                            | Rows_sent | Rows_examined |
+----+------+-----------+------+---------+------+---------------------------------+---------------------------------+-----------+---------------+
| 23 | root | localhost | test | Query   |    0 | init                            | show processlist                |         0 |             0 |
| 24 | root | localhost | test | Query   |    8 | Waiting for table metadata lock | alter table t change a a bigint |         0 |             0 |
+----+------+-----------+------+---------+------+---------------------------------+---------------------------------+-----------+---------------+
2 rows in set (0.00 sec)

```

When we access the table first, a metadatalock is taken and the alter will not succeed.
## Summary

As we see in the different tests, the error happens in 2 occasions:
- When the table did not exist before the transaction was started
- When the table was altered/dropped before any transaction accessed it
# Suggested Fix `--metadata-locks`

In order to prevent this, I suggest to add an option `--metadata-locks` and ensure the main `mydumper` transaction, which remains active for the duration of the backup (if there's such thing in `mydumper`) to 
- gather a list of all tables and keep it as method to figure out which tables to backup (to not backup tables which are created after the backup started)
- open all tables as soon as possible, taking metadatalocks (not including the schema's/tables that don't match the filters)
## Benefits

This will avoid any `ALTER`/`DROP` table on existing tables and allow `mydumper` to remain a consistent snapshot of the dataset.

This should prevent any `1412` errors except that you might get them during gathering of the list of tables and opening tables, where `mydumper` can just retry the whole process)

This is also better than doing `FLUSH TABLE WITH READ LOCK` as this only takes metadatalocks and does not prevent reads/writes but only schema changes.
### timeout metadatalocks

Maybe as addition there should be functionality to determine if a backup should abort if it holds metadatalocks too long and starts causing too much impact on the environment.
### kill schema changes

Opposite to the 'timeout metadatalocks' feature, killing schema changes that wait on metadatalocks automatically by `mydumper` might also be desired as this would reduce impact.

However, don't think too much about it, this just breaks many things, especially when run on a slave, but just might be desired in some cases.
## Drawbacks

As drawback, this actually avoids any schema changes during the backup process and if schema changes happen, subsequent queries on those tables will be locked until the backup is complete.

This can be serious and other options such as `--use-savepoints` are there to reduce impact on metadatalocking, but if you really want a consistent backup, it's what we need to do IMO.

**Comment by grypyrg** [comment]
Did I just describe Percona's backup locks? 😄  https://www.percona.com/doc/percona-server/5.6/management/backup_locks.html

**Comment by maxbube** [comment]
Hey @grypyrg !

What you are describing is how mydumper were working before --use-savepoints. Before that the main connection, which loops all schemas adding table to the queues, were taking MDL during the whole backup duration.

>>>
As drawback, this actually avoids any schema changes during the backup process and if schema changes happen, subsequent queries on those tables will be locked until the backup is complete
<<<

This scenario could cause a production outage,  i.e. hit max_connection, excessive load, SBM, if the application is not able to handle it.

>>>
This is also better than doing FLUSH TABLE WITH READ LOCK as this only takes metadatalocks and does not prevent reads/writes but only schema changes.
<<<

MDL doesn't avoid the need of a global read lock, as we need to coordinate thread snapshots to be within the same binlog position, that could be done by FTWRL or as you mention Percona Backup Locks (BTW they are already implemented on master branch :) ). 

That said, one option could be to keep all MDL and release them only if --use-savepoints. But still I don't think this would help for ALL scenarios, and Im worried about outages this could cause.

**Comment by grypyrg** [comment]
Actually I think the suggestion I made is basically a hack to get Percona's Backup Locks functionality.
This doesn't require new functionality but just requires the hosts that get these errors to get Percona Server with Backup Locks.

What do you think?

**Comment by verwilst** [comment]
I'm running into this regularly, is there anything that can be done to alleviate the issue for the time being?

**Comment by magenbrot** [comment]
same problem here. Maybe there's some workaround for this until it's fixed?

**Comment by DimitriSteyaert** [comment]
@grypyrg @maxbube I'm still encountering this issue when the table did not exist before the transaction was started. Did you guys find a workaround for this?

**Comment by Raman2407kumar** [comment]
I was having the same issue when I tried to read data from one of the tables. Well, the problem seems to be internet connectivity. I restarted MySQL and Apache and improved on the internet connectivity and it was solved :)

**Comment by davidducos** [comment]
In order to fix this issue and also:
- https://github.com/mydumper/mydumper/issues/254
- https://github.com/mydumper/mydumper/issues/383
We need to establish how we are going to finally implement the solution.
First of all, we will need to keep FTWRL to sync all the threads, but that just give us the same starting point for all the threads, which is needed, but what about the DDLs that break the consistency of the backup? 
The different solutions that provide the databases are going to be used:
- LOCK INSTANCE FOR BACKUP on MySQL 8
- What is already implemented for PS5.7: LOCK TABLES FOR BACKUP
- or the different options in MariaDB.

So, what we are going to be doing will be:
- main connection: FTWRL 
- each thread: START TRANSACTION WITH CONSISTENT SNAPSHOT
- main connection: LOCK INSTANCE FOR BACKUP with MySQL/PS 8 | BACKUP STAGE with MariaDB
- main connection: UNLOCK TABLES
- main connection: LOCK TABLES FOR BACKUP with PS 5.7  | BACKUP STAGE [START|BLOCK_DDL] with  MariaDB 
- main connection: UNLOCK INSTANCE | UNLOCK TABLES | BACKUP STAGE END MariaDB

**Comment by davidducos** [comment]
Or:
- main connection: LOCK INSTANCE FOR BACKUP with MySQL/PS 8 | BACKUP STAGE with MariaDB
- main connection: LOCK TABLES FOR BACKUP with PS 5.7 | BACKUP STAGE [START|BLOCK_DDL] with MariaDB
- main connection: FTWRL
- each thread: START TRANSACTION WITH CONSISTENT SNAPSHOT
- main connection: UNLOCK TABLES
- main connection: UNLOCK INSTANCE | UNLOCK TABLES | BACKUP STAGE END MariaDB
-

**Comment by davidducos** [comment]
I have just realize that when PS 5.7 is used, the release command is UNLOCK TABLES which also releases the FTWRL, in such cases we will need another connection to send the LOCK TABLES FOR BACKUP.
