### ISSUE TITLE
Mysql restore failed because of corrupted root user password

### ISSUE THREAD

**Issue by ajay56611** [mydumper/mydumper#802]
What mydumper and myloader version has been used?

0.9.5

**Expected behavior**
without changing the root user password restore needs to be successful

**Environment (please complete the following information):**
 - OS version: [debian]
 - MyDumper version: 0.9.5

**Additional context**
![image](https://user-images.githubusercontent.com/19441176/185698420-921f0220-b763-4439-8217-853053a52d82.png)

**Comment by davidducos** [comment]
Why don't you test with a newer version?
