### ISSUE TITLE
myloader on centos 7 not working GLIBC_2.28 ZLIB_1.2.7.1 ZLIB_1.2.9

### ISSUE THREAD

**Issue by aliparsa** [mydumper/mydumper#809]
myloader: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by myloader)

myloader: /lib64/libz.so.1: version `ZLIB_1.2.7.1' not found (required by myloader)

myloader: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by myloader)

**Comment by davidducos** [comment]
Can you explain more about your issue? did you install it from a package? What version?
