### ISSUE TITLE
[BUG] version number in debian package for 0.12.5-3 release are not good

### ISSUE THREAD

**Issue by aqueos** [mydumper/mydumper#811]
**Describe the bug**
Debian package mydumper_0.12.5-3-zstd.bullseye_amd64.deb
 and mydumper_0.12.5-3.buster_amd64.deb
 and  mydumper_0.12.5-3.bullseye_amd64.deb
conflict in repository

**To Reproduce**
add to a private repo the two package and they conflict

```
/root/mydumper_0.12.5-3.buster_amd64.deb: component guessed as 'main'
ERROR: '/root/mydumper_0.12.5-3.buster_amd64.deb' cannot be included as 'pool/main/m/mydumper/mydumper_0.12.5-3_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 9d3083b6222896ca8d8639d0ff5e2e05, got: 6e54a51f734c783a96e1fd88a336b199
sha1 expected: 3724fd3c2d2c7bf88c4fa921a2c0eb6a7861043d, got: 4e4553190d3683d1d53bf95fd2f07d59dea9ffa3
sha256 expected: f8ca3aaee242df4abea979554681db8bceb1bcf9cd5e4e7c9f2c4606e1496aea, got: 88f1e0e118d1976fa49f12dc5a17783dc3fab316bb3ad6d4aa528a34c09ff2d7
size expected: 2895644, got: 1012224
There have been errors!
```

Seems the zstd version miss the zstd somewhere in the version of the package. 
There was no issue for the previous ones.

```
Package: mydumper
Version: 0.12.5-3
```

from https://github.com/mydumper/mydumper/issues/534

we should have 

```
Version: 0.12.5-3~jessie 
Version: 0.12.5-3~buster
Version: 0.12.5-3-zstd~buster
```

or something like this  ?

best regards,
Ghislain.

**Comment by davidducos** [comment]
Hi @aqueos, I have just realized that the `~` is being replaced with `.` by github. That is why you can see that the filename in the MD5/SHA1/SHA256 list are ok, but they are not in the file list. 
The `Version: ` has been fixed.

**Comment by aqueos** [comment]
thanks a lot that was fast ! :)
well if our tools where not messing with us what fun would it be !

quick question, will you rebuild the latest release packages or is the 0.12.7 ready to launch ? :)

best regards,
Ghislain.

**Comment by davidducos** [comment]
@aqueos, sorry, you will need to wait...
