### ISSUE TITLE
[BUG] Increasing the amount of threads, increases the amount of memory usage

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#850]
During one of my tests, I realized that when I set the amount of threads to 12, the % of memory used by mydumper went from 5% to 15%.

**Comment by ToothlessRebel** [comment]
Does that not make sense?

**Comment by davidducos** [comment]
At this point, I think that it is too much, but I will be reviewing to confirm that it is what we should expect or fix the memory leaks.

**Comment by davidducos** [comment]
After implementing #859 or which is the same, second stage of #529, fixed this "issue".
