### ISSUE TITLE
[BUG] 0.12.7-3 crashed, mysql 5.7 and mysql 8.0

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#853]
**Describe the bug**
mysql version: 5.7, 8.0
Only a few instances have triggered the bug
segfault at 10 ip 0000000000443067 sp 00007f6825965b40 error 4 in mydumper[400000+369000]
![image](https://user-images.githubusercontent.com/9590209/194684786-47fcaf75-5b97-47f4-b806-24cba165bff0.png)

**To Reproduce**
Command executed:
* mydumper with all the parameters
* myloader with all the parameters
```
mydumper -h IP -P 23306 -u backup -p password  --set-names=utf8 --no-backup-locks --less-locking --skip-tz-utc --complete-insert --trx-consistency-only -R -G -c -v 3 -r 100000   -x '^(?!(test\.|information_schema\.|performance_schema\.|sys\.))' -L dump_2022
1008.log -o 20221008020002
```

What mydumper and myloader version has been used?
mydumper 0.12.7-3, built against MySQL 5.7.39-42

**Log**
The log content is interrupted

no coredump

**Comment by Dansthunder** [comment]
Same, with lots of rows.  Try rolling back to v0.11.x   Version 0.12.x with --rows segfaults for us as well.

**Comment by peng19832** [comment]
Duplicate #848

**Comment by kkpeter** [comment]
Same with me

**Comment by davidducos** [comment]
Hi @peng19832 @kkpeter @Dansthunder 
I need  you to test https://github.com/mydumper/mydumper/releases/tag/v0.13.0-1 to close this issue.

**Comment by peng19832** [comment]
> https://github.com/mydumper/mydumper/releases/tag/

manual complie? i will try try ^_^
