### ISSUE TITLE
[BUG] Tables having column type ' text DEFAULT NULL, ' get "0x" appended to their statement where value in dump is NULL.

### ISSUE THREAD

**Issue by itstin** [mydumper/mydumper#869]
**Describe the bug**
Creating a dump using mydumper, causes statements on tables with column type: " text DEFAULT NULL, " append '0x' on NULL values, where no value exists. The dump itself did NOT produce any errors in verbose 3 logs, but the error message is produced while  importing dump using myloader, or when manually inserting the problematic statements.

**To Reproduce**
Command executed:
* mydumper with all the parameters
/usr/bin/mydumper -c -t 6 --trx-consistency-only --build-empty-files -G -E -R --verbose 3 --outputdir=/backup  >>  /log/dumper.log 2>&1
* myloader with all the parameters
/usr/bin/myloader --directory /backup --verbose 3 --threads 6 --overwrite-tables --compress-protocol >>  /log/loader.log 2>&1

What mydumper and myloader version has been used?
mydumper --version
mydumper0.13.0-1, built against MySQL 5.7.39-42 with SSL support with GZIP
myloader --version
myloader0.13.0-1, built against MySQL 5.7.39-42 with SSL support with GZIP

**Expected behavior**
Normal dump/restore just like in previous versions

**Log**
[mydumper.log](https://github.com/mydumper/mydumper/files/9901210/mydumper.log)
[myloader.log](https://github.com/mydumper/mydumper/files/9901213/myloader.log)

**Backup**
Clean creation of all neccessary files, no unexpected behaviour, of every table we have "-metadata" , "-schema.sql.gz" , ".00000.sql.gz" , and ofcourse the global "metadata" file

**How to repeat**
Using table created by mysql will still produce this error, if we spin up fresh instance of mariadb 10.6.10 and perform both mydumper and myloader, we will get this issue 

**Environment (please complete the following information):**
 - OS version: [CentOS-79-64-minimal]

**Comment by datascience-dba** [comment]
Thank you for logging this as a bug. I was collecting info on it for the same purpose.

Please note that this also occurs on mediumblob fields.
In mysqldump the data is just an empty string - '' while in mydumper it is 0x.

**Comment by davidducos** [comment]
Hi @datascience-dba @itstin 
I did the next test case:
```
CREATE TABLE `issue_869` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `val` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
insert into issue_869(val) values ("test");
insert into issue_869(val) values (NULL);
insert into issue_869() values ();

[root@mydumper1 mydumper]# ./mydumper -T test.issue_869  -o data --stream
-- test.issue_869-schema.sql
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

/*!40103 SET TIME_ZONE='+00:00' */;
CREATE TABLE `issue_869` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `val` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- test.issue_869.00000.sql
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `issue_869` VALUES(1,0x74657374)
,(2,NULL)
,(3,NULL)
;
[root@mydumper1 mydumper]# ./mydumper -T test.issue_869  -o data --stream | ./myloader -d data/ -B test2 -v 3 -o --stream
** Message: 20:01:18.291: Server version reported as: 5.7.38-41-log
** Message: 20:01:18.304: Intermediate queue: Sending END job
** Message: 20:01:18.305: Removing file: /root/issue_869/mydumper/data/test.issue_869-schema.sql
** Message: 20:01:18.305: Intermediate thread ended
** Message: 20:01:18.306: Thread 1 restoring table `test2`.`issue_869` from /root/issue_869/mydumper/data/test.issue_869-schema.sql
** Message: 20:01:18.306: Dropping table or view (if exists) `test2`.`issue_869`
** Message: 20:01:18.307: Intermediate thread: SHUTDOWN
** Message: 20:01:18.392: Thread 1: Creating table `test2`.`issue_869` from content in /root/issue_869/mydumper/data/test.issue_869-schema.sql
** Message: 20:01:18.852: Thread 3 restoring `test2`.`issue_869` part 1 of 1 from test.issue_869.00000.sql. Progress 1 of 1.
** Message: 20:01:18.853: Thread 4: Data import ended
** Message: 20:01:18.853: Thread 1: Data import ended
** Message: 20:01:18.854: Thread 2: Data import ended
** Message: 20:01:18.857: Removing file: /root/issue_869/mydumper/data/test.issue_869.00000.sql
** Message: 20:01:18.857: Thread 3: Data import ended
** Message: 20:01:18.857: Thread 3: Starting post import task over table
** Message: 20:01:18.858: Thread 4: Starting post import task over table
** Message: 20:01:18.858: Thread 1: Starting post import task over table
** Message: 20:01:18.858: Thread 2: Starting post import task over table
** Message: 20:01:18.859: Starting table checksum verification
[root@mydumper1 mydumper]# mysql test2 -e 'select * from issue_869';
+----+------+
| id | val  |
+----+------+
|  1 | test |
|  2 | NULL |
|  3 | NULL |
+----+------+
```
If I don't understood incorrectly the error, that says that the problem is in the FIELD LIST, not in the data. Can you share the file that is failing? or at least the INSERT INTO statement without any value.

**Comment by datascience-dba** [comment]
Good evening.

Please see the attacment. It contains the commands and the files etc.

The 0x is inserted as a hex number in the mediumblob field.

Let me know if you need anything else.

Regards


Quoting David Ducos ***@***.***>:

**Comment by datascience-dba** [comment]
[dbname.tabname_0x_issue_869.tar.gz](https://github.com/mydumper/mydumper/files/9924119/dbname.tabname_0x_issue_869.tar.gz)

**Comment by davidducos** [comment]
@datascience-dba I was able to reproduce your issue, but it is not NULL values, it is EMPTY values, like `""`

**Comment by datascience-dba** [comment]
Good afternoon David.

Correct. This is from my original comment:

Please note that this also occurs on mediumblob fields.
In mysqldump the data is just an empty string - '' while in mydumper it is 0x.

I did an export with mysqldump and the field value was just empty.



--
-- Dumping data for table `tabname`
--
-- WHERE:  id = '1ec1d483-6fec-0687-b613-cfbe4bea2b86'  and  
downstream_process_id = '1ec1d482-fe54-0c5c-b613-cfbe4bea2b86'

LOCK TABLES `tabname` WRITE;
/*!40000 ALTER TABLE `tabname` DISABLE KEYS */;
INSERT INTO `tabname` VALUES  
('1ec1d483-6fec-0687-b613-cfbe4bea2b86','1ec1d482-fe54-0c5c-b613-cfbe4bea2b86','','UPDATE_FROM_DOWNSTREAM_FAILED','SYS','2021-09-24  
15:00:53',NULL,NULL,'QRPPPPPPPPPPP001');
/*!40000 ALTER TABLE `tabname` ENABLE KEYS */;
UNLOCK TABLES;
SET @@SESSION.SQL_LOG_BIN = @MYSQLDUMP_TEMP_LOG_BIN;
/*!40103 SET ***@***.***_TIME_ZONE */;

Regards




Quoting David Ducos ***@***.***>:

**Comment by itstin** [comment]
I would not know on which subject to open bug report, so you can refer me @davidducos .
Did you manage to take a look at error inside myloader.log on line nr.519 ? 
The blob fix did it's job but now I am dealing with some temp table.
Same error occures on new myloader0.13.0-3
` Table 'sys.x$memory_by_thread_by_current_bytes' doesn't exist`
Sorry if I'm spamming this issue number

**Comment by davidducos** [comment]
@itstin go to https://github.com/mydumper/mydumper/issues/new/choose on `Bug report` hit on `Get started`, be careful... it is a one way journey... 🤣 

I don't know which log are you talking about...

**Comment by itstin** [comment]
Pardon my ignorance, the myloader.log I've uploaded in this original bug report shows the CRITICAL error i've discovered during restore 
https://github.com/mydumper/mydumper/files/9901213/myloader.log

I will be creating new bug report later on and will try to gather all neccessary information. Thank you David !!
