### ISSUE TITLE
[FEATURE] per table --where.  --where-table

### ISSUE THREAD

**Issue by maxpowerstl** [mydumper/mydumper#881]
I know this sounds daunting but it would allow for some pretty complex extraction of specific data (mock joins against other tables using EXISTS()).  How to implement this?  I haven't the foggiest idea.  Maybe something like --where-table "_tablename_:_where clause_" ?

We have an multi tenant application.   Some of those tenants are quite large and we pull a copy of the database with only their data and a snapshot of the application for use in a DR environment should something end up happening with our company.  The current process (due to it being a live system):

1. grabs a snapshot of the entire database.
2. Loads that snapshot into a temporary instance (it's pretty big database and takes a long time to load, even with myloader)
3. Selects the specific tenant data across multiple related tables (sometimes multiple relations deep) into a another blank copy of the schema.
4. Dumps the final filtered copy of the database

All of this is done in order to work from a consistent snapshot and to minimize cost.  The temporary db instance is only kept around long enough to do the work.  The problem is the data is getting larger and larger (even with archiving of older data).

I think it would be entirely possible, due to how mydumper locks the tables initially and then acquires a transaction for each connection, to completely forgo the existing process and simply use a per table where clause.

**Comment by maxpowerstl** [comment]
I just thought of another really nice hack you could do with this (maybe already a feature but I don't think it is).  Dumping the table schema but not the data ... using --where-table "tablename:0"

**Comment by davidducos** [comment]
Did you check the last bullet point in https://github.com/mydumper/mydumper#defaults-file ? We already have a where clause per table. If that is what you need, then please, close this issue.

**Comment by maxpowerstl** [comment]
oh wow! that's awesome.  I completely overlooked it.  thanks!
