### ISSUE TITLE
Question using MariaDB 10.9.3

### ISSUE THREAD

**Issue by Thechag77** [mydumper/mydumper#882]
I'm using Mydumper .12.7-3 to backup a mariadb 10.5 prod server and i'm testing a restore in a staging environment with mariaDB 10.9.
For some reasons, although structure is the same, and no errors during the restore, I seem to be having issues accessing my application.
I've also tried taking a working mariadb 10.9 DB and restore it to another DB and i'm unable to, i get the same result in my application. 
But using Mysqldump i'm able to restore 10.5 to 10.9 without a glitch.
Is there a known issue with Mariadb 10.9 and mydumper/myloader .12.7-3 ?

As a side note, the staging env was 10.5 upgraded to 10.9, and all the hosted DB on it are still working. it's only new restore that don't seems to be working fine. The same Mariadb 10.5 backup restored on a 10.5 environment works fine.

**Comment by davidducos** [comment]
Hi @Thechag77 , your question is vague, we need a test case to reproduce your issue. Please, check the bug template to send us the information needed to be able to help you.

**Comment by Thechag77** [comment]
Hi David, sorry for being vague. Here's some more detailed information

Using Mydumper/loader .12.7-3 or .9.5 (tested both)

Backup command : 
mydumper --user=$Dbuser --password=$Dbpassword --host=$dbHost -B '$db' \
 -o /data/backup/pprod/`date +%Y-%m-%d_%H-%M` --long-query-guard=120 --triggers --events --routines \
 --build-empty-files --less-locking --success-on-1146  --compress-protocol --threads=4 --verbose=3 \
 --use-savepoints --logfile=/data/backup/pprod/mydumper_`date +%Y-%m-%d_%H-%M`.txt

Restore command : 
myloader --user=$Dbuser --password=$Dbpassword --host=$dbHost --source-db='$db' \
 --directory=/data/backup/pprod/2022-11-09_14-30  --queries-per-transaction=50000 --compress-protocol \
 --threads=4 --verbose=3 --overwrite-tables --logfile=/data/backup/pprod/myloader_`date +%Y-%m-%d_%H-%M`.txt

Everything runs fine, no error whatsoever, but if those backup are restored on mariaDB 10.9 instead of MariaDB 10.5 the application using that DB hangs, as if Indexes or triggers aren't present (Same feeling for end user in our app).

I also get Aborted connection in the the logs.

2022-11-09 10:09:54 530756 [Warning] Aborted connection 530756 to db: '$DB' user: '$User' host: '$Host' (Got timeout reading communication packets)

Permissions are fine, indexes and triggers are also restored properly, but the effect on the application is everything is very slow as if indexes weren't there.
Executing the exact same restore command with a MariaDB 10.5 yield no issues, everything works fine. This is why i was wondering if any other issues were identified with MariaDB 10.9.

This has been tested on an Upgraded MariaDB 10.5 --> 10.9 and also on a new fresh MariaDB 10.9 with same result.

A restore using Mysqldump with the below command work, without any issues describe above.
Mysqldump command : 
                  mysqldump -u$DB_BACKUP_USERNAME -p$DB_BACKUP_PASSWORD  -h$DB_HOSTNAME  $db --single-transaction  --quick > "$db.sql"

Not sure what else to provide to you.
