### ISSUE TITLE
[BUG] Error restoring sys.processlist-schema-view 

### ISSUE THREAD

**Issue by itstin** [mydumper/mydumper#885]
**Describe the bug**
During restore procedure, after `Data Import` has ended, Myloader hits an error restoring `sys.processlist-schema-view.sql.gz` from dump created using Mydumper

**To Reproduce**
Command executed:
mydumper with all the parameters
~  /usr/bin/mydumper -c -t 6 --trx-consistency-only --build-empty-files -G -E -R --verbose 3 --outputdir=/backup >> /log/dumper.log 2>&1
myloader with all the parameters
~ /usr/bin/myloader --directory /backup --verbose 3 --threads 6 --overwrite-tables --compress-protocol >> /log/loader.log 2>&1

What mydumper and myloader version has been used?
mydumper0.13.0-3, built against MySQL 5.7.39-42 with SSL support with GZIP
myloader0.13.0-3, built against MySQL 5.7.39-42 with SSL support with GZIP

**Expected behavior**
Restore all `sys` tables with no issues. 

**Log**
I will be uploading 2 errors corelating to the same type of issue using 2 diffenent mydumper/myloader versions
[myloader_0.13.0-1.log](https://github.com/mydumper/mydumper/files/9981939/myloader_0.13.0-1.log)
[myloader_0.13.0-3.log](https://github.com/mydumper/mydumper/files/9981940/myloader_0.13.0-3.log)

**Backup**
For the sake of data secrecy, i will only be uploading a list of sys.* files created by mydumper0.13.0-3 
[longlist of sys. tables.log](https://github.com/mydumper/mydumper/files/9981966/longlist.of.sys.tables.log)

**How to repeat**
Restore data into empty 10.6.11-MariaDB Server

**Environment (please complete the following information):**
 - [CentOS-79-64-minimal]

**Additional context**

**Comment by davidducos** [comment]
Hi @itstin I need the full myloader log with all the entries related to sys to understand why sys.x$memory_by_host_by_current_bytes has not been created.

**Comment by itstin** [comment]
[full_sys_log.log](https://github.com/mydumper/mydumper/files/9987794/full_sys_log.log)

**Comment by davidducos** [comment]
Hi @itstin, you didn't provide the information that I requested, so let me be more specific. 
In one of the files like this: `sys.mydumper_*-schema.sql.gz` you should have the CREATE TABLE statement for `sys.x$memory_by_host_by_current_bytes`. In the log, should be an entry like this:
```** Message: 12:29:24.206: Thread 4: Creating table `sys`.`x$memory_by_host_by_current_bytes` from content in sys.mydumper_23-schema.sql.gz```
There is anything like that in the log?

**Comment by itstin** [comment]
Yup there is plenty, I took my time to prepare a bit better report for you. I started by tracking down 
`** Message: 13:08:34.556: Thread 3: Creating table `sys`.`x$memory_by_thread_by_current_bytes` from content in //backup/restore/folder/1668171968/sys.mydumper_16-schema.sql.gz`
I've noticed there were two very similarly-named tables, first one being `memory_by_thread_by_current_bytes` , and second one being `x$memory_by_thread_by_current_bytes` with the prepended `x$`

 cat sys.mydumper_16-schema.sql 
/*!40101 SET NAMES binary*/;
CREATE TABLE IF NOT EXISTS `x$memory_by_thread_by_current_bytes`(
`thread_id` int,
`user` int,
`current_count_used` int,
`current_allocated` int,
`current_avg_alloc` int,
`current_max_alloc` int,
`total_allocated` int
);

Also: 
`** Message: 13:08:34.518: Thread 5: Creating table `sys`.`memory_by_thread_by_current_bytes` from content in //backup/restore/folder/1668171968/sys.memory_by_thread_by_current_bytes-schema.sql.gz`
cat sys.memory_by_thread_by_current_bytes-schema.sql 
/*!40101 SET NAMES binary*/;
CREATE TABLE IF NOT EXISTS `memory_by_thread_by_current_bytes`(
`thread_id` int,
`user` int,
`current_count_used` int,
`current_allocated` int,
`current_avg_alloc` int,
`current_max_alloc` int,
`total_allocated` int
);

cat sys.memory_by_thread_by_current_bytes-schema-view.sql 
/*!40101 SET NAMES binary*/;
DROP TABLE IF EXISTS `memory_by_thread_by_current_bytes`;
DROP VIEW IF EXISTS `memory_by_thread_by_current_bytes`;
SET @PREV_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @PREV_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @PREV_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET character_set_client = utf8mb3;
SET character_set_results = utf8mb3;
SET collation_connection = utf8mb3_general_ci;
CREATE ALGORITHM=TEMPTABLE DEFINER=`mariadb.sys`@`localhost` SQL SECURITY INVOKER VIEW `memory_by_thread_by_current_bytes` AS select `mt`.`THREAD_ID` AS `thread_id`,if(`t`.`NAME` = 'thread/sql/one_connection',concat(`t`.`PROCESSLIST_USER`,'@',`t`.`PROCESSLIST_HOST`),replace(`t`.`NAME`,'thread/','')) AS `user`,sum(`mt`.`CURRENT_COUNT_USED`) AS `current_count_used`,`sys`.`format_bytes`(sum(`mt`.`CURRENT_NUMBER_OF_BYTES_USED`)) AS `current_allocated`,`sys`.`format_bytes`(ifnull(sum(`mt`.`CURRENT_NUMBER_OF_BYTES_USED`) / nullif(sum(`mt`.`CURRENT_COUNT_USED`),0),0)) AS `current_avg_alloc`,`sys`.`format_bytes`(max(`mt`.`CURRENT_NUMBER_OF_BYTES_USED`)) AS `current_max_alloc`,`sys`.`format_bytes`(sum(`mt`.`SUM_NUMBER_OF_BYTES_ALLOC`)) AS `total_allocated` from (`performance_schema`.`memory_summary_by_thread_by_event_name` `mt` join `performance_schema`.`threads` `t` on(`mt`.`THREAD_ID` = `t`.`THREAD_ID`)) group by `mt`.`THREAD_ID`,if(`t`.`NAME` = 'thread/sql/one_connection',concat(`t`.`PROCESSLIST_USER`,'@',`t`.`PROCESSLIST_HOST`),replace(`t`.`NAME`,'thread/','')) order by sum(`mt`.`CURRENT_NUMBER_OF_BYTES_USED`) desc;
SET character_set_client = @PREV_CHARACTER_SET_CLIENT;
SET character_set_results = @PREV_CHARACTER_SET_RESULTS;
SET collation_connection = @PREV_COLLATION_CONNECTION;

Let me know if i missed something again so I can get back to you. I've provided complete logs this time.
[myloader.log](https://github.com/mydumper/mydumper/files/9991077/myloader.log)
[mydumper.log](https://github.com/mydumper/mydumper/files/9991080/mydumper.log)

**Comment by davidducos** [comment]
Oh good... we are restoring views in a multithreaded fashion and we don't expect that a view will be calling another view. However, you are doing exactly that, memory_by_thread_by_current_bytes is a view that is using another view: x$memory_by_thread_by_current_bytes.
Ok, the views needs to be restored single threaded...
