### ISSUE TITLE
[BUG] v0.13.0-1，mysql8.0，coredump

### ISSUE THREAD

**Issue by peng19832** [mydumper/mydumper#889]
**Describe the bug**
dump data failed，exit code：-11
[coredump.tar.zip](https://github.com/mydumper/mydumper/files/9986133/coredump.tar.zip)

**To Reproduce**
Command executed:
* mydumper with all the parameters
* myloader with all the parameters
--set-names=utf8 --no-backup-locks --less-locking --skip-tz-utc --complete-insert --trx-consistency-only --hex-blob --skip-definer -R -G -c -r 100000 -v 3   -x '^(?!(test\.|information_schema\.|performance_schema\.|sys\.))' -L dump_20221111.log -o 20221111100520

What mydumper and myloader version has been used?
v0.13.0-1

**Expected behavior**
use --hex-blob --skip-definer

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
![image](https://user-images.githubusercontent.com/9590209/201249383-2dfe8399-ba4a-4c1e-92c6-44a99b18f28b.png)

**Environment (please complete the following information):**
 - OS version: [e.g. CentOS 7.9, Ubuntu 20.04]
 centos 7
 - MyDumper version: [ mydumper --version ]
 v0.13.0-1

**Comment by peng19832** [comment]
Oh,no, The coredump is still caused by “--row“

**Comment by davidducos** [comment]
Hi @peng19832 why don't you test with latest prerelease v0.13.0-3

**Comment by peng19832** [comment]
v0.13.0-3 is fine, thks Boss ^-^
