### ISSUE TITLE
Ability to dump and load backups to / from object store

### ISSUE THREAD

**Issue by aadant** [mydumper/mydumper#893]
For example S3 or GCS

https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-utilities-load-dump.html#mysql-shell-utilities-load-dump-opt-s3-aws

**Comment by davidducos** [comment]
I will be writing a Blog Post and documentation this week about it, test were made and found a bug.

**Comment by davidducos** [comment]
Hi @aadant, Here is the BP that I wrote about upload a backup: https://www.percona.com/blog/upload-ongoing-mydumper-backups-to-s3/.
If you want to to load from a backup in S3, I think that using stream is you best choice, as --exec nor --exec-per-thread is not implemented yet on myloader. However, --exec-per-thread will be https://github.com/mydumper/mydumper/issues/924, but I'm not sure how can that will allow you to restore it. I'm still think that stream is the best choice for it.

**Comment by LinuxJedi** [comment]
By the way, we could integrate tighter S3 and compatible support relatively easy, I wrote a library that MariaDB uses for its S3 engines called libmarias3 (https://github.com/mariadb-corporation/libmarias3). It should be relatively easy to integrate if it is something you want to do.

**Comment by davidducos** [comment]
Hi @LinuxJedi, honestly, adding this will be another thing to maintain, and that we will need to test. And we already gave a solution to upload to S3 and actually it is an option to do whatever you want. 
You can convince me if there is a use case that I'm not seeing... :D

**Comment by LinuxJedi** [comment]
Nope, I was just suggesting a tighter integration option, that is all :)
