### ISSUE TITLE
Detected automatically if SSL should be enabled

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#896]
It would be nice if the cmake setup detected which dev headers were in use and set the correct defines.

_Originally posted by @drawks in https://github.com/mydumper/mydumper/issues/808#issuecomment-1312138766_

**Comment by davidducos** [comment]
Hi @LinuxJedi , 

Can I assign this to you?

**Comment by LinuxJedi** [comment]
> Hi @LinuxJedi ,
> 
> Can I assign this to you?

Yes, sorry, last couple of weeks have been hectic. Self-assigned.
