### ISSUE TITLE
[BUG] Segfaults with different versions

### ISSUE THREAD

**Issue by knutov** [mydumper/mydumper#912]
I have segfaults when creating dump with mydumper. The strange thing - on one server stable (0.12.7-3) version segfaults while (0.13.0-6) version works fine and on another server they are act opposite.

Segfault with 0.12.7-3 on AMD Ryzen 5950x with 5.4.17-2136.313.6.el7uek.x86_64 kernel (alpha version works fine here):

```
[ 9559.871772] mydumper[11988]: segfault at 10 ip 0000000000439ee7 sp 00007f69b5ffab40 error 4 in mydumper[400000+363000]
[ 9559.871776] Code: 89 df 48 8b 10 e8 b9 ae ff ff 31 c0 eb b5 4c 89 e7 e8 2d 3e 01 00 31 c0 eb a9 66 0f 1f 84 00 00 00 00 00 55 48 89 e5 41 54 53 <48> 83 7f 10 00 48 89 fb 74 27 48 8b 57 18 48 85 d2 0f 84 d2 00 00
```

On Xeon v3 server with 5.11.22-4-pve alpha version segfaults, while stable works fine.

**Log**
> If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.

have no access to the production setup now, but may be will be able to reproduce and run with `--verbose` later.

Latest Percona MySQL 5.7 installed on both servers.

**Comment by knutov** [comment]
```
[22381.793193] myloader[561]: segfault at 4 ip 00007f0c971a4dd7 sp 00007f0bd5ffabb0 error 4 in libglib-2.0.so.0.5600.1[7f0c9713c000+114000]
[22381.793207] Code: 8d 75 ff 4c 89 f1 48 c1 e1 04 49 89 cc 4c 03 23 49 8b 14 24 48 85 d2 0f 84 06 01 00 00 48 8b 5a 08 48 85 db 0f 84 e9 00 00 00 <48> 8b 03 48 89 42 08 49 8b 44 24 08 48 85 c0 74 09 48 83 e8 01 49
```

```
myloader0.13.0-6, built against MySQL 5.7.39-42 with SSL support with GZIP
```

**Comment by davidducos** [comment]
Hi @knutov,

Can you fill up in this thread the info in: https://github.com/mydumper/mydumper/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D ??
