### ISSUE TITLE
[BUG] Huge memory leaks in current master

### ISSUE THREAD

**Issue by LinuxJedi** [mydumper/mydumper#916]
**Describe the bug**
Current master is leaking a lot of memory according to ASAN (patch coming to provide that soon) and valgrind. This appears to be due to commented out frees from recent patches.

**To Reproduce**
Command executed:
* valgrind -s --leak-check=full ./mydumper --user=root --socket=/tmp/mysql.sock

What mydumper and myloader version has been used?

0.13.0-6 (current master)

**Environment (please complete the following information):**
 - OS version: Ubuntu 22.04

**Comment by davidducos** [comment]
Duplicate of #794
