### ISSUE TITLE
[BUG] Mydumper is terminating abruptly when using --rows option while exporting data into csv format

### ISSUE THREAD

**Issue by psgandhi12** [mydumper/mydumper#939]
**Describe the bug**
Mydumper is getting terminated abruptly when we pass --rows parameter while exporting data into csv format.

**To Reproduce**
Command executed:
* mydumper with all the parameters

nohup mydumper --host=xxxx --user=xuser1 --password=xxxx--outputdir=/mnt/disks/mysqldmp/mydumper5 --threads=8 --verbose=3 --rows=10000 --port=3306 --trx-consistency-only --long-query-guard=600  --tables-list=default_dcorder.DCO_ORDER_LINE --csv  --fields-terminated-by='|' --logfile /mnt/disks/mysqldmp/mydumper5.log &

What mydumper and myloader version has been used?

mydumper -V
mydumper0.13.1-1, built against MySQL 5.7.40-43 with SSL support with GZIP

We had raised below issue where mydumper is not working as expected for both --rows and -F (chunk size) and it has been fixed in 0.13.1-1. -F (--chunk-size) option is working but --rows option is failing. Please refer to below case for more details.

https://github.com/mydumper/mydumper/issues/790

**Expected behavior**
expected to generate multiple csv files 

**Log**
Getting below error
(mydumper:464730): GLib-ERROR **: 05:11:08.776: ../../../glib/gmem.c:173: failed to allocate 1048576 bytes
Trace/breakpoint trap (core dumped)

**Backup**
If applicable, add the list of content of the database path, an `ls -l` will be enough

**How to repeat**
If applicable, add the minimal table structure and data that we need to reproduce the issue.
Or upload a [core dump](https://github.com/mydumper/mydumper/wiki/Support#core-dump) for cases where mydumper or myloader is crashing.

**Environment (please complete the following information):**
 OS version:
          Ubuntu 20.04.4 LTS
MyDumper version:
          mydumper0.13.1-1, built against MySQL 5.7.40-43 with SSL support with GZIP

**Additional context**

**Comment by davidducos** [comment]
Hi @psgandhi12, I was not able to reproduce the issue with the latest version in master.
I will be releasing v0.13.1-2 soon, that might fix this issue.
