### ISSUE TITLE
[BUG] myloader hangs if there are more threads than jobs in the stream queue

### ISSUE THREAD

**Issue by LinuxJedi** [mydumper/mydumper#951]
**Describe the bug**
If you only have two tables and four threads you end up with threads stuck waiting on jobs that never happen. These are not sent to shutdown. All threads _must_ process at least one job at the moment. Otherwise you have threads stuck waiting on sync_mutex1 and others on `process_stream_queue`.

**To Reproduce**
Restore a single schema with just 2 tables. Using default options.

Current master (2022-12-21) was used.

**Environment (please complete the following information):**
 - OS version: Fedora 37
 - MyDumper version: mydumper0.13.1-1, built against MySQL 10.6.11 with GZIP

**Comment by davidducos** [comment]
Hi @LinuxJedi, I tried with this test case:
```
create database issue_951;
use issue_951
create table t1 (id int primary key auto_increment, val int);
create table t2 (id int primary key auto_increment, val int);
```
With this execution:
```
./mydumper -B issue_951 --stream > test.sql
```
And it worked.
