### ISSUE TITLE
[BUG] Setting to allow ANSI_QUOTE mode to be overridden / choose SQL delimiter

### ISSUE THREAD

**Issue by mgoodfellow** [mydumper/mydumper#968]
**Describe the bug**

Similar to https://github.com/mydumper/mydumper/issues/861

I've been down the rabbit hole trying to find out why mydumper is generating what I thought to be incorrect SQL (using double quotes around table names etc.)

A basic mydumper -> myloader caused seg faults on restore, and if the database name was overridden, then a SQL error on the database create SQL.

```
** Message: 14:31:34.088: Server version reported as: 8.0.30
** Message: 14:31:34.169: Intermediate queue: Sending END job
** Message: 14:31:34.169: Thread 1 restoring create database on `some_database` from some_database-schema-create.sql.gz

** (myloader:8559): CRITICAL **: 14:31:34.170: Thread 1: Error restoring: CREATE DATABASE /*!32312 IF NOT EXISTS*/ "some_database" /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"some_database" /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_09' at line 1

** (myloader:8559): CRITICAL **: 14:31:34.170: Error occurs between lines: 0 and 1 on file some_database-schema-create.sql.gz: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"some_database" /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_09' at line 1
Segmentation fault
```

Long story short - our source database had ANSI_QUOTES as a global SQL mode, and our target database we are migrating to did not. Both servers run mysql 8.0.30

I tried many historical versions and they all produce the seg fault on restore. I realise now in hindsight that the seg fault with no description or logs is the SQL statement failing to apply as above. Unfortunately this error above is only shown if overriding the database with -B 

I think it would be handy to override this delimiter option when dumping or restoring, OR give a more useful error to the user when loading a dump.

Potentially we should always generate backticks as this is MySQL standard and works regardless of global SQL settings?

As an aside, when using streaming mode this causes the connection to be lost with no explanation as to why.

**To Reproduce**
Command executed:

Source DB - mysql 8.0.30 - ANSI_QUOTES on
```
mydumper --host=[] --port=[] --user=[] --password=[] -G -E -R --compress --build-empty-files --threads=4 --compress-protocol --regex '^(testdb\.)' --lock-all-tables -v 3
```
 
Target DB - mysql 8.0.30 - ANSI_QUOTES off

```
myloader --threads=4 -u [] --password [] -h [] -P 3306 -v 4 --innodb-optimize-keys=AFTER_IMPORT_PER_TABLE -d
```

What mydumper and myloader version has been used?
Various from latest to v0.11

**Environment (please complete the following information):**
 - OS version: both CentOS 7.9 and Ubuntu 20.04]

**Comment by davidducos** [comment]
Hi @mgoodfellow, 
Do you know that sql_mode is a session variable? and that mydumper/myloader allow you to set session variables in the default-file ?
Which means that for instance, if you have in your source database:
```
sql_mode="ANSI_QUOTES,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```
Then you can create mydumper.cfg like (without ANSI_QUOTES):
```
[mydumper_variables]
sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```
And then execute mydumper --defaults-file=mydumper.cfg to export the data in the format that you want to import.

Please, let me know if that fixes the issue.

**Comment by mgoodfellow** [comment]
Hi @davidducos,

I knew it was available as a session variable, but I wasn't aware that these could be set in the defaults file. Apologies for missing that.

I would however reiterate the issue I suffered, which is feedback from `myloader`. If you have a dump which is done in ANSI_QUOTES format, you just get instant segmentation fault when trying to restore to a different server.

It is obscure to know this, and I'm sure others have been hit by it. As I referenced: https://github.com/mydumper/mydumper/issues/861 - see below the output for `myloader` in this instance.

Log
```
Accept: TCP{100.85.237.42:54622 > 100.65.237.20:3306} 60 ok out
Accept: TCP{100.65.237.20:3306 > 100.85.237.42:54622} 60 tcp non-syn
** Message: 17:29:13.854: Server version reported as: 8.0.29
** Message: 17:29:13.909: Thread 1 restoring create database on HWO_SBR619 from HWO_SBR619-schema-create.sql
** Message: 17:29:13.910: Intermediate queue ending
Segmentation fault
```

This segmentation fault is confusing to receive as a user, but I believe the source of that segmentation fault is that the SQL fails to apply due to the mismatch in formats.

I wonder if there is anyway to feedback to the user that the SQL failed to apply, and what possible reasons could cause that.

**Comment by davidducos** [comment]
The segfault issues that you are mentioning is because we use by default: backticks. So, I can say that we don't support ANSI_QUOTES yet... but it might not be hard to implement. 
So, I will be changing this to enhancement and the title.

**Comment by mgoodfellow** [comment]
I wonder if the simplest option would be for mydumper to always use backticks regardless of the ANSI_QUOTES setting? I wasn't even aware my Managed DB had this ANSI_QUOTES option on. I've always used backticks for MySQL, and my understanding is that this is always supported.

By this logic, the dump should always be done in backticks?

That would then solve this issue on the import side as well at the same time? 

Thanks for taking the time to take a look at the issue I raised, appreciated!

**Comment by davidducos** [comment]
We need to add an option to select the identifier quote character (https://dev.mysql.com/doc/refman/8.0/en/identifiers.html). 
The default will be BACKTICK and we are going to add ANSI. Do we have others? mmm we need to search.

About, change it automatically, it will be a HUGE NO!!! as people that don't need it, we are going to cause issues. 

And, before you ask, or anyone else, we are going to do this on mydumper, myloader is not going to change from ANSI to backticks format!!! :D
