### ISSUE TITLE
[ Refactoring ] Review PMM integration

### ISSUE THREAD

**Issue by davidducos** [mydumper/mydumper#978]
After several changes on the mydumper and myloader engine, we are not sending good metrics to PMM. We need to review this feature to show users what really is happening with their backup and restores.

**Comment by matthewlenz** [comment]
David, is there support for mydumper as an alternative to xtrabackup in PMM?

**Comment by davidducos** [comment]
Hi @matthewlenz I didn't understand your question.

**Comment by matthewlenz** [comment]
PMM supports backup and restore using xtrabackup. I was curious if there are any plans to make mydumper/myloader an alternate method of backup and restore in PMM.

**Comment by davidducos** [comment]
Hi @matthewlenz,  
I'm not a the top of the roadmap of PMM and nobody from PMM team created a ticket here, so, I will assume there aren't plans to add MyDumper as an alternative to xtrabackup in PMM. 
Take into account that Xtrabackup and PMM are both Percona products, MyDumper isn't, so I don't see any business reason why the want to implement it. I'm not saying that it is a bad or good idea, just I don't think that is going to happen.
