### ISSUE TITLE
[BUG] myloader performance regression for MariaDB 10.6

### ISSUE THREAD

**Issue by LinuxJedi** [mydumper/mydumper#987]
**Describe the bug**
MariaDB 10.6 tries to accelerate loading for InnoDB tables when using `SET foreign_key_checks=0, unique_checks=0;`. This is outlined in [MDEV-515](https://jira.mariadb.org/browse/MDEV-515). Unfortunately whilst this increases single-threaded bulk insert performance this introduces table-level locks which reduce the performance of myloader.

To fix this we need to not do `unique_checks=0` for myloader for MariaDB 10.6+ restorations.

**Comment by davidducos** [comment]
Hi @LinuxJedi, 
I think that you will be able to achieve that using --defaults-file under session variables section https://github.com/mydumper/mydumper#defaults-file as the session variables are executed after SET unique_checks:
```
  mysql_query(td->thrconn, "/*!40014 SET UNIQUE_CHECKS=0 */");
  mysql_query(td->thrconn, "/*!40014 SET FOREIGN_KEY_CHECKS=0*/");

  execute_gstring(td->thrconn, set_session);
```

**Comment by davidducos** [comment]
I'm thinking that in the future we need to keep a `/etc/mydumper.cnf` file with this defaults settings there, to let the users determine the defaults values and change them at wish.

**Comment by LinuxJedi** [comment]
Right. But since this affects pretty much all MariaDB users (all should be on at least 10.6 this year) wouldn't be easier to just disable this if MariaDB is detected? There isn't a default `mydumper.cnf` right now and myloader is doing the wrong thing here.

**Comment by davidducos** [comment]
Adding the if clause will be the simplest solution, but after implemented https://github.com/mydumper/mydumper/issues/566, it should be smarter to start loading /etc/mydumper.cnf. As I don't want to do things for particular vendors when we can do it from a configuration file, for instance, maintain the different locking mechanism is not easy, an we are not even close to test all that.

**Comment by TomMettam** [comment]
Setting UNIQUE_CHECKS=1 has..

* No positive impact unless `--rows` is used, because without the `--rows` option myloader doesn't use multiple threads to write to the same table anyway
* A catastrophic impact on import performance with large tables

In my test cases, importing with  UNIQUE_CHECKS=0 and without "--rows" is always significantly faster than importing with --rows. I've tested on tables with just a few thousand rows, and one with 0.3 billion rows.

**Comment by davidducos** [comment]
@TomMettam 
Probably you need to review https://jira.mariadb.org/browse/MDEV-515 and comment there, as that was the reason why we change that on MariaDB 10.6.
Take into account that --rows doesn't have significant impact on myloader, it just reduce the INSERT statement size when possible. However, the option --rows on mydumper has a huge performance impact depending the scenario.

**Comment by TomMettam** [comment]
But an export which was not split with --rows, will be imported with a single thread - setting UNIQUE_CHECKS=1 in this case incurs a massive performance penalty.

**Comment by davidducos** [comment]
Hi @TomMettam, why don't you edit the configuration file in /etc/mydumper.cnf or use a different --defaults-file ? The UNIQUE_CHECKS=1 is not hardcoded.
