### ISSUE TITLE
mydumper --disk-limits doesn't check free space [BUG]

### ISSUE THREAD

**Issue by szuras** [mydumper/mydumper#994]
**Describe the bug**
When I try to use --disk-limits parameter it seems that the free space is counted in wrong way.

**To Reproduce**
Command executed:
*  mydumper -h host.source.com -u user -p pass -o /mnt/big/tmp/export/ -L export.log -v 3 --disk-limits '1154122:1164122' -F 500 --split-partitions -B data -t 1 --stream | myloader -h host.destination.com -u user -p pass -o -B test -d import/ -L import.log -v 3 --max-threads-per-table 8 -t 5 --stream

the free space '_df -m'_
Filesystem       1M-blocks    Used Available Use% Mounted on
/dev/sdc5          3823367 2590223   **1038857**  72% /mnt/big

'_df -h'_
Filesystem        Size  Used Avail Use% Mounted on
/dev/sdc5         3.7T  2.5T  1.1T  71% /mnt/big

What mydumper and myloader version has been used?
mydumper0.13.1-1

**Expected behavior**
It looks the --disk-limits parameter is ignored and the mysqldumper downloads data even a free space dropped below specified limit. The downloader will stop processing/downloading data once I'll set very high limit e.g. **--disk-limits "1248000:1249000"** so then I see in logs:

_2023-01-23 11:10:18 [INFO] - MyDumper backup version: 0.13.1-1
2023-01-23 11:10:18 [INFO] - Server version reported as: 8.0.31
2023-01-23 11:10:18 [INFO] - Connected to a MySQL server
2023-01-23 11:10:18 [WARNING] - Pausing backup disk space lower than 1254122MB. You need to free up to 1264122MB to resume_

Additionally disk limits specified by me differ that those which I see in a log file:
1248000 [ specified by me ] vs 1254122 [ value in the log ]

**Environment (please complete the following information):**
 - OS version: Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
 - MyDumper version: mydumper0.13.1-1, built against MySQL 8.0.30-22 with SSL support with GZIP

**Comment by davidducos** [comment]
Hi @szuras,
I was not able to reproduce your issue:
```
[root@mydumper1 mydumper]# ./mydumper --disk-limits "1248000:1249000"

** (mydumper:14125): WARNING **: 12:56:46.583: Pausing backup disk space lower than 1248000MB. You need to free up to 1249000MB to resume
```

BTW, on each command that you mention --disk-limits you have different values. Are you setting them dynamically?

**Comment by szuras** [comment]
what kind of values should I use for the parameter _--disk-limits_ if I want to leave eg 900GB free space on my drive? A let's say resume downloading if there is more that 1TB free space,

Currently on my drive I habe 1.1TB of free space:
_df -h
/dev/sdc5         3.7T  2.5T  1.1T  71% /mnt/big_

**Comment by szuras** [comment]
I run mydumper with a stream option which is consumed by myloader like this:
_mydumper -h source.server.eu -u user -p XXXXXXXXXXXXXXXX -o /mnt/big/server1/ -B data --disk-limits 900000:1000000 -L dumper.log -v 3 -F 200 --split-partitions -t 4 --stream
myloader -h destination.server.eu  -u user -p XXXXXXXXXXXXXXXX -o -B test -d /mnt/big/server2/ -L import.log -v 3 -t 16 --max-threads-per-table 8 --stream_

so the mydumper should stop downloading data once there is less than 900GB  [ there is a limit 900000 ] of free space on the drive but it doesn't stop:

df -m
Filesystem        Size          Used          Avail     Use%   Mounted on
/dev/sdc5      3823367    2800143    **828936**  78%    /mnt/big

**Comment by davidducos** [comment]
Hi @szuras,

I will be packaging a new prerelease today that you will be able to test and see if that fix your issue.

**Comment by szuras** [comment]
I've checked prerelease version https://github.com/mydumper/mydumper/releases/tag/v0.14.0-2 and it looks the problem is not solved.

It looks like the disk status check [ disk usage ] is executed a few minutes after starting mydumper [ the check should be executed more often? ]. The mydumper discovers lack of space too late, a few minutes after the pause value was reached. 

Additionally the description about this parameter - resume and pause don't correspond to later information: 
_--disk-limits                    Set the limit to pause and resume if determines there is no enough disk space.Accepts values like: '<**resume**>:<**pause**>' in MB.For instance: 100:500 will **pause when there is only 100MB** free and will **resume if 500MB** are available_

**Comment by davidducos** [comment]
Hi @szuras,
Last change should be stoped every 200M, as that is what you are setting in -F, because we are checking every time the file is rotated. We can't check every time that a row is written on disk. We could check every time that a new insert statement is written but it will slow down things more. 
I have to ask, is mydumper stopping and resuming? is it stopping at the most when it reaches more than 800M (200M * 4 threads) ? if it is under, then, we are ok.
I will check the doc to explain the correct behavior:
`--disk-limits Set the limit to pause and resume if determines there is no enough disk space when new job is starting or file rotated. Accepts values like: '<resume>:<pause>' in MB.For instance: 100:500 will pause when there is only 100MB free and will resume if 500MB are available`
